### ISSUE TITLE
ci: add testing for vendored esbuild

### ISSUE THREAD

**Issue by lino-levan** [denoland/fresh#1012]
Tests do not fail currently if no wasm esbuild is included. This isn't great.

**Comment by hashrock** [comment]
This we need to do; we need to run CI on the WASM version to see if it works with Deno Deploy.

**Comment by hashrock** [comment]
Notes:

We might do it by writing a wrapper which deletes `Deno.run` before execute main.ts

Related:

https://github.com/denoland/fresh/blob/54259ee9eec489864da80a81cf71b1f3221edadf/src/server/bundle.ts#L14

**Comment by hashrock** [comment]
closed with https://github.com/denoland/fresh/pull/1082
