### ISSUE TITLE
Middlewares' order of execution problems

### ISSUE THREAD

**Issue by starrematte** [denoland/fresh#1016]
Hi all,
I noticed a strange behaviour using multiple handlers, where as soon you call `await ctx.next()` it procedes to the next middleware/resource. But in this way the guide shows something misleading (I mean this part: https://fresh.deno.dev/docs/concepts/middleware#:~:text=resp.headers.set(%22server%22%2C%20%22fresh%20server%22)%3B). 

I have a vanilla fresh project with a middleware and wich inside there are two handlers, and a second route also with a middleware and a resource. I'll show you what I have:

![Screenshot 2023-02-04 alle 17 25 14](https://user-images.githubusercontent.com/34447249/216778482-c522bd64-7cf5-45cf-8529-61704d36952b.png)

![Screenshot 2023-02-04 alle 17 26 05](https://user-images.githubusercontent.com/34447249/216778486-25c67b0b-cc78-429d-821e-bcafe5590e82.png)

When I try to call `joke`, something weird with the order of execution is happening as you can see from the console:

![Screenshot 2023-02-04 alle 17 26 37](https://user-images.githubusercontent.com/34447249/216778487-d156571c-399e-4020-9422-0cc6fda5346c.png)

The order of execution that I expect is:

```
1
Response {
  body: ReadableStream { locked: false },
  bodyUsed: false,
  headers: Headers { "content-type": "text/plain;charset=UTF-8" },
  ok: true,
  redirected: false,
  status: 200,
  statusText: "",
  url: ""
}
2
3
```

Is this a real issue? Or is just a normal behaviour and so I'm doing something wrong?

Thanks in advance.

**Comment by thegaryroberts** [comment]
The order of execution you are showing with console logs does match my understanding of the docs and what I would've expected. i.e outer most folder / left-most url segment first, then proceeding inwards.

I have a project with quite deeply nested routes and multiple middleware files at differing depths and can verify it consistently follows that execution order.

**Comment by lucacasonato** [comment]
Yes, this is intended behaviour. `ctx.next()` only resolves once all middleware and routes inwards have been resolved. This allows you to do things like:

```ts
export function handler(req: Request, ctx: MiddlewareHandlerContext) {
  const start = performance.now();
  const resp = await ctx.next();
  const diff = performance.now() - start;
  console.log(`Request took ${diff}ms`);
  resp.headers.set("server-timing", `handler;dur=${diff}`);
  return resp;
}
```
