### ISSUE TITLE
Dependency caching issue

### ISSUE THREAD

**Issue by rojvv** [denoland/fresh#1021]
We cannot cache all our dependencies in our build step, as the following dependencies won’t be automatically cached by `deno cache`:

```text
https://deno.land/x/fresh/src/runtime/main_dev.ts
https://deno.land/x/fresh/plugins/twind/main.ts
https://deno.land/x/fresh/src/runtime/main.ts
https://esm.sh/preact/debug
https://esm.sh/stable/preact/deno/debug.js
https://esm.sh/stable/preact/deno/devtools.js
```

**Comment by marvinhagemeister** [comment]
Closing as this is a Deno issue not a Fresh issue. This has been resolved in Deno a while back by setting `vendor: true` in `deno.json`.
