### ISSUE TITLE
Not ready for self hosting (?)

### ISSUE THREAD

**Issue by vjdv** [denoland/fresh#1022]
Not sure if documentation is lacking this or the project still don't consider this options.

I don't want to use Deno Deploy, I want to deploy to my own server, for this a want to know two things:

- How to set a basepath? My project will be hosted in a subpath of my site.
- How to run in production mode? I see a refresh.js script waiting for events, I don't want this in production and I cannot find how to disable it.

**Comment by sylc** [comment]
to disable production mode, set en environment variable DENO_DEPLOYMENT_ID 
see related https://fresh.deno.dev/docs/concepts/deployment#docker and https://github.com/denoland/fresh/issues/535#issuecomment-1193080186

**Comment by thegaryroberts** [comment]
> to disable production mode, ...
I think you meant *enable*

**Comment by digitaldesigndj** [comment]
In your `deno.json` you can do something like this:
```
  "tasks": {
    "start": "deno run -A --watch=static/,routes/ dev.ts",
    "reload": "deno run -A --watch=static/,routes/ --reload dev.ts",
    "run": "DENO_DEPLOYMENT_ID=$(git rev-parse --short HEAD) deno run -A main.ts"
  },
```
Then I use `pm2` to launch, manage and log my `deno task run` process.

**Comment by hashrock** [comment]
as sylc commented, it was described in docs. close for now but feel free to make PR if docs seems unfriendly for you.
