### ISSUE TITLE
Typo in Blog Post on Auth

### ISSUE THREAD

**Issue by mrcampbell** [denoland/fresh#1029]
Hey! Not sure where to put this, but there is a typo in the Fresh blog post here. I'm new to Deno as of today! Good to be here ❤️

https://deno.com/blog/setup-auth-with-fresh

[In this segment on #add-login-and-logout-to-index](https://deno.com/blog/setup-auth-with-fresh#add-login-and-logout-to-index)

The code reads

```
// routes/index.tsx

export default function Home({ data }: PageProps<Data>) {
  return (
    <div>
      <div>
        You currently {data.isAllowed ? "are" : "are not"} logged in.
      </div>
      {!data.isAllowed ? <Login /> : <a href="/logout">Logout</a>}
    </div>
  );
}
```

and that `href` on the Logout button should be `<a href="/api/logout">Logout</a>` as the other 404's.

Freaking love this project!!

**Comment by lambtron** [comment]
thanks for reporting the typo! we'll update it.
