### ISSUE TITLE
Slow serving of twind, main.js and island js files on Deploy

### ISSUE THREAD

**Issue by cknight** [denoland/fresh#1037]
Apologies for the cross post, but I'm unclear if this issue is a Deploy issue, Fresh issue, or lack of understanding on my part.  To summarize, on load of the Fresh app on Deploy, the initial route request is fast, but there is a significant delay (~4 seconds) to return the twind plugin js, main.js and island js files.  I've seen this on my own app and others.  Here's an example from Deno's merch site:

![image](https://user-images.githubusercontent.com/1248238/219902887-7b28011a-1871-4612-b014-4f89a9a984c5.png)

I'm unclear why this is so slow.  Is this a first time generation cost which is then cached in server side memory for future use?  Locally I observe approximately 420ms to generate these files and respond, which is slow, but acceptable.  Subsequent requests to those resources are fast (0-2ms).

See also:
https://github.com/denoland/deploy_feedback/issues/340

**Comment by Vehmloewff** [comment]
Ah, now that I see this, I realize I should have posted here. See https://github.com/denoland/deploy_feedback/issues/340#issuecomment-1478546904

**Comment by cknight** [comment]
Closing in favour of #1062
