### ISSUE TITLE
global layout docs

### ISSUE THREAD

**Issue by elycheikhsmail** [denoland/fresh#1043]
how create global layout in fresh must be documented even this subject is related to preact/react and not specific to fresh, fresh documention should take in mind  that some dev using fresh come from laravel, django,... then not confortable a enought with react concept and best pratic.

**Comment by hashrock** [comment]
I think it was resolved by app-wrapper.

https://fresh.deno.dev/docs/concepts/app-wrapper

or, more advanced layout feature should be discussed in https://github.com/denoland/fresh/issues/403. close for now.
