### ISSUE TITLE
changes to import map do not reflect across hot reload

### ISSUE THREAD

**Issue by swiftsword94** [denoland/fresh#1045]
steps to reproduce:

1. run "deno task start"
2. add a package in your ts file
3. update the import map
4. save

found when trying to import djwt from tpm.
originally message was saying "Warning Implicitly using latest version (v2.8) for https://deno.land/x/djwt" however the correct value was explicitly in import map.

**Comment by ghost** [comment]
add it in the start command aka change the task "start" to have the import map included

**Comment by deer** [comment]
It should be noted that even with the new project structure (i.e. imports being in `deno.json`) a problem still exists.

Changing `deno.json` will result in a reload, even without modifying `start` to explicitly watch `deno.json`. But adding a value to the import map still results in an error. In my test I get...
```
Watcher File change detected! Restarting!
error: Uncaught (in promise) TypeError: Relative import path "$gfm" not prefixed with / or ./ or ../ and not in import map from "file:///Users/reed/code/temp/fresh-project/routes/_middleware.ts"
    at file:///Users/reed/code/temp/fresh-project/routes/_middleware.ts:2:21
  await import(entrypoint);
  ^
    at async dev (file:///Users/reed/code/fresh/src/dev/mod.ts:140:3)
    at async file:///Users/reed/code/temp/fresh-project/dev.ts:5:1
Watcher Process finished. Restarting on file change..
```

Stopping the server and starting it again (with no file changes) results in:
```
Watcher Process started.
The manifest has been generated for 4 routes and 1 islands.

 🍋 Fresh ready
    Local: http://localhost:8000/
```

**Comment by marvinhagemeister** [comment]
Fresh reuses the watch capabilities from `deno` itself. Reading the comments here it sounds like an issue in deno itself. It looks like they already have an issue for this: https://github.com/denoland/deno/issues/19468 .

**Comment by dsherret** [comment]
Should be fixed in the latest Deno patch release.

**Comment by marvinhagemeister** [comment]
Awesome, can confirm that this works with the latest Deno v1.34.3 release 🎉
