### ISSUE TITLE
deno 1.31.1: deno check main.ts failed

### ISSUE THREAD

**Issue by theowenyoung** [denoland/fresh#1052]
Create new project:

```bash
deno run -A -r https://fresh.deno.dev deno-fresh-demo
cd deno-fresh-demo
```

```bash
deno check ./main.ts
Check file:///Users/green/inbox/deno-fresh-demo/main.ts
error: TS2305 [ERROR]: Module '"internal:///missing_dependency.d.ts"' has no exported member 'JSX'.
import { JSX } from "preact";
         ~~~
    at file:///Users/green/inbox/deno-fresh-demo/components/Button.tsx:1:10
```

**Comment by kt3k** [comment]
probably related to https://github.com/ije/esm.sh/issues/534

**Comment by ije** [comment]
<img width="531" alt="Screenshot 2023-03-02 at 07 45 31" src="https://user-images.githubusercontent.com/2883484/222292632-5499184c-774a-437c-a386-c484e0d09177.png">
fixed in v110, and updated the checker script

**Comment by ije** [comment]
<img width="500" alt="Screenshot 2023-03-02 at 07 49 36" src="https://user-images.githubusercontent.com/2883484/222293222-58aae8bf-b541-4af0-898f-c67403ccb446.png">

**Comment by theowenyoung** [comment]
Thanks, everything is ok now.

**Comment by kt3k** [comment]
Thank you @ije!

**Comment by ynwd** [comment]
Failed when run script test

```ts
import { dark } from "https://esm.sh/react-syntax-highlighter@15.5.0/dist/esm/styles/prism";
```

```zsh
error: TS2305 [ERROR]: Module '"internal:///missing_dependency.d.ts"' has no exported member 'dark'.
import { dark } from "https://esm.sh/react-syntax-highlighter@15.5.0/dist/esm/styles/prism";
```

<img width="696" alt="Screenshot 2023-07-07 at 01 18 01" src="https://github.com/denoland/fresh/assets/10122431/78f0f366-5a48-4be2-ba6e-aab439e33e27">

module: https://github.com/react-syntax-highlighter/react-syntax-highlighter

@ije
