### ISSUE TITLE
vscode: JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists

### ISSUE THREAD

**Issue by andresv** [denoland/fresh#1054]
I just did a fresh vscode and deno install on a windows machine and created example project using https://fresh.deno.dev/docs/getting-started/create-a-project.

Vscode installed twind and deno plugins, but when opening `routes/index.tsx` it is full of such errors.

```
JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists
```
![Screen Shot 2023-03-02 at 10 39 30](https://user-images.githubusercontent.com/809232/222376802-6035c72d-dd7d-4dfa-9e76-323e3a49ee9c.jpg)

I tried:
* Deno: Restart Language Server
* Deno: Initialize workspace configuration
* Developer Reload Window

What else must be configured to get it going in vscode?

**Comment by andresv** [comment]
Okay on this machine it started to work after `deno task start`. Have to check what i going on with the other one.

**Comment by Benji377** [comment]
I'm having the exact same issue, even after `deno task start`, have you been able to solve this? @andresv

**Comment by marvinhagemeister** [comment]
@Benji377 This is a pending open issue in Deno. There is a workaround though: By running `deno cache main.ts` it should work.

The issue is tracked here https://github.com/denoland/deno/issues/20582

**Comment by Benji377** [comment]
Thank you!

**Comment by adamzerner** [comment]
> There is a workaround though: By running deno cache main.ts it should work.

That didn't work for me in my Fresh project nor did `deno task start`.

**Comment by lihe6666** [comment]
+1
