### ISSUE TITLE
deno task screenshot is not working

### ISSUE THREAD

**Issue by niLPotential** [denoland/fresh#1056]
## Command 1:

    deno task screenshot https://example.com example

## Output 1:

    Task screenshot deno run -A www/utils/screenshot.ts "https://example.com" "example"
    error: The source code is invalid, as it does not match the expected hash in the lock file.
    Specifier: https://esm.sh/jszip@3.5.0
    Lock file: [path]/fresh/www/deno.lock

## Command 2:

    deno cache --lock www/deno.lock www/utils/screenshot.ts

## Output 2:

    error: The source code is invalid, as it does not match the expected hash in the lock file.
    Specifier: https://esm.sh/jszip@3.5.0
    Lock file: www/deno.lock

Simply reloading the cache doesn't solve the error.
When I look at `www/deno.lock`, the hash for `https://esm.sh/jszip@3.5.0` is
> fc902480ac412bc3b3441ed511b7158bab3477a63940748be3cc4c602a56bfb8

## Command 3:

    deno cache --reload --lock www/deno.lock --lock-write www/utils/screenshot.ts

This updates the hash in `www/deno.lock` for 
> https://esm.sh/jszip@3.5.0
> https://esm.sh/v107/core-util-is@1.0.3/deno/core-util-is.js
> https://esm.sh/v110/jszip@3.5.0/deno/jszip.js
> https://esm.sh/v110/jszip@3.5.0/index.d.ts
> https://esm.sh/v110/lie@3.3.0/deno/lie.js
> https://esm.sh/v110/readable-stream@2.3.8/deno/readable-stream.js
> https://esm.sh/v110/safe-buffer@5.1.2/deno/safe-buffer.js

But when I run Command 1 again it throws a different error
## Output 3:

    Task screenshot deno run -A www/utils/screenshot.ts "https://example.com" "example"
    error: Uncaught BadResource: Bad resource ID
    const result = await reader.read(inspectArr);
                   ^
    at async read (internal:runtime/js/12_io.js:104:17)
    at async readDelim (https://deno.land/std@0.93.0/io/bufio.ts:652:20)
    at async readStringDelim (https://deno.land/std@0.93.0/io/bufio.ts:702:20)
    at async readLines (https://deno.land/std@0.93.0/io/bufio.ts:711:18)
    at async waitForWSEndpoint (https://deno.land/x/puppeteer@16.2.0/src/deno/BrowserRunner.ts:168:20)
    at async BrowserRunner.setupConnection (https://deno.land/x/puppeteer@16.2.0/src/deno/BrowserRunner.ts:146:31)
    at async FirefoxLauncher.launch (https://deno.land/x/puppeteer@16.2.0/src/deno/Launcher.ts:276:26)
    at async [path]/fresh/www/utils/screenshot.ts:24:17

I used both `firefox` and `chrome` for `PUPPETEER_PRODUCT`.
Both don't work and I'm stuck here.
Any tips or workarounds?
I am running on WSL2 openSUSE-Tumbleweed, could that be the problem?

**Comment by niLPotential** [comment]
I didn't think that I would actually need to install chromium on my machine.
The dependencies weren't there and of course chrome couldn't launch, causing an error.
There was nothing wrong with the script.
Sorry for the inconvenience.

**Comment by shijianzhong** [comment]
shijianzhong@‘史建忠’ www-main % deno task screenshot http://localhost:8000/ fresh-blog-system
Task not found: screenshot
Available tasks:
- start
    deno run -A --watch=static/,routes/ dev.ts

**Comment by ctran** [comment]
@shijianzhong the above task is only available in the [denoland/fresh](https://github.com/denoland/fresh/tree/main) repo, as can be seen here:
* https://github.com/denoland/fresh/blob/main/www/utils/screenshot.ts
* https://github.com/denoland/fresh/blob/main/deno.json#L7
