### ISSUE TITLE
Custom component support

### ISSUE THREAD

**Issue by HelloFillip** [denoland/fresh#1061]
As Preact has native support for custom components it would be useful to include this support as part of the islands. 

Although there's a lack of DOM / HTMLElement support in Deno, there should be a capability in Fresh to support the registering of custom components in the browser, potentially during hydration. 

I've been experimenting with getting re-usable custom component libraries working in Fresh, with some difficulty, and have resorted to adding the _pre-built_ libraries into the client using routes. However, this feels like aa rather laborious and imperfect workaround so far.

A more elegant approach would be welcome.

**Comment by marvinhagemeister** [comment]
What are "custom components"? Do you mean [Custom Elements](https://developer.mozilla.org/en-US/docs/Web/API/Web_components/Using_custom_elements)?

**Comment by marvinhagemeister** [comment]
Closing, as we haven't heard back what is meant by custom components from the OP. Happy to reopen if somebody is interested in this.

**Comment by HelloFillip** [comment]
@marvinhagemeister Missed this response. 

Yes, I mean Custom Elements. I'm looking back at this as I'm building an isomorphic portable component library in Fresh (with Preact) and this would make it significantly easier. 

With Preact you can use the following approaches to registering custom elements:

```typescript
register(Collection, 'minttu-collection', [], { shadow: true });
```

Or the web standard method:

```typescript
customElements.define('minttu-collection', class extends HTMLElement {
    // ...
});
```

The latter clearly requires support for `HTMLElement`.
