### ISSUE TITLE
Refactor tests

### ISSUE THREAD

**Issue by hashrock** [denoland/fresh#1070]
We see a lot of duplicate code where the test creates a process.

```
      const serverProcess = new Deno.Command(Deno.execPath(), {
        args: ["run", "-A", "--check", "main.ts"],
        stdin: "null",
        stdout: "piped",
        stderr: "inherit",
        cwd: tmpDirName,
      }).spawn();

      const lines = serverProcess.stdout
        .pipeThrough(new TextDecoderStream())
        .pipeThrough(new TextLineStream());
```

I think it would be nice to have a test util. if anyone can think of a better way to organize it, feel free to comment here :)

Related: 
https://github.com/denoland/fresh/pull/1050#pullrequestreview-1327002774

**Comment by digitaldesigndj** [comment]
I put what I have been using into a module here: https://deno.land/x/fresh_marionette@v1.1.1

I created it mostly to wrap up Puppeteer, but it does export a function called `freshTestWrapper` that does the thing you're looking for here. I just updated my examples to include the case asked for:

```javascript
import { assertEquals } from "https://deno.land/std@0.178.0/testing/asserts.ts"
import { freshTestWrapper } from "https://deno.land/x/fresh_marionette@v1.1.1/mod.js"

Deno.test(
  "Some Testing",
  freshTestWrapper(async (t) => {
    // fresh has been started
    await t.step("The homepage should work (200)", async () => {
      const requestStatus = await fetch(`http://localhost:8000`).then(
        async (res) => {
          await res.text()
          return res.status
        },
      )
      assertEquals(requestStatus, 200)
    })
    // all done? Fresh will close gracefully
  }),
)
```

source code is here: https://deno.land/x/fresh_marionette@v1.1.1/mod.js?source

**Comment by iuioiua** [comment]
For those wanting to target this, something like this has been done in https://github.com/denoland/fresh/blob/98636ec8a078ab781c38f7164d68cd66b5400b45/tests/islands_test.ts#L60-L108

It just needs to be pulled into its own test utility and applied to any remaining applicable tests.
