### ISSUE TITLE
Why is there no lock file in Fresh?

### ISSUE THREAD

**Issue by cknight** [denoland/fresh#1075]
A recent upgrade of Deno broke my GitHub CI pipeline as the lock file no longer matched.  I'm unclear what originally generated it.  Digging deeper I see someone else had a [similar problem](#1063 ) and the recommended fix was to delete the lock file.  I also note that in the new deno.json a [commit](https://github.com/denoland/fresh/pull/1005) was added to disable the lock file.

What is the reasoning behind this?  Are we unable to effectively use lock files in Fresh?

**Comment by hashrock** [comment]
I'm thinking that repositories using esm.sh should set `lock: false` for now.

https://github.com/denoland/deno-gfm/issues/47#issuecomment-1460872019
