### ISSUE TITLE
Hydration does not use cached modules with cached-only

### ISSUE THREAD

**Issue by hlv** [denoland/fresh#1077]
Even with --cached-only option, the hydration of an island, fresh still tries to fetch packages.

✘ [ERROR] [plugin deno] error sending request for url (https://deno.land/x/fresh@1.1.4/plugins/twind/main.ts): error trying to connect: tcp connect error: Connection refused (os error 111)

    deno:data:application/javascript,import hydrate from "https://deno.land/x/fresh@1.1.4/plugins/twind/main.ts";import options from "file:///app/twind.config.ts";export default function(state) { hydrate(options, state); }:1:20:
      1 │ ...drate from "https://deno.land/x/fresh@1.1.4/plugins/twind/main.t...
        ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

An error occurred during route handling or page rendering. Error: Build failed with 2 errors:
error: error sending request for url (https://deno.land/x/fresh@1.1.4/src/runtime/main.ts): error trying to connect: tcp connect error: Connection refused (os error 111)
deno:data:application/javascript,import hydrate from "https://deno.land/x/fresh@1.1.4/plugins/twind/main.ts";import options from "file:///app/twind.config.ts";export default function(state) { hydrate(options, state); }:1:20: ERROR: [plugin: deno] error sending request for url (https://deno.land/x/fresh@1.1.4/plugins/twind/main.ts): error trying to connect: tcp connect error: Connection refused (os error 111)

**Comment by marvinhagemeister** [comment]
This is resolved by going with AOT builds, see the documentation for it here https://fresh.deno.dev/docs/concepts/ahead-of-time-builds . That way all dependencies are fetched and the islands are built once per deployment.
