### ISSUE TITLE
Server stalls when clicking quickly between pages

### ISSUE THREAD

**Issue by audionerd** [denoland/fresh#1079]
Steps to reproduce:

    deno --version
    deno 1.31.1 (release, aarch64-apple-darwin)

    fresh@1.1.4

Start a new Fresh project

```js
deno run -A -r https://fresh.deno.dev my-project
```

Add two simple routes to link between:

```js
// routes/index.tsx:
export default function One(props) {
  return <a class="underline" href="/two">Two</a>;
}
```

```js
// routes/two.tsx
export default function Two(props) {
  return <a class="underline" href="/">One</a>;
}
```

Run: `deno task start`

Then:
- Open http://localhost:8000 in Google Chrome and click the "Two" link
- Click the "One" link
- Click the "Two" link
- Click the "One" link
- Click the "Two" link
- Click the "One" link and wait ~60 seconds for a response

In Chrome Developer Tools > Network > Timing, Connection Start we can see Stalled for ~60s. Seems like we’re hitting the six TCP connection limit for HTTP.

This does not happen when `DENO_DEPLOYMENT_ID` is set, leading me to believe it was a problem with `_frsh/alive`.

So I believe the problem is that the alive stream’s `cancel` is never called, which can be confirmed with a `console.log` here:
https://github.com/denoland/fresh/blob/4bfab6a8a92e6cc62fe9e0e19d1ecdf2454f3487/src/server/context.ts#L421

I started digging into why that is and ran out of time. Possibly related:
- https://www.reddit.com/r/Deno/comments/111xbtw/does_denolistentls_not_support_calling_cancel_in/
- https://github.com/denoland/fresh/pull/995

**Comment by JacobWeisenburger** [comment]
I've had the same issue

**Comment by digitaldesigndj** [comment]
I see this too, my reaction has been to restart the server.

**Comment by audionerd** [comment]
Quick fix when running locally on `HTTP/1.1` is to `close` the `EventSource` on `beforeunload`.
https://github.com/denoland/fresh/blob/4bfab6a/src/server/context.ts#L405
```diff
- `new EventSource("${ALIVE_URL}").addEventListener("message", function listener(e) { if (e.data !== "${BUILD_ID}") { this.removeEventListener('message', listener); location.reload(); } });`;
+ `let es = new EventSource("${ALIVE_URL}"); window.addEventListener('beforeunload', event => { es.close() }); es.addEventListener("message", function listener(e) { if (e.data !== "${BUILD_ID}") { this.removeEventListener('message', listener); location.reload(); } });`;
```

**Comment by lino-levan** [comment]
Ah this makes sense actually. EventSource has a limit of 6 per host per browser iirc (in non `http/2`)? I guess when quickly switching tabs, the event sources build up (but never get closed), pass that limit, and the browser eventually automatically closes them at 60 seconds.

**Comment by thegaryroberts** [comment]
I've been hitting this issue for a long time, now reflexively / painfully restarting the server when working with multiple tabs.

Should Fresh swap Deno.serve to Deno.serveHttp for HTTP/2 support?
[Deno.serveHttp](https://deno.land/api@v1.32.5?s=Deno.serveHttp)

(or apply the HTTP/1.1 fix above)

**Comment by lino-levan** [comment]
Seems like @audionerd's quick fix would be accepted in a PR pretty fast.

**Comment by audionerd** [comment]
I hesitated making a PR because that quick fix doesn’t really solve the core problem, and I didn’t fully understand why the connections aren’t being closed without it.
Hoping someone who better understands the server guts has time to take a look.

**Comment by lino-levan** [comment]
> doesn’t really solve the core problem

The core problem seems to be a bug with browsers. Unless I'm misunderstanding something (which if very possible), we should do our best to make sure the UX is good even if browsers are messy.

**Comment by audionerd** [comment]
The quick fix above solves a problem for most Fresh users, so it’s an improvement, and it does close this specific issue. Thinking about it more, I guess it is worth a PR :)

But if a Fresh app has any other SSE client code (and mine does) you’ll still run into the problem of connections remaining open, and it may trip up developers running locally. 

Although the connection limit is a browser limitation, stalling happens even if you don't have multiple windows open. Can occur just clicking between pages in a single window. So I wonder if it’s a Fresh or Deno server issue. Haven’t had time to investigate though. If I do, I'll open a new issue about it.

**Comment by lino-levan** [comment]
I probably have misunderstood the issue, but still am in support of doing this quick fix. Is this a Deno bug or a browser bug?

**Comment by audionerd** [comment]
Updated my comment. I think it’s a Deno or Fresh server bug.

**Comment by audionerd** [comment]
Update: It’s probably not a server bug 🙃  

As noted above, I thought it was weird that the SSE ReadableStream’s `cancel` is not called when clicking between pages, ~but I wrote some quick test SEE servers with both Deno std/http/server and Node/Express and they exhibit the same behavior.~

**Comment by lino-levan** [comment]
Strange. I guess that means that we should just work around this and it's not the end of the world.

**Comment by audionerd** [comment]
Yeah, to be clear, I’m in favor of the workaround PR being accepted.

**Comment by audionerd** [comment]
Added my research here: https://github.com/audionerd/fresh-sse-issue-1079

Actually was able to demonstrate that a simple Deno std/http/server SSE server _does not_ have the stalling behavior exhibited by Fresh, so I'm still confused. But that’s all I had time for today.
