### ISSUE TITLE
`Deno` namespace in Deno standard library causes error on client side

### ISSUE THREAD

**Issue by JacobWeisenburger** [denoland/fresh#1080]
![image](https://user-images.githubusercontent.com/31667350/225727678-80a80b4c-b616-47e0-a7d2-4bbf6d60e701.png)
![image](https://user-images.githubusercontent.com/31667350/225727746-64c7973b-81f0-45f4-819d-a6bd98dc3d10.png)

Here is the line that is causing the problem from Deno standard library:
https://github.com/denoland/deno_std/blob/847720dd4141118e2d87f7bba469054c5f21254f/fs/move.ts#L4

I have reverted back to `std@0.153.0` for now, but it would be cool if there was a better way to deal with this. Does anyone know how to fix this?

**Comment by dogovornyachok** [comment]
This is a entirely expected behavior. You cannot use Deno's APIs in the browser because Deno is a server-side JS runtime. You must use some browser APIs instead

**Comment by JacobWeisenburger** [comment]
But I'm not trying to use Deno in the browser. It just runs automatically. I don't want that code to run in my islands, but I can't figure out how to stop it from running. This is the problem I'm needing help with.

**Comment by alexnguyennz** [comment]
What is actually causing this error? I get `Deno is not defined` as well when I import/use a particular library.

**Comment by JacobWeisenburger** [comment]
Part of what is happening is that this is being defined on the top level and not in a function:

```ts
const EXISTS_ERROR = new Deno.errors.AlreadyExists( 'dest already exists.' )
// throws ReferenceError: Deno is not defined
```

If the above code were to be defined in a function and that function was never called, then no error would be thrown.

```ts
const getExistsError = () => new Deno.errors.AlreadyExists( 'dest already exists.' )
// if getExistsError never gets called, then no error
```

So I'm guessing that one of my deps are including deno std lib in my islands. It could be `fresh` that is doing this. But I'm not sure. Is someone able to confirm this?
