### ISSUE TITLE
islands redirect

### ISSUE THREAD

**Issue by mrtornado** [denoland/fresh#1083]
Is it really no way to redirect from an island after you get the response ? I couldn't find anything that works.
My onSubmit looks like this:
I'm using state in the island component with preact that's why I need a redirect in here. I know about the the native form element but I need state.

```
const onSubmit = async (e: any) => {
    e.preventDefault();
    if (pass.length < 6) {
      return setError("Pass must be at least 6 chars");
    }
    if (pass.length > 32) {
      return setError("Pass must be at most 32 chars");
    }
    try {
      const response = await fetch("/api/members/changePassword", {
        method: "POST",
        body: JSON.stringify({
          pass,
        }),
      });
      const data = await response.json();
      console.log(data);

      //TODO: REDIRECT
    } catch (error) {
      alert("Something went wrong!");
    }
  };
```

**Comment by mrtornado** [comment]
nvm `return window.location.reload(false);` worked for me , seems I forgot I'm in an island :) guess window.location methods work :)

**Comment by hashrock** [comment]
how about generate `form` element and execute `form.submit()`?

```ts
function submit(){
  const form = document.createElement("form")
  form.action = '/search';
  form.method = 'POST';

  const formData = new FormData(form);
  formData.append('q', 'test');
  document.body.appendChild(form);

  form.submit()
}
```

**Comment by hashrock** [comment]
I feel this is more of a general question about web app coding than an issue with the framework itself.
I will close the Issue to keep this repo clean, but if you feel your problem has not been resolved, please reopen it.
