### ISSUE TITLE
Docs: Slideshow Island Demo

### ISSUE THREAD

**Issue by digitaldesigndj** [denoland/fresh#1085]
I have a slideshow Island and I was thinking about adding it to the Components section of the website. My island is on the larger side, so I am not sure if it belongs. Is there a vetting process?

The Demo
https://slides.deno.dev

The Island
https://github.com/Hyprtxt/slides.deno.dev/blob/main/islands/Slideshow.jsx

Also I just have a need to post this somewhere so people can find Fresh Slideshow code. 😸

**Comment by hashrock** [comment]
Great! feel free to add it to fresh components.
I think it might be a bit buried if you just post it on showcase.
