### ISSUE TITLE
Passing object from islands to server side ctx.state . Is it possible ? 

### ISSUE THREAD

**Issue by mrtornado** [denoland/fresh#1094]
I'm trying to pass an object from islands to ctx.state trought api , basically I want to pass some props from the cart to my backend... so I have the next functions: 
this is in an island in` /islands/Cart.tsx`: 
```javascript
  const handleCheckout = async () => {
    const response = await fetch("/api/setCart", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ cart: cartData.value }),
    });
```
From here I pass it to `/routes/api/setCart.ts` that looks like this: 
```javascript
export const handler: Handlers = {
  async POST(req, ctx) {
    const { cart } = await req.json();
    console.log("Before setting cart", ctx.state.cart);
    ctx.state.cart = cart;
    console.log("After cart set", ctx.state.cart);
    return new Response("Cart updated");
  },
};
```
Here the `console.log("Before setting cart", ctx.state.cart);` is empty and `console.log("After cart set", ctx.state.cart);` has the object set in it, but when I try to pull the ctx.state.cart again in `/routes/members/cart/locations.tsx` that looks like this: 

```javascript
export const handler: Handlers = {
  async GET(_req, ctx) {
    console.log(ctx.state.cart);
    const loc = await db
      .selectFrom("location")
      .selectAll()
      .execute();
```
so here the console.log is undefined. 
I don't know if it is even possible to do what I'm trying to do :) so if anybody can help that would be great. BTW I have no middleware that overwrites the ctx.state.cart object, but my middleware is adding other props to state. 
like this: 
``` javascript
 if (memberId && username) {
    ctx.state.memberId = memberId.split(".")[0];
    ctx.state.username = username.split(".", 2).join(".");
  }
```

**Comment by BernieSumption** [comment]
The `ctx.state` object holds state within a single HTTP request, so that you can for example pass objects from middleware to a handler function. It looks like you're setting state in one request and expecting it to be available in a later HTTP request? If so, that will not work. You need to save the cart information to the database in one request and retrieve it in the next.

**Comment by mrtornado** [comment]
I managed to do it using a utils function that sets an array on the ctx.state.cart: 
so in the end I need to setCart in 1 page and getCart in the next. If somebody needs it, just let me know.
