### ISSUE TITLE
deno-fresh-demo not working

### ISSUE THREAD

**Issue by MarybethGasman** [denoland/fresh#1098]
Deno 1.32.3
```sh
deno run -A -r https://fresh.deno.dev deno-fresh-demo
cd deno-fresh-demo
deno task start
```

```js
An error occurred during route handling or page rendering. Error: Build failed with 1 error:
error: Module not downloaded yet.
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.14.51/mod.js:1601:15)
    at https://deno.land/x/esbuild@v0.14.51/mod.js:1243:28
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.14.51/mod.js:1023:63)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.14.51/mod.js:1241:7)
    at https://deno.land/x/esbuild@v0.14.51/mod.js:1354:14
    at https://deno.land/x/esbuild@v0.14.51/mod.js:655:9
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.14.51/mod.js:752:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.14.51/mod.js:621:7)
    at https://deno.land/x/esbuild@v0.14.51/mod.js:1880:11
```

**Comment by dugi-x** [comment]
Same problem

```
Task start deno run -A --watch=static/,routes/ dev.ts
Watcher Process started.
The manifest has been generated for 3 routes and 1 islands.
Listening on http://localhost:8000/
✘ [ERROR] [plugin deno] Module not downloaded yet.

An error occurred during route handling or page rendering. Error: Build failed with 1 error:
error: Module not downloaded yet.
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.14.51/mod.js:1601:15)
    at https://deno.land/x/esbuild@v0.14.51/mod.js:1243:28
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.14.51/mod.js:1023:63)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.14.51/mod.js:1241:7)
    at https://deno.land/x/esbuild@v0.14.51/mod.js:1354:14
    at https://deno.land/x/esbuild@v0.14.51/mod.js:655:9
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.14.51/mod.js:752:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.14.51/mod.js:621:7)
    at https://deno.land/x/esbuild@v0.14.51/mod.js:1880:11
```
    
    
![image](https://user-images.githubusercontent.com/7407297/229532477-7c0439b9-345f-4967-a54e-d633d7ae86d9.png)

**Comment by JonatanAlcaraz** [comment]
I tried to run the same example and it returned the same thing

**Comment by kellenproctor** [comment]
I had this issue too, I have no idea how to fix it. Previous versions of deno seem to run the demo just fine, so this is clearly a v1.32.3 problem. You can downgrade your deno version to <1.32.3 and it should work.

To downgrade:
`deno upgrade --version 1.32.2`

**Comment by JonatanAlcaraz** [comment]
it still happens with the downgrade
```
~ $ deno --version

deno 1.32.2 (release, x86_64-unknown-linux-gnu)
v8 11.2.214.9
typescript 5.0.3

~ $ deno task start

Task start deno run -A --watch=static/,routes/ dev.ts
Watcher Process started.
The manifest has been generated for 3 routes and 1 islands.
Listening on http://localhost:8000/
✘ [ERROR] [plugin deno] Module not downloaded yet.

An error occurred during route handling or page rendering. Error: Build failed with 1 error:
error: Module not downloaded yet.
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.14.51/mod.js:1601:15)
    at https://deno.land/x/esbuild@v0.14.51/mod.js:1243:28
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.14.51/mod.js:1023:63)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.14.51/mod.js:1241:7)
    at https://deno.land/x/esbuild@v0.14.51/mod.js:1354:14
    at https://deno.land/x/esbuild@v0.14.51/mod.js:655:9
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.14.51/mod.js:752:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.14.51/mod.js:621:7)
    at https://deno.land/x/esbuild@v0.14.51/mod.js:1880:11
 ```

**Comment by kellenproctor** [comment]
@JonatanAlcaraz maybe try downgrading to 1.32.1?

I'm using 1.32.2 with no issues - Windows 11, WSL2, Ubuntu.

**Comment by Wolven531** [comment]
Getting this error on MacOS 10.15 using Deno 1.32.3.

Output of `deno --version`

```
deno 1.32.3 (release, x86_64-apple-darwin)
v8 11.2.214.9
typescript 5.0.3
```

Tried to downgrade via `deno upgrade --version 1.32.2`, and got the same error.

Downgraded to 1.32.1 via `deno upgrade --version 1.32.1` and the issue is resolved.

New output of `deno --version`

```
deno 1.32.1 (release, x86_64-apple-darwin)
v8 11.2.214.9
typescript 5.0.2
```

**Comment by JonatanAlcaraz** [comment]
@kellenproctor well i tried that version and it works. Thanks for the advice.

```
~ $ deno --version

deno 1.32.1 (release, x86_64-unknown-linux-gnu)
v8 11.2.214.9
typescript 5.0.2
```

**Comment by Wolven531** [comment]
I wonder if the issue is in TS 5.0.3. Because both Deno 1.32.3 and 1.32.2 use TS 5.0.3 but Deno 1.32.1 uses TS 5.0.2. 🤔

I can't see the TS 5.0.3 release on the repo release page - https://github.com/microsoft/TypeScript/releases nor that tag on the tags page - https://github.com/microsoft/TypeScript/tags

I do see a milestone of it here - https://github.com/microsoft/TypeScript/milestone/181, but it isn't complete and has no due date yet.

![image](https://user-images.githubusercontent.com/2125913/229650007-b30ee5db-bbb6-4905-9df6-2e25469a1472.png)

**Comment by Wolven531** [comment]
Also worth noting, once downgraded to Deno 1.32.1, you can upgrade again to 1.32.3 and it still works. @JonatanAlcaraz , @kellenproctor 

Some dep must get downloaded in Deno 1.32.1 that is a safe fallback version, so future Deno versions work after it is installed.

For future readers - workaround below:

```
deno upgrade --version 1.32.1
```

then

```
deno upgrade
```

**Comment by lifeofdan** [comment]
Just as an fyi, I had to do a 

`deno upgrade --version 1.32.1`

then

`deno task start` in the my project directory

then

`deno upgrade`

**Comment by demizer** [comment]
I had to uninstall the deno tool from my os package manager and install using the official curl bashing instructions so I could easily downgrade. Probably worth noting that on the official docs somewhere since minor point releases can still break things at this stage.

**Comment by hashrock** [comment]
Does this still happen with latest deno?

**Comment by MarybethGasman** [comment]
@hashrock It works fine now.

**Comment by ooker777** [comment]
I get this error with the latest version 1.39.1 with a [different repo](https://github.com/jiawei397/yaml_to_ts_web/issues/1)

**Comment by marvinhagemeister** [comment]
@ooker777 That's great that you are on the latest Deno version. Have you also updated Fresh to `1.6.1`? I recall having fixed that issue a while ago by upgrading esbuild. Looking at the trace in the linked issue it seems like you're on an older version of Fresh. Can you try upgrading to `1.6.1`?

**Comment by ooker777** [comment]
It works now thanks.

[Updating Fresh | Fresh docs](https://fresh.deno.dev/docs/concepts/updating "Updating Fresh | Fresh docs")
