### ISSUE TITLE
Performance hit after twind v1 migration

### ISSUE THREAD

**Issue by tlgimenes** [denoland/fresh#1116]
Hi folks.

I was giving twind v1 a shot after fresh@1.1.5 got released. After migrating, I realized that my app's total blocking time got 4x bigger. As a sanity check, I've [forked](https://github.com/tlgimenes/fresh) fresh's www and migrated it to twind v1 and I saw the same slowdown. 

As evidence, here are the differences in profiling between twindv0 and twindv1:
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/1753396/232235268-bc29bb48-ae0f-44b7-a187-92023cff4abf.png">

<img width="1508" alt="image" src="https://user-images.githubusercontent.com/1753396/232235133-fbf57722-6e8f-4925-85fe-717d22d407ab.png">

As you can see, twind v1 has a huge new executing block right after fresh's revive function. This is a HUGE increase and really kills any hope of having a nice lighthouse score (mine went down around 10points). Also, I noticed that the JS generated by the twind plugin is around 15Kb whereas the `www` website has 32Kb of JavaScript in total, i.e. twind is around 50% of all JavaScript on the page.

I know this is probably a twind issue and not due to fresh, however, I'd like to bring this issue up. Also, I'd like to know your opinions on ditching twind on the client side and focusing on a server only alternative. My ideal solution would be:

1. No JS shipped to the browser
2. all CSS is generated on the server
3. Only the CSS for that page (components + islands) is delivered to the browser. 

I think these 3 principles would be an approach more in line with the fresh philosophy of not delivering unnecessary JS to the browser. A possible implementation would be to use postcss on the esbuild bundler for generating islands -> css map and something else for the rest of the page.

What do you think? Are you having the same issues with twind v1? Are you also bothered by the fact of delivering 15Kb of JS to the browser only by using tailwind classes on fresh?

cheers!

**Comment by marvinhagemeister** [comment]
Thanks for bringing this up. The performance slowdown is a bit of a bummer and so is having to send JS to the browser to make CSS work. That shouldn't be necessary and generating CSS on the server is preferable. It would fit fresh's philosophy much more of not shipping unnecessary JS to the browser like you mentioned.

Doing this requires some form of preprocessing to detect which class names are used in JS. To me that's one of the missing pieces in fresh that would also unlock a couple of Preact-specific optimizations as well as open up the door for HMR and other developer facing features.

**Comment by lveillard** [comment]
One of the cool things of twind is being able to mutate style at runtime. So receiving the processor in the browser helps for that unique particularity of twind.

By the way not related but migrating to twindv1 plugin, the `w-full` of a Fresh fresh installation stops working.

**Comment by rschristian** [comment]
> One of the cool things of twind is being able to mutate style at runtime. So receiving the processor in the browser helps for that unique particularity of twind.

You don't necessarily need Twind in the client to facilitate that, however. You can build a (static) list of classes on the server and ship to the client, though obviously you're restricted in the same way that Tailwind is regarding templating (can't get away with `bg-${color}-500` easily).

In the off chance it's of any use, I'll drop [this](https://github.com/rschristian/tailwind-grouping/tree/master/packages/babel) here. Probably some edge cases & not the most refined thing, but you might need something along these lines if Fresh does go the way of static extraction; will need to get those grouped class names out of any client-side JS.

**Comment by marvinhagemeister** [comment]
Closing this as we've switched to Tailwind CSS which allows us to compile the style sheet ahead of time and move it out of the render path. The Tailwind CSS plugin will be released in the next Fresh 1.6 version which I'm hoping to release later this week.

**Comment by lveillard** [comment]
> Closing this as we've switched to Tailwind CSS which allows us to compile the style sheet ahead of time and move it out of the render path. The Tailwind CSS plugin will be released in the next Fresh 1.6 version which I'm hoping to release later this week.

Understood, thanks. How to do runtime style changes after that?

**Comment by rschristian** [comment]
> Understood, thanks. How to do runtime style changes after that?

It generally works in a pretty similar way, except all classes need to be discoverable at build time, you cannot rely on interpolation (`x ? 'bg-blue-500' : 'bg-red-500'` instead of `bg-${x ? 'blue' : 'red'}-500`, for example). [Docs](https://tailwindcss.com/docs/content-configuration#dynamic-class-names)

Switching of classes/style should work the same otherwise.

**Comment by marvinhagemeister** [comment]
>> Closing this as we've switched to Tailwind CSS which allows us to compile the style sheet ahead of time and move it out of the render path. The Tailwind CSS plugin will be released in the next Fresh 1.6 version which I'm hoping to release later this week.
>
> Understood, thanks. How to do runtime style changes after that?

With TailwindCSS there is no need for that, as all potential class names are extracted ahead of time. Only requirement is like @rschristian showed that Tailwind tokens must not be split apart by string interpolation or other things.
