### ISSUE TITLE
✘ [ERROR] [unreachable] Not an ESM module. [plugin deno]

### ISSUE THREAD

**Issue by joansebgarcia** [denoland/fresh#1117]
![freshbug](https://user-images.githubusercontent.com/116913262/232596336-e74b82cc-f48e-4b3e-8189-17ef570d9388.png)

When trying to build a project in Deno the esbuild library throws an error stating **"[unreachable] Not an ESM module"**. The error occurs during route manipulation or page rendering.

**Comment by sebastian009w** [comment]
![freshbug](https://user-images.githubusercontent.com/116913262/232595967-d5646f6e-4220-494d-9b3e-953a759319f2.png)

**Comment by guillermocalleja** [comment]
I got the same error. I have created a new project and when I add a component to the islands folder I get this error if I move the component to the component folder, everything works fine.

![fresh-error](https://user-images.githubusercontent.com/101449523/232744914-50d84ab3-7b72-49c9-b4c6-c70ce441f8f7.png)

**Comment by hashrock** [comment]
Do you have the same problem with deno 1.32.5?

**Comment by guillermocalleja** [comment]
Hi, I was using deno 1.32.3. I have just upgraded to deno 1.32.5, tested it and everything works perfectly now. 
SOLVED!!!
Many thanks for your help!!!
