### ISSUE TITLE
Trailing slash redirect doesn't work as expected with CDNs

### ISSUE THREAD

**Issue by dasmeet** [denoland/fresh#1121]
I have a fresh app installed on Deno deploy, say xyz.deno.dev

I am then using Bunny CDN with mysite.com as primary domain with xyz.deno.dev as origin. 

Everything else works fine. CDN fetches from xyz.deno.dev and servers on mysite.com.

However, when I open mysite.com/category/ , it should redirect to mysite.com/category (without slash).

Instead it redirects to **xyz.deno.dev**/category 

Is there a way to configure the trailing slash redirect to use relative redirect? Or to specify a base url to redirect to?

**Comment by iuioiua** [comment]
Hi @dasmeet, we just pushed #1024 which would've fixed this issue. Are you able to confirm?
