### ISSUE TITLE
Refactor: To use the esbuild plugin for preact instead

### ISSUE THREAD

**Issue by barelyhuman** [denoland/fresh#1126]
Hey, 

This is with regards to moving to the plugin https://github.com/barelyhuman/preact-island-plugins, which while being in development handles the islands based on the file extensions instead of a specific folder for islands. 

I could be biased here but it'd be better dx if any file anywhere could be an island. 

There's also a [tiny demo repo](github.com/barelyhuman/prev) which tries to implement something similar to fresh with twind.style. 

Would like to know your thoughts about this.

**Comment by marvinhagemeister** [comment]
Let's track the ability to use any file as an island in #1486 . I'm general I'm hesitant to take on dependencies for core features that are Fresh specific. This makes maintenance harder as we'd need to switch between repositories constantly.
