### ISSUE TITLE
[Chrome] SVG does not render

### ISSUE THREAD

**Issue by thorwebdev** [denoland/fresh#1130]
Strangely on Chrome [my SVG](https://thor.bio/logo.svg) does not render. It renders fine on Firefox and Safari. Any ideas why and if I can fix on my end? I've confirmed that this also happens for others both across desktop and mobile. 

![image](https://user-images.githubusercontent.com/5748289/234182473-52465b36-d46f-4b04-bc22-135bb168cd37.png)

Details: https://www.whatsmybrowser.org/b/2Y8UZ
* Version 112.0.5615.137 (Official Build) (arm64)
* macOS 13.2.1 (22D68)

**Comment by huai-jie** [comment]
try direct render from your svg

replace 
```
<picture class="block mt-4 md:mt-0">
     <img src="/logo.svg?__frsh_c=1cv5020ef8q0" class="w-80 mx-auto" width="800" height="678" alt="Thor Hammer">
</picture>
```

to (your SVG)
```
<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="700" height="700" viewBox="0 0 700 700">
    <image id="thorwebdev_standard" x="87" y="19" width="526"  height="662" xlink:href....../>
 </svg>
 ```
 
 You could open `Icons.tsx` file & then export it as function as well , refer to this https://github.com/denoland/fresh/blob/main/www/components/Icons.tsx.

**Comment by thorwebdev** [comment]
@huai-jie thanks, but I don't think that's a reasonable thing to do. 

The Deno Fresh website uses the same approach: https://github.com/denoland/fresh/blob/main/www/routes/index.tsx#L157-L165

So it should work. So I think this should be treated as a bug.

**Comment by huai-jie** [comment]
I see, but I still don't think it is a bug from Fresh.

It could be the incorrect HTML data type format in your SVG file.

Refer to this
> https://www.w3.org/TR/html4/types.html [ Content types (MIME types) section ]


Okay, here is another potential solution: correct your HTML data type

replace

`xlink:href="data:img/...`  in the image tag of your svg file

to 

`xlink:href="data:image/...`  

It should resolve the issue. 

Anyway, please correct me if I'm misunderstood or wrong*

**Comment by thorwebdev** [comment]
That indeed did the trick, thank you so much @huai-jie ! I guess deno fresh just does things according to proper spec 👍 I'll close this out, but am sure it will be a helpful resource for others in the future, thank you!
