### ISSUE TITLE
fresh.gen.ts is no longer auto generating

### ISSUE THREAD

**Issue by JacobWeisenburger** [denoland/fresh#1132]
I don't get any warnings or errors, it's just not updating `fresh.gen.ts`.

How do I make dev mode auto update `fresh.gen.ts` again?

```ts
{
    "imports": {
        "$fresh/": "https://deno.land/x/fresh@1.1.5/",
    }
}
```

**Comment by hashrock** [comment]
Could you provide minimal reproduction repo?

**Comment by JacobWeisenburger** [comment]
apparently if you move `dev.ts` to a different dir, then it prevents `fresh.gen.ts` from auto generating. I moved `dev.ts` to my `scripts` dir, because arguably, it is a script.

So moving `dev.ts` back to the root dir fixed the issue. Perhaps this should be documented or something.

**Comment by lino-levan** [comment]
The whole fresh manifest generation is pretty fragile. I'd like to move away from hardcoding certain file positions in the code (such as the import map), but it's quite troublesome to actually do that.

**Comment by marvinhagemeister** [comment]
Closing as moving around `dev.ts` files is not a supported scenario. Fully agree that it is a bit fragile, but it's a necessary evil to make the "no build mode" work.

Closing, as there is nothing for us to do here.
