### ISSUE TITLE
Fresh Islands and twind classes error

### ISSUE THREAD

**Issue by benjaminviaud** [denoland/fresh#1135]
Hello,

OS version : MacOS Catalina 10.15.7
Deno version : 1.33.0
Fresh version : 1.1.5

When i tried to used twind classes in islands sometimes the classes in <style id="__FRSH_TWIND"> are not in good order.

Exemple when it's work fine (component not in islands folder) :
![image](https://user-images.githubusercontent.com/25077689/235089340-ac3e0e10-3797-45de-8473-71df36d1729f.png)

Same exemple, I just move the components in islands folder :
![image](https://user-images.githubusercontent.com/25077689/235089786-6c99e5e7-d86a-426c-b78e-ab6f48f5faed.png)

Thanks for your reply and for your work.

Have good day

**Comment by marvinhagemeister** [comment]
Thanks for filing an issue. It's a bit hard for me to reproduce the error based on the screenshots alone. Can you share a github repository or something similar where the error is visible?

**Comment by marvinhagemeister** [comment]
Closing because we haven't heard back from the issue author.

**Comment by benjaminviaud** [comment]
Hi @marvinhagemeister,

I'm in the process of setting up a github repository.
I'll get back to you soon.

Sorry for the delay

Thank you for your understanding.

**Comment by benjaminviaud** [comment]
Hello @marvinhagemeister,

You can close this ticket.
The problem is solved.

I didn't use the tw() function in the class attributes (eg class={tw`p-0 lg:p-3 lg:flex lg:basis-auto`})

Regards

**Comment by marvinhagemeister** [comment]
@benjaminviaud happy to hear that the issue is resolved. Thanks for getting back to us 👍
