### ISSUE TITLE
Broken Dockerfile in deployments.md

### ISSUE THREAD

**Issue by George-Spanos** [denoland/fresh#1136]
Just going though Fresh documentation, I believe just by following the documentation and trying to create the Dockerfile as described in [deployments](https://fresh.deno.dev/docs/concepts/deployment) i get the 

```
✘ [ERROR] Deno.Command is not a constructor [plugin deno]

✘ [ERROR] Deno.Command is not a constructor [plugin deno]

✘ [ERROR] Deno.Command is not a constructor [plugin deno]
```

**Cause**:
It seems that `FROM denoland/deno:1.25.0` is the issue in the Dockerfile

**Proposed Solution**
Bump up Dockerfile version to ^1.32.0

PS: If you verify this issue I can of course create the PR :)

**Comment by lino-levan** [comment]
Makes sense, if you can, please open a PR!
