### ISSUE TITLE
Change BUILD_ID to not use DENO_DEPLOYMENT_ID

### ISSUE THREAD

**Issue by innovatedev-john-pope** [denoland/fresh#1142]
DENO_DEPLOYMENT_ID gives access to old builds on Deno Deploy. It should not be exposed publicly.

Context:

The fresh.deno.dev source code has a JavaScript URL that exposes the deployment ID:
/_frsh/js/xv0bcetb883g/plugin-twind-main.js

This can lead to the discovery of old builds if the page source is cached, such as: https://fresh-xv0bcetb883g.deno.dev/

Using a site like the Internet Archive's Way Back Machine, it is trivial to find builds for any site that has any pages built with Fresh in the archive.

For example: looking at this snapshot from June 2022, I find the deployment id and can pull up that build still:

view-source:https://web.archive.org/web/20220613114408/http://fresh.deno.dev/
https://fresh-0npz6ckppgeg.deno.dev/

Code that causes the issue:

https://github.com/denoland/fresh/blob/f481c1a03fc3e194efa0fe0fb0c5e568cd2994f7/src/server/constants.ts#L5

**Comment by kt3k** [comment]
I think we should use some digest function to generate BUILD_ID to obscure DENO_DEPLOYMENT_ID

**Comment by lino-levan** [comment]
I think this makes sense, but confused on what the danger is of finding old builds of the site? Is it just undesirable? If there is a security issue with an old version, I assume that relevant actions must be taken anyways to patch out the issue (revoking API keys, etc), so I'm not quite sure what the advantage of this is.

**Comment by innovatedev-john-pope** [comment]
You are correct. However, I don't think there is a good argument as to why a framework should be revealing an identifier to old builds automatically. As a developer who uses Fresh, this was an unexpected and is an undesirable consequence of using this framework on Deno Deploy.

All that this really is for is making cache busting simpler and there are alternatives like hashing the deployment id that would accomplish the same thing without unnecessarily revealing build IDs publicly. Making sure the build ID does not match the deployment ID removes Fresh from the equation.

Ideally Deno Deploy would allow you to turn off old builds, or at least delete specific ones if they were issues in any way, but that doesn't really change anything about what I would expect from a framework. A framework shouldn't be making the decision to publicly publish something like this for me.

**Comment by lino-levan** [comment]
Completely agree, I misunderstood your original point. This seems more than reasonable. Thanks for opening an issue (and a PR)!
