### ISSUE TITLE
Error when handling file upload with `PUT`

### ISSUE THREAD

**Issue by sntran** [denoland/fresh#1148]
## Describe the issue

I have some issue with building a island for file upload in Fresh. The PUT route handler throws ERR_CONNECTION_RESET on submission.

## How to reproduce

- Creates a new Fresh project.
- Adds the following `PUT` handler to "routes/index.ts"

```ts
export const handler: Handlers = {
  PUT(request: Request) {
    return new Response(null, {
      status: 307,
      headers: {
        "Location": "https://httpbin.org/put",
      },
    });
  },
};
```

- Updates "islands/Counter.ts" to:

```ts
export default function Counter(props: CounterProps) {
  const [files, setFiles] = useState<FileList | null>(null);

  const submit = async (event: Event) => {
    event.preventDefault();
    await fetch(event.target.action, {
      method: "PUT",
      body: files![0], // This doesn't work
      // body: "Hello World", // This works
    });
  }

  return (
    <form
      method="PUT"
      onSubmit={submit}
    >
      <input type="file" onChange={({target}) => setFiles(target.files)} />
      <Button type="submit">Upload</Button>
    </form>
  );
}
```

- Opens `http://localhost:8000`
- Select a file from your file system
- Click "Upload".
- Check the browser's Dev console for error.

I have created an example Fresh project that can reproduce the issue: https://github.com/sntran/gdrive

**Comment by kt3k** [comment]
I was able to make `PUT` request with your example repo:

<img width="1364" alt="Screenshot 2023-05-04 at 14 19 51" src="https://user-images.githubusercontent.com/613956/236118131-2eb60a4d-55d5-420e-b0e8-9cd5843efb6a.png">

Maybe `httpbin.org` had a temporary issue?

**Comment by sntran** [comment]
That's weird. Would you mind trying with bigger files? I was able to run with files less than 200KB. More than that and I see the error.

**Comment by innovatedev-john-pope** [comment]
I tried with a large file. It was slow... 7minutes, but it worked. Doesn't appear to be an issue with Fresh.

![image](https://github.com/denoland/fresh/assets/88814278/122e5eb0-bb4f-423e-a8f6-743b93cc313e)

**Comment by marvinhagemeister** [comment]
Works for me as well. I can't reproduce the described issue. One thing of note is that the `PUT` handler drops the `body` with the files of the incoming request. I had to change it to:

```diff
  export const handler: Handlers = {
    PUT(request: Request) {
-     return new Response(null, {
+     return new Response(request.body, {
        status: 307,
        headers: {
          "Location": "https://httpbin.org/put",
        },
      });
    },
  };
```

**Comment by sntran** [comment]
Sounds like it's some misconfiguration on my end. Thanks everyone for testing!
