### ISSUE TITLE
Preloading JavaScript files (`link rel="modulepreload"`)

### ISSUE THREAD

**Issue by ayame113** [denoland/fresh#1187]
I would like to bring back [JavaScript preloading](https://developer.chrome.com/blog/modulepreload/) which has been disabled since #97.

https://github.com/denoland/fresh/blob/b9db46eccb9eb49fdcc040c044b99407b27e71b0/src/server/bundle.ts#L112-L118

Preloading helps avoid [critical request chains](https://developer.chrome.com/docs/lighthouse/performance/critical-request-chains/), so it should speed up loading.

related: #14, #15, #497, #741

**Comment by iuioiua** [comment]
A PR would be welcome 😄

**Comment by ayame113** [comment]
I think it probably worked, I'll file a PR later! 😄
![image](https://github.com/denoland/fresh/assets/40050810/b8261460-ffd5-4f7f-ba4b-2718cc0e73cb)

**Comment by iuioiua** [comment]
Nice! A performance comparison before and after would be nice too.
