### ISSUE TITLE
Bug: Fresh does not work on MacOS

### ISSUE THREAD

**Issue by emilkrebs** [denoland/fresh#1194]
When running `deno task start` or when creating a new fresh project, I always get the same error message:
<img width="677" alt="image" src="https://github.com/denoland/fresh/assets/68400102/6ffda5c4-4e15-4bcd-bc50-57bb9ec6e268">

however, this error does not show up on Windows.

I installed deno using: `brew install deno` 
```
deno 1.26.1 (release, x86_64-apple-darwin)
v8 10.7.193.3
typescript 4.8.3
```

and I am running `MacOS Ventura 13.3.1` 
on a `MacBook Pro 2017`

**Comment by iuioiua** [comment]
What does `deno --version` print?

**Comment by emilkrebs** [comment]
```
$ deno --version
deno 1.26.1 (release, x86_64-apple-darwin)
v8 10.7.193.3
typescript 4.8.3
```

**Comment by iuioiua** [comment]
Please upgrade Deno to the latest version. You're on an old version that doesn't have the `Deno.Command` API.

**Comment by emilkrebs** [comment]
Thanks @iuioiua upgrading deno using `curl -fsSL https://deno.land/x/install/install.sh | sh` fixed it. 
Seems like `brew install deno` did not install the latest version.
