### ISSUE TITLE
路由，中间件问题，如何自定义路由

### ISSUE THREAD

**Issue by gaojishu** [denoland/fresh#1202]
随着业务越来复杂，需要自定义路由

**Comment by lino-levan** [comment]
Google Translate says:
- Title: Routing, middleware issues, how to customize routing
- Description: As the business becomes more and more complex, custom routing is required

Not sure how actionable of an issue this is. What specifically are you requesting?

**Comment by gaojishu** [comment]
项目介绍：比如要做一个b2b2c项目，可能涉及到几百接口和页面，几十个中间件。

mvc：在传统的mvc框架中，可以在控制器创建3个目录用来区分后台，商家，用户。
然后用自定义路由链接控制器，路由分组。

中间件：中间件可以作用于全局或路由组，结构清晰，便于理解。

Fresh路由和控制器不能分离，随着项目功能越来越多，就很难受。

最近在学习新的框架和技术，刚接触deno，fresh，还是比较认同的。

目前deno没有复杂项目的方案和框架。考虑使用nodejs框架。

**Comment by lucacasonato** [comment]
Hey, thanks for taking the time to open an issue on the Fresh repo. We currently only take issues in english. If you are not a native english speaker, you can use a translation service like Google Translate to convert from your native language to english before posting.

Thanks!
