### ISSUE TITLE
proposal(docs): examples section

### ISSUE THREAD

**Issue by iuioiua** [denoland/fresh#1204]
Like https://deno.com/manual/examples, but for Fresh. I imagine things like https://github.com/denoland/fresh/issues/527#issuecomment-1190379084 to be included.

This will be snippets-based and replace the bringing on of more examples in the `examples` folder. Reason-being is the maintenance incurred by having multiple fully-fledged Fresh apps in the `examples` folder.

Related: #1212

**Comment by lino-levan** [comment]
This makes a ton of sense. Huge +1 from me.
