### ISSUE TITLE
useState not working in _app.tsx

### ISSUE THREAD

**Issue by techpanga** [denoland/fresh#1209]
useState not working in _app.tsx, just to show or hide menu on clicking a button. So moved my menu handling code to islands. 

Including islands and passing <Component /> as children to the island causing below error.

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property '__c' -> object with constructor 'Object'
    --- property '__v' closes the circle
    at JSON.stringify (<anonymous>)
    at render (https://deno.land/x/fresh@1.1.6/src/server/render.ts:280:33)
    at eventLoopTick (ext:core/01_core.js:182:11)
    at async https://deno.land/x/fresh@1.1.6/src/server/context.ts:501:24

Am I missing anything here , please advise.

**Comment by kamilogorek** [comment]
Please provide a repro case that can be used for debugging this issue, thanks!

**Comment by huai-jie** [comment]
> Including islands and passing as children to the island causing below error.

Ya, you can't pass `island` as children to another `island`

Refer to this: https://fresh.deno.dev/docs/concepts/islands
> This means that it is not possible to pass children to an island, as children are VNodes, which are not serializable.

You could try this:
- Including your `Menu` components and its `js` handling code to an island i.e `islands/Menu.tsx` 
- Then import it in `_app.tsx`

```
// routes/_app.tsx

import { AppProps } from "$fresh/server.ts";
import Menu from "../islands/Menu.tsx";

export default function App({ Component }: AppProps) {
  return (
    <div class="wrapper">
     <Menu />
      <Component />
    </div>
  );
}
```

**Comment by techpanga** [comment]
> > Including islands and passing as children to the island causing below error.
> 
> Ya, you can't pass `island` as children to another `island`
> 
> Refer to this: https://fresh.deno.dev/docs/concepts/islands
> 
> > This means that it is not possible to pass children to an island, as children are VNodes, which are not serializable.
> 
> You could try this:
> 
> * Including your `Menu` components and its `js` handling code to an island i.e `islands/Menu.tsx`
> * Then import it in `_app.tsx`
> 
> ```
> // routes/_app.tsx
> 
> import { AppProps } from "$fresh/server.ts";
> import Menu from "../islands/Menu.tsx";
> 
> export default function App({ Component }: AppProps) {
>   return (
>     <div class="wrapper">
>      <Menu />
>       <Component />
>     </div>
>   );
> }
> ```

Thank you for the explanation. The page shared has the rules of islands. 

Counter is simple example. Many web components need to pass the children and to render using reusable components. If islands do not support the reusability via children (example: like Sortable to sort the children using DnD), and do not intended for complex web components, what is the alternative/right approach using deno fresh to implement reusability. 
Looks like, i am missing some key understanding here. Please help.

Plan html node/elements are working as child components to islands.

I am able to envision the serialization need for route pages, Is there a reason islands are not designed to be children of other islands?

I tried to use existing DnD frameworks but could not because npm: specifiers are not supported and started to implement my own from scratch.

thanks in advance.

**Comment by lucacasonato** [comment]
Passing JSX nodes to islands will eventually be supported - it just isn't yet.

This would allow the use case you are envisioning. For now, you can create an island that wraps your "Sortable" component with it's children.

**Comment by TheYuriG** [comment]
I don't know if my use case fits the reason why this issue was opened, but I've got the same error trying to use a Component inside an Island. I don't recall having this issue before. This is a micro example of what I had:

`/islands/CartButton.tsx`
```ts
import CartIcon from "../../assets/CartIcon.tsx";
import AccentButton from "../../islands/AccentButton.tsx";

//? Define Cart Button properties
interface CartButtonProperties {
  pulseState: boolean;
  openModal: () => void;
  totalItems: number;
  cost: number;
}

//? Renders a cart button that will open the cart modal
export default function CartButton({
  pulseState,
  openModal,
  totalItems,
  cost,
}: CartButtonProperties) {
  return (
    <AccentButton
      //? Adds the pulsing animation when a food item is added
      style={pulseState
        ? "animation: pulseCartOnItemAdd 0.3s ease-in-out;"
        : ""}
      onClickFunction={openModal}
    >
      <span class="cart-total-items">
        <CartIcon />
        {totalItems}
      </span>
      <span>${cost.toFixed(2)}</span>
    </AccentButton>
  );
}
```
that file imports:

`/assets/CartIcon.tsx`
```ts
import { IconProperties } from "../types/IconProperties.ts";

export default function CartIcon(
  { iconHeight, iconWidth, iconColor }: IconProperties,
) {
  return (
    <svg
      xmlns="http://www.w3.org/2000/svg"
      height={iconHeight ?? "1em"}
      width={iconWidth ?? "1em"}
      viewBox="0 0 576 512"
      fill={iconColor ?? "var(--neutral-color)"}
    >
      <path d="M0 24C0 10.7 10.7 0 24 0H69.5c22 0 41.5 12.8 50.6 32h411c26.3 0 45.5 25 38.6 50.4l-41 152.3c-8.5 31.4-37 53.3-69.5 53.3H170.7l5.4 28.5c2.2 11.3 12.1 19.5 23.6 19.5H488c13.3 0 24 10.7 24 24s-10.7 24-24 24H199.7c-34.6 0-64.3-24.6-70.7-58.5L77.4 54.5c-.7-3.8-4-6.5-7.9-6.5H24C10.7 48 0 37.3 0 24zM128 464a48 48 0 1 1 96 0 48 48 0 1 1 -96 0zm336-48a48 48 0 1 1 0 96 48 48 0 1 1 0-96z" />
    </svg>
  );
}
```
(not going to display `IconProperties` since not relevant, but all interface properties are of type `string`). This setup allowed me to have commonly used SVGs reusable through my app without code duplication but caused the issue above.

**Edit:** is there a code playground for `Fresh` where I could create a repro without having to open another repository?

What worked for me was replacing `CartIcon` (as a `JSX.Element`) and using it as a `function` instead:
in `/islands/CartButton.tsx`, replaced `<CartIcon />` with `{CartIcon({})}`

This allowed my page to render as normal.

Github repo [here](https://github.com/TheYuriG/deno-portfolio), live version [here](https://www.theyurig.com/projects/food-order).

**Edit 2:** Weirdly enough, I was able to render another SVG icon inside another Island just fine. I guess my problem wasn't the same as OP, despite being somewhat connected? Regardless, hopefully what I did helps other people as it helped me.

**Comment by kamilogorek** [comment]
>Edit: is there a code playground for Fresh where I could create a repro without having to open another repository?


@TheYuriG https://deno.com/deploy/docs/playgrounds

**Comment by TheYuriG** [comment]
> > Edit: is there a code playground for Fresh where I could create a repro without having to open another repository?
> 
> @TheYuriG https://deno.com/deploy/docs/playgrounds

Am I blind or isn't there a playground button for me?
![image](https://github.com/denoland/fresh/assets/63727493/24b4afef-742a-4ea1-86b4-e1a09f29f151)
I was able to fork a base project, but that created a repository on my account which is exactly what I didn't want. I just want to be able to create a repro without needing to have this forever [attached to my github profile for posterity/historical reasons](https://github.com/TheYuriG/mongoose-map-saving-issue).

Essentially like a CodePen or a CodeSandbox where I can just give a link that will have display and source code side by side without forcing a clone+run.

**Comment by deer** [comment]
<img width="1174" alt="Screen Shot 2023-06-10 at 08 50 25" src="https://github.com/denoland/fresh/assets/1494757/66e5ecf4-6afe-4109-9376-3bfa2c5d27bd">
When you click on New Project you should then have the option to go into a playground.

**Comment by TheYuriG** [comment]
> When you click on New Project you should then have the option to go into a playground.

Nope, just shows the templates for me or deploy an existing GitHub repo. Do I need to be logged off?

EDIT: I don't know why it works that way, but the Template options for `Fresh`, `Fresh+KV`, `Oak` will prompt to start a repo, while the options for `Hello World` and `JSX Example` will start a playground. I guess I have no option but to create useless repos if I want to make a repro. Thanks for your time either way.

**Comment by deer** [comment]
> EDIT: I don't know why it works that way, but the Template options for `Fresh`, `Fresh+KV`, `Oak` will prompt to start a repo, while the options for `Hello World` and `JSX Example` will start a playground. I guess I have no option but to create useless repos if I want to make a repro. Thanks for your time either way.

Ok, I see what you mean now, so I checked the changelog. They announced it at the beginning of the month: https://deno.com/deploy/changelog#new-project-creation-flow

**Comment by iuioiua** [comment]
I've created [an issue](https://github.com/denoland/deploy_feedback/issues/401) regarding this new behaviour surrounding playgrounds in Deno Deploy. I agree, it can be improved.
