### ISSUE TITLE
How to navigate to another page without refresh page?

### ISSUE THREAD

**Issue by skorotkiewicz** [denoland/fresh#1210]
I don't see that Fresh have `<Link>` component, then, how we navigate throw app without `<a>` and losing state?
PS. I have already a state management, but I need a `<Link>` component to not refresh page.

**Comment by lifegpc** [comment]
You can do it with `useState` and `useEffect`.
Here is a example: https://github.com/lifegpc/eh-downloader/blob/0ab1c45bdcf30421408a01a2c04987231fe19213/islands/Container.tsx#L22

**Comment by lucacasonato** [comment]
Navigation always requires a full page reload. If you want to tie some URL state to part of your application, you can use `location.replace` and `#` navigations.
