### ISSUE TITLE
proposal(docs): add an example of how to modify `<head />` element

### ISSUE THREAD

**Issue by iuioiua** [denoland/fresh#1215]
I.e. using the `<Head />` element.

**Comment by DanielXing1103** [comment]
Hi, I am new to this repo. Do you mean to modify the HTML <head /> tag like this?
 <Head>  
        <title>Fresh App</title>
        _<p>Fresh App</p>_
 </Head> 
Or you mean there is a different <Head /> element specifically in this framework.

**Comment by iuioiua** [comment]
In Fresh, the `<Head />` component is used to modify the `<head />` element. An example can be seen [here](https://github.com/denoland/saaskit/blob/main/components/Head.tsx).

**Comment by DanielXing1103** [comment]
Hi, I am new to this repo. Do you mean to add an example of modifying the HTML <Head /> element like in default index.tsx or do you mean there is a different <Head /> element specifically in this framework?

**Comment by iuioiua** [comment]
Fresh has a `<Head />` component located in `/runtime.ts`. When you modify the inner portion of this, you modify the `<head />` element of the current page. Yes, this is what's done in the default route, `routes/index.tsx` of the demo app:
```ts
import { Head } from "$fresh/runtime.ts";
import Counter from "../islands/Counter.tsx";

export default function Home() {
  return (
    <>
      <Head>
        <title>Fresh App</title>
      </Head>
      <div>
        <img
          src="/logo.svg"
          width="128"
          height="128"
          alt="the fresh logo: a sliced lemon dripping with juice"
        />
        <p>
          Welcome to `fresh`. Try updating this message in the
          ./routes/index.tsx file, and refresh.
        </p>
        <Counter start={3} />
      </div>
    </>
  );
}
```

**Comment by DanielXing1103** [comment]
Thank you very much for the explanation.
