### ISSUE TITLE
proposal(docs): add an example of how to work with Supabase Auth

### ISSUE THREAD

**Issue by iuioiua** [denoland/fresh#1217]
This would be a helpful guideline: https://github.com/thorwebdev/everydaylytics

**Comment by mcgear** [comment]
Is something like this what you had in mind?
https://dev.to/morlinbrot/simple-auth-with-denos-fresh-supabase-2e68

**Comment by iuioiua** [comment]
The repo I provided in the initial comment is a better example. It's more up-to-date and takes advantage of PKCE.

**Comment by morlinbrot** [comment]
No way, I was just randomly browsing through the issues and see my little project mentioned here.

I was always planning to evolve that original project a little and I think this shall be the moment. Give me some time to do some reading (and let me actually find time next to work & family) and I would be glad to contribute something to the docs of this wonderful project!

**Comment by morlinbrot** [comment]
Quick heads up that I now finally found the time to get into this again, should have something up at the end of the week.

**Comment by morlinbrot** [comment]
PR is up, lmk what you think!
