### ISSUE TITLE
`fresh manifest --watch`

### ISSUE THREAD

**Issue by lucacasonato** [denoland/fresh#124]
What are your thoughts re: a new `--watch` option for `fresh manifest`?

If you think it’s worth exploration, do you suppose it’d be dependent or complementary to the stated issue? (i.e. Could they be worked on in parallel?)

(BTW, I really admire your’s and others’ work on this project—especially the JIT bundler. Truly liberating DX.)

_Originally posted by @tylerbrostrom in https://github.com/lucacasonato/fresh/issues/123#issuecomment-1061215053_

**Comment by lucacasonato** [comment]
Yup, that sounds like a great feature. I assume it will essentially involve wrapping the core functionality of `fresh manifest` with a file watcher from `Deno.watchFs()`.

**Comment by thegaryroberts** [comment]
@lucacasonato this is a very useful feature thank you! However it has lead onto a few new issues/items:

- The project scaffolding doesn't add this command automatically.
- The documentation is missing an explanation of this.
- It might be helpful to mention the created deno.json file on the "Create a project page" (for inexperienced users).
- The Counter example isn't as easy to replicate locally now if it lives outside the Fresh source code structure (1)
 
When I attempted implementation in my own projects it lead to a few more issues. Some of these might be limitations of the new deno task runner or my misunderstanding/documentation. I thought I would list them here in case you were aware of a solution or upcoming support in Deno.

- I couldn't find a shorthand to reference deno bin executables in tasks (I was sure this was a feature, but cannot find a mention of it here: https://deno.land/manual@v1.20.1/tools/task_runner) 
- When targeting my home directory (for ~/.deno/bin) it doesn't appear that tilde ~ expansion is implemented (would be nice, but I understand this might cause cross compatibility issues).
- When I put the full home directory to the fresh executable it resulted in this error:
_error: The module's source code could not be parsed: Expected ';', '}' or <eof> at file:///{My Home Dir}/.deno/bin/fresh:2:13_

In the end this is the slightly clunky command I had to use to enable the manifest watch:

`"start": "deno run -A --watch --no-check main.ts & deno run -A https://raw.githubusercontent.com/lucacasonato/fresh/main/cli.ts manifest --watch ."`

---

(1) It might be useful to have a separate repo with a demo site for reference and also testing for unintended dependencies between example project code and framework internal code. If this was upgraded alongside releases it would also provide users with a clear diff for reference when upgrading their own projects.

**Comment by lucacasonato** [comment]
> The project scaffolding doesn't add this command automatically.

I am aware. `fresh manifest --watch` is a stop gap solution for something I am working on that will remove the explicit manifest creation step entirely.

> - The documentation is missing an explanation of this.

See above :)

> - It might be helpful to mention the created deno.json file on the "Create a project page (for inexperienced users).

Good catch! Will definitely do!

> The `Counter` example isn't as easy to replicate locally now if it lives outside the Fresh source code structure (1)

Agreed. The reason the `Counter` example is in tree right now, is so I can easily update it as I make breaking changes to fresh to see if things are still working.
