### ISSUE TITLE
`fresh routes add <pattern>`

### ISSUE THREAD

**Issue by lucacasonato** [denoland/fresh#126]
A subcommand to create a new route file at the given pattern. Automatically runs `fresh manifest` after creating the new route.

**Comment by crowlKats** [comment]
How should this behave with a complex pattern that isnt FS friendly? or more specifically, what path would it create for such a pattern to then use the override?

How about `fresh routes add <pattern> [path]`, and it will error in case of a non-fs friendly `pattern` with a message saying that `path` needs to be specified?

**Comment by lucacasonato** [comment]
I was imagining this `<pattern>` here is just the file path name (so `users/[id]` for example. For advanced patterns, we can add a `--custom-pattern` flag or something.

**Comment by lucacasonato** [comment]
No CLI, so isn't needed anymore.
