### ISSUE TITLE
Unable to run deno fresh demo

### ISSUE THREAD

**Issue by harirupan** [denoland/fresh#1268]
Hi, I am new to Typescript/Javascript, fresh. I am trying to run the fresh demo. But I am getting the following error message:
C:\deno-fresh-demo>deno task start
Task start deno run -A --allow-net --allow-read --allow-env --allow-run --watch=static/,routes/ dev.ts
Watcher Process started.
The manifest has been generated for 3 routes and 1 islands.
error: Uncaught (in promise) TypeError: error sending request for url (https://raw.githubusercontent.com/lucacasonato/esbuild_deno_loader/8031f71afa1bbcd3237a94b11f53a2e5c5c0e7bf/mod.ts): error trying to connect: tcp connect error: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. (os error 10060)
    at https://deno.land/x/fresh@1.1.6/src/server/deps.ts:32:28
  await import(entrypoint);
  ^
    at async dev (https://deno.land/x/fresh@1.1.6/src/dev/mod.ts:186:3)
    at async file:///C:/deno-fresh-demo/dev.ts:5:1
Watcher Process finished. Restarting on file change...

I am using windows 11, deno version 1.34.2 .
 Please help.
I tried to downgrade to version 1.32.1. but I am still getting the same error

**Comment by ozgurrgul** [comment]
can you try to run with `deno task start`?

**Comment by harirupan** [comment]
I got this error When I am running "deno task start"

**Comment by harirupan** [comment]
Hi,I got the error when I ran the command "deno task start".
    On Sunday, 11 June, 2023 at 06:46:22 pm IST, Ozgur ***@***.***> wrote:  
 
 


can you try to run with deno task start?

**Comment by iuioiua** [comment]
This is a network error. Are you able to navigate to https://raw.githubusercontent.com/lucacasonato/esbuild_deno_loader/8031f71afa1bbcd3237a94b11f53a2e5c5c0e7bf/mod.ts in the browser? Have you also tried re-installing the Fresh demo again and running it since you first encountered this issue?

**Comment by harirupan** [comment]
> This is a network error. Are you able to navigate to https://raw.githubusercontent.com/lucacasonato/esbuild_deno_loader/8031f71afa1bbcd3237a94b11f53a2e5c5c0e7bf/mod.ts in the browser? Have you also tried re-installing the Fresh demo again and running it since you first encountered this issue?

I tried. I am getting "This site cannot be reached " Error.
Is there a way for me to manually download the .zip file of source from Github and extract the contents on to my system. Then set the "DENO_DIR" in environment settings?

**Comment by lucacasonato** [comment]
No, this is unfortunately not possible.

**Comment by harirupan** [comment]
After browsing the internet, and fiddling the url. This is taking me to the site:
https://github.com/lucacasonato/esbuild_deno_loader/blob/8031f71afa1bbcd3237a94b11f53a2e5c5c0e7bf/mod.ts
But what is it. And how do I resolve the issue in my system?
can anyone please help me with getting fresh up and running on windows?

**Comment by harirupan** [comment]
Finally solved it. I changed the dns server to 8.8.8.8. I got the fresh framework going. It seems the ISP(JIO) has an issue.
Thanks for all who cared to reply.
