### ISSUE TITLE
`./routes/[id]/[path].tsx` catches request for `_frsh/refresh.js`

### ISSUE THREAD

**Issue by kuboon** [denoland/fresh#128]
Should we move this block up?
https://github.com/lucacasonato/fresh/blob/026ed86f4009fc0a35463d43218bf8c34aead98e/src/server/context.ts#L395

**Comment by lucacasonato** [comment]
@kuboon Oh yeah, that would be great. We should move the INTERNAL_PREFIX handlers above everything else. Do you want to open a PR?
