### ISSUE TITLE
proposal: export `startFreshServer` function in `test_utils.ts` file 

### ISSUE THREAD

**Issue by huai-jie** [denoland/fresh#1296]
So that the island's behavior could be tested by using it.

i.e To test for `Power` island in my `fresh-project` 

```
import { withPageName } from "$fresh/tests/islands_test.ts";

Deno.test({
  name: "Test`Power`island",
  async fn() {
    await withPageName("./main.ts", async (page, address) => {
      await page.goto(`${address}/`, {
        waitUntil: "networkidle2",
      });

      const btnElem = await page.$(`#power-btn`);
      let value = await btnElem?.evaluate((el) => el.textContent);
      assertEquals(value, `OFF`, `Power should be OFF initially.`);
      await btnElem?.click();
      await delay(100);
      value = await btnElem?.evaluate((el) => el.textContent);
      assertEquals(value, `ON`, `Power should be ON now.`);
      await btnElem?.click();
      await delay(100);
      value = await btnElem?.evaluate((el) => el.textContent);
      assertEquals(value, `OFF`, `Power should be OFF now.`);
    });
  },

  sanitizeOps: false,
  sanitizeResources: false,
});
```

Edited:
Add On:
```
async function withPageName(
  name: string,
  fn: (page: Page, address: string) => Promise<void>,
) {
  const { lines, serverProcess, address } = await startFreshServer({
    args: ["run", "-A", name],
  });

  try {
    await delay(100);

    const browser = ...

     try {
      const page = await browser.newPage();
      await fn(page, address);
    } finally {
      await browser.close();
    }
  } finally {
    await lines.cancel();

    serverProcess.kill("SIGTERM");

    // Wait until the process exits
    await serverProcess.status;
}
```

**Comment by marvinhagemeister** [comment]
Exporting a couple of helper functions to make testing `fresh` easier is a great idea! However, I'm not sure if exporting the `withPageName` is the right way to go about that though. Internally `fresh` uses `puppeteer` for testing and the `withPageName` is strongly coupled to that. But thing is there are lots more browser based testing solutions out there like `playwright`, `cypress` and others and giving preference to a single one of them seems wrong.

Instead I feel like we should export the `startFreshServer` function which starts the server as a sub process and waits until it's ready to accept requests. Something like that is useful even if all you're doing is firing `fetch()` requests and would make it easy to integrate with `puppeteer`, `playwright`, `cypress` or any other too.

**Comment by huai-jie** [comment]
Ah, that makes a lot of sense. In that case, it would be beneficial to include some sample documentation for it too.

**Comment by kamilogorek** [comment]
> Instead I feel like we should export the startFreshServer function which starts the server as a sub process and waits until it's ready to accept requests. Something like that is useful even if all you're doing is firing fetch() requests and would make it easy to integrate with puppeteer, playwright, cypress or any other too.

That function is already exported and can be imported directly from `"https://deno.land/x/fresh@1.2.0/tests/test_utils.ts"`.
Do you just want to modify it in a way that it's more dev-friendly or am I missing something?

**Comment by deer** [comment]
Is there anything to do here other than write some documentation about testing islands?

**Comment by marvinhagemeister** [comment]
Closing. The upcoming Fresh 2 release makes it fairly trivial to test Fresh apps:

```ts
const app = new App()
  .get("/foo", () => new Response("ok"))
  
const handler = await app.handler();

// Test code
const response = await handler(new Request("https://localhost/foo"))
console.log(await res.text()) // "ok"
```
