### ISSUE TITLE
Error: Component's "onInvalid" property should be a function

### ISSUE THREAD

**Issue by martpet** [denoland/fresh#1309]
After upgrading from 1.1.6 to 1.2.0.

`<input onInvalid="this.classList.add('foo')" />`

_Error: Component's "onInvalid" property should be a function, but got [string]_

Is it possible to use inline event handlers anymore?

**Comment by kamilogorek** [comment]
It should say `<input onInvalid={() => this.classList.add('foo')} />` instead, but in this case `this.classList` will not refer to your `input` anyway and you'll need to use `ref` if you really want to use `classList` directly.
(although better way to achieve this is to use conditional class names based on the input state)

**Comment by marvinhagemeister** [comment]
The error is thrown from `preact/debug` and this warning is meant to prevent users from unknowingly making themselves vulnerable to XSS injection attacks. But in your case the supplied event handler is fine to my knowledge. I ran into this myself on some projects and I'm looking to find a way to detect these static JSX attribute values and make an exception for them.

You can work around the warning for now by making the first two letters uppercase. Might need to silence the resulting TS warning too via a `// @ts-ignore` comment.

```jsx
<input ONInvalid="this.classList.add('foo')" />
```

**Comment by martpet** [comment]
Hi @kamilogorek, thanks.

It's about server-rendered components, not islands. I'm not sure about `ref`.

I want to style invalid form inputs with the [:invalid](https://developer.mozilla.org/en-US/docs/Web/CSS/:invalid) CSS pseudo class. The Problem is that form fields are considered invalid immediately after document loads . 

So, to style form fields as invalid only **after** form submittion, I listen for the [HTMLInputElement: invalid event](https://developer.mozilla.org/en-US/docs/Web/API/HTMLInputElement/invalid_event)  which fires when "a submittable element has been checked for validity", which happens on form submit, then I add the `was-checked` CSS class, like this:

`<input type="text" required onInvalid="this.classList.add('was-checked')" />`

The *twind* class is `[&.was-checked]:invalid:border-red-400`

This worked in Fresh 1.1.6, but in 1.2.0 it throws the above mention error.

An alternative could be: 
`<input type="text" required id="random-input-id" />`

`<script>
document.getElementById('random-input-id').addEventListener('invalid', (e) => { e.target.classList.add('my-class')});
</script>`

but I don't like how it looks.

**Comment by martpet** [comment]
Thank you very much @marvinhagemeister 🙇
