### ISSUE TITLE
island not working in component subroute

### ISSUE THREAD

**Issue by Amalzybu** [denoland/fresh#1316]
my project directory look like this
├───islands
│       TestIsland.tsx
│
├───routes
│   │   index.tsx
│   │
│   └───test
│           test1.tsx
│
├───static
│   │   logo.png
│   └───test
│           a.css
│

the TestIsland.tsx working fine in index.tsx. in test1.tsx it will render fine but activities like button press is not working

**Comment by marvinhagemeister** [comment]
@Amalzybu Thanks for reporting this. Can you share how we can reproduce it or do you have a github repo we can check out?

**Comment by Amalzybu** [comment]
sorry, i think the middileware code preventing flow of loading script files, that's why islands are not working
