### ISSUE TITLE
dangerouslySetInnerHTML not rendering as expected

### ISSUE THREAD

**Issue by HelloFillip** [denoland/fresh#1329]
I'm new to Preact and I'm attempting to render the majority of my application on the server. 

I plan to load a sprite map from a data store and then inline it at runtime. 

Based on the comments, issues, and references I've seen the normal approach to this would be to use `dangerouslySetInnerHTML`. I've attempted this below (both by using `render` from `gfm` and with a string literal) and I'm clearly missing something in the setup as it's not working.

```typescript
export default function App(props: AppProps) {
	return (
		<>
			<Head>
				<link rel="stylesheet" href={asset("/assets/css/base.min.css")} />
			</Head>
			<HeaderElement />
			dangerouslySetInnerHTML={{ __html: render('<svg></svg>') }}
			<props.Component />
		</>
	);
}
```

Instead the page is rendering:

```html
<header>
        <div class="titlebar">
            <span class="title">Taira Stylebook</span>
            <svg viewBox="0 0 600 600">
                <use xlink:href="#brandmark-symbol"></use>
            </svg>
        </div>
</header>
dangerouslySetInnerHTML=
<undefined></undefined>
```

Any pointers on how to set this up, and how it should work would be appreciated!

**Comment by marvinhagemeister** [comment]
@HelloFillip `dangerouslySetInnerHTML` is a property that needs to be passed to an HTML-element like `<div>`, `<span>` or any other. In the snippet provided here, it's just passed around as text which is why it's rendered as text.

This does not work, passed as text, not as prop:

```jsx
<div>
  dangerouslySetInnerHTML={{ __html: "<h1>hello world</h1>" }}
</div>
```

This works, passed as prop:

```jsx
<div dangerouslySetInnerHTML={{ __html: "<h1>hello world</h1>" }} />
```

**Comment by HelloFillip** [comment]
Thanks @marvinhagemeister. Quick response and worked perfectly. Much appreciated!
