### ISSUE TITLE
`h('!--frsh')` generates `<!--frsh></!--frsh>` which is invalid closing tag

### ISSUE THREAD

**Issue by kuboon** [denoland/fresh#134]
https://github.com/lucacasonato/fresh/blob/67b3eb470e35abe50b0b9838ad05e5ac1a743e86/src/server/render.tsx#L313-L317

Passing `voidElements` option to `renderToString` can fix this behavior.
https://github.com/preactjs/preact-render-to-string/blob/936f71d60a67336bc2639de15dd1c323aa4ff669/src/index.js#L320-L322

**Comment by kuboon** [comment]
Oh, `<!--frsh-- />` is still invalid..

**Comment by lucacasonato** [comment]
@kuboon This is actually a valid HTML comment. When a compliant HTML parser encounters a `<`, followed by a `/`, followed by something other than an ASCII alpha, `/`, or EOF, it goes into a ["bogus comment"](https://html.spec.whatwg.org/multipage/parsing.html#bogus-comment-state) parsing state that will parse the bytes up to the next `>` as a HTML comment. The relevant soft parse error is https://html.spec.whatwg.org/multipage/parsing.html#parse-error-invalid-first-character-of-tag-name.

This is why the comment text of `</--frsh-blabla-->` is `--frsh-blabla--` and not `frsh-blabla`.
