### ISSUE TITLE
Improve error overlay design

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/fresh#1344]
The region where the error is shown is way to narrow and hides all the important details:

<img width="711" alt="Screenshot 2023-06-22 at 15 23 57" src="https://github.com/denoland/fresh/assets/1062408/45320a38-fd36-47ec-89c8-ac43f94bb409">

**Comment by pulkitxm** [comment]
Can I get assigned ?

**Comment by marvinhagemeister** [comment]
sure, assigned this issue to you.
