### ISSUE TITLE
Confusing naming `handler` when types is plural `Handlers

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/fresh#1350]
This is tripping folks up (for good reason). We currently expect the export to be named `handler` but the type name is the same word in plural: `Handlers`. See https://discord.com/channels/684898665143206084/991511118524715139/1121692086886993970

```ts
// Export is singular "handler", type is plural
export const handler: Handlers = {
  // ...
}
```

**Comment by aushwin** [comment]
Hey @marvinhagemeister, I would like to work on this issue. (Please note sometimes would need some guidance as am new into open source contribution)

**Comment by marvinhagemeister** [comment]
The solution to this problem very likely looks like something along the lines of this:

1. Rename `Handlers` type to `MultiHandler`
2. Ensure that we still export a `Handlers` type nonetheless, to ensure we don't break existing apps. Can be done via `export type Handlers<T> = MultiHandler<T>` or something similar
3. To encourage folks to migrate to `MultiHandler`, mark the `Handlers` type as deprecated via the `@deprecated` JSDoc comment.
4. If one feels extra fancy, we could add a check to detect when a `handler` export is missing but a `handlers` export is present here: https://github.com/denoland/fresh/blob/7a7d0e77d0dd1d67371b5efff8d55bd2cf6aa85e/src/server/context.ts#L194 . Add a test case for this by adding a new route to `tests/fixture/`. Everything in that directory is basically a bog standard fresh app, so you might need to run it's `dev.ts` command to refresh the contents of the `fresh.gen.ts` file.

**Comment by aushwin** [comment]
Could you please assign this to me? And how can I setup the project locally, so that I make changes and test it?

**Comment by aushwin** [comment]
@marvinhagemeister please review 
https://github.com/denoland/fresh/pull/1360

**Comment by lausuarez02** [comment]
Hey I see that you are missing the test case that @marvinhagemeister recommended to you, i would be happy to add it :)

**Comment by aushwin** [comment]
@lausuarez02 Hey am working on it. Will ping you if am unable to do it 😄

**Comment by marvinhagemeister** [comment]
FWIW: I've opened a PR for a lint rule to catch the incorrect name directly in the editor https://github.com/denoland/deno_lint/pull/1173

**Comment by aushwin** [comment]
Cool 🔥.

**Comment by frou** [comment]
I thought of suggesting the type name `MethodHandler` (Deno seems to use the term Method rather than Verb for GET/POST/PUT/DELETE etc. And I believe that is also the official term in the specifications).

Of course the word method can also be interpreted as OOP parlance. But that interpretation also works here because these HTTP Method handlers are supplied as JS Methods in the object literal:

```ts
export const handler: MethodHandler = {
  async GET(req, ctx) {
    // ...
  },
  async POST(req, ctx) {
    // ...
  }
};
```

Finally, the user doesn't necessarily write more than one handler, even when using this type, which also makes `Handlers` or `MultiHandler` an awkward type name in some cases.

```ts
export const handler: MethodHandler = {
  async POST(req, ctx) {
    // ...
  }
};
```
