### ISSUE TITLE
(learning fresh / preact) set "active" prop of Header example

### ISSUE THREAD

**Issue by choucavalier** [denoland/fresh#1359]
https://github.com/denoland/fresh/blob/2b92b1c526c98a870d9cae6bdf7f876c18fe6faa/www/routes/components.tsx#L57

in here the `active` prop of the `Header` component is hardcoded to `"/components"`.

what's the right way to make this dynamic with Fresh? i.e. have some sort of "active" state that is updated from one page to another?

it would be nice to update this example in a way that showcases the actual functionality

thanks!

**Comment by kamilogorek** [comment]
> what's the right way to make this dynamic with Fresh? i.e. have some sort of "active" state that is updated from one page to another?

One way to achieve this is to create a `Layout` component, which would be shared between all pages, and get `PageProps` passed. You can use `props.url` to create a matcher that suits your needs.
Alternatively, you can pass it right now, "as is" to the `Header` component and implement the logic there.

Eg. here's a quick example what you'll get passing props directly to the header (whether you use `url` or `route` and how you decide on adding the class/style is up to you:

```ts
// routes/some/[id].tsx

import { PageProps } from "$fresh/server.ts";

function Header(props: { url: URL; route: string }) {
  function isActive(name: string): string {
    return props.route.startsWith(name) ? "color: green" : "color: red";
  }

  return (
    <header>
      <p>Active url: {props.url.pathname}</p>
      <p>Active route: {props.route}</p>

      <nav>
        <ul>
          <li>
            <a href="/some" style={isActive("/some")}>Some</a>
          </li>
          <li>
            <a href="/none" style={isActive("/none/")}>None</a>
          </li>
        </ul>
      </nav>
    </header>
  );
}

export default function NestedPage(props: PageProps) {
  return (
    <>
      <Header url={props.url} route={props.route} />
    </>
  );
}
```

![image](https://github.com/denoland/fresh/assets/1523305/a95b200b-92c9-42de-852c-a8eede6a1cfa)

**Comment by choucavalier** [comment]
thanks a lot @kamilogorek 

do you know if it's possible to access `pageProps` from within the `App` main component?

it does not seem to work (`props.route` is always `null` or empty)

```tsx
import { AppProps, PageProps } from "$fresh/server.ts";
import Header from "../components/Header.tsx";

export default function App({ Component }: AppProps, props: PageProps) {
  return (
    <div class="wrapper">
      <Header route={props.route} />
      <Component />
    </div>
  );
}
```

**Comment by kamilogorek** [comment]
Yes, you can do this, as `AppProps` extend `PageProps`, so everything there is available, see:
https://github.com/denoland/fresh/blob/2b92b1c526c98a870d9cae6bdf7f876c18fe6faa/src/server/types.ts

```tsx
import { AppProps, PageProps } from "$fresh/server.ts";

export default function App({ Component, url, route }: AppProps) {
  return (
    <div class="wrapper">
      <pre>url: {JSON.stringify(url, null, 2)}</pre>
      <pre>route: {JSON.stringify(route, null, 2)}</pre>
      <Component />
    </div>
  );
}
```

**Comment by choucavalier** [comment]
awesome! thank you so much for your availability and quick responses :)

**Comment by kamilogorek** [comment]
Anytime! Enjoy your learning time and have a great day!
