### ISSUE TITLE
Refactor: Refactor ts in utils

### ISSUE THREAD

**Issue by lausuarez02** [denoland/fresh#1369]
### Description
Refactor of typescript in the utils file where i've found that we can add more types to be precise about what we are waiting for the function to return

**Comment by marvinhagemeister** [comment]
There is no need to open up issues for cosmetic PRs. Adding a explicit TS return types instead of letting TS infer them automatically doesn't change behaviour of the code in any observable way.

**Comment by marvinhagemeister** [comment]
Closing this issue, because the mentioned changes have no visible effect for users or folks working on fresh.
