### ISSUE TITLE
fresh@1.2.0 Fetch "POST" request not working, JSON data not sending to server api.

### ISSUE THREAD

**Issue by MrPKJ** [denoland/fresh#1378]
Fresh POST request denied to take JSON data. hence , Fresh server api not able to receive body's json data.

Fresh 'version@1.2.0'.
![Screenshot from 2023-06-30 19-37-11](https://github.com/denoland/fresh/assets/127951878/49b1072c-2f9b-46f5-a697-5d073e52cd39)

File : 'routes/users/github.ts'.

`
 import { Handlers } from "$fresh/server.ts";
 import { User } from "../../types/user.ts";
export const handler: Handlers = {
  async POST(req) {
    console.log(req)
    const body = await req.json();
    const res = await fetch(`https://api.github.com/users/${body.q}`);
    if (res.status === 404) {
      return new Response(null, { status: 404 });
    }
    const user: User = await res.json();
    return new Response(JSON.stringify(user));
  },
 };
`

File : 'routes/users/github.tsx'.

`
import Layout from '../../components/Layout.tsx';
  import SearchGithubUser from "../../islands/SearchGithubUser.tsx";
 import { tw } from "twind";
export default function Github() {
    return (
        <Layout>
            <div class={tw`flex justify-center`}>
                <div class={tw`m-auto`}>
                    <SearchGithubUser />
                </div>
            </div>
        </Layout>
    )
}
`

File : 'islands/SearchGihubUser.tsx'.
`
import { useState } from "preact/hooks";
import { tw } from "twind";
import { User } from "../types/user.ts";

export default function SearchGithubUser() {
    const [user, setUser] = useState<User>();
    const [q, setQ] = useState<string>('');

    async function onSubmit(e: Event) {
        e.preventDefault();
        const res = await fetch('/users/github', {
            method: "POST",
            body: JSON.stringify({ q })
        });
        const data: User = await res.json();
        if (res.ok) {
            setUser(data)
        }
    }

    function handleInput(e: { target: { value: string | ((prevState: string) => string); }; }) {
        setQ(e.target.value)
    }

    return (
        <div>
            <section>
                <form onSubmit={onSubmit}>
                    <input
                        type="text"
                        class={tw`border rounded shadow-md px-4 py-2 w-72`}
                        name="q"
                        value={q}
                        onChange={() => handleInput}
                        placeholder="Search Github user by Username"
                    />
                    <button class={tw`border rounded shadow-md px-4 py-2 bg-blue-800 text-white ml-4`} type="submit">Search</button>
                </form>
            </section>

            {user?.name && (
                <section class={tw`mt-10`}>
                    <a href={user.html_url} target="_blank">
                        <p class={tw`text-2xl text-center`}>Username: {user.login}</p>
                        <img class={tw`border rounded shadow-md w-32 h-32`} src={user.avatar_url} alt={user.login} />
                    </a>

                </section>
            )}
        </div>
    );
}
`

File : 'deno.json'.
![Screenshot from 2023-06-30 19-38-22](https://github.com/denoland/fresh/assets/127951878/5f679bfe-537b-46ba-9946-a427eb6ce9e7)

Fresh 'version@1.0.1'.
![Screenshot from 2023-06-30 19-39-47](https://github.com/denoland/fresh/assets/127951878/7ace644e-e889-41ab-b790-0dfb2c3cf208)

File : 'routes/users/github.ts'.

`
import { Handlers}  from "$fresh/server.ts"

export const handler: Handlers = {
    async POST(req) {
        const body = await req.json();
        
        const res = await fetch(`https://api.github.com/users/${body.q}`);
        if(res.status === 404){
          return new Response(null,{status:404});
        }
    
        const user = await res.json();
        return new Response(JSON.stringify(user));
      }
}`

File : 'routes/users/github.tsx'.
`
/** @jsx h */
import {h} from "preact"
import Layout from '../../components/layouts.tsx';
import SearchGithubUser from "../../islands/SearchGithubUser.tsx";
import {tw} from "@twind";

export default function Github() {

  return (
    <Layout>
      <div class={tw`flex justify-center`}>
        <div class={tw`m-auto`}>
          <SearchGithubUser />
        </div>
      </div>
    </Layout>
  )
}
`
File : 'islands/SearchGithubUser.tsx'.

`
/** @jsx h */
import {h} from "preact"
import { useState } from "preact/hooks";
import {tw} from "@twind";

export default function SearchGithubUser() {
  const [user, setUser] = useState();
  const [q, setQ] = useState('');

  async function onSubmit(e) {
    e.preventDefault();
    const res = await fetch('/users/github', {
      method:"POST",
      body: JSON.stringify({q})
    });
    const data = await res.json();
    if(res.ok){
      setUser(data)
    }
  }

  function handleInput(e) {
    setQ(e.target.value)
  }

  return (
    <div>
      <section>
        <form onSubmit={onSubmit}>
          <input
            type="text"
            class={tw`border rounded shadow-md px-4 py-2 w-72`}
            name="q"
            value={q}
            onChange={handleInput}
            placeholder="Search Github user by Username"
          />
          <button class={tw`border rounded shadow-md px-4 py-2 bg-blue-800 text-white ml-4`} type="submit">Search</button>
        </form>
      </section>

      {user?.name && (
        <section class={tw`mt-10`}>
          <a href={user.html_url} target="_blank">
            <p class={tw`text-2xl text-center`}>Username: {user.login}</p>
            <img class={tw`border rounded shadow-md w-32 h-32`} src={user.avatar_url} alt={user.login} />
          </a>
        </section>
      )}
    </div>
  );
}
`
File : 'import_map.json'.

`
{
  "imports": {
    "$fresh/": "https://deno.land/x/fresh@1.0.1/",
    "preact": "https://esm.sh/preact@10.8.2",
    "preact/": "https://esm.sh/preact@10.8.2/",
    "preact-render-to-string": "https://esm.sh/preact-render-to-string@5.2.0?deps=preact@10.8.2",
    "@twind": "./utils/twind.ts",
    "twind": "https://esm.sh/twind@0.16.17",
    "twind/": "https://esm.sh/twind@0.16.17/"
  }
}
`

**Comment by lucacasonato** [comment]
You have both a `routes/users/github.ts` and a `routes/users/github.tsx` file. Move the handlers array from `routes/users/github.ts` into `routes/users/github.tsx`.

@marvinhagemeister we should error when there are two routes that have the same name (only different exts).
