### ISSUE TITLE
New twind plugin (fresh ^1.2.0) requires you to add `twind/` to your import map

### ISSUE THREAD

**Issue by felix-schindler** [denoland/fresh#1379]
## Reason

The new plugin imports `twind/sheets` which can't be resolved, because the import map is only for this project

https://github.com/denoland/fresh/blob/18bf977052a589cba5a70ecf0da35e0b577e3b0a/.vscode/import_map.json#L3

```
error: Uncaught (in promise) TypeError: Relative import path "twind/sheets" not prefixed with / or ./ or ../ and not in import map from "https://deno.land/x/fresh@1.2.0/plugins/twind.ts"
    at https://deno.land/x/fresh@1.2.0/plugins/twind.ts:1:30
  await import(entrypoint);
  ^
    at async dev (https://deno.land/x/fresh@1.2.0/src/dev/mod.ts:140:3)
    at async file:///some_path/dev.ts:5:1
```

## Proposed fix

Update the import to be a URL instead of something from a import map (as it was in the v1 of the plugin).

https://github.com/denoland/fresh/blob/18bf977052a589cba5a70ecf0da35e0b577e3b0a/plugins/twind.ts#L1

https://github.com/denoland/fresh/blob/18bf977052a589cba5a70ecf0da35e0b577e3b0a/plugins/twindv1.ts#L1

## Workaround

Add this to your fresh projects import map

```json
"twind/": "https://esm.sh/twind@0.16.19/",
```

**Comment by deer** [comment]
@marvinhagemeister, I guess this one can also get closed due to tailwind migration.
