### ISSUE TITLE
docs: better explain island architecture and server components

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/fresh#1384]
Seems like our docs don't communicate that aspect good enough. Got a tweet where somebody didn't know that fresh had this: https://twitter.com/CodeMonument/status/1675084963295764486 

Here is the conversation:

> **kasvith:** Waiting for PSC, Preact Server Components
> **marvinhagemeist:** A form of that is already available in fresh  [https://fresh.deno.dev](https://t.co/IxuBinVhhQ). The Deno sites have been running this in production for a good while.
> **CodeMonument**: Can you link the exact docs for these „preact server components“ like things in fresh? I think I know nearly all of the docs, but I know nothing in there which resembles RSCs to me :O
> **marvinhagemeist**: We don't mention the term explicitly in the docs. Basically every route is treated internally as a server component and islands are client components. When you pass server side rendered children to an Island, then these children are treated internally like a server component.

**Comment by deer** [comment]
The link is broken for me, but I also don't have an account.

**Comment by marvinhagemeister** [comment]
@deer sorry about that, seems like twitter cut off access for non-registered users which is a shame. Added the conversation. It seems like folks are explicitly looking for the term "server component" in our docs and nothing shows up on our end. Server components for us are basically a byproduct for going with the islands architecture.

**Comment by deer** [comment]
As a native islander (i.e. I never did (p)react when it was purely rendered on clients), I find this confusion strange. But I guess if this is the popular term, then it should probably be mentioned.

**Comment by marvinhagemeister** [comment]
Yeah, it's an unfortunate trait of the JS community that we always come up with new terms and assume a "thing" doesn't have it when we can't find that term in the docs. That said I feel like we don't really explain the island architecture well either way. It's a bit hidden in the docs.
