### ISSUE TITLE
proposal: use dynamic imports for routes

### ISSUE THREAD

**Issue by iuioiua** [denoland/fresh#1405]
[Deno Deploy now supports statically analyzable dynamic imports.](https://deno.com/deploy/changelog#statically-analyzable-dynamic-imports) This may remove, if not reduce, reliance on the `fresh.gen.ts` file.

**Comment by marvinhagemeister** [comment]
I'm not sure how it would allow us to get rid of the manifest. Would love to learn more as I'd like to get rid of it too if possible.

**Comment by lionel-rowe** [comment]
I don't think this could eliminate `fresh.gen.ts` as the static file names still have to be hard-coded, but it could at least make for cleaner git diffs, as you wouldn't have to store each import in a dynamic `$n` variable that gets re-numbered any time a file with a lexicographically earlier name is added. Something like this:

```diff
- import * as $0 from "./routes/index.tsx";
- import * as $1 from "./routes/passthrough.tsx";
- import * as $$0 from "./islands/Counter.tsx";
- import * as $$1 from "./islands/Passthrough.tsx";

  const manifest = {
    routes: {
-     "./routes/index.tsx": $0,
+     "./routes/index.tsx": () => import("./routes/index.tsx"),
-     "./routes/passthrough.tsx": $1,
+     "./routes/passthrough.tsx": () => import("./routes/passthrough.tsx"),
    },
    islands: {
-     "./islands/Counter.tsx": $$0,
+     "./islands/Counter.tsx": () => import("./islands/Counter.tsx"),
-     "./islands/Passthrough.tsx": $$1,
+     "./islands/Passthrough.tsx": () => import("./islands/Passthrough.tsx"),
    },
    baseUrl: import.meta.url,
  };
```

**Comment by iuioiua** [comment]
Ah, sorry for not responding sooner. Yes, after creating this issue, I realised I was wrong. Though, @lionel-rowe, your idea looks like it has potential! I'd happily look at a PR if you wanted to submit one. @marvinhagemeister, do you see any issues with the proposal?

**Comment by iuioiua** [comment]
Another idea:
```diff
- import * as $0 from "./routes/index.tsx";
- import * as $1 from "./routes/passthrough.tsx";
- import * as $$0 from "./islands/Counter.tsx";
- import * as $$1 from "./islands/Passthrough.tsx";

  const manifest = {
    routes: {
-     "./routes/index.tsx": $0,
+     "./routes/index.tsx": await import("./routes/index.tsx"),
-     "./routes/passthrough.tsx": $1,
+     "./routes/passthrough.tsx": await import("./routes/passthrough.tsx"),
    },
    islands: {
-     "./islands/Counter.tsx": $$0,
+     "./islands/Counter.tsx": await import("./islands/Counter.tsx"),
-     "./islands/Passthrough.tsx": $$1,
+     "./islands/Passthrough.tsx": await import("./islands/Passthrough.tsx"),
    },
    baseUrl: import.meta.url,
  };
```

**Comment by iuioiua** [comment]
Actually, I have some time. I'll look into this.

**Comment by lionel-rowe** [comment]
@iuioiua is there a reason the deferred `() => import(...)` version wouldn't work? Obviously it'd necessitate changes in the calling code, and maybe it wouldn't play nicely with sync plugins etc, but the advantage if it could be made to work is that you'd get code splitting for free.

**Comment by csvn** [comment]
Wouldn't it be a bit slower to do `await import(...)` in serial like that? It would be one FS operation at a time in serial instead of doing all of them in parallell. The deferred option of doing `() => import(...)` would not necessitate the loading of all routes in serial when loading `fresh.gen.ts`.

**Comment by marvinhagemeister** [comment]
Closing, the upcoming Fresh 2 release uses dynamic glob imports.
