### ISSUE TITLE
Proposal: DevTools panel

### ISSUE THREAD

**Issue by wtchen** [denoland/fresh#1409]
This is the first step in https://github.com/denoland/fresh/issues/1321

My thinking is to have the DevTools be its own app of sorts, like the `demo` folder; we'd just put it inside a separate `devtools` folder in this repo. This DevTools app can then be embedded into an iframe panel which can be injected into dev apps during hydration. This is roughly how Nuxt does it.

The initial PR would just have some placeholders so everyone can review the design. We can use the `demo` folder to test before we code the injection logic.

I can work on this, but I will need some time learning the ins-and-outs of this app and probably Nuxt as well.

**Comment by marvinhagemeister** [comment]
Let's keep the discussion in #1321 . We can always split it up into more issues when the need arises.
