### ISSUE TITLE
Test Example does not work with twind

### ISSUE THREAD

**Issue by digitaldesigndj** [denoland/fresh#1413]
I am trying to understand how to write fast handler tests for complex apps that use twind.

Simply I want to add this style of test to some existing project: https://fresh.deno.dev/docs/canary/examples/writing-tests

I made a demo repo: https://github.com/digitaldesigndj/fresh-test-example

Clone that and run `deno test -A`

<img width="860" alt="Screenshot 2023-07-05 at 9 33 56 PM" src="https://github.com/denoland/fresh/assets/539320/911b8abb-d7c4-4a72-a99e-3b63e3c10d96">

I have been using startFreshServer for testing, but these faster and smaller tests appeal to me, the example just doesn't jive with `tw` or something about twind and I don't know where to start fixing this. Why do we need a document for tw?

**Comment by kamilogorek** [comment]
You can skip using `tw` template tag entirely, it's all handled by preconfigured Fresh plugin.

**Comment by marvinhagemeister** [comment]
Yup the `tw` template tag is only needed client side when you're conditionally rendering CSS classes that are not part of the initial server renderer. Usually that's only ever inside an island.

**Comment by digitaldesigndj** [comment]
Ok. So it's probably a consequence of me using twind wrong, but I need the `tw` function to clobber some global styles into my layouts. If I don't use `tw` it stops working?

https://github.com/Hyprtxt/hyprtxt.deno.dev/blob/main/components/Layout.jsx#L67

I suppose it could be an issue with `asset` and I am confused? The CSS in question is static; Link so you don't have to dig: https://github.com/Hyprtxt/hyprtxt.deno.dev/blob/main/utils/style.js#L35-L81

**Comment by marvinhagemeister** [comment]
Yup, you need the `tw` function when you're passing stuff from twind's `css` function and the like. Took a look why the test case is failing and reason is that calling handlers directly bypasses the whole plugin system. The `render` method of the Fresh twind plugin is never called in that setup.

I quite like the idea of an in-process way of testing Fresh routes.

**Comment by digitaldesigndj** [comment]
So I think I need to get my Global Styles `globalStyles` into `render`? 

I was trying to understand this page: https://twind.dev/usage-guides/ssr.html

I guess I just don't understand; It does work, cause my website **does work**, without understanding the twind plugin render. However I now have this feeling its all wrong and I am trying to configure ... like fresh webpack because I wanted to use the example tests? 

btw... I am super stoked you're on this project 👍

**Comment by digitaldesigndj** [comment]
Okay I don't think I really understood your comment until I got that posted. I need to fix the test

**Comment by marvinhagemeister** [comment]
Closing this as we've switched to Tailwind CSS which allows us to compile the style sheet ahead of time and move it out of the render path. The Tailwind CSS plugin will be released in the next Fresh 1.6 version which I'm hoping to release later this week. We're likely going to deprecate the twind plugin and keep it on life support.
