### ISSUE TITLE
BUG: Fresh 1.2.0 initial setup and update is broken 

### ISSUE THREAD

**Issue by bjesuiter** [denoland/fresh#1420]
I tried to setup a completely new fresh project with 

```sh
deno run -A -r https://fresh.deno.dev fresh120-test
cd fresh120-test 
deno task start
```

my Repo: https://github.com/jbscratch/fresh120-test

I get the following error: 

```sh
❯ deno task start       
Task start deno run -A --watch=static/,routes/ dev.ts
Watcher Process started.
The manifest has been generated for 3 routes and 1 islands.
error: Uncaught (in promise) TypeError: invalid data
    at https://deno.land/x/fresh@1.2.0/src/server/render.ts:1:32
  await import(entrypoint);
  ^
    at async dev (https://deno.land/x/fresh@1.2.0/src/dev/mod.ts:140:3)
    at async file:///Users/bjesuiter/Develop/jbscratch/fresh120-test/dev.ts:5:1
Watcher Process failed. Restarting on file change...
```

## Things I tried
I discovered this problem as I updated fresh in one of my real projects and deno start did not work anymore. 

### Going back to fresh 1.1.6 -  not working
Interestingly, going back to fresh 1.1.6 did not help, same error. 
Now I wonder, what could be wrong with my system that breaks fresh in this way? 

### Going Back to Deno 1.34.3 - not working

I'm currently using 1.35.0 currently, but going back to 1.34.3 did not change anything.

### fresh 1.2.0 - `deno cache main.ts dev.ts ` 

Also errors with 

```sh
✖ deno cache main.ts dev.ts     
error: invalid data
    at https://deno.land/x/fresh@1.2.0/src/server/render.ts:1:32
```

**Comment by falvarador** [comment]
I have the same error, yesterday I was trying to create a new Deno Fresh project and I got this error always 😬

**Comment by marvinhagemeister** [comment]
We've seen a very similar issue across other non-fresh projects too. So far everything points to esm.sh having returned unexpected html files instead of JS or even binary blobs at times. Can you try running the start command with the `-r` flag? That should force the cache to be refreshed.

```sh
 deno run -A -r --watch=static/,routes/ dev.ts
 ```

**Comment by lino-levan** [comment]
This was reported on discord and as far as I can tell it's been fixed on the `esm.sh` side. If you're still getting the error, run the dev script with the reload flag to refresh the deps.

**Comment by bjesuiter** [comment]
Seems to indeed be fixed with esm.sh now, but only after doing the suggested: 

```ts
 deno run -A -r --watch=static/,routes/ dev.ts
```

Note: Doing `deno task start -r` does not work for some reason, so you have to use the exact command without deno tasks.

**Comment by marvinhagemeister** [comment]
@bjesuiter FYI: When running `deno task start -r` the `-r` flag is passed to the `dev.ts` script as an argument, not to `deno run`. That's why the underlying run command needs to be run manually with `-r`.

**Comment by bjesuiter** [comment]
Thanks for clarification!

**Comment by marvinhagemeister** [comment]
Closing this as the issue has been resolved on the esm.sh side. Passing `-r` refreshes the cache and resolves the issue.
