### ISSUE TITLE
Is it possible to generate `fresh.gen.ts` without starting a server?

### ISSUE THREAD

**Issue by ApproximateIdentity** [denoland/fresh#1429]
I.e. is there a cmd that I could run so that `[CMD] ...` creates the `fresh.gen.ts` file and does nothing else instead of having it just generated as a side-effect of running `deno run dev.ts`? I can create it by starting up the server, but I don't want to start the server and would instead just like to produce the file programmatically.

**Comment by lino-levan** [comment]
There is no explicit command, but it would be pretty easy to make one. https://github.com/denoland/fresh/blob/main/src/dev/mod.ts exposes the api to generate `fresh.gen.ts` so I'd recommend looking at that.

**Comment by ApproximateIdentity** [comment]
Thanks! I'm totally clueless when it comes to deno in general (doing some automation of others' work), but I see the function you're talking about and can take this as an excuse to improve my deno skills!

**Comment by lino-levan** [comment]
Good luck with whatever you're doing! Glad I could help.
