### ISSUE TITLE
dev.ts does not work when there is no `islands/` directory in the PWD

### ISSUE THREAD

**Issue by rojvv** [denoland/fresh#1430]
Sometimes we just want `routes/`.

**Comment by lino-levan** [comment]
This already works in canary, I haven't tested it in stable. What error are you getting?

**Comment by rojvv** [comment]
<img width="1032" alt="image" src="https://github.com/denoland/fresh/assets/49933115/6d995c8d-4f6a-4e5f-8be7-1f0e17a1e3f9">

**Comment by marvinhagemeister** [comment]
Can confirm that this is resolved in `main` but not released yet. The fix for this will be included in the next release.

@roj1512 The trace shows that you're using Fresh 1.2.0 . The fix will be part of the next release sometime this week.

**Comment by rojvv** [comment]
Thanks, I will just use `main` now on!
