### ISSUE TITLE
Incorrectly handles routes that have (non-ASCII?) non-Latin characters

### ISSUE THREAD

**Issue by rojvv** [denoland/fresh#1432]
<img width="937" alt="Screenshot 2023-07-08 at 10 49 21 PM" src="https://github.com/denoland/fresh/assets/49933115/6af0ecc3-ef62-4e48-8a2c-d470de2135b6">

e.g., تایبەتێتی.tsx

**Comment by rojvv** [comment]
Hmm, I believe it is an issue with Deno Deploy since the screenshot works locally.

<img width="372" alt="Screenshot 2023-07-08 at 10 53 26 PM" src="https://github.com/denoland/fresh/assets/49933115/2eba3510-1b9a-4f29-bb05-f92c55e1094b">

Nonetheless, the fresh.gen.ts should better not look like that.

**Comment by rojvv** [comment]
<img width="447" alt="Screenshot 2023-07-08 at 10 55 13 PM" src="https://github.com/denoland/fresh/assets/49933115/6f7c6cd1-30e2-4236-b83a-2b62f8a03af8">

I did this cool trick anyway.

**Comment by marvinhagemeister** [comment]
The notation in the `fresh.gen.ts` file is a bit unexpected, but in essence it still points to the very same file. It seems like it gets parsed as an URL somewhere in Fresh before writing it to the manifest.

**Comment by rojvv** [comment]
I was thinking of having a feature to use a different path than the file name ~as a workaround for this~. Not sure how would that work tho.

**Comment by marvinhagemeister** [comment]
Reopening, because the issue needs to be resolved on the deploy side too.

**Comment by marvinhagemeister** [comment]
@roj1512 Would love to know more about the use case. Can you share more what the intention should be?

**Comment by rojvv** [comment]
The use case in this case (the Deno Deploy issue being a thing) is simple: be able to have a non-Latin/ASCII route (e.g., /пример) that has its source code in an ASCII name (e.g., routes/primer.tsx).

A more general use case would be to make the codebase more consistent by not having file names that include non-Latin/ASCII characters (e.g., пример.tsx, and especially RTL ones which are a little bit more messy, for example, نموونە.tsx).

I have already done this by modifying the generated `fresh.gen.ts` to for example, replace `"./routes/something.tsx": $0` with `"./routes/شتێک.tsx": $0`.

A way to implement this functionality would be allowing the user to redirect from the non-Latin/ASCII paths to the Latin/ASCII ones, but the end user would see the Latin/ASCII path instead of the real one.

**Comment by marvinhagemeister** [comment]
@roj1512 That should be doable via the `routeOverride` option. It allows you to overwrite the file based route. The bottom of the "Routing" page in the docs has an example on how to use that https://fresh.deno.dev/docs/concepts/routing

**Comment by rojvv** [comment]
Nice! I also thought that there must be something like that but was too lazy to search. I will try it later!

**Comment by marvinhagemeister** [comment]
We just deployed the remaining fix on the Deno Deploy side and can confirm that this issue is resolved 🎉

**Comment by rojvv** [comment]
Yes, it is.
