### ISSUE TITLE
Wrong comment

### ISSUE THREAD

**Issue by vitorbiqua** [denoland/fresh#1436]
Hi everyone, everything fine?

Browsing through the documentation, some code comments on the "https://fresh.deno.dev/docs/examples/creating-a-crud-api" page are inconsistent with the page structure presented by the beginning of the explanation. For example, the comment "//routes/api/index.ts" should be //routes/api/users/index.ts (given the structure shown).

I'm learning the framework and maybe some newbies might end up getting confused.

**Comment by deer** [comment]
Thanks for pointing this out @vit0rBianchini. I have a fix up for review now.
