### ISSUE TITLE
Throwing inside handler doesn't render 500 template

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/fresh#1439]
Reported on discord: https://discord.com/channels/684898665143206084/991511118524715139/1127723854194806784

**Comment by deer** [comment]
There's a test for exactly this case: https://github.com/denoland/fresh/blob/main/tests/fixture_custom_500/routes/index.tsx

Are we sure?

**Comment by deer** [comment]
Oh, canary vs main. This can probably be closed as a duplicate of https://github.com/denoland/fresh/issues/1357.

**Comment by fkdiomande** [comment]
How to install the canary version?

**Comment by deer** [comment]
> How to install the canary version?

https://fresh.deno.dev/docs/examples/using-fresh-canary-version

**Comment by marvinhagemeister** [comment]
@deer Oh good catch! Didn't check existing issues. Closing this one then.
