### ISSUE TITLE
Running instructions

### ISSUE THREAD

**Issue by UltiRequiem** [denoland/fresh#144]
While creating a new project, reading the readme file, it says to run the file like 
```sh
deno run -A --watch main.ts
```

And that produces
```
error: TS2304 [ERROR]: Cannot find name 'URLPattern'.
        const pattern = new URLPattern({
                            ~~~~~~~~~~
    at https://crux.land/api/get/2H5yPV.ts:145:29
```
But if I run the file like 
```
./main.ts
```
It works OK, this is a bug or is just needed to update the docs?

**Comment by hyp3rflow** [comment]
I think this is duplicate of https://github.com/lucacasonato/fresh/issues/76
How about adding `--no-check`? It will resolve this issue.

**Comment by UltiRequiem** [comment]
> I think this is duplicate of #76

Yep, closing in favor.
