### ISSUE TITLE
Documentation search input throws setTimeout error

### ISSUE THREAD

**Issue by NuroDev** [denoland/fresh#1441]
Currently if you try to search for anything on the documentation site/page(s) you will receive the following error in the console upon every key press:
```
Uncaught TypeError: o.environment.setTimeout is not a function
```

Seeing as the documentation primarily just renders a button to mount the Algolia search modal I presume this is some kind of issue with their script getting mounted?
The current `SearchButton` component [is pinned to version 3](https://github.com/denoland/fresh/blob/main/www/islands/SearchButton.tsx#L3C24-L3C52) but it seems the latest version is `3.5.1` so maybe a dependency upgrade could fix this?

**Comment by deer** [comment]
I can't reproduce this locally, even with https://github.com/denoland/fresh/pull/1423 merged. And when I go to a previous commit, I still can't reproduce locally. I'll let an expert deal with this 😅

**Comment by marvinhagemeister** [comment]
Yeah we've been noticing that on Friday too. So far I'm stumped on why it happens. Locally everything works fine, but when deployed the error pops up. I'm guessing something goes wrong during bundling maybe? I don't know, haven't found the cause yet.

**Comment by NuroDev** [comment]
> Locally everything works fine, but when deployed the error pops up

I did try running locally (without an env token cause I don't have one) & I got the same issue so IDK if there is any possible difference between the token you're using locally & production?

Additionally I have noticed that when using the search shortcut (CMD+K) it double opens the modal. (I can open a new issue for this if needed but is still slightly related)

https://github.com/denoland/fresh/assets/4991309/b3bce017-90b7-4153-b646-ae8d714a3528

**Comment by dsosby** [comment]
In the minified code, there's a check here that the global `Deno` is not undefined. In the production build, `typeof Deno < "u"` is false, so the environment is set to `{}` instead of `window`:

`    var n, r = typeof Deno < "u" ? window : {}, o = t.plugins || [];`
^`r` is `environment`

**Comment by marvinhagemeister** [comment]
@dsosby Ohh that's a very good find. Looks like the same problem is causing DevTools to fail #1461 .

**Comment by marvinhagemeister** [comment]
Looks like `esm.sh` started silently replacing `typeof window` checks with `typeof Deno` when it encountered the Deno user agent: https://github.com/esm-dev/esm.sh/issues/681
