### ISSUE TITLE
@preact/signals-core@1.3.x breaks passing signal as island property

### ISSUE THREAD

**Issue by marcushultman** [denoland/fresh#1445]
Upgrading to `@preact/signals-core@1.3.1` in a newly created project breaks the `Counter` island example. It seems like the property is serialized as the raw value (`3` by default in the example). Downgrading to `@preact/signals-core@1.2.3` works.

**Comment by marvinhagemeister** [comment]
Thanks for reporting this. We have a fix for this in `main` already and a new Fresh version is planned to be released later this week. This was resolved in #1348 .
