### ISSUE TITLE
Error: debug.js:10 Uncaught TypeError: _4.__ is not a function

### ISSUE THREAD

**Issue by rafael-zacca-sumup** [denoland/fresh#1457]
Hello everyone.

I have a project using deno fresh and preact.

After running `deno run -A --watch=static/,routes/ dev.ts` it seems to finish up successfully, but when I open the App using Chrome (Version 114.0.5735.198) as a browser I get the following error in console:

`Uncaught TypeError: _4.__ is not a function
    at E (hooks.js:2:3344)
    at Array.forEach (<anonymous>)
    at R (hooks.js:2:2157)`

The app does not behave correctly, like having a problem with the useEffect and useState, not making them work.

I am using:
- deno 1.35.0 (release, aarch64-apple-darwin)
- v8 11.6.189.7
- typescript 5.1.6
- fresh 1.2.0
- preact 10.16.0
- macOs Ventura 13.1

## Things I tried
**Going back to previous versions of deno:**
Going back to 1.24.2, using deno version manager. The error changes, getting:

`Uncaught TypeError: e.__ is not a function
    at qt (island-app.js:1:2162)`

The App still doesn't behaves as expected. The problem seems to be the same.

**Going back to previous versions of preact and fresh:**
Using preact 10.8.2 and fresh 1.0.1, still having the same error:

`Uncaught TypeError: e.__ is not a function
    at qt (island-app.js:1:2162)`

**Running it on another OS:**
I have tried lifting it up on a Linux based system, without success, having the same error as above.

**Refreshing the cache:**
Trying `deno cache --reload dev.ts` and adding the `-r` command to my `deno run -A --watch=static/,routes/ dev.ts` command did not changed the result. Still having the same error.

Please if you could give me any help with this I would really appreciate it. Any required information I will be happy to share. Thank you in advance.

**Comment by deer** [comment]
Hi @rafael-zacca-sumup, thanks for logging this. Do you have a repo we can look at? Or reproduction steps?

**Comment by marvinhagemeister** [comment]
Yeah I'm afraid the error message is not enough to know what's going on. Can you share your code of the island? It sounds like something is wrong with the hooks used there.

**Comment by rafael-zacca-sumup** [comment]
[code.zip](https://github.com/denoland/fresh/files/12071924/typescript-terminal-api-main.zip)
Hello. Thank you for your response. This is a `.zip` file containing the code of the project that has the issue. I know in the readme file it describes how to configure the credentials as an important step, but the problem can be reproduced without having to configure it. Please, if there is another question, let me know. Thanks for your help.

**Comment by marvinhagemeister** [comment]
Thanks for sharing, that was very helpful in getting to the bottom of the error. The project makes use of `react-json-inspector` to render JSON data which hasn't been updated in the last 6 years. Because of that it uses some very very old React APIs that have been removed from the normal `preact/compat` layer. The most obvious API that this package uses is `React.createClass`. But instead of outright dropping support for these, we moved those older APIs to https://github.com/preactjs/legacy-compat/ .

In other words, aliasing to `@preactjs/legacy-compat` instead of `preact/compat` does the job. Note that you can simplify the import map significantly by adding an entry for `react` and `react-dom` instead of having to add an alias to every other entry to alias React to Preact.

Here is the final import map with which everything works:

```json
{
  "imports": {
    "$fresh/": "https://deno.land/x/fresh@1.2.0/",
    "preact": "https://esm.sh/preact@10.16.0",
    "preact/": "https://esm.sh/preact@10.16.0/",
    "react": "https://esm.sh/@preact/legacy-compat?external=preact",
    "react-dom": "https://esm.sh/@preact/legacy-compat?external=preact",
    "create-react-class": "https://esm.sh/@preact/legacy-compat?external=preact",
    "preact-render-to-string": "https://esm.sh/preact-render-to-string@6.2.0?external=preact",
    "@twind": "./utils/twind.ts",
    "twind": "https://esm.sh/twind@0.16.17",
    "styled-components": "https://esm.sh/styled-components@5.3.5",
    "twind/": "https://esm.sh/twind@0.16.17/",
    "react-json-inspector": "https://esm.sh/react-json-inspector@7.1.1"
  }
}
```

**Comment by rafael-zacca-sumup** [comment]
Thank you! That would solve the issue. I really appreciate the help!
