### ISSUE TITLE
Weird bug renders conditional components if condition is written in a specific way.

### ISSUE THREAD

**Issue by iivvaannxx** [denoland/fresh#1464]
# The Problem

I am trying to set up a simple "collapsible" section with a button to show or hide the inner content (passed as children to an 'Accordion' island). The accordion component is as follows:

```tsx
const [isOpen, toggle] = useToggle(open)

return (

  <div class={`bg-red-300 p-4 ${clazz}`}>

    <div class='flex justify-between items-center'>
      <span>{text}</span>
      <button type='button' class='p-2 bg-black text-white' onClick={toggle}>Open</button>
    </div>

    <If condition={isOpen.value}>

      <div class='mt-4 w-full'>
        {children}
      </div>

    </If>

  </div>
)
```

The 'If' component is a simple wrapper (non-interactive and lives outside the 'islands' folder) that renders the passed children depending on the given condition.

```tsx
return (

  <Fragment>
    {condition === true && children}
  </Fragment>
)
```

The problem is that this doesn't work, it renders the `<div class='mt-4 w-full'>` but the children do not get rendered. The thing that I genuinely don't understand is that if I change the `<If>`  component to this:

```tsx
return (

  <Fragment>
    {condition === false && children}
  </Fragment>
)
```

Then it works as expected, and the children get rendered. This also happens without the `<If>` wrapper (by inlining the condition into the `<Accordion>` component), I just like to do it this way because of personal preference.

# Additional Information

`deno --version` outputs the following:

```
deno 1.33.3 (release, x86_64-unknown-linux-gnu)
v8 11.4.183.2
typescript 5.0.4
```
I don't know why it prints `unknown-linux-gnu` but in case it's needed I am using [NixOS](https://nixos.org/). Also, and just in case, I am running my application with the `--unstable` flag.

**Comment by marvinhagemeister** [comment]
Can you share a repo where we can reproduce the error? The snippets posted here look fine and I'm assuming the error is somewhere else.

**Comment by iivvaannxx** [comment]
Sure, I thought that the easiest way was to share a Docker container with the problem, so I created a copy of my app removed every piece of code which wasn't related to the problem, and left only the involved code. 

[This repo](https://github.com/iivvaannxx/conditional-bug) is the minimal example I could reproduce, it's only a single page. In the repo itself, I left a README on how to run it (made a script that does it for you) and how to reproduce my problem. If you need any other thing don't hesitate to tell me.

Make sure port 80 is available or edit the `run.sh` script to modify the `-p 80:8000` binding in the `docker run` command.

EDIT: Of course you can also run the app with `deno task start`. I only created the Docker container to ensure the app runs under the same conditions for both of us (mainly the `deno` version).

**Comment by marvinhagemeister** [comment]
Thanks for providing the reproduction case. Took a look and this is the same issue as described in #1322 . When server rendered children are passed to a component and _not_ rendered in the initial HTML, they won't appear. To resolve that we need to send `children` to the client as a template and collect children from that instead. It's something we need to address in Fresh itself.

Let's track the discussion in #1322.
