### ISSUE TITLE
July - August 2023 iteration plan

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/fresh#1485]
A new Fresh version is cut on a monthly basis around the middle of the month and this post intends to capture the main tasks we want to focus on. It replaces #563 as that has gotten hard to keep track of. A monthly plan matches the release cycle and allows for more flexibility by making it easier to account for shifts in priorities.

The current list of tickets included in this release can always be found in the related GitHub milestone: https://github.com/denoland/fresh/milestone/3

## Plan items

The current plan of main features planned for this cycle:

- [x] Layouts - #1506 
- [x] Route Groups - #1150
- [ ] twind v1 remaining issues - #1116 
- [x] Prebuilt islands - #1062
- [x] Allow feature based folders instead of separating by tech (island/routes/etc) - #1486

Moved to next cycle:

- [ ] Preact Actions - to be announced
- [ ] Simplify Fresh server setup (run in one file) - #1487, #1602

Note that this list is not set in stone. Random ideas occur spontaneously and the async route components in last release for example were only added later in the cycle based on an evening exploration I did.

## Engineering

- [x] Solve the flaky windows CI - #1476

**Comment by lino-levan** [comment]
> Allow feature based folders instead of separating by tech (island/routes/etc)

Going to open a discussion here before creating an issue with a description of what needs to be done. I see a few approaches to this which could be fine:
1. Introduce a new directory in which we do app-directory-next-style routing
2. Use the same directory, and have islands be named `something.island.tsx` and components be named `something.component.tsx` (or another pattern)

What would your preference be?

**Comment by Norfeldt** [comment]
> twind v1 remaining issues - https://github.com/denoland/fresh/issues/1116

Would like to bring attention to an elephant in the room 🐘. 

Twind is like tailwind a great tool - however using it without the right tooling makes it painful and difficult to learn. The [vscode-twind-intellisense](https://github.com/tw-in-js/vscode-twind-intellisense) is only maintained by 2 contributors, last commit was 2 years ago and it has been [broken since typescript 5](https://github.com/tw-in-js/vscode-twind-intellisense/issues/22) was the default in vscode.

**Comment by marvinhagemeister** [comment]
@Norfeldt That's a very good point and something that concerns me as well. On top of that I feel like moving to a non-runtime solution would fit better into the Fresh philosophy too.

**Comment by Norfeldt** [comment]
> @Norfeldt That's a very good point and something that concerns me as well. On top of that I feel like moving to a non-runtime solution would fit better into the Fresh philosophy too.

And tailwind can't be used? Or is there a problem with it?

**Comment by lino-levan** [comment]
Sorry, to clarify, are you talking about Tailwind the specification, or Tailwind the PostCSS plugin, or perhaps something else? With unocss (which is what I believe we're thinking about adding / moving to), we should have all of the Tailwind classes as with our current solution.

**Comment by marvinhagemeister** [comment]
@Norfeldt I'm all for using tailwind directly.

**Comment by wtchen** [comment]
> @Norfeldt I'm all for using tailwind directly.

On a related note, does Fresh support using stylesheets directly at the moment?

**Comment by lino-levan** [comment]
Yes. You can put them in your `static` folder and simply reference them using standard html `link` tags

**Comment by marvinhagemeister** [comment]
FYI I've moved the `app.use()` idea to simplify the Fresh server setup to the next cycle. There is ongoing discussion in #1602 what the API shape should look like. I don't want to rush that just to get something in the current release and thereby create API churn once the proper API lands. It needs more time to cook, so moving that to next cycle.

**Comment by marvinhagemeister** [comment]
This cycle is completed. Closing this issue in favour of the new one for the next cycle: https://github.com/denoland/fresh/issues/1618
