### ISSUE TITLE
Allow putting islands + routes + components in the same folder

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/fresh#1486]
Currently, the way Fresh works is that it scans for an `islands/` and a `routes/` folder in which Islands and Routes have to live respectively. This grouping by purpose is fine for smaller projects, but grouping by feature makes a lot more sense. Putting everything related to a certain route in the same folder makes a lot of sense.

Another motivation for this feature is that I notice folks putting everything in one single route file as a workaround to having to put the code outside of `routes/`.

We have the distinct notion of the `islands/` and `routes/` folder, because it signals to Fresh what to bundle for the browser and what routes to resolve.

The details on this still need to be worked out.

**Comment by marvinhagemeister** [comment]
From discord: Astro allows you to opt out of route matching via an `_` suffix.

**Comment by barelyhuman** [comment]
https://github.com/denoland/fresh/issues/1126#issuecomment-1649676762

I understand, the plugin is small enough to be added in directly into the core though so it shouldn't be a problem. Also , considering how far Fresh has moved it'd be hard to reason with users with regards to the change in behaviour so I would also not recommend using the web components implantation right now

Let me know if you need a PR for the specific changes of accessing any files as island. 

Based on evaluation the easiest one is using the top level comment of `//@island` which doesn't take any parameters so it's a simple string search and doesn't need parsing. 

Thoughts?
