### ISSUE TITLE
Hot Reloading no longer works after failed import.

### ISSUE THREAD

**Issue by AngelEscobedo01** [denoland/fresh#1513]
I was able to recreate this bug using the initialized Fresh project.
I created a component with Fragments and imported that into my index.tsx route.
This worked fine.
![image](https://github.com/denoland/fresh/assets/73673445/a8b147c5-4fd9-4025-a0ba-ebe168600183)

But when I created a new component, and either kept it empty or commented it out, I get an error message as intended.
![image](https://github.com/denoland/fresh/assets/73673445/46f00b07-0eca-4af6-9641-d79e587aefa8)

The issue comes after correcting this error and creating a valid import. 

![image](https://github.com/denoland/fresh/assets/73673445/54646cd2-778a-4e3f-b3d3-b501e7b6f4e7)

When I save the NotSaved.tsx file and ensure that it is not exporting a valid component, the website no longer hot reloads. Making new changes or removing the import does not bring it back either.
![image](https://github.com/denoland/fresh/assets/73673445/fdfe5e67-2f8b-4918-8236-70907ef67f40)

Only refreshing the page reenables hot reloading.

**Comment by deer** [comment]
It seems to be working for me. Am I doing the same steps as you are?
https://github.com/denoland/fresh/assets/1494757/e5e0ba50-6941-4c22-bc29-8b2c55118d44
Perhaps this is a bug on windows?

**Comment by AngelEscobedo01** [comment]
I can try it again soon, I tried chasing it down and it had something to do with some frsh _alive script that was getting generated on build. 
I'll update my version and retest with video like you did. If I can't reproduce, I'll close this issue.

**Comment by marvinhagemeister** [comment]
Closing, as we haven't heard back.
