### ISSUE TITLE
Inconsistent default preact imports

### ISSUE THREAD

**Issue by kibibites** [denoland/fresh#1517]
```ts
// signals must be imported from preact with a @
import { useSignal } from "@preact/signals";
// while hooks don't require the @
import { useEffect } from "preact/hooks";
```
fresh version: `v1.3.1`

**Comment by marvinhagemeister** [comment]
The naming is correct. These are two different packages that are originally published to npm. Deviating from the official naming would only cause confusion. In npm land there are two kind of package names:

1. "normal" package names  have the format `<name>` like `preact`, `express`, etc
2. Scoped packages must start with an `@` character and have the format `@<scope>/<name>` like `@vite/core`

This gives us:

- `preact` -> The main preact package
- `preact/hooks` -> The `hooks` entry point of the `preact` package
- `@preact/signals` -> The `@preact/signals` package.
