### ISSUE TITLE
Question: Non-autocomplete twind extension

### ISSUE THREAD

**Issue by joansebgarcia** [denoland/fresh#1519]
Good afternoon, deno fresh community this issue should not be here but I take the trouble to ask Why I do not want to autocomplete the twind classes

![extesion](https://github.com/denoland/fresh/assets/116913262/3993db22-da27-484b-b96c-d50eb33864c6)

![code](https://github.com/denoland/fresh/assets/116913262/9ae9d763-b622-48cd-abe7-05293c17e793)

***What a shame my ignorance and thank you for your attention***

**Comment by afifurrohman-id** [comment]
Me too, alternatively you can create **empty** file `tailwind.config.ts` in root project directory and using **tailwind extension** instead twind

**Comment by joansebgarcia** [comment]
Do you recommend it for style ***development***, do you have any configuration in the file or is it simply empty?

**Comment by afifurrohman-id** [comment]
> 

Only empty file, just for tailwind extension auto complete, for config keep using `twind.config.ts` and ignore it using `.gitignore`

**But this tailwind extension is not 100% compatible with twind v0,**
### so you can use twind v1 and it's work fine like tailwind, tutorial already included in fresh docs [here](https://fresh.deno.dev/docs/examples/using-twind-v1)

**Comment by afifurrohman-id** [comment]
**I also using in my personal project if want to see more details examples [here](https://github.com/afifurrohman-id/notes-sync)**

**Comment by joansebgarcia** [comment]
![Captura de pantalla 2023-07-26 090504](https://github.com/denoland/fresh/assets/116913262/1802d693-eab8-4bf5-9b57-f0e5a774d4ba)
**Thank you very much mate, it worked**

**Comment by joansebgarcia** [comment]
In this case the tailwindcss extension is activated, right?

**Comment by willpuckett** [comment]
It seems like it would be nice to be able to use the twind extension, but seeing the color previews in the tailwind version is kinda nicer anyway

**Comment by u-yas** [comment]
I think the workaround introduced here is the best.

https://github.com/tw-in-js/vscode-twind-intellisense/issues/9#issuecomment-1173095315

**Comment by anilanar** [comment]
I think the main confusion stems from the fact that some people use **tailwind** extension while others use **twind** extension. Possibly, most people don't even know that they are different. 

In my case, I couldn't make **twind extension** have autocompletes. The **twind** extension output has pretty much nothing even with `debug: true`. It seems twind extension is pretty much dead, with [bunch of issues](https://github.com/tw-in-js/vscode-twind-intellisense/issues) left open.

It would be great to update the project scaffold to either suggest a better extension that works, or use something else than  `twind`.

**Comment by marvinhagemeister** [comment]
@anilanar We're in the process of moving away from twind. There is both a proper Tailwind CSS plugin in development as well as one for UnoCSS.

**Comment by marvinhagemeister** [comment]
Closing this as we've switched to Tailwind CSS which allows us to compile the style sheet ahead of time and move it out of the render path. The Tailwind CSS plugin will be released in the next Fresh 1.6 version which I'm hoping to release later this week.
