### ISSUE TITLE
async route incompatible with index

### ISSUE THREAD

**Issue by zbynekwinkler** [denoland/fresh#1528]
Creating `async.tsx` file in `routes` according to https://fresh.deno.dev/docs/concepts/routes#async-route-components results in a cryptic typescript error/warning:

![image](https://github.com/denoland/fresh/assets/1130051/df297047-ce2a-4a70-ad05-cdceecc7dc73)

Contents of `/routes/async.tsx`:

```javascript
import { RouteContext } from "$fresh/server.ts";

// deno-lint-ignore require-await
export default async function (
    req: Request,
    ctx: RouteContext,
  ) {
    return <div>async</div>;
  }
```

The problem seems to be related to `RouteContext`. If I remove it, the error disappears. Running `deno check` reports no error however. So it might be related to the language server or the vscode extension. I am not sure how to debug it further.

**Comment by sant123** [comment]
To see the type checking error run:

`deno check main.ts`

I'm having the same issue ^^

![image](https://github.com/denoland/fresh/assets/7959437/27e25410-879e-4571-8a94-2d4ef206d2c6)

**Comment by sant123** [comment]
https://deno.com/blog/v1.23#no-type-checking-by-default

**Comment by deer** [comment]
A workaround is to change your
```tsx
export default async function (
  req: Request,
  ctx: RouteContext,
) {
  return <div>async</div>;
}
```
to
```tsx
export default async function (
  req: Request,
  ctx: RouteContext<PageProps>,
) {
  return <div>async</div>;
}
```

As for an actual fix, I came up with two approaches
1) 
```diff
--- a/src/server/types.ts
+++ b/src/server/types.ts
@@ -59,7 +59,7 @@ export interface PageProps<T = any, S = Record<string, unknown>> {
 /**
  * Context passed to async route components.
  */
-export type RouteContext<T = unknown, S = Record<string, unknown>> =
+export type RouteContext<T = any, S = Record<string, unknown>> =
   & Omit<
     HandlerContext<T, S>,
     "render"
```
2)
```diff
--- a/src/server/types.ts
+++ b/src/server/types.ts
@@ -129,7 +129,7 @@ export type Handlers<T = any, State = Record<string, unknown>> = {
 export type MultiHandler<T> = Handlers<T>;

 export interface RouteModule {
-  default?: PageComponent<PageProps>;
+  default?: PageComponent<PageProps | unknown>;
   // deno-lint-ignore no-explicit-any
   handler?: Handler<any, any> | Handlers<any, any>;
   config?: RouteConfig;
```

@iuioiua , thoughts on this one? I see you fixed another typing issue in this area, so maybe you can help out here.

To summarize, here are the relevant types (shortened to only show the necessary properties):
```tsx
export interface RouteModule {
  default?: PageComponent<PageProps>;
}

export type PageComponent<T = any, S = Record<string, unknown>> =
  | ComponentType<PageProps<T, S>>
  | AsyncRoute<T, S>
  | ((props: any) => VNode<any> | ComponentChildren);

export type AsyncRoute<T = any, S = Record<string, unknown>> = (
  req: Request,
  ctx: RouteContext<T, S>,
) => Promise<ComponentChildren | Response>;

export type RouteContext<T = unknown, S = Record<string, unknown>> =
  & Omit<HandlerContext<T, S>, "render">
  & Omit<PageProps<unknown, S>, "data">;
```

The core issue is that users write `RouteContext` which gets defaulted to `RouteContext<unknown, Record<string, unknown>>`. But we've typed `RouteModule` as `PageComponent<PageProps>`, and so then down the chain the `PageProps` flows, which leads to an expected `RouteContext<PageProps, Record<string, unknown>>`.  But this is isn't compatible with what it actually receives (`RouteContext<unknown, Record<string, unknown>>`), hence the error.

I suspect the error is made worse by the fact that the async route isn't correctly getting typed as an `AsyncRoute`, and then it falls back to `((props: any) => VNode<any> | ComponentChildren)` which pollutes the message. Or something like that.

If someone can provide a different solution and why it works I'd be interested to see. Or some better explanation of what's going on. If I get a tentative approval of one of my fixes, then I can create a PR tomorrow.

**Comment by iuioiua** [comment]
> ```diff
> --- a/src/server/types.ts
> +++ b/src/server/types.ts
> @@ -59,7 +59,7 @@ export interface PageProps<T = any, S = Record<string, unknown>> {
>  /**
>   * Context passed to async route components.
>   */
> -export type RouteContext<T = unknown, S = Record<string, unknown>> =
> +export type RouteContext<T = any, S = Record<string, unknown>> =
>    & Omit<
>      HandlerContext<T, S>,
>      "render"
> ```

This appears to be the correct solution as it makes the `data` type variable, `T`, consistent with the rest of the codebase, being `any` instead of `unknown`. Good catch!
