### ISSUE TITLE
Allow head + body creation in `_app.tsx`

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/fresh#1529]
This week I've come across a couple of fresh projects which add the `<html>`, `<body>` and `<head>` tag respectively inside `_app.tsx`. Most other frameworks like Remix, astro or nextjs work that way, so it's a natural assumption that this would work in Fresh too.

Example:

```tsx
// _app.tsx
export default function App({ Component }: AppProps) {
  return (
    <html class="h-full bg-[#010524] overflow-hidden">
      <head>
        <title>Just Lists</title>
        <meta name="title" content="" />
        <meta name="description" content="" />
      </head>
      <body class="h-full text-slate-600">
        <Component />
      </body>
    </html>
  )
}
```

**Comment by lino-levan** [comment]
Perhaps this is a little naïve, but why limit this to `_app.tsx`? I feel like this makes sense in a per-page or per-layout context as well.

**Comment by lino-levan** [comment]
I drafted a quick prototype of extracting (obtaining and deleting) `head` elements from a VNode tree (for [Pyro](https://github.com/lino-levan/pyro), but I assume this could be a little helpful for fresh as well):

```ts
import { type VNode, type ComponentChild, isValidElement, toChildArray } from 'preact';

/**
 * Given a VNode (that isn't a head), return a list of nodes which were in
 * `head` elements found throughout the tree.
 *
 * The VNode tree is modified to remove the `head` elements.
 */
function extractHead(node: VNode): ComponentChild[] {
  // Convert child nodes into a list of VNodes / strings / numbers
  const children = toChildArray(node.props.children);

  return children.map((child, i)=>{
    // If the child is a VNode
    if(isValidElement(child)) {
      if(child.type === "head") {
        // Delete head from VNode tree
        if(isValidElement(node.props.children)) {
          // Case A - head is the only child
          delete node.props.children;
        } else {
          // Case B - head is just one of the children
          const children = node.props.children as ComponentChild[];
          const index = children.indexOf(child);
          children.splice(index, 1);
        }

        // Return the ComponentChill of the head
        return toChildArray(child.props.children)
      }
      // If the child isn't a head element, recursively extract head elements
      return extractHead(child);
    }
    // If it's not a VNode, we can safely ignore it
    return [];
  }).reduce((p, c)=>[...p, ...c], []);
}
```
Would this be the right way to approach doing this?

**Comment by marvinhagemeister** [comment]
Extracting the necessary values after the fact always works, but I'd love for us to find a way to get the right values directly. One way to do that would be to hook into Preact's options plugin API to collect those values during rendering.

The thing I'm not clear on is how this would interact with `_app` or `_layouts`. Should the head component overwrite existing definitions of `<head>` or should it extend it? I'm not sure yet. We need a way to overwrite inherited layouts anyway regardless of the `<head>` topic. Maybe some additional options to route config like `overrideLayout: true` or `overrideApp: true` could work.

That would make it explicit that you don't want to extend stuff and allow you to opt-out of inheriting stuff.

**Comment by lino-levan** [comment]
Ah! Nice tip, I had no idea that Preact had hooks for this sort of thing 😅. That would definitely be a better way of doing it.

> Maybe some additional options to route config like overrideLayout: true or overrideApp: true could work.

I think this is the right approach. I believe this is what the NextJS folks came up with.
