### ISSUE TITLE
[Plugins] PluginMiddleware Type isn't  conforms to existing Type ?

### ISSUE THREAD

**Issue by Octo8080X** [denoland/fresh#1531]
I am in need of advice. Please let me know if you have a better implementation and I would be happy to help.

I have been creating middleware for some time and responded to the middleware as it became available to be applied via plugins.

However, I have one question.
Without error, it seems to conform to existing types but not to new types.

Therefore, I had to make a special assertion.

Is this the recommended way to write this?

For example.

```typescript
export function getLoggerHandler(logSender?: RemoteLogSenderFunction): Plugin {
  const handler: MiddlewareHandler<Logger> = async function (
    _req: Request,
    ctx: MiddlewareHandlerContext<Logger>  // <= Logger can be applied.
  ) {
    ctx.state.logger = new LogModule(logSender);
    return await ctx.next();
  };

  return {
    name: "loggerPlugin",
    middlewares: [
      {
        middleware: {
          handler: handler as MiddlewareHandler<Record<"logger", unknown>>, // <= Logger can't be applied. use Record<"logger", unknown>
        },
        path: "/",
      },
    ],
  };
}
```
(https://github.com/Octo8080X/fresh-logger/blob/main/src/loggerPlugin.ts)

`MiddlewareHandler<Record<"logger", unknown>>`  is not applicable. However, `MiddlewareHandlerContext<Logger>` is applicable.

MiddlewareHandler MiddlewareHandlerContext

The generics for both `MiddlewareHandler` and `MiddlewareHandlerContext`, though, is `Record<string, unknown>`,　and `Logger` is compatible.

Is there any other recommended way to write this?

**Comment by deer** [comment]
Thanks for opening this @Octo8080X! Looks like we need even more generics. I made the following changes in Fresh locally:
```diff
-export interface Plugin {
+export interface Plugin<State = Record<string, unknown>> {
-  middlewares?: PluginMiddleware[];
+  middlewares?: PluginMiddleware<State>[];
-export interface PluginMiddleware {
+export interface PluginMiddleware<State = Record<string, unknown>> {
-  middleware: Middleware;
+  middleware: Middleware<State>;
```

and then to your code:
```diff
-export function getLoggerHandler(logSender?: RemoteLogSenderFunction): Plugin {
+export function getLoggerHandler(logSender?: RemoteLogSenderFunction): Plugin<Logger> {
-          handler: handler as MiddlewareHandler<Record<"logger", unknown>>,
+          handler: handler,
```

Now all the type errors go away. Is this the type of solution you're looking for?

**Comment by Octo8080X** [comment]
@deer san
Thanks!
This is just what I wanted.
Looking forward to this being released. Once it is, I will have the plugin side supported as soon as possible.
