### ISSUE TITLE
Canary docs updating page returns 500 server error

### ISSUE THREAD

**Issue by NuroDev** [denoland/fresh#1543]
In looking through the current canary docs ([Commit](https://github.com/denoland/fresh/tree/5af441cde674ec528605eadcf4c56f26683f153a)) the `/concepts/updating` page ([Production URL](https://fresh.deno.dev/docs/canary/concepts/updating)) is broken & returns a 500 internal server error.

I have tried to reproduce this locally but had no success. Maybe this the issue has already been resolved & the fix is yet to be deployed?

**Comment by marvinhagemeister** [comment]
Thanks for reporting this. We should really add a check to our docs that verifies that all links are correct on the CI in the future.
