### ISSUE TITLE
Using React libraries that depend on process.env.NODE_ENV

### ISSUE THREAD

**Issue by Dgiulian** [denoland/fresh#1548]
I'm trying to integrate `dnd-kit` into a Fresh project, but I'm getting the following error:

```
error: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'env')
    at Object.<anonymous> (file:///deno-dir/npm/registry.npmjs.org/@dnd-kit/core/6.0.8/dist/index.js:4:13)
    at Object.<anonymous> (file:///deno-dir/npm/registry.npmjs.org/@dnd-kit/core/6.0.8/dist/index.js:10:4)
    at Module._compile (internal:ext/node/02_require.js:747:36)
    at Object.Module._extensions..js (internal:ext/node/02_require.js:780:12)
    at Module.load (internal:ext/node/02_require.js:658:34)
    at Function.Module._load (internal:ext/node/02_require.js:515:14)
    at Module.require (internal:ext/node/02_require.js:680:21)
    at require (internal:ext/node/02_require.js:820:18)
    at file:///deno-dir/npm/registry.npmjs.org/@dnd-kit/core/6.0.8/dist/index.js:2:13
```
This error is caused because the library is relying on `process.env.NODE_ENV`, which obviously doesn't exist in the Deno world.

What would be a good approach to circumvent this issue? As this isn't an error in the library per se, as is intended to be used in React. But I think this issue is present in many other libraries that are built with Node in their mind. Are there any examples on how to avoid these errors?

Here's a code sandbox to reproduce the issue [https://codesandbox.io/p/sandbox/brave-glitter-wy9384](https://codesandbox.io/p/sandbox/brave-glitter-wy9384).

**Comment by Dgiulian** [comment]
I was able to make it work by importing from `esm.sh` instead of `npm:@dnd-kit`  here's my import section of `deno.json` file in case someone else have the same issue.

```
  "imports": {
    "$fresh/": "https://deno.land/x/fresh@1.3.1/",
    "preact": "https://esm.sh/preact@10.15.1",
    "preact/": "https://esm.sh/preact@10.15.1/",
    "preact-render-to-string": "https://esm.sh/*preact-render-to-string@6.2.0",
    "@preact/signals": "https://esm.sh/*@preact/signals@1.1.3",
    "@preact/signals-core": "https://esm.sh/*@preact/signals-core@1.2.3",
    "twind": "https://esm.sh/twind@0.16.19",
    "twind/": "https://esm.sh/twind@0.16.19/",
    "react": "https://esm.sh/preact@10.15.1",
    "react-dom": "https://esm.sh/preact@10.15.1",
    "@dnd-kit/core": "https://esm.sh/@dnd-kit/core@6.0.8?alias=react:preact/compat,react-dom:preact/compat,@types/react:preact/compat&external=preact/compat&deps=preact@10.15.1",
    "$std/": "https://deno.land/std@0.193.0/"
  },
```

Basically I just added the import map `@dnd-kit/core` mapped to the `esm.sh` import and I updated the import in the component to use  `import { DnDContext } from '@dnd-kit/core'`

**Comment by marvinhagemeister** [comment]
@Dgiulian FYI: you can skip all the `?alias=...` parameters and only use `?external=react,react-dom`. No need to have both at the same time.

**Comment by Dgiulian** [comment]
> @Dgiulian FYI: you can skip all the `?alias=...` parameters and only use `?external=react,react-dom`. No need to have both at the same time.

Thanks for the tip, I got to the solution after trying different suggestions on Discord and Github. I'll try to remove the alias parameter.
