### ISSUE TITLE
The landing page components don't seem to work

### ISSUE THREAD

**Issue by hashrock** [denoland/fresh#156]
The hero animation is stopped and the counter example is disabled for now.

![image](https://user-images.githubusercontent.com/3132889/164915971-08fb112d-9bc6-48be-9bb1-454932be1146.png)

Browser error here: 

![image](https://user-images.githubusercontent.com/3132889/164915649-d303e385-4e69-47a1-9971-3ea0133091cf.png)

Deno Deploy error logs (with my fork): 

![image](https://user-images.githubusercontent.com/3132889/164915695-67bc9a64-0abb-4f44-9273-3c1ac66bd654.png)

And error line is here:

![image](https://user-images.githubusercontent.com/3132889/164915792-40a9c63a-fe02-4cc8-b9bc-f5b6cbbbf4bc.png)

https://unpkg.com/esbuild-wasm@0.14.34/esm/browser.js

it seems failed to fetch wasm binary.

**Comment by hashrock** [comment]
`src/server/esbuild-wasm/esbuild.wasm` is deleted at #151, then it should be hosted somewhere?

**Comment by lucacasonato** [comment]
whoops, i'll fix this.

**Comment by hashrock** [comment]
Oh I made PR just now but if you fix by yourself, please close the PR.

**Comment by tylerbrostrom** [comment]
🤦‍♂️ sorry folks

**Comment by lucacasonato** [comment]
@tylerbrostrom Not your fault! I didn't review as well as I should have. No big deal :-)
