### ISSUE TITLE
Nodejs globals are `undefined` in modules imported by `npm:` specifier

### ISSUE THREAD

**Issue by osddeitf** [denoland/fresh#1577]
Recently, there is `npm:` specifier support in Fresh. As far as I know, it was possible with `esbuild_deno_loader`.
And I was writing a `POST` handler:
```typescript
import arangodb from 'npm:arangojs'
export const handler: Handlers = {
  async POST(req, _ctx) {
    // connect to the database, query for data
  }
}
```
`npm` imports work fine, but I run into issue in which the global symbols of `nodejs` (in particular, `Buffer`) are not supported.:
```js
function base64Encode(str) {
    return Buffer.from(str).toString("base64");
}
```
I guess that is how far `esbuild_deno_loader` can support at bundling the codes for now.
But I think instead of submitting a request to update `esbuild_deno_loader`, there's better way.
Deno already supports all things from using `npm:` specifier, to executing Typescript directly.
The handlers for requests are run server-side, why the need of bundling it?

So I propose that we only bundle client-side codes with `esbuild_deno_loader`, let server-side codes as is.
Not only the performance will improve, but also more use cases will be supported out-of-the-box.

Edit: For a second thought, I don't know for sure how Fresh works behind the scenes. I may be wrong that `esbuild_deno_loader` bundle the server-side codes then Fresh executes it.

**Comment by marvinhagemeister** [comment]
Fresh only bundles client side code, meaning everything reachable from the `/islands` directory. If you are able to provide a reproduction case we'd be happy to look into that.

**Comment by osddeitf** [comment]
This is my reproduction code:
```typescript
import { Handlers } from "$fresh/server.ts";
import arangodb from 'npm:arangojs'

const mydb = new arangodb.Database({ databaseName: 'test-db' })

export const handler: Handlers = {
  async POST(req, _ctx) {
    const collection = mydb.collection('test-collection')
    const exists = await collection.exists()
    return new Response(
      JSON.stringify({ exists }),
      { headers: { 'content-type': 'application/json' } }
    )
  }
}
```
You can try even without a database server up and running.

**Comment by marvinhagemeister** [comment]
Can reproduce this issue without Fresh too. It's an issue in Deno's node compat layer. Filed a report over there https://github.com/denoland/deno/issues/20028 with a minimal reproduction case.

Closing the issue here as there's nothing to do on the Fresh side of things.

**Comment by osddeitf** [comment]
Thank you, I didn't know that we can bypass that by not running `dev.ts` script.
