### ISSUE TITLE
Cannot override type for state in `AppProps` and `LayoutProps`

### ISSUE THREAD

**Issue by csvn** [denoland/fresh#1580]
It's not possible to override the `state` property generic type in `AppProps`/`LayoutProps`. This makes us stuck with `Record<string, unknown>` as the type for `props.state`, even if we have a correct interface for use for state based on what global middleware adds.

```ts
export default function App(props: AppProps) {
  props.state.foo;
  // type: unknown
}
```

I suggest adding a generic to make it possible to configure the `state` type:

```ts
export default function App(props: AppProps<{ foo: string }>) {
  props.state.foo;
  // type: string
}
```

`PageProps` has generic for both `data` and `state`, but it does not make sense to be able to set a type for `data`, as neither App and Layout can load data, and it's the page that determines what data is available. Either we can keep the `any` type for `data`, or set it to something safer than `any`, like `unknown` or `undefined`.

```ts
export interface AppProps<S = Record<string, unknown>> extends PageProps<undefined, S> { ... }
export interface LayoutProps<S = Record<string, unknown>> extends PageProps<undefined, S> { ... }
```

This change should be backwards compatible, and allow typing `state` properly.

**Comment by deer** [comment]
I already have https://github.com/denoland/fresh/pull/1449. I guess the same idea could be applied to `LayoutProps`.

**Comment by csvn** [comment]
Ahh, yes. This seems to be a duplicate of #1446, if we don't include adding generic for `LayoutProps` as well. Should I close this issue, or keep it open to track this being applied to `LayoutProps` as well?

**Comment by deer** [comment]
I must admit I haven't had time to play with layouts yet. I'll let someone more knowledgable than myself comment on whether supporting this for layouts makes sense.

**Comment by mcgear** [comment]
I would say it definitely makes sense for `LayoutProps`.  One of the best parts of TS is its typing, so I think supporting throughout would be the right idea. Looking at #1446 and #1449. It does seem like we should close this in favor of adding the same AppProps changes to LayoutProps.

This then begs the question, should AppProps and LayoutProps be the same type instead of spearate? Should AppProps extend LayoutProps?

**Comment by deer** [comment]
I'll take a stab at this now.
