### ISSUE TITLE
Question: Use of css files

### ISSUE THREAD

**Issue by lausuarez02** [denoland/fresh#1581]
I've been reading the documentation of how to use css files but i can't find exactly how to it for specific components. 
Such as having a css file inside components, inside a folder of that component, the error i`ve received is that is not supported.

Is there a way to import css files in components or islands?

Cheers.

**Comment by marvinhagemeister** [comment]
CSS Modules are not supported at the moment. You can create a static CSS file and include that via a `<link>` tag as a workaround for now.

**Comment by lausuarez02** [comment]
I see, thanks so much for replying!
