### ISSUE TITLE
[Bug Report] Can't get client's Real IP / remoteAddr after upgrading to v1.3.0

### ISSUE THREAD

**Issue by etnperlong** [denoland/fresh#1585]
Hi, after I updated fresh to v1.3.0 and after. I cannot get the client's real IP by `ctx.remoteAddr` method.
This is the test code of `_middleware.ts`

```typescript
interface State {
  ip: string;
}

export async function handler(
  req: Request,
  ctx: MiddlewareHandlerContext<State>,
) {
  const ip = (ctx.remoteAddr as Deno.NetAddr).hostname;
  ctx.state.ip = ip;
  const resp = await ctx.next();
  console.debug(`Addr: ${(ctx.remoteAddr as Deno.NetAddr).hostname}, ${(ctx.remoteAddr as Deno.NetAddr).port}`);
  return resp;
}
```

The server can only get **Addr: localhost, 1234** after being upgraded to v1.3.0, but the real IP from the client is expected. I read the code and I found that the issue might come from this PR: https://github.com/denoland/fresh/pull/1278

I can see there is a static code to set the `DEFAULT_CONN_INFO` in the file `src/server/context.ts` , which overwritten the `remoteAddr`

I am not good at coding can you please help me check and fix the issue? Thank you!

**Comment by lausuarez02** [comment]
Hey,
I could be wrong but i`ve seen that you could use this to get the IP in deno and i've tried it my self and it works even though it's giving me a warning.
https://deno.land/x/get_ip@v2.0.0

Cheers.

**Comment by marvinhagemeister** [comment]
@lausuarez02 Taking [a look at the source](https://github.com/denorg/get-ip/blob/master/mod.ts#L6) that module does an actual network request to `https://api.ipify.org` to get the users IP. That definitely works but seems pretty overkill.

**Comment by EthanBnntt** [comment]
Yeah, you should be able to get a user's IP address without network requests.

**Comment by lausuarez02** [comment]
Indeed, so could it maybe be a feature?
Cause DEFAULT_CONN_INFO it's not mean to be to get the ip address.
So it should maybe be a new function? If you see it accurate i can probably work on it.

**Comment by etnperlong** [comment]
> Hey, I could be wrong but i`ve seen that you could use this to get the IP in deno and i've tried it my self and it works even though it's giving me a warning. https://deno.land/x/get_ip@v2.0.0
> 
> Cheers.

It's a good tool. But I think it's for the client side and I think Fresh can handle the user's IP on the server side without any additional request.

**Comment by etnperlong** [comment]
> 

In my opinion, `ctx.remoteAddr` should contain the remote address in context by default. Because that's what it's supposed to literally mean. However, this function was broken after v1.3.0 by using a default value.

I prefer to call it a bug. If additional features such as "Consider Privacy" are needed, then at least one switch is needed instead of the default.

Cheers!

**Comment by Jabolol** [comment]
I agree with @etnperlong, the `remoteAddr` parameter should be set. One way to avoid having `localhost` as a default fallback and report the correct information would be to expose the second parameter of `Deno.serve`, that has the correct information when the fresh server starts here:

https://github.com/denoland/fresh/blob/efcaa2dee2ae5b43f53ae2c943780a15c3cd4e24/src/server/mod.ts#L168-L177

## Edit

Fixed on my own fork, [`this`](https://github.com/Jabolol/fresh/blob/ee0d00c717e9acbad44080599696e9ea27144ead/src/server/mod.ts#L168-L181) is the solution that I came up with. Let me know if I should create a Pull Request.
