### ISSUE TITLE
www: lemondrop animation renders slightly differently SSR than on first client render

### ISSUE THREAD

**Issue by lucacasonato** [denoland/fresh#161]
See the below screenshot. The left side is the SSR with JS disabled, the right side is the client side render. The white part of the lemon drop animation is not visible at all on the SSR render, and but averages around 50% of the SVG height on the client render. I think it would make sense if the "start state" of the client animation matched the SSR render.

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/7829205/164934361-06978053-a408-4c4a-9eb4-ad0b698a7a02.png">

cc @hashrock

**Comment by hashrock** [comment]
I'll try it!
