### ISSUE TITLE
August - September 2023 iteration plan

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/fresh#1618]
A new Fresh version is cut on a monthly basis around the middle of the month and this post intends to capture the main tasks we want to focus on. A monthly plan matches the release cycle and allows for more flexibility by making it easier to account for shifts in priorities.

The current list of tickets included in this release can always be found in the related GitHub milestone: https://github.com/denoland/fresh/milestone/4

## Plan items

The current plan of main features planned for this cycle:

- [x] SPA-like client side navigation https://github.com/denoland/fresh/issues/1609
- [ ] View Transitions https://github.com/denoland/fresh/pull/1532
- [ ] Replace twind with https://github.com/denoland/fresh/pull/1303

[to be done]

Note that this list is not set in stone. Random ideas occur spontaneously and the async route components in last release for example were only added later in the cycle based on an evening exploration I did.

**Comment by miguelrk** [comment]
**Friendly reminder:** the following appear as "Moved to next cycle" in the previous iteration plan but are not listed above:

- Preact Actions - to be announced
 - Simplify Fresh server setup (run in one file) - https://github.com/denoland/fresh/issues/1487, https://github.com/denoland/fresh/issues/1602

**Comment by marvinhagemeister** [comment]
As folks might have noticed, we're reaching the end of September already. The next release is currently scheduled to be around Oct 4th, give or take a couple of days. Main reason for the delay was that I was on vacation. There is some talks if we should move to a 6 weeks cycle, given that this matches what the v8 team is doing. I'm open to experiment with different models, although I like the monthly cadence as it's easier to remember for me.

**Comment by marvinhagemeister** [comment]
This cycle took a bit longer and I've moved the open tasks to the current one https://github.com/denoland/fresh/issues/1891 . My main takeaway this time is that I had too many projects running simultaneously in the last cycle. That lead to me being spread a bit too thin and whilst lots of thing progressed further, most of it needs a bit more work to bring over the finish line.

**Comment by waldyrious** [comment]
> I've moved the open tasks to the current one https://github.com/denoland/fresh/issues/1618

Don't you mean #1891? :thinking:

**Comment by marvinhagemeister** [comment]
@waldyrious yup, you're absolutely right. Not sure what happened there 😅
