### ISSUE TITLE
suggestion: adding optional import alias 

### ISSUE THREAD

**Issue by fdemir** [denoland/fresh#1620]
It would be great to have a optional import alias. Imo import alias like a default thing that we have to include to avoid `../../` hell at long term. Default may be `@/*`, but the user should be able to choose according to their taste at the init stage. Here is example at following:

```js
import Counter from "@/islands/Counter"
```

We can include it as an option at init. For instance, `What import alias would you like configured? › @/*`.

**Comment by marvinhagemeister** [comment]
I'm not sure if adding more steps to the init script is a good idea. The more decisions we confront first time users with, the more likely we are causing friction in the onboarding process. Not everyone uses these either. Seeing that this is a oneliner that can be copy & pasted directly into `deno.json` I'm not sure what we'd gain by that.

**Comment by marvinhagemeister** [comment]
Closing, because whether folks have an aliased import or not is personal preference. So far there doesn't seem to be a clear winner of either approach. It's easy enough to add if you want it I think.
