### ISSUE TITLE
Racing condition causing Cross-Data usage and content leakage in page rendering

### ISSUE THREAD

**Issue by igorbrasileiro** [denoland/fresh#1636]
## Issue
After receiving a customer reporting they were seeing someone else's data in our application, we went out to investigate and boiled down to a bug in fresh, specifically related to context render function. It's not hard to reproduce:
If you have a dynamic route like `/admin/[site]/index.tsx` and receive a lot of requests with different `site` some requests will show incompatible data. We suspect there is something to do with islands.

## How to reproduce:
1. Fork https://github.com/igorbrasileiro/fresh_render_concurrency.
2. install k6 (brew Install k6).
3. Run `deno task start`.
4. Run `k6 run script.js & k6 run script_2.js &`.
5. Open the browser in `http://localhost:8000/admin/demo` and wait to see `fashion` being rendered, when the correct value would be `demo`.

```tsx
// routes/admin/[site]/index.ts
import Counter from "../../../islands/Counter.tsx";

export const handler = (req, ctx) => ctx.render({ site: ctx.params.site });

export default function Component(props) {
  const {
    data,
    url: { search },
  } = props;

  return <Counter site={data.site} />;
}
```

<img width="942" alt="image" src="https://github.com/denoland/fresh/assets/15680320/d456dea4-dcf3-4a86-9e7b-56b5b3d72d5b">

## Versions
fresh 1.3.1
deno 1.36.1
v8 11.6.189.12
typescript 5.1.6

**Comment by mcandeia** [comment]
Cc: @marvinhagemeister

**Comment by marvinhagemeister** [comment]
Can reproduce it on my end and I know where the issue is coming from. Will fix it tomorrow as it's 1AM here.

**Comment by vibegui** [comment]
Thanks @marvinhagemeister !! Thanks for the detailed report @igorbrasileiro

**Comment by marvinhagemeister** [comment]
Fix is ready and awaiting review. We had planned to cut a new release later today anyway. So the fix should roll out pretty soon.

Also I'd really like to thank @igorbrasileiro for the excellent reproduction! That was really helpful in narrowing down the issue and I didn't know about `k6` prior. Thank you again for reporting this 👍

**Comment by marvinhagemeister** [comment]
Just published the release which includes the fix for this issue https://github.com/denoland/fresh/releases/tag/1.4.0
