### ISSUE TITLE
Can't update to Fresh 1.4: error: Relative import path "preact" not prefixed with / or ./ or ../

### ISSUE THREAD

**Issue by ryota-murakami** [denoland/fresh#1643]
Run `deno run -A -r https://fresh.deno.dev/update .`,  I got this error and update not working.

```
error: Relative import path "preact" not prefixed with / or ./ or ../
    at https://deno.land/x/fresh@1.4.0/src/server/mod.ts:2:35
```

![Screenshot 2023-08-17 at 2 41 00](https://github.com/denoland/fresh/assets/5501268/d941db95-e392-4302-baab-36767e549fbc)

## Production
Clone https://github.com/laststance/blog and run `deno run -A -r https://fresh.deno.dev/update .`.

## Environment
deno 1.36.0 (release, x86_64-apple-darwin)
v8 11.6.189.12
typescript 5.1.6

**Comment by marvinhagemeister** [comment]
Thanks for reporting this. I'll push a patch release.

Fixed by https://github.com/denoland/fresh/pull/1642

**Comment by ryota-murakami** [comment]
@marvinhagemeister Thanks! Now it works!
