### ISSUE TITLE
Running `deno run -A -r https://fresh.deno.dev` results in "preact" not prefixed with / or ./ or ../

### ISSUE THREAD

**Issue by jake-danton** [denoland/fresh#1644]
When I run `deno run -A -r https://fresh.deno.dev` (as recommended in [README.md](https://github.com/denoland/fresh#readme)  I get the following:

```
error: Relative import path "preact" not prefixed with / or ./ or ../
    at https://deno.land/x/fresh@1.4.0/src/server/mod.ts:2:35
```

I also get it when trying to update a currently working fresh project with `deno run -A -r https://fresh.deno.dev/update .`

**Comment by jake-danton** [comment]
Output of `deno --version`:
```
deno 1.36.1 (release, x86_64-pc-windows-msvc)
v8 11.6.189.12
typescript 5.1.6
```

**Comment by marvinhagemeister** [comment]
Thanks for reporting this. I'll push a patch release.

Fixed by https://github.com/denoland/fresh/pull/1642
