### ISSUE TITLE
Auto-reloading browser not working in Fresh 1.4.1

### ISSUE THREAD

**Issue by timharek** [denoland/fresh#1647]
Tested in both a long-standing project and a freshly created project with `deno run -A -r https://fresh.deno.dev`.

Tested for:
- Firefox 116.0.2
- Safari 16.6
- Chrome 115.0.5790.170

**Comment by mitchwadair** [comment]
Having the same issue on my project as well

**Comment by afifurrohman-id** [comment]
**yes me too**
