### ISSUE TITLE
bug: running dev.ts uses the snapshot

### ISSUE THREAD

**Issue by sigmaSd** [denoland/fresh#1650]
Using `deno run -A dev.ts` after building the assets I get `Using snapshot found at ..`

I expected the dev builds to not use the snapshots, and thats what the docs here https://fresh.deno.dev/docs/concepts/ahead-of-time-builds seems to say 
>When Fresh is started in **non-development** mode (usually via main.ts), Fresh will automatically pick up optimized assets

**Comment by lionel-rowe** [comment]
Is there a workaround for this in 1.4.2 without deleting `./_fresh`?

**Comment by sheepsteak** [comment]
I'm having this issue too. It's particularly bad with islands as if you update one of them it refreshes with the correct changes from the server but then they're instantly replaced with the out-of-date snapshot in the client render it seems.

**Comment by sheepsteak** [comment]
I think I've tracked down why this happens to this code:

https://github.com/denoland/fresh/blob/fb6d11747b0f0e17af0e43be2331db35946c6900/src/dev/dev_command.ts#L37-L41

Running `deno task start` always goes through the `else` branch. `deno task build` always goes through the `if`. The `build` function is using `skipSnapshot` to force a new `_fresh` directory:

https://github.com/denoland/fresh/blob/fb6d11747b0f0e17af0e43be2331db35946c6900/src/dev/build.ts#L18-L21

When it goes through the `else` branch above it ends up starting a server as though it was running in production, I think, as `entrypoint` seems to be the `main.ts` in our projects.

**Comment by lionel-rowe** [comment]
> Is there a workaround for this in 1.4.2 without deleting `./_fresh`?

Assuming no, my current workaround is just to change the `start` task to `rm -r ./_fresh ; deno run -A --watch=static/,routes/ dev.ts`.
