### ISSUE TITLE
Exclude `_fresh` from lint and fmt paths on init/update

### ISSUE THREAD

**Issue by imblowfish** [denoland/fresh#1652]
Hi, updated the project to Fresh 1.4 and saw 2 new tasks: `build` and `preview`. After calling `task build`, the `_fresh` directory was generated, to which the linter and formatter react with errors, it would be great to add them as `exclude` for `fmt` and `lint` in `deno.json` when updating/initializing

**Comment by afifurrohman-id** [comment]
i also suggests remove task name with **build** and **preview** in `deno.json` if the build steps it's really **optional**

So comeback with the headline of `fresh` **NO BUILD STEPS**

**Comment by marvinhagemeister** [comment]
@afifurrohman-id That sounds like a separate topic from excluding `_fresh` from `deno lint` and `deno fmt`. Please open a new issue for that.
