### ISSUE TITLE
Suggestions: `remove task build and preview`

### ISSUE THREAD

**Issue by afifurrohman-id** [denoland/fresh#1662]
If the build steps it's really optional?

So comeback with the headline of fresh **NO BUILD STEPS**

Maybe docs has been described the option.
So. no need to add when start fresh project template

**Comment by marvinhagemeister** [comment]
Thanks for opening a separate issue. The build step is optional and Fresh works without that. We make it easy to use Fresh without a build step, but we should also make it easy to use Fresh _with_ a build step if desired.

The `preview` task has nothing to do with the build step. It would be the same task without it. Not sure why you added that in the headline.

**Comment by marvinhagemeister** [comment]
Closing, as the build task is optional and not required. It can be easily removed if that's not your style.
