### ISSUE TITLE
`<body>` is placed inside `<head>` in the HTML

### ISSUE THREAD

**Issue by frou** [denoland/fresh#1666]
Fresh 1.4.1

Set up the demo project (`deno run -A -r https://fresh.deno.dev`) and look at the textual HTML returned by the server for the page. It's of the form:

```
<html>
  <head>
    <body>
    </body>
  </head>
</html>
```

rather than

```
<html>
  <head>
  </head>
  <body>
  </body>
</html>
```

**Comment by marvinhagemeister** [comment]
~~@frou I'm unable to reproduce that on my end. Can you share the exact steps you did?~~

Nevermind, I can reproduce it.

**Comment by frou** [comment]
It's happening live on Fresh's own homepage :)

View the source of https://fresh.deno.dev/ and see it ends with 

```html
</body></head></html>
````

Seemingly the browsers tolerate it because of Postel's Law?

**Comment by marvinhagemeister** [comment]
That's a bit embarrassing. Thanks for reporting it 👍
