### ISSUE TITLE
Documentation: examples: 'Using Twind v1' is partially outdated

### ISSUE THREAD

**Issue by pintoflager** [denoland/fresh#1672]
Create new fresh project with ```deno run -A -r https://fresh.deno.dev``` and both main.ts and dev.ts import config from same place: ```import config from "./fresh.config.ts";``` but example suggests to import plugin and config separately and do the same as  fresh.config.ts already does:
```
import twindPlugin from "$fresh/plugins/twindv1.ts";
import twindConfig from "./twind.config.ts";

await start(manifest, { plugins: [twindPlugin(twindConfig)] });
```

Following instructions as they are now leaves fresh.config.ts as it is and that leads to an type error in ```twindPlugin(twindConfig)```
in fresh.config.ts which still imports twindPlugin from old version.

To fix the example update it with suggested modifications for main.ts to be included for the fresh.config.ts instead

**Comment by joehillen** [comment]
I don't understand what you're saying the fix is. Can you clarify?

This might be related to the issue I'm having in 1.4.2:

```
Loading module from “http://localhost:8000/_frsh/js/5f2ef3d40dc7377b1d88e63323b4db924fd1efb4/plugin-twind-main.js” was blocked because of a disallowed MIME type (“”).
```

**Comment by pintoflager** [comment]
Documentation should say something like this:
### Using Twind v1

When you initialize a project with ```deno run -A -r https://fresh.deno.dev```, you’ll end up with a **fresh.config.ts** like the following:
```typescript
import { defineConfig } from "$fresh/server.ts";
import twindPlugin from "$fresh/plugins/twind.ts"
import twindConfig from "./twind.config.ts";
export default defineConfig({
  plugins: [twindPlugin(twindConfig)]
});
```

Change **twindPlugin** import path to twind version 1:
```typescript
import twindPlugin from "$fresh/plugins/twindv1.ts"
```

Typescript gives error for twind config object imported from peer file **twind.config.ts**
```typescript
import twindConfig from "./twind.config.ts";
```
so lets open that file and we should see something like this:
```typescript
import { Options } from "$fresh/plugins/twind.ts";

export default {
  selfURL: import.meta.url,
} as Options;
```

The twind config object has changed significantly in v1, so has to change our config. Following should be a good starting point: 
```typescript
import { defineConfig, Preset } from "https://esm.sh/@twind/core@1.1.3";
import presetTailwind from "https://esm.sh/@twind/preset-tailwind@1.1.4";
import presetAutoprefix from "https://esm.sh/@twind/preset-autoprefix@1.0.7";

export default {
  ...defineConfig({
    presets: [presetTailwind() as Preset, presetAutoprefix()],
  }),
  selfURL: import.meta.url,
};
```
Hit save and typescript should not display any errors.
Run ```deno task start``` and yor project boots using twind version 1.

Note: the ```as Preset``` typecast is required for ```presetTailwind()``` to fix a typing issue with twind.

And remember that the same requirement might apply for other presets as well (at least [@twind/preset-typography](https://twind.style/preset-typography) requires the same typecast)

To see what other presets exist, you can go to the [twind docs](https://twind.style/presets).

**Comment by pintoflager** [comment]
@joehillen
I'm just pointing out a documentation issue that applies for new projects started with the instructions from [Using Twind v1](https://fresh.deno.dev/docs/examples/using-twind-v1)

Your issue is something else
