### ISSUE TITLE
Moving root `index.tsx` into a route group causes 404 to be returned

### ISSUE THREAD

**Issue by tmns** [denoland/fresh#1689]
Seems that if you move the root `index.tsx` (i.e. the `index` that is served when navigating to `/`) into a route group, the server returns 404 when trying to navigate to `/`. Since route groups are not supposed to interfere with routing, I would expect it to still find & serve `index.tsx`.

Example folder structure:

```
routes/
  _404.tsx
  _app.tsx
  (group)
    index.tsx <-- root /
    ...
```

Repro steps:
1. Set up a new project
```
deno run -A -r https://fresh.deno.dev
cd fresh-project
```
2. Create a route group and move `index.tsx` into it
```
cd routes
mkdir \(group\)
mv index.tsx \(group\)
```
3. Fix the import path to `Counter.tsx` in `index.tsx`
4. Run the app
```
deno task start
```
5. Navigate to `http://localhost:8000/`

**Comment by marvinhagemeister** [comment]
Thanks for opening an issue. This is an excellent reproduction case and with it I was able to spot the cause quickly 👍
