### ISSUE TITLE
Optional Dynamic Routes

### ISSUE THREAD

**Issue by cymkd** [denoland/fresh#1690]
**Fresh DX would benefit with supporting optional dynamic routes via filename convention**

Common scenario:
- multi-language routing where default language is not shown in the url.

Using an example for [lang] parameter.
/home 
/en/home 
/de/home

Whilst the folder structure might be
- [[lang]]
- - home.tsx

[[lang]]
[+lang]
[?lang]

**Comment by mbhrznr** [comment]
fwiw we could already apply optional dynamic params via `RouteConfig`.
successfully tested the following example:
```tsx
import { RouteConfig, RouteContext } from "$fresh/server.ts";

export const config: RouteConfig = {
  routeOverride: "{/(de|en)}?/home",
};

export default function HomePage(req: Request, ctx: RouteContext) {
  console.log(ctx.params);
  return <h1>i'm home!</h1>;
}
```

this would successfully catch `/home`, `/de/home` and `/en/home`.  
`ctx.params` would be logged as `{}`, `{ "0": "de" }` and `{ "0": "en" }` respectively.

might be worth some exploration as well?

**Comment by cymkd** [comment]
That is a great solution.

If I am not mistaken, when having 3000/4000 pages, we would need to maintain this Config, with routes and with allowed parameters. (or maybe just use .* and alike).
It's another thing to take care of.

In terms of DX it feels an improvement to have the optional dynamic routes filename convention, as we already have routing conventions.

**Comment by marvinhagemeister** [comment]
Yeah, the route config is more of an escape hatch when you need more control. It can do everything you need to, but nothing wrong with making common scenarios easier. It's the reason we have `[id]` or `[...slug]` after all.

**Comment by mbhrznr** [comment]
with #1706 being merged we could probably close this, wdyt?

**Comment by marvinhagemeister** [comment]
Ah good point. I missed this 👍
