### ISSUE TITLE
Cannot load `.env` with JSON value when run `deno task build` 

### ISSUE THREAD

**Issue by afifurrohman-id** [denoland/fresh#1695]
# Project Info
- Fresh 1.4.2
- Deno 1.36.2
- Project template from fresh 

# Description
> This issue happen when i have **JSON value** in `.env` and run `deno task build`.

> but using `deno task preview` or `deno task start` it's work fine
 

## Fixed by
> Add import `https://deno.land/std/dotenv/load.ts` in `dev.ts`

# Steps
```diff
# ./.env
DATA_SECRET={"message":"hello"}
```

```ts
// ./utils/app.ts
export const { message } = JSON.parse(Deno.env.get("DATA_SECRET")!);
```

```tsx
// ./routes/index.tsx
import { message } from "../utils/app.ts";

export default function Home() {
  return (
       <>
        <h1 class="text-4xl font-bold">{message}</h1>
    </>
  );
}

```

### Error:

```
error: Uncaught (in promise) SyntaxError: "undefined" is not valid JSON
export const { message } = JSON.parse(Deno.env.get("DATA_SECRET")!);
```

**Comment by marvinhagemeister** [comment]
`.env` files aren't automatically read. Therefore the environment variable `DATA_SECRET` is never set, which means `Deno.env.get()` returns `undefined`. And calling `JSON.parse(undefined)` throws an error as it should.

Since you didn't say what your intended goal of the issue is: Do you expect Fresh to read `.env` files automatically?

**Comment by afifurrohman-id** [comment]
yes, like when run `deno task start`

**Comment by dogukanakkaya** [comment]
I have faced with the same issue. Adding `import "$std/dotenv/load.ts";` at the top of `dev.ts` fixes the issue. But I'd agree that it's good to have it automatically loaded.

`preview` already runs `main.ts` directly. `start` also imports the entrypoint which is the `main.ts` so in both of those tasks env is loaded but not in build.

`src/dev/dev_command.ts:37`
```ts
if (Deno.args.includes("build")) {
  await build(join(dir, "fresh.gen.ts"), options);
} else {
  await import(entrypoint);
}
```

**Comment by marvinhagemeister** [comment]
The proper way to do this going forward is to add the `import "$std/dotenv/load.ts";` into `fresh.config.ts`. That's loaded whenever fresh runs, regardless of whether it was invoked via `build`, `dev.ts` or `main.ts`.

**Comment by marvinhagemeister** [comment]
FYI: We're moving away from `dev.ts` importing `main.ts` as it makes dev-specific modifications difficult. Adding it to `dev.ts` is the right way to go.
