### ISSUE TITLE
Caching Images - 304 on deno deploy 

### ISSUE THREAD

**Issue by adamgasiorek** [denoland/fresh#1698]
Hello
I have ecommerce website which display multiple of images. It generates enormous amount of requests because images are not cached.
Is there any reason why we cannot cache images ? 
Instead we are getting 304 status so it makes unneccessery request to server .

**Comment by marvinhagemeister** [comment]
Can you share more details on your setup? How are you serving those images? Are these files in the `static/` directory? Are you serving the images yourself via your own middleware?

**Comment by adamgasiorek** [comment]
Yes they are in `static` directory and i serve them through variable in handler->GET-> image: 'img.jpg'

`<img className="galleryItem" src={asset(image)} />`

![Zrzut ekranu 2023-08-24 o 09 44 59](https://github.com/denoland/fresh/assets/46958110/fd51e1dc-70ca-480c-9c8f-87b1e4740c21)

**Comment by marvinhagemeister** [comment]
From the looks of it, this seems to be a matter of visualization in browser DevTools. I made a quick example project and from what I can tell the asset is not served on a `304` response. I've logged all requests on the server and there are none there.

I think this [information on MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/304) describes what's happening:

> Note: Many [developer tools' network panels](https://firefox-source-docs.mozilla.org/devtools-user/network_monitor/index.html) of browsers create extraneous requests leading to 304 responses, so that access to the local cache is visible to developers.

**Comment by marvinhagemeister** [comment]
Closing, since it's the way browser DevTools handle `304` responses.
