### ISSUE TITLE
Plugin AOT Build Hook

### ISSUE THREAD

**Issue by adamgreg** [denoland/fresh#1700]
A plugin hook (or hooks) that run during/after an AOT build would be helpful.

Motivating example: Plugins that parse Tailwind classes from page content currently will miss any dynamic content not included in the initial SSR, which means runtime JS needs to be sent to the client to observe any content that is conditionally rendered. I suspect dynamic building of the class strings themselves is relatively rare, so it would be possible to generate complete CSS by parsing the source files in an AOT build. Then no Tailwind-related JS would need to be sent to the client.

I think this would work well as an optional feature in such plugins - the user could have the option of running either during SSR or during builds, and another option to either send the runtime JS or not.

**Comment by fdemir** [comment]
Agree. For instance, Nuxt.js provides custom hooks for this type of handler. Can be used as reference https://nuxt.com/docs/api/advanced/hooks

**Comment by miguelrk** [comment]
The ⚡ [**nitro engine**](https://nitro.unjs.io/) which powers nuxt itself could also serve as a great reference, and not only for their [runtime hooks](https://nitro.unjs.io/guide/plugins#nitro-runtime-hooks), but also for other areas in general e.g. auto-imports, storage, assets, etc. I would encourage everyone to check out their docs...

**Comment by marvinhagemeister** [comment]
Closing as we have a `buildStart()` and `buildEnd()` hook now similar to vite.
