### ISSUE TITLE
Plugin HTML transformations

### ISSUE THREAD

**Issue by adamgreg** [denoland/fresh#1701]
In some cases it would be helpful to be able to transform the HTML string in a plugin. Currently plugins have access to the HTML string from the render, but can't make any changes to it. An optional `htmlText` property in `PluginRenderResult` would help.

For example, UnoCSS user configs can include "transformers" that transform the HTML to support things like variant groups - https://unocss.dev/transformers/variant-group . The UnoCSS plugin being developed in https://github.com/denoland/fresh/pull/1303 currently can not apply these transformers.

**Comment by marvinhagemeister** [comment]
For the UnoCSS scenario: Is it important that it receives the full HTML string or would it suffice if it gets all the className strings?

**Comment by zhmushan** [comment]
@marvinhagemeister UnoCSS requires obtaining the full HTML string.

This is because in UnoCSS, we can not only set atomic styles using the `<... className="color-red" ... />` approach, but it also supports [valueless attributify](https://github.com/unocss/unocss/blob/main/packages/transformer-attributify-jsx/README.md) by using transformers.

**Comment by marvinhagemeister** [comment]
@zhmushan How is the type checking story on that? I'd assume `deno check` would throw an error when those unknown JSX attributes are set?

**Comment by zhmushan** [comment]
@marvinhagemeister Resolve by using [a .d.ts file](https://github.com/unocss/unocss/blob/main/examples/vite-preact/src/preact.d.ts).

**Comment by adamgreg** [comment]
I'm not really a fan of the attributify transform, but I'm definitely keen on the variant group one, so I can do things like group together a few different classes to apply on hover. In any case it would still have to be the full HTML string.. we already receive it, but would need to be able to set/return it as well.

I've had a quick look at how this might be implemented, and I think this could be accomplished just by adding something like `bodyHtml = res.htmlText ?? bodyHtml` after the two `renderResults.push([plugin, res])` lines in `server/render.ts`. Plus updating `PluginRenderResult` and the docs. I might be missing something though, of course.

**Comment by adamgreg** [comment]
It's not absolutely necessary for UnoCSS support, it just might be confusing for the user if they specify transforms in their config and they aren't applied.. it certainly confused me for a while!

I implemented support for transformers in the plugin, before getting stuck on this issue. The code is here, in case it helps explain what I'm hoping to do:
https://github.com/adamgreg/fresh_unocss/commit/9754c4b2e189bf18346c8077d8b718eb93d14274

**Comment by marvinhagemeister** [comment]
We can certainly expose a way to mess with the HTML string before sending it out.

It still seems odd to me to take on an additional parse step, since we are the ones creating the HTML string in the first place. My gut instinct is that doing those transforms before we render the HTML string in the first place would be faster, but I don't have numbers to back this up. Measuring just the extractors with the default uno preset, it seems like it adds about 1.2ms of overhead per request. This is just for the extractors, not the rest of uno.

Admittedly, I'm not much of a fan of the [valueless attributify](https://github.com/unocss/unocss/blob/main/packages/transformer-attributify-jsx/README.md?rgh-link-date=2023-08-24T09%3A10%3A44Z) option. The variant group one would be cool to have given that twind supported that too.

**Comment by adamgreg** [comment]
@marvinhagemeister Oh, do you mean maybe plugins could get smaller hooks that are called during the rendering of individual components instead of just on the final full HTML string? That would be interesting, although I wonder if it would be more performant or not.

If you directly used something like `magic-string` to expose a mutable interface over the HTML to plugins, that might be more performant than what I've suggested.

To be honest, for my project I'll do an AOT build, and then to me it makes more sense to run UnoCSS at build time over the whole code base. No need to run it after every SSR (getting the same results each time), and no need to send a runtime to the browser, so much more performant all round. A single static generated CSS file for the whole site, that can be cached. I like the idea of being able to use the Fresh plugin to support this (depending what happens with https://github.com/denoland/fresh/issues/1700 !), but otherwise I might not use the plugin myself (other than for dev), and just run the UnoCSS CLI over the project. It sidesteps issues like this, and avoids what feels like wasted CPU effort on both server & client just to generate the same predictable set of styles. Will be lovely if Fresh can offer both the same flexible twind-style experience and a good AOT build experience with the same plugin,

**Comment by zhmushan** [comment]
As mentioned by @adamgreg, UnoCSS's transformers are not necessary for us, so we can separate these two things.

Let's first complete the transformer-less version of the UnoCSS plugin as an experimental feature and inform users not to use those unimplemented transformers for the time being. Then, we can explore how to implement these transformers.

For me, I'm not fond of doing these transformations at runtime as it incurs additional performance overhead. Additionally, in traditional frontend development workflows, source code transformation is an essential step, which implies that the transformers in UnoCSS are specifically designed for that purpose. I'm concerned that directly incorporating them into the runtime could result in unpredictable errors. Perhaps it would be more appropriate to include these transformers in the esbuild build process.

**Comment by marvinhagemeister** [comment]
Resolved by https://github.com/denoland/fresh/pull/2022
