### ISSUE TITLE
Regression: Middleware Execution Limited to Route Path in Version 1.4.0

### ISSUE THREAD

**Issue by mcandeia** [denoland/fresh#1704]
**Description:**
I have identified a regression in version 1.4.0 of the framework related to middleware execution behavior. Prior to version 1.4.0, middleware handlers were consistently executed when matching the URL path. However, with the introduction of middleware plugin support, only the target middleware in the route **folder** is executed. This change has significant implications for existing projects and has led to unexpected behavior in middleware execution.

**Steps to Reproduce:**
1. Set up a project using version 1.3.0 of the framework.
2. Create a catch-all route handler (e.g., `[...catchall].tsx`) in the root directory.
3. Create a middleware file (e.g., `_middleware.ts`) in a subdirectory under `/routes/a/_middleware.ts`.
4. Trigger a request to a URL that matches the catch-all route, such as `http://localhost:8000/a/b/c`.

**Expected Behavior (Version 1.3.0):**
The middleware (`_middleware.ts`) placed inside the `/routes/a/` subdirectory is executed, as it previously matched the URL path and was consistent with the established middleware execution behavior.

**Observed Behavior (Version 1.4.0):**
Only the middleware placed inside the folder `/routes/` is executed. This change in behavior contradicts the previous middleware execution logic, leading to unintended consequences for projects relying on certain middleware.

I've created a sample repo to reproduce the issue: https://github.com/mcandeia/fresh-middleware-breakingchange

**Comment by mcandeia** [comment]
cc: @marvinhagemeister

**Comment by marvinhagemeister** [comment]
This is a very creative setup of using middlewares. I'm quite surprised that an app would rely on this, given it was never officially supported, nor documented as far as I'm aware. It's concerning because it has two major problems:

1. It introduces matching ambiguity in more complex route setups:
  ```sh
  routes/
    (group-1)/
      _middleware.ts    # this should only match for `page-1.tsx`, but with the old behavior it would match
      page-1.tsx
      
    (group-2)/
      _middleware.ts    # this should only match for `page-2.tsx`, but with the old behavior it would match
      page-2.tsx
    
    [...catchall].tsx
  ```
2. Worse performance, because route matching algorithm needs to be run twice: Once for middlewares and once for the actual route.

**Comment by mcandeia** [comment]
So I can assume that this will not be “fixed”, right @marvinhagemeister ?

**Comment by mcandeia** [comment]
> This is a very creative setup of using middlewares. I'm quite surprised that an app would rely on this, given it was never officially supported, nor documented as far as I'm aware. It's concerning because it has two major problems:
> 
> 1. It introduces matching ambiguity in more complex route setups:
> 
> ```shell
> routes/
>   (group-1)/
>     _middleware.ts    # this should only match for `page-1.tsx`, but with the old behavior it would match
>     page-1.tsx
>     
>   (group-2)/
>     _middleware.ts    # this should only match for `page-2.tsx`, but with the old behavior it would match
>     page-2.tsx
>   
>   [...catchall].tsx
> ```
> 
>  2. Worse performance, because route matching algorithm needs to be run twice: Once for middlewares and once for the actual route.

What are the paths in the first example? It gives me the impression that it will work fine, /page-1 and /page-2 ?

About 2. I think the behavior is the same as re-exporting the innermost catchall route in the a/ folder in the example that I provided when assigning routes/middleware. That should mimic the old behavior fine. Not tested yet but  can be used as a workaround for me.

**Comment by mcandeia** [comment]
> Not tested yet but can be used as a workaround for me.

I can confirm that it works, although unnecessary but I'm ok with the handmade solution. If you think that fresh should not support this, go ahead and close the issue. Thanks!

**Comment by mcandeia** [comment]
@marvinhagemeister Closing even though I think it was a nice feature =) (so that I can create middlewares for added by plugins routes - which is my case)

**Comment by marvinhagemeister** [comment]
@mcandeia I'm happy to reconsider with a proper use case. Now that I'm back from vacation, I have more time to garner some more opinions on the different behaviors.

**Comment by mcandeia** [comment]
Great! Let me know if I can help on anything
