### ISSUE TITLE
Bug: Islands inside folder based dynamic routes not recognized

### ISSUE THREAD

**Issue by cbinzer** [denoland/fresh#1708]
Hi,

first thank you for the cool feature of route groups. I like it much.

In the moment I’m restructuring my project and I noticed that is not possible to use islands inside folder based dynamic routes. For example I have the following structure: `routes/wissen/[uid]/index.tsx`. Now I added the islands folder to this directory: `routes/wissen/[uid]/(_islands)`. Unfortunately the islands are not recognized. I see in the console that all islands has been generated but in the browser the functionality of the islands are missing. The browser console shows me the following: `Uncaught SyntaxError: Unexpected token '[' (at (index):82:12375)`. So it seems like there is a problem with square brackets in the import statement.

Regards
Christian

**Comment by deer** [comment]
Looks like we're just not sanitizing the name properly. The client gets:
```js
import * as Routes_dynamic_[tenant]___islands__Counter_default from "/_frsh/js/18aa19eeadb3ce22cc8a1ae9445d843d397036ac/island-routes_dynamic_[tenant]___islands__counter_default.js
```
and `Routes_dynamic_[tenant]___islands__Counter_default` is not a valid javascript variable name, hence the error. I'm working on a test to ensure this doesn't break in the future.
