### ISSUE TITLE
`_app.tsx` does not receive `state` in component props if rendered for a `_500.tsx` page

### ISSUE THREAD

**Issue by lucacasonato** [denoland/fresh#1717]
When rendering an error via `_500.tsx`, the `_app.tsx` does not receive the `state` parameter. This is unlike when the `_app.tsx` is rendered for a `notFound` or `route`.

**Comment by deer** [comment]
Can I be assigned here? I have a fix and a test, but not quite enough time to do all the paperwork. Will create the PR later tonight or tomorrow morning.
