### ISSUE TITLE
checked attributed ignored on JSX passed to an island

### ISSUE THREAD

**Issue by zbynekwinkler** [denoland/fresh#1725]
I have an island form that renders regular components as children (as described in https://fresh.deno.dev/docs/concepts/islands#passing-jsx-to-islands)

```tsx
import { ComponentChildren } from "preact";

export default function IslandForm(props: {
  children?: ComponentChildren;
}) {
  return (
    <form action="javascript:">
      <fieldset>
        {props.children}
      </fieldset>
    </form>
  );
}

```

When the child is either a checkbox or a radio button, the `checked` attribute is ignored:

```tsx
import IslandForm from "../islands/IslandForm.tsx";

export default function () {
  return (
    <IslandForm>
      <label>
        <input type="radio" checked />first option
      </label>
      <label>
        <input type="checkbox" checked />checkbox
      </label>
    </IslandForm>
  );
}
```

The result:
![image](https://github.com/denoland/fresh/assets/1130051/b5d2bca4-5b2c-425a-af8b-f1d878ba2b4a)

If the checkbox or radio button is directly in the island, it works as expected:

```tsx
import { ComponentChildren } from "preact";

export default function IslandForm(props: {
  children?: ComponentChildren;
}) {
  return (
    <form action="javascript:">
      <fieldset>
        <label>
          <input type="radio" checked />first option
        </label>
        <label>
          <input type="checkbox" checked />checkbox
        </label>
      </fieldset>
    </form>
  );
}

```

Results in
![image](https://github.com/denoland/fresh/assets/1130051/d20d6113-4334-4238-875e-844e57a93930)

**Comment by marvinhagemeister** [comment]
Thank you for providing a snippet with which the problem can be reproduced. This was really helpful in getting to the bottom of the issue 👍
