### ISSUE TITLE
Updating the twind template or providing a section for Twind v1 plugin

### ISSUE THREAD

**Issue by ghost** [denoland/fresh#1728]
Hello 👋🏼.

Today Twind is providing a template for using tailwind CSS transparently with twind. However it is providing twind v0 despite v1 being available as an official plugin. I was wondering if we could update it or provide a documentation page to explain how to setup Twind V1 ? Currently from looking at the docs, I can only see a page for describing how to write [plugins](https://fresh.deno.dev/docs/concepts/plugins).

WDYT ?

---

# How I did it

If anyone coming across the same issue wants to do it here's a tl;dr regarding how to do it, it can also give a hint as-to how could it look like if we end up providing a tutorial or an updated template regarding this issue:

1. Create a `twind.config.ts` to bootstrap twind and the tailwind prefix lib since `@twind/core` does not include tailwind base rules. Here, autoprefix is included as well but it's not necessary.

```ts
import { Options } from "$fresh/plugins/twindv1.ts";

import { Preset } from "https://esm.sh/v131/@twind/core@1.1.3/core.d.ts";

import presetAutoprefix from "https://esm.sh/@twind/preset-autoprefix@1.0.7";
import presetTailwind from "https://esm.sh/@twind/preset-tailwind@1.1.4";

interface OptionsWithPresets extends Options {
  presets: Preset[];
}

export default {
  presets: [presetAutoprefix(), presetTailwind()],
  selfURL: import.meta.url,
} as OptionsWithPresets;
```

2. Then, edit the `fresh.config.ts` to include twind:

```ts
import { defineConfig } from "$fresh/server.ts";
import twindPlugin from "$fresh/plugins/twindv1.ts";
import twindConfig from "./twind.config.ts";

export default defineConfig({
  plugins: [twindPlugin(twindConfig)],
});
```

**Comment by rojvv** [comment]
@marvinhagemeister This can be closed.

**Comment by marvinhagemeister** [comment]
Closing as we're officially recommending to use the tailwindcss plugin instead.
