### ISSUE TITLE
Disable animation on home page when `prefers-reduced-motion` is set

### ISSUE THREAD

**Issue by lucacasonato** [denoland/fresh#173]
[prefers-reduced-motion](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion) is an accessibility feature that lets developers know that a user prefers to not see motion on the page (like animations).

We should disable the animation on the home page when a user has this set.

cc @hashrock

**Comment by hashrock** [comment]
Good catch! I'll take it.
