### ISSUE TITLE
Issues with Server Sent Events Client

### ISSUE THREAD

**Issue by mcgear** [denoland/fresh#1754]
Having a bit of an issue getting a fresh implementation going of an SSE client.

We are doing some work with OpenAI through Azure and are trying to stream the responses back to the UI.

If you check out our project [Communit Chat](https://github.com/fathym-deno/community-chat/) you can run it with `deno task start` and then if you navigate to `/api/openaistream/gpt-35-turbo` you'll see that the API is responding with SSE and that the story comes in written in chunks.

The issue is that i can't figure out how to get an Island together that renders the chunks into view.  We are trying in the `islands/TextStream.tsx` but I am running into issues.

1) EventSource is not defined error is thrown due to there not being a Deno EventSource definition [#10298](https://github.com/denoland/deno/issues/10298)
2) When i try to use the third party module from [here](https://deno.land/x/eventsource@v0.0.3/mod.ts) I get an error: caught (in promise) TypeError: reader is not async iterable
    at #fetch (mod.ts:124:35)

Any help in what i am doing wrong would be awesome, and i figure at the end of this we can PR into the docs a page on Server/Client SSE in Deno Fresh.

Thanks for the help!

**Comment by smitssjors** [comment]
https://github.com/denoland/pixelpage Is implemented using SSE. Checkout `islands/Pixels.tsx` and `routes/api/listen.ts`. Also make sure that the events are properly [formatted](https://developer.mozilla.org/en-US/docs/Web/API/Server-sent_events/Using_server-sent_events#examples) (e.g., `data: some text\n\n`).

I hope this helps

**Comment by mcgear** [comment]
I was working on trying this out, but the biggest issue i have is that it says BroadcastChannel and EventSource are not defined. Trying to see what i missed to have those included.  I see your on fresh version 1.2, not sure if that is the issue

**Comment by mcgear** [comment]
Well that was easy, i didn't realize i needed the --unstable flag for those 2 to work.

**Comment by mcgear** [comment]
Alright, this is working for me now, i am able to stream stuff in, however, the EventSource just keeps reconnecting and calling the API over and over again.  Any thoughts on how i can make the EventSource only execute once?

**Comment by mcgear** [comment]
I was able to address this issue by sending a [DONE] event at the end of the stream and listening for that on the client side, which allows me to then close the connection.  This can probably be considered done in terms of my issues.

Is there any value in my documenting the entire process for SSE in the docs for Fresh?

Thanks for the help @smitssjors

**Comment by marvinhagemeister** [comment]
FYI: We've just switched over from SSE to websockets to establish a connection in development mode in https://github.com/denoland/fresh/pull/1943 .

**Comment by sebringj** [comment]
v1.6 working here https://stackoverflow.com/questions/76493038/possible-to-do-server-side-events-with-deno-fresh-framework/77712227#77712227
