### ISSUE TITLE
Node compatibility

### ISSUE THREAD

**Issue by coxmi** [denoland/fresh#1755]
Is there any interest in this being compatible with node?

This fits my needs perfectly, but our team aren't prepared to move away from node. I'm happy to work on this to provide shims wherever deno-specific functionality is used, but understand if the core team are set on deno-only.

I absolutely love the simplicity of this, but it would be fantastic to make it more portable to other runtimes, even if just for some core features.

Thanks!
Michael

**Comment by marvinhagemeister** [comment]
This is the first time this question has come up. I'm not sure if that will happen as there is a conflict of interest. This project is 100% funded by the company behind deno.

**Comment by coxmi** [comment]
That's a shame, but I totally understand!
