### ISSUE TITLE
Twind not injecting styles after updating to Fresh `v1.4.3`

### ISSUE THREAD

**Issue by timharek** [denoland/fresh#1756]
After updating to Fresh `v1.4.3` all my styles disappeared. I was using the `<Head>` component in `_app.tsx`, but even after switching it to `<head>` my styles does not get injected anymore. I compared my project with the starter-template, but I can't see what is wrong.

This is the project that I'm trying to update to  `v1.4.3`: https://github.com/timharek/timharek.no

**Comment by topce** [comment]
I have same problem 
resolve it by modifying files dev.ts and fresh.config.ts   
like in commit 
https://github.com/topce/tic-tac-toe/commit/3bea1d60236b4ce8a7c78432c1be63e1b231a414

**Comment by marvinhagemeister** [comment]
Can confirm this bug. I'm quite worried that our test suite didn't catch this.

Workaround:

1. Move fresh config to its own file `fresh.config.ts`
2. Import that into `main.ts` and pass it there to `start()`
3. Import that into `dev.ts` and pass it to `dev()`

If you init a new fresh project you can see an example of how that setup looks like.

**Comment by timharek** [comment]
Strange 😅 I guess I will wait to upgrade until this bug is resolved then. Thanks for looking into it, @marvinhagemeister. And thanks for the workarounds, both of you, @topce :)

**Comment by marvinhagemeister** [comment]
Resolved by https://github.com/denoland/fresh/pull/1764
