### ISSUE TITLE
suggestion: automatically render not found page

### ISSUE THREAD

**Issue by iuioiua** [denoland/fresh#1759]
If [`Deno.errors.NotFound`](https://deno.land/api@v1.36.4?s=Deno.errors.NotFound) or [`errors.NotFound`](https://deno.land/std@0.201.0/http/http_errors.ts?s=errors) is thrown within a handler, the "HTTP 404 Not Found" page should be automatically rendered, by default. In other words, `throw new Deno.errors.NotFound()` would be the same as `return ctx.renderNotFound()`.

**Comment by lausuarez02** [comment]
Hey, 
If no one took this, i would like to take it :)

**Comment by lausuarez02** [comment]
Hey, 
After looking the code i do not see Deno.errors.NotFound or errors.NotFound being thrown at any point. 
I've seen that inside the catch of getServerContext is doing nothing in case of error being an instanceof Deno.errors.NotFound. 
If you talk about that case for example i could extract the renderNotFound function from inside ServerContext class to be able to access it from SeverContext and getServerContext.
Let me know so i know if i can do something with this ticket :).

**Comment by iuioiua** [comment]
> After looking the code i do not see Deno.errors.NotFound or errors.NotFound being thrown at any point.
> I've seen that inside the catch of getServerContext is doing nothing in case of error being an instanceof Deno.errors.NotFound.

Perhaps I could've explained it clearer. The idea was for when these errors are thrown within a handler rather than from within the codebase. We often use this pattern in [Deno SaaSKit](https://github.com/denoland/saaskit).

> If you talk about that case for example i could extract the renderNotFound function from inside ServerContext class to be able to access it from SeverContext and getServerContext.

Sure! Let's try that 👍🏾

**Comment by diecodev** [comment]
In the current latest vresion this is not working (Fresh@1.5.4):
![image](https://github.com/denoland/fresh/assets/51871681/0c11f3f9-f14b-4c96-83a7-6195229529c9)

But, if you use the canary version with the hash of your PR (@deer) then it works:
![image](https://github.com/denoland/fresh/assets/51871681/586d4a57-a468-4d36-9f28-12dc8a41af82)
