### ISSUE TITLE
docs:  clarify what the difference is between dev.ts and main.ts

### ISSUE THREAD

**Issue by cknight** [denoland/fresh#1761]
Reading the docs, it states that `dev.ts` is the development entry point for my app, while `main.ts` is the production entry point.  What's different between these two?  The [Running locally](https://fresh.deno.dev/docs/getting-started/running-locally) docs point to using `deno task start` which runs `dev.ts`, but then go on to describe how you would run it manually, which boils down to the same command as `deno task start` swapping out `dev.ts` with `main.ts`.

**Comment by marvinhagemeister** [comment]
You want to develop your site? -> use `dev.ts`
You want to run your site on a production server? -> use `main.ts`

The `dev.ts` script enables a bunch of development only features such as including `preact/debug`, regenerating `fresh.gen.ts` automatically and potentially more stuff in the future.
