### ISSUE TITLE
Auto-reloading fresh site does not work in Firefox 

### ISSUE THREAD

**Issue by cknight** [denoland/fresh#1765]
Developing a site in Fresh.  Auto-reload works as expected in Chrome 116, but not in Firefox 117.  Error in console is:

> Firefox can’t establish a connection to the server at http://localhost:8000/_frsh/alive.

As a new user to Firefox, this may be some configuration issue on my end.  Here's the first request in the network logs to _frsh/alive:

![image](https://github.com/denoland/fresh/assets/1248238/7942b368-8c84-4899-bbbe-0a324c171dc2)

**Comment by cknight** [comment]
Closing as this suddenly seems to have started working.  No clear reason as to why.

**Comment by guy-borderless** [comment]
![image](https://github.com/denoland/fresh/assets/100129659/32c96017-2606-4bab-aabd-fb30290b85d6)
![image](https://github.com/denoland/fresh/assets/100129659/9b0f1ebd-520b-4cb7-a404-c800709ab146)
I get the same on firefox, works on chrome.

**Comment by cknight** [comment]
Reopening as over time i auto refresh continually stops working in Firefox, only occasionally auto refreshing

**Comment by marvinhagemeister** [comment]
Can confirm, it tends to stop for me from time to time too. Not sure why yet though. Maybe this has something to do with Fresh using SSE instead of a websocket connection.
