### ISSUE TITLE
form handling idea.

### ISSUE THREAD

**Issue by danilovmy** [denoland/fresh#1766]
right now we have handler by methods(get/post) for all froms on the page.

But some times i have one form in one island, and other form in other island on the one page.
(subscription form & contact form.)

It can be easier to have a  handler  for form on the island and not on the page. In this case i can split and place send-form logic on the right places, and dont have all logic in the one huge page handler. ALso the returned ctx.render() will re-render only the current island an not the whole page.

**Comment by marvinhagemeister** [comment]
You can re-render sections of the page via Partials. To be able to compose handlers, you can extract the relevant code into functions and call those functions in the handler instead.

**Comment by danilovmy** [comment]
Yes, you are right, manually I could do it before my question. The idea is to implement this at the framework level.
