### ISSUE TITLE
Fresh breaks when Island returns nested Island component directly

### ISSUE THREAD

**Issue by vibegui** [denoland/fresh#178]
Apparently, when an Island returns another Island directly, instead of wrapped
in an element such as div, fresh breaks with this in the console:

```
main.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'nextSibling')
    at h (main.js:1:99)
    at n (main.js:1:659)
    at n (main.js:1:690)
    at n (main.js:1:717)
    at n (main.js:1:717)
    at S (main.js:1:722)
    at (index):4:1
```

You can find a reproduction here: https://github.com/FutureDrivenDev/fresh-nested-islands/blob/main/islands/Outer.tsx#L10

**Comment by lucacasonato** [comment]
Duplicate of #168 maybe?

**Comment by vibegui** [comment]
Yes! Will close in favour of #168

**Comment by igorbrasileiro** [comment]
> Duplicate of #168 maybe?

@lucacasonato I'm facing this problem without nested islands.
If you get this page document (view-source:https://deco-sites-fashion-fb34r6n15tg0.deno.dev/feminino?filter.category-1=feminino&filter.category-3=calca) exists an island with this comment `<!--frsh-sendeventbutton:9-->` related to this island (https://github.com/deco-sites/fashion/blob/c4672dfa5b93cd65ae74e27d6181b9eae8ccfcf1/components/product/ProductCard.tsx#L97-L115)

Something interesting is that the HTML tree is
```xml
<div>
  <ul />
  <a />
</div>
```

But the dom after fresh revive, be like this:
```html
<div>
   <a> // I don't know which anchor is this
      <ul />
   </a>
   <a /> // the same a from the HTML
</div>
```

You can also test here: https://deco-sites-fashion-fb34r6n15tg0.deno.dev/live/previews/deco-sites/fashion/sections/ProductShelf.tsx?props=eyJwcm9kdWN0cyI6eyJfX3Jlc29sdmVUeXBlIjoiZGVjby1zaXRlcy9zdGQvZnVuY3Rpb25zL3Z0ZXhQcm9kdWN0TGlzdC50cyIsInF1ZXJ5IjoiY2FsY2EifSwidGl0bGUiOiJ0aXRsZSJ9

**Comment by luanfonceca** [comment]
> > Duplicate of #168 maybe?
> 
> @lucacasonato I'm facing this problem without nested islands. If you get this page document (view-source:https://deco-sites-fashion-fb34r6n15tg0.deno.dev/feminino?filter.category-1=feminino&filter.category-3=calca) exists an island with this comment `<!--frsh-sendeventbutton:9-->` related to this island (https://github.com/deco-sites/fashion/blob/c4672dfa5b93cd65ae74e27d6181b9eae8ccfcf1/components/product/ProductCard.tsx#L97-L115)
> 
> Something interesting is that the HTML tree is
> 
> ```
> <div>
>   <ul />
>   <a />
> </div>
> ```
> 
> But the dom after fresh revive, be like this:
> 
> ```
> <div>
>    <a> // I don't know which anchor is this
>       <ul />
>    </a>
>    <a /> // the same a from the HTML
> </div>
> ```
> 
> You can also test here: https://deco-sites-fashion-fb34r6n15tg0.deno.dev/live/previews/deco-sites/fashion/sections/ProductShelf.tsx?props=eyJwcm9kdWN0cyI6eyJfX3Jlc29sdmVUeXBlIjoiZGVjby1zaXRlcy9zdGQvZnVuY3Rpb25zL3Z0ZXhQcm9kdWN0TGlzdC50cyIsInF1ZXJ5IjoiY2FsY2EifSwidGl0bGUiOiJ0aXRsZSJ9

Believe it or not, but I just had the same issue and fixed that by deleting the `LiveControls.jsx` component from the `islands` folder.

The odd part to me is that I have another project running pretty much the same versions on `import_map.json` and deno and in there I could not reproduce the Uncaught TypeError, which means to me that I have no idea what's going on hahaha but I hope it helps

**Comment by igorbrasileiro** [comment]
> Believe it or not, but I just had the same issue and fixed that by deleting the `LiveControls.jsx` component from the `islands` folder.
> 
> The odd part to me is that I have another project running pretty much the same versions on `import_map.json` and deno and in there I could not reproduce the Uncaught TypeError, which means to me that I have no idea what's going on hahaha but I hope it helps

This project doesn't have this file livecontrols.tsx 👀  (https://github.com/deco-sites/fashion/tree/c4672dfa5b93cd65ae74e27d6181b9eae8ccfcf1/islands).
I can fix this just adding an empty div after the island, because the "node.nextSibling" isn't undefined, but I didn't get why it work and still adding an anchor from elsewhere
