### ISSUE TITLE
Application and Layout wrappers as async

### ISSUE THREAD

**Issue by mcgear** [denoland/fresh#1796]
Is it currently possible to look at making the Application and Layout wrappers async?

currently looking at adding some usage of the deno kv oauth plugin, like get session id around the whole app, or in a layout in a sub folder.

I am getting errors when i do that.

Any initial thoughts?

**Comment by marvinhagemeister** [comment]
@mcgear Both async layouts and async app wrapper is possible and we're using that in some of our projects in production. Can you share what kind of errors you are getting?

**Comment by mcgear** [comment]
I took my _app.tsx file and just added async to the function:

import { AppProps } from "$fresh/server.ts";
import NavbarBranded from "../islands/NavBarBranded.tsx";

export default async function App({ Component }: AppProps) {
  return (
    <html>
      <head>
        <link rel="icon" type="image/svg+xml" href="/logo.svg" />
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>community-chat</title>
      </head>
      <body class="mx-auto dark:text-white dark:bg-gray-900">
        <div class="mx-auto dark:bg-gray-900">
          <NavbarBranded />

          <div class="mx-auto flex flex-col">
            <Component />
          </div>
        </div >
      </body>
    </html>
  );
}


And now i get this:
![image](https://github.com/denoland/fresh/assets/1460046/e149734e-cfeb-43c3-bc49-3c4b55a2b3d9)

**Comment by mcgear** [comment]
Also curious if Islands can be written as async for use of things like fetch...  Maybe i have some versions out of sync or something?

**Comment by mcgear** [comment]
What projects in production use it that i could checkout and compare with?

**Comment by marvinhagemeister** [comment]
@mcgear Adding the `async` keyword is not enough as also the arguments change, see https://fresh.deno.dev/docs/concepts/app-wrapper#async-app-wrapper .

```diff
- export default async function App({ Component }: AppProps) {
+ export default async function App(req: Request, ctx: AppContext) {
    // ...
  }
```

The easiest way to avoid such issues is via the `defineApp` helper, because they are already strongly typed. This reduces the risk of getting the types wrong yourself.

```jsx
export default defineApp((request, context) => {
  // ...
});
```

Note, that there is also `defineLayout` and `defineRoute` respectively for async routes and layouts.

**Comment by mcgear** [comment]
I missed that in the documentation, thank you for the clarification on this!
