### ISSUE TITLE
Island Conditional Render Bug

### ISSUE THREAD

**Issue by mitchwadair** [denoland/fresh#1810]
Okay, so I think I have a similar issue to what is described in #1322 and #1464, but my setup is slightly more complicated.

I have an island component (a dropdown) that I want to have customizable children for, so I created some components to wrap certain child elements in that use a signal in context to conditionally render/perform some actions:
```tsx
// islands/Dropdown.tsx
import { ComponentChildren, createContext } from "preact";
import { createSignal } from "/utils/hooks.ts";

const DropdownContext = createContext<ReturnType<typeof createSignal<boolean>>>(
  [false, () => false],
);

export default function Dropdown(
  { children }: { children: ComponentChildren },
) {
  return (
    <DropdownContext.Provider value={createSignal(false)}>
      {children}
    </DropdownContext.Provider>
  );
}

export function DropdownHandle(
  { children }: { children: ComponentChildren },
) {
  return (
    <DropdownContext.Consumer>
      {([isMenuOpen, setIsMenuOpen]) => (
        <button onClick={() => setIsMenuOpen(!isMenuOpen)}>
          {children}
        </button>
      )}
    </DropdownContext.Consumer>
  );
}

export function DropdownMenu({ children }: { children: ComponentChildren }) {
  return (
    <DropdownContext.Consumer>
      {([isMenuOpen]) => {
        if (isMenuOpen) {
          return children;
        }
      }}
    </DropdownContext.Consumer>
  );
}
```
My signal hook looks like this, just gives it a more `useState`-like API:
```ts
import { useSignal } from "@preact/signals";

export function createSignal<T>(initialValue: T): [T, (newValue: T) => T] {
  const signal = useSignal(initialValue);
  return [signal.value, (newValue: T) => signal.value = newValue];
}
```

Now, if I use this component somewhere in my app like this:
```tsx
<Dropdown>
    <DropdownHandle>Click me!</DropdownHandle>
    <DropdownMenu>Hello Menu!</DropdownMenu>
</Dropdown>
```
Clicking on the button does nothing. However, reversing the condition in the `DropdownMenu` component will cause it to work. The only issue being that the menu is open by default.

Hopefully there is enough context here to repro/find a solution.

Also, if I am overthinking my use-case please let me know, I'm always down to learn how to simplify my code.

versions
```
"$fresh/": "https://deno.land/x/fresh@1.4.3/",
"preact": "https://esm.sh/preact@10.15.1",
"@preact/signals": "https://esm.sh/*@preact/signals@1.1.3",
```

**Comment by marvinhagemeister** [comment]
Deleted my previous comment. Originally I thought the function children are an issue, but the again these happen _inside_ the island so it should be fine. Needs more investigation.

**Comment by afifurrohman-id** [comment]
Any progress to this? I have the same issue.

**Comment by marvinhagemeister** [comment]
@mitchwadair thanks for the detailed reproduction. Was able to reproduce the issue and get to the bottom of this.

As a side node, I noticed that the `createSignal` function immediately unwraps the signal which removes all the benefits of going with singals in the first place. I think it should look like this instead:

```tsx
export function createSignal<T>(initialValue: T): [Signal<T>, (newValue: T) => T] {
  const signal = useSignal(initialValue);
  return [signal, (newValue: T) => signal.value = newValue];
}
```

**Comment by mitchwadair** [comment]
> @mitchwadair thanks for the detailed reproduction. Was able to reproduce the issue and get to the bottom of this.

Great, happy to help!

> As a side node, I noticed that the `createSignal` function immediately unwraps the signal which removes all the benefits of going with singals in the first place. I think it should look like this instead:
> 
> 
> 
> ```tsx
> 
> export function createSignal<T>(initialValue: T): [Signal<T>, (newValue: T) => T] {
> 
>   const signal = useSignal(initialValue);
> 
>   return [signal, (newValue: T) => signal.value = newValue];
> 
> }
> 
> ```

Ah good to know, thanks for that 👍
