### ISSUE TITLE
twind docs out of date

### ISSUE THREAD

**Issue by crowlsyong** [denoland/fresh#1812]
I'm working on an app and i want to add a custom font and upgrade to twindv1. I looked in your docs and the more I read your docs to work with my project, the more I find mismatches. Example:

**I boot up a fresh project with twind and look at the `main.ts` file**
```
/// <reference no-default-lib="true" />
/// <reference lib="dom" />
/// <reference lib="dom.iterable" />
/// <reference lib="dom.asynciterable" />
/// <reference lib="deno.ns" />

import "$std/dotenv/load.ts";

import { start } from "$fresh/server.ts";
import manifest from "./fresh.gen.ts";
import config from "./fresh.config.ts";

await start(manifest, config);
```
**But [your docs](https://fresh.deno.dev/docs/examples/using-twind-v1) say:** (notice the `import twind` code)

> When you initialize a project with deno run -A -r https://fresh.deno.dev, you’ll end up with a main.ts like the following:
> 
> main.ts
> ```
> /// <reference no-default-lib="true" />
> /// <reference lib="dom" />
> /// <reference lib="dom.iterable" />
> /// <reference lib="dom.asynciterable" />
> /// <reference lib="deno.ns" />
> 
> import { start } from "$fresh/server.ts";
> import manifest from "./fresh.gen.ts";
> 
> import twindPlugin from "$fresh/plugins/twind.ts";
> import twindConfig from "./twind.config.ts";
> 
> await start(manifest, { plugins: [twindPlugin(twindConfig)] });
> ```
> 

**These are mismatched. The docs are incorrect here.**
So I looked around other files to see if I could find what seemed like the right place to put the twind config code, and I found out that fresh.config.ts seems to fit the right look, given that I see twind imports. 
```
import { defineConfig } from "$fresh/server.ts";
import twindPlugin from "$fresh/plugins/twind.ts"
import twindConfig from "./twind.config.ts";
export default defineConfig({
  plugins: [twindPlugin(twindConfig)]
});
```
So, do I make my changes here? Is there anywhere else that I have to change twind to twindv1 without breaking stuff? 

Also custom css/adding my own custom woff2 file font type is pretty weird. I've been bouncing between twind docs and fresh docs to try and figure it out. I found [this guy who made custom styles work](https://dev.to/guiguerreiro39/ive-made-a-blog-using-the-fresh-framework-1198) (ctrl + F 'stylesheet') or [view his source code here](https://github.com/Guiguerreiro39/fresh-blog), but it's super weird and I don't really understand what is going on here nor do I want to (I just want to add a custom font, not hack css). 

**I'm a noob dev**, only a few years of basic web design under my belt. I'm just starting to work on making my own apps and I want Fresh/Deno/Deno KV to be at the center of it all. Deploying with your services is a godsend....but I didn't think I was so inept that I couldn't figure out how to use a custom font. I've spent about an hour researching how to add a font into Fresh Framework, looking at Fresh docs, twind docs, Deno docs....I can't figure it out. I am requesting that someone look over the docs, go through them, step by step, like a new developer would, and find the mismatches and update them to match the default code that comes with a new fresh project, and to try to do basic web dev stuff like try adding a custom font from a woff2 file. 

Thanks for any help you can give. Cheers

**Comment by crowlsyong** [comment]
Another docs issue: docs show incorrect code

> 
> [Modifying the head
> ](https://fresh.deno.dev/docs/examples/modifying-the-head) in routes/index.tsx
> 
> ```
> import { Head } from "$fresh/runtime.ts";
> 
> export default function Home() {
>   return (
>     <>
>       <Head>
>         <meta charset="UTF-8" />
>         <title>Fresh App</title>
>         <meta
>           name="description"
>           content="This is a brief description of Fresh"
>         />
>         <link rel="stylesheet" href="styles.css" />
>         <script src="script.js"></script>
>       </Head>
>       <div class="p-4 mx-auto max-w-screen-md">
>         <h1>Hello World</h1>
>       </div>
>     </>
>   );
> }
> ```
> 

I get a squiggly under `charset` and VS Code tells me to change it to `charSet` and then it works.

**Comment by marvinhagemeister** [comment]
Thanks for opening an issue about this. I share your frustration about all things twind, which is why we want to move away from it. Their docs are super confusing to me (they have 2 different sites), autocompletion never works and it's unmaintained above all. That there are two different twinds (v0 + v1) doesn't help either. I'm sorry that you got caught in the transition phase of all that.

To add custom fonts, put the font files in the `static/` folder and add a [`font-face`](https://developer.mozilla.org/en-US/docs/Web/CSS/@font-face) declaration in your CSS. I guess we haven't documented that because there is barely anything Fresh specific about this, so I can certainly see why entering these keywords didn't show a result in our docs. We should add something for that on our [static files](https://fresh.deno.dev/docs/concepts/static-files) page.

The `charSet` vs `charset` is a typing issue. Both work internally in Preact but looks like we forgot to add the lowercase variant to its JSX types. Will fix that.

**Comment by crowlsyong** [comment]
Wow that was fast! Majorly cool!!! Honestly that is legendary speed, dude. 
I will attempt the changes soon, report back, and close the issue if everything works.

**Comment by crowlsyong** [comment]
Still playing around with custom css. Would I have to refactor my project (remove twind entirely) in order to get vanilla css to work? 

Also, when I `deno run -A -r https://fresh.deno.dev`, after I enter my project name, I get the following: 
```
 🍋 Fresh: The next-gen web framework. 

Project Name [fresh-project] hello-github
Let's set up your new Fresh project.

Fresh has built in support for styling using Tailwind CSS. Do you want to use this? [y/N] 
```
When I type 'y' `enter`, twind is installed, not Tailwind. I wonder if maybe I could use the real Tailwind with Fresh. If it is possible/easy to configure, would I have to enter `N` `enter` to avoid installing twind, then follow[ this guide ](https://medium.com/frontendweb/how-to-use-tailwindcss-with-deno-and-fresh-framework-f1b8f48d7c87)to install Tailwind?

**Comment by marvinhagemeister** [comment]
> Still playing around with custom css. Would I have to refactor my project (remove twind entirely) in order to get vanilla css to work?

No, nothing needs to be refactored to make CSS work. CSS always work, regardless of whether you use twind or something else on top. In fact in the end all the CSS solutions like twind, tailwind or whatever generate a plain CSS file in the end under the hood.

Yes, it's possible to use tailwindcss directly see https://dev.to/iasqiti/replacing-twind-with-tailwind-in-fresh-1j4d . The reason Fresh picks twind by default is because of the just in time bundling, which doesn't work well with tailwindcss. I really would like to get rid of the JIT mode as it makes a lot of things pretty complex and it's not good for performance either, but there are some vocal users who are strongly opposed to this.

**Comment by crowlsyong** [comment]
I spun up a new project with no tailwind, I was able to get a custom font to work with a new styles folder inside of static.
I returned to my other project _with_ tailwind/twind installed. I copy/pasted that same styles folder into my project, then I updated `_app.tsx` with `<link rel="stylesheet" href="./styles/styles.css" />`
so now it looks like
```
import { AppProps } from "$fresh/server.ts";

export default function App({ Component }: AppProps) {
  return (
    <html>
      <head>
        <meta charSet="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Oh yeah!</title>
        <link rel="stylesheet" href="./styles/styles.css" /> 
      </head>
      <body>
        <Component />
      </body>
    </html>
  );
}
```
Then, I ran `deno task start` and there was no change to my fonts— twind is still taking precedent.
I changed fresh.config.ts from 
```
import { defineConfig } from "$fresh/server.ts";
import twindPlugin from "$fresh/plugins/twind.ts";
import twindConfig from "./twind.config.ts";
export default defineConfig({
  plugins: [twindPlugin(twindConfig)]
});
```
to
```
import { defineConfig } from "$fresh/server.ts";

export default defineConfig({});
```
and now my custom fonts work, but I lose my twind styles config. 

**Question 1:** How do I configure it such that twind handles all styling unless I specify otherwise via my styles.css?

**Question 2:** Going forward, it sounds like twind/tailwind being part of the default setup for Fresh is going to be removed, am I correct in making that statement?
**Question 2.1:**  If this the case, what would you recommend that I avoid starting new fresh projects with twind? 
**Question 2.2:**  Is there a different styling 'stack' that you would deem wise to use with most basic fresh apps?

**Comment by marvinhagemeister** [comment]
What does your CSS look like?

**Comment by crowlsyong** [comment]
```
└── static
    ├── styles
    │   ├── styles.css
    │   ├── fonts
    │   │   └── Satoshi-Black.woff2
    │   │   └── Satoshi-other-variations-of-this-font.woff2   # just for show
    │   │   └── satoshi.css
    └── otherstuff.png
    └── otherstuff.ico
```

`static/styles/styles.css`
```
@import url('./fonts/satoshi.css');

*,
*::before,
*::after {
  box-sizing: border-box;
}
* {
  margin: 0;
}
button {
  color: inherit;
}
button, [role="button"] {
  cursor: pointer;
}
code {
  font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas,
    "Liberation Mono", "Courier New", monospace;
  font-size: 1em;
}
img,
svg {
  display: block;
}
img,
video {
  max-width: 100%;
  height: auto;
}

html {
  line-height: 1.5;
  -webkit-text-size-adjust: 100%;
  font-family: 'Satoshi-Variable', ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont,
    "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif,
    "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
}
.transition-colors {
  transition-property: background-color, border-color, color, fill, stroke;
  transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1);
  transition-duration: 150ms;
}
.my-6 {
  margin-bottom: 1.5rem;
  margin-top: 1.5rem;
}
.text-4xl {
  font-size: 2.25rem;
  line-height: 2.5rem;
}
.mx-2 {
  margin-left: 0.5rem;
  margin-right: 0.5rem;
}
.my-4 {
  margin-bottom: 1rem;
  margin-top: 1rem;
}
.mx-auto {
  margin-left: auto;
  margin-right: auto;
}
.px-4 {
  padding-left: 1rem;
  padding-right: 1rem;
}
.py-8 {
  padding-bottom: 2rem;
  padding-top: 2rem;
}
.bg-\[\#86efac\] {
  background-color: #86efac;
}
.text-3xl {
  font-size: 1.875rem;
  line-height: 2.25rem;
}
.py-6 {
  padding-bottom: 1.5rem;
  padding-top: 1.5rem;
}
.px-2 {
  padding-left: 0.5rem;
  padding-right: 0.5rem;
}
.py-1 {
  padding-bottom: 0.25rem;
  padding-top: 0.25rem;
}
.border-gray-500 {
  border-color: #6b7280;
}
.bg-white {
  background-color: #fff;
}
.flex {
  display: flex;
}
.gap-8 {
  grid-gap: 2rem;
  gap: 2rem;
}
.font-bold {
  font-weight: 700;
}
.max-w-screen-md {
  max-width: 768px;
}
.flex-col {
  flex-direction: column;
}
.items-center {
  align-items: center;
}
.justify-center {
  justify-content: center;
}
.border-2 {
  border-width: 2px;
}
.rounded {
  border-radius: 0.25rem;
}
.hover:bg-gray-200:hover {
  background-color: #e5e7eb;
}
```

**Comment by crowlsyong** [comment]
└── static
    ├── styles
    │   ├── styles.css  # only applies to about.tsx and career.tsx
    │   ├── fonts
    │   │   └── Satoshi-Black.woff2
    │   │   └── Satoshi-other-variations-of-this-font.woff2   # just for show
    │   │   └── satoshi.css
    └── otherstuff.png
    └── otherstuff.ico

**Comment by crowlsyong** [comment]
I'm such a silly goof! I didn't have any headings, body, or paragraph in my css! 😆
To `styles.css`, I added 
```
h1, h2, h3, h4, h5, h6 {
  font-family: 'Satoshi-Variable', ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont,
    "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif,
    "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
}
```
and it worked. Yay!!!
Thank you for your help and patience with my noobishness.

**Comment by crowlsyong** [comment]
however, adding this to my css does not seem to work:
```
body {
  font-family: 'Satoshi-Variable', ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont,
    "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif,
    "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji";
}
```
[Here is my project](https://github.com/crowlsyong/competition-app-playground) if you want to tinker around. Please don't judge me and my garage code, I'm learning!!!

**Comment by marvinhagemeister** [comment]
Thanks for sharing more information. I don't have access to view that GitHub repository. My assumption is that twind inserts its own CSS reset which overwrites `font-family` on `body`. Adding an `!important` is a quick check to verify that.

**Comment by crowlsyong** [comment]
[It's public now](https://github.com/crowlsyong/competition-app-playground) **plz don't judge my garbage code 😆**
`!important` worked as an override. 
[twind docs](https://twind.dev/handbook/configuration.html#theme) say I could do something like this:
```
import { setup } from 'twind'

setup({
  theme: {
    extend: {
      fontFamily: {
        sans: 'Roboto, sans-serif',
        'proxima-nova': '"Proxima Nova"',
      },
    },
  },
  preflight: {
    // Import external stylesheet
    '@import': `url('https://fonts.googleapis.com/css2?family=Roboto:ital,wght@0,400;0,700;1,400&display=swap')`,
    // Declare font face
    '@font-face': [
      {
        fontFamily: 'Proxima Nova',
        fontWeight: '400',
        src: 'url(/fonts/proxima-nova/400-regular.woff) format("woff")',
      },
      {
        fontFamily: 'Proxima Nova',
        fontWeight: '500',
        src: 'url(/fonts/proxima-nova/500-medium.woff) format("woff")',
      },
    ],
  },
})
```
But in its current state (without making any changes), the above code doesn't work when I add it to `_app.tsx`

Also just for the record, I'm not messing with twindv1 right now. I'm just sticking with the regular twind that comes with fresh.

**Comment by crowlsyong** [comment]
Since you confirmed that you aware of and will fix the docs mismatch and VS code squiggly line for charset, I will close this issue. 
Thanks again for your speedy and accurate replies, you legend. 🙏

**Comment by salvaft** [comment]
Documents still missmatch. I came across that glitch and found this topic about it. Dunno if the issue should be closed...
