### ISSUE TITLE
Deno caching to support Fresh

### ISSUE THREAD

**Issue by mgenereu** [denoland/fresh#1813]
Please review denoland/deno#20354.

I created the issue in Deno but it originated in using Fresh.  I would like to get traction from the Fresh users through this issue and point them to the Deno issue.

Deno caching depends on the entry point TypeScript file importing all other TypeScript files in the project.  Fresh doesn't have this import relationship and rather imports by convention.  Therefore, caching doesn't catch all the imports of the project.

**Comment by marvinhagemeister** [comment]
Let's keep the discussion in https://github.com/denoland/deno/issues/20354 as it's about how deno's `cache` command works. Nothing we can do in Fresh to change that as changes need to happen in Deno itself.

**Comment by mgenereu** [comment]
Is there any way in the Deno issue to mark it as important to Fresh when it might be unimportant to Deno in general?

**Comment by marvinhagemeister** [comment]
Good idea. I've added a new "important for fresh" label to the issue in the deno cli tracker.
