### ISSUE TITLE
dev - FreshOptions interface doesnt contain a port 1.4.3

### ISSUE THREAD

**Issue by SimonKraushaar** [denoland/fresh#1815]
Seems dev.ts no longer calls main.ts, therefore signiture should be changed

dev.ts

` await dev(import.meta.url,"", { port:3000,plugins: [twindPlugin(twindConfig)] });`

 "Argument of type '{ port: number; plugins: Plugin<Record<string, unknown>>[]; }' is not assignable to parameter of type 'FreshOptions'.\n  Object literal may only specify known properties, and 'port' does not exist in type 'FreshOptions'.",

Interface FreshOptions doesn't include port so while its functional it throws an error in the lint.

**Comment by SimonKraushaar** [comment]
`export async function dev(
  base: string,
  entrypoint: string,
  options: FreshOptions = {},
)`
Shouldn't this just take the StartOptions interface instead?

**Comment by bastilian** [comment]
@SimonKraushaar I tried investigating this, but I'm unable to reproduce this.

What version of Deno are you running? (I'm on deno 1.37.1)

I believe that in older Deno versions where `ServeTlsOptions` is not available it might cause this issue.
