### ISSUE TITLE
[Bug] Hash value is not present in URL object of PageProps and POST requests

### ISSUE THREAD

**Issue by cknight** [denoland/fresh#1817]
I cannot seem to access the hash value of the URL server side in my Fresh application, which I'm assuming I should.

Example code:
```ts
export const handler: Handlers = {
  async POST(req, ctx) {
    console.log("POST", req)
  }
}
```
when submitting a POST request to `http://localhost:8000/#delete` I get the following in the console:
```
POST Request {
  bodyUsed: false,
  headers: Headers {
  accept: "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8",
  "accept-encoding": "gzip, deflate, br",
  "accept-language": "en-GB,en;q=0.5",
  "cache-control": "no-cache",
  connection: "keep-alive",
  "content-length": "40",
  "content-type": "application/x-www-form-urlencoded",
  host: "localhost:8000",
  origin: "http://localhost:8000",
  pragma: "no-cache",
  referer: "http://localhost:8000/",
  "sec-fetch-dest": "document",
  "sec-fetch-mode": "navigate",
  "sec-fetch-site": "same-origin",
  "sec-fetch-user": "?1",
  "upgrade-insecure-requests": "1",
  "user-agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:106.0) Gecko/20100101 Firefox/106.0"
},
  method: "POST",
  redirect: undefined,
  url: "http://localhost:8000/"
}
```
and if I access via an implicit GET to load index.html, `pageProps` shows the following:
```ts
export default function Home(data: PageProps<SearchData>) {
  console.log(data);
  return (<></>);
}
```
```
{
  url: URL {
    href: "http://localhost:8000/",
    origin: "http://localhost:8000",
    protocol: "http:",
    username: "",
    password: "",
    host: "localhost:8000",
    hostname: "localhost",
    port: "8000",
    pathname: "/",
    hash: "",
    search: ""
  },
  route: "/",
  data: undefined,
  state: {},
  params: {}
}
```
As you can see the hash value `#delete` is missing in both cases.

**Comment by marvinhagemeister** [comment]
The hash is client-side only and not sent to the server by clients. It's intended to refer to a fragment identifier in the current document. That's the way the internet works and URLs have been specified. If you open the "Network" tab in your browser's DevTools panel, you'll see that the hash value will never be sent to the browser. Same is true for `curl` or anything else that works with URLs for that matter.

There is a good explanation paragraph on that in the wikipedia article about URIs:

> The fragment identifier functions differently than the rest of the URI: namely, its processing is exclusively client-side with no participation from the server — of course the server typically helps to determine the MIME type, and the MIME type determines the processing of fragments. When an agent (such as a Web browser) requests a resource from a Web server, the agent sends the URI to the server, but does not send the fragment. Instead, the agent waits for the server to send the resource, and then the agent processes the resource according to the document type and fragment value.[2]

Source: http://en.wikipedia.org/wiki/Fragment_identifier

Here is the relevant section in [RFC 3986](https://datatracker.ietf.org/doc/html/rfc3986#section-3.5)

**Comment by cknight** [comment]
Thanks for the prompt reply.  I'll rework my solution based on URL params.
