### ISSUE TITLE
the same update warning after update to Fresh 1.4.3

### ISSUE THREAD

**Issue by danilovmy** [denoland/fresh#1832]
i see the Warning:

```
Fresh 1.4.3 is available. You're on 1.4.2                                                                                                                                                      
To upgrade, run: deno run -A -r https://fresh.deno.dev/update .              

```
I run upgrade.
After upgrade und deno task start, i see this warning again.

to check - this is test repository: https://github.com/danilovmy/freshframework

**Comment by marvinhagemeister** [comment]
I recall that this was a bug in our update code in the sometime > 1.5. I'm closing this for now, but happy to reopen if it pops up again.
