### ISSUE TITLE
tanstack table throws error

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/fresh#1857]
Report on discord https://discord.com/channels/684898665143206084/991511118524715139/1159153386965438566

**Comment by adamgreg** [comment]
Thanks. I don't have a public repo to share, but I'm trying to put together a minimal reproduction right now.

**Comment by adamgreg** [comment]
No luck with the reproduction (things never break when you want them to!). I'll try to provide more info when I can

**Comment by adamgreg** [comment]
Sorry, false alarm! There was a non-island usage that I forgot about (I was just for convenience in the initial render).

**Comment by marvinhagemeister** [comment]
No worries, could've been a real issue. Thanks for taking the time to look into it 👍
