### ISSUE TITLE
Unknown issue with npm specifier

### ISSUE THREAD

**Issue by Sleepful** [denoland/fresh#1882]
Currently I can run a version of fresh, but what if I want to run the latest commit?
I want to run these changes but I don't want to wait for a version release:
https://github.com/denoland/fresh/pull/1841

**Comment by Sleepful** [comment]
Alright I tried doing this:

`deno.json`
```json
    "$fresh/": "https://raw.githubusercontent.com/denoland/fresh/main/",
```
but `npm` specifier still broken inside `islands` directory.

**Comment by marvinhagemeister** [comment]
@Sleepful Just checked and npm specifiers work without issues for me. What does "is still broken" mean in your comment? Is there a specific module that you are trying to use that isn't working? Can you share the code that triggers the error?

**Comment by Sleepful** [comment]
Oh, thanks for the prompt response. I will share more info when I'm back at the kbd!

**Comment by Bloxs** [comment]
I'm having the same issue with npm specifiers in islands specifically on deploy. 
[Logs](https://paste.gg/p/anonymous/e5b4fec1ca7549e5a0bf5b5b560dcaf6)  
[Island causing the errors](https://github.com/Wave-Studio/Events/blob/master/islands/events/scanning.tsx) 
 [Deno config](https://github.com/Wave-Studio/Events/blob/master/deno.jsonc) in which `nodeModulesDir` is set to true
 Has been tested on 1.4.3, 1.5, and 1.5.1 and still occurs

**Comment by Sleepful** [comment]
@marvinhagemeister 

 
```ts
import {
  initializePaddle,
  Paddle,
  PaddleEventData,
} from "npm:@paddle/paddle-js@0.3.1";
```

<details>

<summary>
Logs

</summary>

```
Done in 236ms.
✘ [ERROR] Could not resolve "@paddle/paddle-js" [plugin deno-loader]

    islands/checkout.tsx:5:7:
      5 │ } from "npm:@paddle/paddle-js@0.3.1";
        ╵        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

  You can mark the path "@paddle/paddle-js" as external to exclude it from the bundle, which
  will remove this error and leave the unresolved path in the bundle.

An error occurred during route handling or page rendering.
An error occurred during route handling or page rendering.
Error: Build failed with 1 error:
islands/checkout.tsx:5:7: ERROR: [plugin: deno-loader] Could not resolve "@paddle/paddle-js"
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.19.4/mod.js:1626:15)
    at https://deno.land/x/esbuild@v0.19.4/mod.js:1035:25
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.19.4/mod.js:1461:45)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.19.4/mod.js:1033:7)
    at https://deno.land/x/esbuild@v0.19.4/mod.js:1062:16
    at responseCallbacks.<computed> (https://deno.land/x/esbuild@v0.19.4/mod.js:679:9)
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.19.4/mod.js:739:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.19.4/mod.js:655:7)
    at https://deno.land/x/esbuild@v0.19.4/mod.js:1924:11
    at eventLoopTick (ext:core/01_core.js:183:11) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}
Error: Build failed with 1 error:
islands/checkout.tsx:5:7: ERROR: [plugin: deno-loader] Could not resolve "@paddle/paddle-js"
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.19.4/mod.js:1626:15)
    at https://deno.land/x/esbuild@v0.19.4/mod.js:1035:25
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.19.4/mod.js:1461:45)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.19.4/mod.js:1033:7)
    at https://deno.land/x/esbuild@v0.19.4/mod.js:1062:16
    at responseCallbacks.<computed> (https://deno.land/x/esbuild@v0.19.4/mod.js:679:9)
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.19.4/mod.js:739:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.19.4/mod.js:655:7)
    at https://deno.land/x/esbuild@v0.19.4/mod.js:1924:11
    at eventLoopTick (ext:core/01_core.js:183:11) {
  errors: [Getter/Setter],
  warnings: [Getter/Setter]
}
```
</details>

**Comment by Sleepful** [comment]
this works fine though:
```ts
// inside /islands dir
import {
  initializePaddle,
  Paddle,
  PaddleEventData,
} from "https://esm.sh/@paddle/paddle-js@0.3.1";
```

**Comment by marvinhagemeister** [comment]
@Sleepful Just tried the `npm:@paddle/paddle-js@0.3.1` import in an island in an new Fresh 1.5.2 project and I get no error.

**Comment by eternaleye** [comment]
A co-worker just tried to spin up a new Fresh project using the command in the docs, and (out of curiosity) I asked him to change the imports in `deno.json` from `esm.sh` to `npm:`. `deno task start` ran fine, but _on loading the page_ we got errors on the server terminal about being unable to move temporaries into place because directories in `~/.cache/deno/deno_esbuild` already existed.

**Comment by Sleepful** [comment]
Hm, I don't think I can provide more information about the issue right now. It seems that we are at a “works on my machine” cross-roads.

**Comment by marvinhagemeister** [comment]
Closing as we don't have sufficient information to help guide/debug this issue further.
