### ISSUE TITLE
Native navigation back not trigger GET handler

### ISSUE THREAD

**Issue by ewiggin** [denoland/fresh#1885]
Hello,
I'm developing a website with Fresh and I'm facing the following issue: I have a list of users and user form. In the form, I use a island component to update the user's skills.

The problem occurs when, after updating the user through the island, I return to the list using the browser's back button. It doesn't retrigger the GET handler of the page, and as a result, I don't see the updated data.

Is there a way to force it to always make the GET request even when navigation is handled by the browser? This is especially useful if we turn this web into a mobile application (add to home screen) and use gestures to navigate between screens.

`Fresh@1.4.3`

**Comment by marvinhagemeister** [comment]
That's the default browser behavior as it caches pages to speed up navigation. There are some more or less hacky ways to force reload a page but I wouldn't recommend them. In the next Fresh release we'll ship a feature called "Partials" which will solve this in a much more elegant way. Current target release date is Monday.

**Comment by ewiggin** [comment]
I saw the release notes, I'm exciting about this feature on `Fresh@1.5` 

Thanks!
