### ISSUE TITLE
in snapshot.json, file names are missing the first character

### ISSUE THREAD

**Issue by MoaathAlattas** [denoland/fresh#1887]
Hi 👋  

I am deploying deno/fresh apps to Google Cloud Run and using a docker file. I have multiple apps in the same repo and they are working as expected until there is an island on the page.

When I access a page that has an island, all client side js files return `404` as they don't exist:
<img width="800" alt="image" src="https://github.com/denoland/fresh/assets/18528024/b2132e92-523b-4924-8440-70a5fe6f61d5">

After hours of debugging I noticed the `snapshot.json` that's generated after the build step is different than the one generated locally and file names are missing the first character:
<img width="420" alt="image" src="https://github.com/denoland/fresh/assets/18528024/e2b9de2a-deb7-4be5-8362-9976c58fec1a">

If your are wondering, those files do exist on cloud run and accessible when removing the first character:
<img width="594" alt="image" src="https://github.com/denoland/fresh/assets/18528024/46df8dfe-ec09-4cab-a33b-fc8623ac25f7">

### Notes
- ~I couldn't produce the same issue locally.~ I could reproduce the same issue only when using docker. If I run the app directly using `deno task`, everything works as expected.
- I tried the last fresh version `1.4.3` as well as the last commit on the main branch as of today.
- I tried to change Deno image in the docker file (ubuntu, alpine ...etc)
- I tried removing the build step (assets would still be accessible if I remove the first character from the file name)
- I tried to manually set a value for `DENO_DEPLOYMENT_ID` or `GITHUB_SHA` on the docker file (no difference)

### docker file
```Dockerfile
FROM denoland/deno:alpine-1.37.1
USER deno

COPY . .
RUN deno task build:xyz
RUN deno cache --unstable ./apps/xyz/main.ts

EXPOSE 8055
ENTRYPOINT ["deno","task", "prod:xyz"]
```

### snapshot file when i build locally
<img width="552" alt="image" src="https://github.com/denoland/fresh/assets/18528024/a3861de1-b289-4505-a06c-006d898e42a5">

### commands
```
"build:xyz": "deno run --unstable -A ./apps/xyz/dev.ts build",
"prod:xyz": "deno run --unstable -A  ./apps/xyz/main.ts",
```

**Comment by marvinhagemeister** [comment]
Which OS do you use? Are you on Windows?

**Comment by MoaathAlattas** [comment]
> Which OS do you use? Are you on Windows?

locally MacOS 14.0

**Comment by marvinhagemeister** [comment]
Ah wait, the OS question was pointless, because you're using the Dockerfile to run Fresh anyway. Apologies. Not sure yet what's going on.

**Comment by MoaathAlattas** [comment]
I was just able to reproduce locally by building the docker file and running it locally. So there is something unexpected in the build step when using the Dockerfile mentioned above.

**Comment by MoaathAlattas** [comment]
I found the root cause 👍 The build command doesn't expect that you are running it on the root directory of the system. Meaning that in docker I am copying files to `/` then running the build command.

```ts
// src/build/esbuild.ts:

const absWorkingDir = Deno.cwd();
...
...
const absWorkingDirLen = toFileUrl(absWorkingDir).href.length + 1;

for (const file of bundle.outputFiles) {
  const path = toFileUrl(file.path).href.slice(absWorkingDirLen);
  files.set(path, file.contents);
}
```

The value of `absWorkingDir` in my docker file would be `/` 😅  Copying files inside a folder in docker would solve this, `COPY . /my-great-app`. I am not sure if this is a bug or just an edge case.

**Comment by marvinhagemeister** [comment]
Nice find! We should definitely handle this case when the cwd is the root path. To me that's a bug in Fresh.
