### ISSUE TITLE
October - November 2023 iteration plan

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/fresh#1891]
A new Fresh version is cut on a monthly basis around the middle of the month and this post intends to capture the main tasks we want to focus on. A monthly plan matches the release cycle and allows for more flexibility by making it easier to account for shifts in priorities.

## Plan items

The current plan of main features planned for this cycle:

- [ ] View Transitions https://github.com/denoland/fresh/pull/1532
- [x] Replace twind with https://github.com/denoland/fresh/pull/1303
- [x] Rendering performance improvements (todo)
- [x] Improve plugin API (todo)

Note that this list is not set in stone.

**Comment by PoignardAzur** [comment]
> Rendering performance improvements (todo)

I'd like to draw attention again to #1042 (Consider adding support for "caching partials") based on Google's [Faster multipage applications with streams](https://developer.chrome.com/docs/workbox/faster-multipage-applications-with-streams/) article.

In that discussion you said

> Navigations typically render the currently active entry differently too.

Which is partially solved by the "active link styling" feature of the last update, so maybe you were already thinking of that.

**Comment by algoflows** [comment]
Storybook support and NX workspace plugin... Lots of framework features but near zero tooling support.

**Comment by marvinhagemeister** [comment]
@algoflows yup, we're painfully aware of that. Thing is that I don't want to reinvent the wheel and duplicate existing work. II haven't shared this yet, but one thing I'm exploring at the side is what Fresh would look like if we'd built it around vite among other things.

**Comment by guillaume86** [comment]
Is there a specific ticket for the plugin API improvements? 

I'm very new to deno/fresh and already very impressed, I would like to try to build a plugin that generates a typed API client from the declared routes/handlers. The islands would then be able to use this client to make fetch calls safely. I guess the hook could be somewhere close to the code that generates fresh.gen.ts.

**Comment by marvinhagemeister** [comment]
Closing in favour of https://github.com/denoland/fresh/issues/2108
