### ISSUE TITLE
More accessible active/ancestor links

### ISSUE THREAD

**Issue by oliverjam** [denoland/fresh#1907]
#1840 is super helpful! It would be nice if Fresh could set the [`aria-current`](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-current) attribute instead of (or as well as) using a custom data attribute. This would help expose this info to non-sighted users. I think you'd want `aria-current="page"` for `data-current`, and `aria-current="true"` for `data-ancestor`.

**Comment by marvinhagemeister** [comment]
Ohh this makes much more sense! I'm angry at myself for not thinking of that 😅
