### ISSUE TITLE
Islands not hydrating

### ISSUE THREAD

**Issue by kitsonk** [denoland/fresh#1921]
I am not sure how to narrow it down, but when upgrading to Fresh 1.5.0 or 1.5.1 one of my projects, the islands don't hydrate though I can see the client side JS being downloaded. Reverting back to 1.4.3 restores the capability.

Under 1.5.1 with a `deno task build` and then `deno task preview` (the same behaviour occurs with `deno task start`:

<img width="1389" alt="kview" src="https://github.com/denoland/fresh/assets/1282577/fc2759f1-27f5-4462-a6d0-23ac73bbf306">

Under 1.4.3, only change being the version of Fresh in the `deno.json`, you can see the interactive :

<img width="1386" alt="Cursor_and_kview" src="https://github.com/denoland/fresh/assets/1282577/c56ca663-1017-4dde-9c1c-423f3b308b44">

The code is here: https://github.com/kitsonk/kview (using 1.4.3) but the application currently needs to run on a local Deno instance and requires a valid Deploy API key to be able to navigate to the point of using the interactive island. I can try to create a minimal reproduction, but right now it is just easier for me to develop on 1.4.3.

**Comment by marvinhagemeister** [comment]
Thanks for the detailed reproduction. That allowed me to find the cause pretty quickly 👍

**Comment by kitsonk** [comment]
Ha, so it was all because my island was named `KeyExplorer`? 🤣

**Comment by marvinhagemeister** [comment]
yeah, it's an embarrassing bug if I'm honest 😬

**Comment by kitsonk** [comment]
> Some people, when confronted with a problem, think
> “I know, I'll use regular expressions.”
> Now they have two problems.

At least I stumbled upon it quickly, it being such a strange edge case which could have been hiding for years before stumbling across it. I will admit I delayed two days reporting it because I though "naw, I gotta be doing something wrong or someone else will come across it too and then I can just go 'me too' on the issue."

**Comment by marvinhagemeister** [comment]
Please always report any issues you find. I'd rather have more issue reports that turn out to be non-issues compared to not being aware of the issues at all.
