### ISSUE TITLE
Add support for disabling top-scroll for partials

### ISSUE THREAD

**Issue by csvn** [denoland/fresh#1923]
The new Partials feature looks really nice so far. Though, when I did a quick test with updating add-to-cart and the cart status via partials, the top-scroll feature was in the way. Scrolling to top is a great thing to do when the entire main content changes and it's a new "page". But if using partials to replace small areas on the page, it's not as great.

Or is it a use-case that is not intended for partials? In the demo below there are only two small partials, highlighted in red.

https://github.com/denoland/fresh/assets/8770194/fbb8cfbd-7556-4947-ba81-1fd65eaa618f

![image](https://github.com/denoland/fresh/assets/8770194/5292dda0-8ce8-4e31-950a-3af10ef27930)

It would be awesome if there was a `f-no-scroll` or similar directive to use. Or perhaps `f-client-nav='no-scroll'`. Some way to say "navigations here should not scroll". Still, it looks to me like Partials are really promising so far!

**Comment by marvinhagemeister** [comment]
This is a perfect use case for partials. Agree that we should have a way to disable the "scroll to top" feature.

**Comment by marvinhagemeister** [comment]
FWIW: As a workaround for now you could use a `<button>` instead of `<a>` for the "Add to Cart" button. The scroll logic only comes into play when clicking on a link.

**Comment by csvn** [comment]
Ohh, interesting. Thanks for the suggestion! I read through the partials documentation, but did not realize you can use other than links. I think this part, and the fact all examples use `<a>`, threw me off:

> When the `f-partial` attribute is present, Fresh will navigate to the page URL defined in the `href` attribute, but fetch the updated UI from the URL specified in `f-partial` instead. This can be a highly optimized route that only delivers the content you care about.
> https://fresh.deno.dev/docs/concepts/partials#optimizing-partial-requests

But I see now that I missed this part:

> Currently, `f-partial` is scoped to `<a>`, `<button>` and `<form>` elements. This might be extended to more elements in the future.

So I guess using on `<form>` will use the `f-partial` URL to post to instead of the configured `action` attribute of the form on submit? That seems really useful. A small form+button example could be nice.

**Comment by marvinhagemeister** [comment]
Forms are a bit unfinished yet, but plan is to make them work with partials too. Also good point on the documentation not mentioning button really

**Comment by marvinhagemeister** [comment]
Closing as form support landed with https://github.com/denoland/fresh/pull/1930
