### ISSUE TITLE
Partials feedback

### ISSUE THREAD

**Issue by cknight** [denoland/fresh#1928]
Just playing around with Partials and forms.  Some feedback:

In the [optimising partial requests](https://fresh.deno.dev/docs/concepts/partials#optimizing-partial-requests) documentation it shows:

![image](https://github.com/denoland/fresh/assets/1248238/50c4de7b-61a3-46a9-8f70-b3b466be9013)

From my experiments, I believe this file location should be `routes/partials/docs/[id].tsx`.

With regards to form usage I ran into several problems:
1. In order to support deep linking for forms and load a specific snapshot of my search, I rely on the `onSubmit` event to update the URL search parms with the values of all the form fields.  However, the `f-partial` form submission isn't triggering this event.
2. The partial fetch is a GET request, meaning no form data is sent.  I could in theory add all form values (for my form anyway) as search parameters onto the `f-partial` value but this needs to be done at submission and I'm not able to hook into this event (but really, I think the fetch needs to be a POST with all form data).

**Comment by adamgreg** [comment]
I'm also trying to use a POST form submission (with onSubmit handler) to fetch a partial, so I was happy to find this issue that explains the situation perfectly, thanks!

**Comment by salvaft** [comment]
> Just playing around with Partials and forms. Some feedback:
> 
> In the [optimising partial requests](https://fresh.deno.dev/docs/concepts/partials#optimizing-partial-requests) documentation it shows:
> 
> ![image](https://user-images.githubusercontent.com/1248238/274747455-50c4de7b-61a3-46a9-8f70-b3b466be9013.png)
> 
> From my experiments, I believe this file location should be `routes/partials/docs/[id].tsx`.
> 
> With regards to form usage I ran into several problems:
> 
> 1. In order to support deep linking for forms and load a specific snapshot of my search, I rely on the `onSubmit` event to update the URL search parms with the values of all the form fields.  However, the `f-partial` form submission isn't triggering this event.
> 2. The partial fetch is a GET request, meaning no form data is sent.  I could in theory add all form values (for my form anyway) as search parameters onto the `f-partial` value but this needs to be done at submission and I'm not able to hook into this event (but really, I think the fetch needs to be a POST with all form data).

I have the same use case as 1. `<a>` tags partial navigation is captured. Form `f-partial` submission navigation is not captured. The solution for progressive enhancement is exactly as you say 
```jsx
const query = useSignal("");
  // Handle input change
  function handleChange(e: Event) {
    query.value = (e.target as HTMLInputElement).value;
  }
function handleSubmit(e: Event) {
    const form = e.target as HTMLFormElement;
    form.setAttribute("f-partial", `/products?search=${query.value}`);
    // Push a new URL to the browser history
    history.pushState(null, "", document.location.href);
    // Replace the current URL in the browser history
    history.replaceState(null, "", "/products?search=" + query.value);
  }

```


Case number I think it is not possible to use partials.

You can implement the logic of a fetch request mode "POST" in the onSubmit handler.  Then you can progressively enhance and match default behaviour you should also replace the POST url.
But to re-render, you need a handler to a get request of the `f-partial` URL that will render what is wrapped into Partial tags. However this handler has no access to the body of the post you did above...

**Comment by marvinhagemeister** [comment]
@SFToro Full form support for partials is coming with https://github.com/denoland/fresh/pull/1930 . I didn't manage to get it ready in time for Fresh 1.5 . It will ship with the next release.
