### ISSUE TITLE
router: URL-route matching is expensive

### ISSUE THREAD

**Issue by lucab** [denoland/fresh#1931]
After profiling a Fresh application in production, we found out that the current URL/route matching through `URLPattern` is expensive both in consumed CPU time and memory usage:
https://github.com/denoland/fresh/blob/d391924885f37992fc116e9ad0df564c693c90da/src/server/router.ts#L146-L152

At the time of this writing our app has ~800 static-files routes, and a total of ~900 routes overall. Each one of those translates to a dedicated `URLPattern` instance.
On each request, `URLPattern.exec(url)` is called in a loop until a matching route is found (if any).
Unfortunately at the moment the `URLPattern` implementation in Deno is known to have some performance issues: https://github.com/denoland/deno/issues/19861.

Under sustained organic traffic, it looks like this quickly becomes an hot tight-loop, consuming most of the CPU active time.
From the same profile, it looks like this is also causing a lot of pressure on V8 memory handler.

**Comment by lucab** [comment]
For future reference, this would likely benefit from the proposed `URLPatternList`: https://github.com/denoland/deno/issues/20899

**Comment by marvinhagemeister** [comment]
Yup, I've discovered this yesterday too while inspecting a site with many static files. I'm already working on a fix.
