### ISSUE TITLE
Add a way to identify if the current request is a Fresh Partial in routes/middleware

### ISSUE THREAD

**Issue by csvn** [denoland/fresh#1935]
I was thinking of doing a PR for this, but realized it's probable best to check interest first. Similar to the reasoning for having `ctx.destination` in middleware, it would be nice for middleware/handlers/async routes to check if the current request is a partial. It's currently possible to do this by checking the URL `?fresh-partial=true`, but this feels a bit brittle (`PARTIAL_SEARCH_PARAM` is not exported).

My use case is having a form both be usable with the regular action, and when updating via partials. For instance, if a `<form>` posts to `/foo` and we want to return partials:

- One way would be to always render partials on the `/foo` endpoint, but this becomes weird if users disable their JS, where we get a strange result back (partial content)
- Another way is to create both a `/routes/foo` and `/routes/partials/foo` and set `action="/foo" f-partial="/partials/foo"` on the form. but it's annoying to have to duplicate the handling of the form in both places
- The way I intended to do it is to only have one the `/foo` route, but check if it's a partial (via query param currently). We first handle the form, then if it's a partial we return partial content, if not we redirect to a suitable place after the form

To make the last point easier it would be great if there was something built in to do something like the below:

```tsx
export const handler: Handlers<unknown, unknown> = {
  GET(req, ctx) {
    const fd = await req.formData();
    // Handle the form

    if (ctx.isPartial) return ctx.render();

    return new Response(undefined, {
      status: 303,
      headers: { location: '/' },
    });
  },
};
```

Another possible solution would be to export a helper function for checking this:
```tsx
import { isPartial } from '$fresh/server.ts';

    if (isPartial(req)) return ctx.render();
    // or
    if (isPartial(ctx)) return ctx.render();
```

**Comment by marvinhagemeister** [comment]
Good idea, thanks for opening an issue for this. We should definitely have a way to detect this built in.
