### ISSUE TITLE
Serve assets generated on build

### ISSUE THREAD

**Issue by jasonjgardner** [denoland/fresh#1938]
Static assets created during `buildStart` are not available during dev. Fresh could use some kind of _generated_, static directory from which content can be served.

Per this Discord conversation: https://discord.com/channels/684898665143206084/991511118524715139/1162453890248224799

**Comment by marvinhagemeister** [comment]
Resolved by https://github.com/denoland/fresh/pull/1999 . Will be part of the upcoming Fresh 1.6 release

**Comment by jasonjgardner** [comment]
This is great news for my Tailwind plugin.
