### ISSUE TITLE
How does one set up google tag for adwords

### ISSUE THREAD

**Issue by uriva** [denoland/fresh#1947]
Couldn't find examples or documentation about this

**Comment by marvinhagemeister** [comment]
To set up Google Tag Manager documentation

**Comment by marvinhagemeister** [comment]
To set up Google Tag Manager follow their documentation. At the end, copy their HTML snippet and insert it into `_app.tsx`.

**Comment by uriva** [comment]
But what if I want to track a conversion event, I need a reference to the function that reports the conversion and activate it from a button, then it's not enough to just insert their script is it?

**Comment by marvinhagemeister** [comment]
Google's documentation for Google Tag Manager will answer those questions. This question is not related to the Fresh project.

**Comment by uriva** [comment]
The question I mean to ask is how can I reference a function inside an island if it's defined in a script as text in `_app.tsx`?
