### ISSUE TITLE
Ability to not load esbuild at runtime

### ISSUE THREAD

**Issue by mfulton26** [denoland/fresh#1954]
With the new ahead of time builds, esbuild isn't needed at runtime but currently it is still loaded. Not loading would reduce loading times, memory usage, deploy times, etc. It could also enable bundling and running Fresh inside of web workers or service workers.

**Comment by selurvedu** [comment]
I was trying to find a way to disable it and this issue is all I found so far.

**Comment by mfulton26** [comment]
I went to work on this, but I think it might already be done by https://github.com/denoland/fresh/pull/1959.

**Comment by selurvedu** [comment]
Yes, before you replied, I switched to main and ran it with `FRESH_ESBUILD_LOADER=portable deno run --allow-env=FRESH_ESBUILD_LOADER,DENO_DEPLOYMENT_ID,__FRSH_LEGACY_DEV,PORT --allow-read=. --allow-net=0.0.0.0:8000,[fdaa::3]:53 main.ts`, and it works pretty well.

**Comment by marvinhagemeister** [comment]
Happy to hear that! I definitely want to get rid of esbuild outside of dev mode completely at some point. But not sure when.

**Comment by marvinhagemeister** [comment]
Closing, as esbuild is only loaded when needed in `main`.
