### ISSUE TITLE
"_500.tsx" Not Rendering in Dev Mode

### ISSUE THREAD

**Issue by gustavomaltez** [denoland/fresh#1978]
I had some trouble setting up a custom error page for my app. I found that the _500.tsx page only seems to show up when I run the app in preview mode. Is there a way I can make it appear in dev mode? In dev mode, the error message is quite descriptive, but I'm wondering if it's possible to show the custom _500.tsx page instead of the default dev error page.

I have a handler intentionally throwing an error:

```ts
export const handler: Handlers<Props> = {
  async GET(_req, ctx) {
    throw new Error('Some error inside the handler');
  }
};
```

When I run in dev mode using `deno run -A --watch=static/,routes/ dev.ts`, I see this screen:

![image](https://github.com/denoland/fresh/assets/57905553/2b1c562d-49ca-4d74-a2ac-0c2611951ba7)

When running in preview mode with `deno run -A main.ts`, this is the screen that appears (my _500.tsx component):

![image](https://github.com/denoland/fresh/assets/57905553/4414fcf3-c215-4d21-9807-49e951ceced3)

These are my dev.ts and main.ts files:

`dev.ts`
```ts
#!/usr/bin/env -S deno run -A --watch=static/,routes/

import dev from 'fresh/dev.ts';
import config from './fresh.config.ts';

import '$std/dotenv/load.ts';

await dev(import.meta.url, './main.ts', config);
```

`main.ts`
```ts
/// <reference no-default-lib='true' />
/// <reference lib='dom' />
/// <reference lib='dom.iterable' />
/// <reference lib='dom.asynciterable' />
/// <reference lib='deno.ns' />

import '$std/dotenv/load.ts';

import { start } from 'fresh/server.ts';
import manifest from './fresh.gen.ts';
import config from './fresh.config.ts';

await start(manifest, config);
```

Fresh version: 1.5.2
Deno version: 1.37.2

Thanks in advance :)

**Comment by deer** [comment]
[Here](https://github.com/denoland/fresh/blob/7ad4610e3a42aba42638cbc1041b96ee58a9b29e/src/server/fs_extract.ts#L215) we check if we're in dev mode and shove in the `DefaultErrorHandler` which has the code box you're seeing.

[This](https://github.com/denoland/fresh/blob/7ad4610e3a42aba42638cbc1041b96ee58a9b29e/src/server/mod.ts#L106) command gets invoked from your `main.ts`. So you can see dev being set to false and then we don't use the `DefaultErrorHandler`.

And finally in [dev mode](https://github.com/denoland/fresh/blob/7ad4610e3a42aba42638cbc1041b96ee58a9b29e/src/dev/dev_command.ts#L54) the flag is set to true.

Sadly I don't see any easy way to opt out of this behavior, although you'd have to wait for @marvinhagemeister to have a definitive answer.

**Comment by gustavomaltez** [comment]
Thanks for the clarification! That would be a nice feature to have if it's not too difficult to implement. In the meantime, it might be a good idea to update the Fresh documentation to inform developers that the custom 500 page won't appear in dev mode.

Something like:

-----
### 500: Internal Server Error

The 500 page can be customized by creating a `_500.tsx` file in the `routes/`
folder. The file must have a default export that is a regular Preact component.
A props object of type `ErrorPageProps` is passed in as an argument.

Please note that while in dev mode, the custom _500.tsx page won't be displayed. 
Instead, the default Fresh error page, containing error details, will be shown. You 
can view the custom _500.tsx page in preview mode and when the app is deployed.

```tsx routes/_500.tsx
import { ErrorPageProps } from "$fresh/server.ts";

export default function Error500Page({ error }: ErrorPageProps) {
  return <p>500 internal error: {(error as Error).message}</p>;
}
```
-----

Do you think this is valid? I'm looking forward to contributing to open-source projects. If the suggestion is valid, should I create a PR to update that part of the documentation?

**Comment by deer** [comment]
Yeah, I agree the "Error pages" page could be more clear about this. I'm sure a PR to improve this page would be appreciated.

**Comment by gustavomaltez** [comment]
Thank you, @deer ! I've just created PR #1983 to update the documentation. I'll dive into the Fresh codebase and attempt to implement some logic that allows developers to decide whether they want to view the 500 error page in dev mode or not.

**Comment by marvinhagemeister** [comment]
I'm not a fan of adding workarounds of bugs in the documentation. We should just fix the bug.

**Comment by deer** [comment]
What is the bug exactly? I thought the desired functionality was to show the error frame in dev mode.

**Comment by marvinhagemeister** [comment]
Yeah it's desired that we show the error frame, but we should load it in an `<iframe>` and add a close button like other frameworks do. That way you can still see the underlying 500 error page from the user.
