### ISSUE TITLE
how to make routes navigation in handle of onclick function?

### ISSUE THREAD

**Issue by j-Cis** [denoland/fresh#1980]
Is it possible to do something like this / similar? please advise. Thank you very much in advance.
```tsx
const handleClickChangePage = (event: MouseEvent) => {
  //?? router.navigateByUrl("/page-xyz");
};
```
I know this isn't the best place to ask questions, but I haven't found a clue for days by looking everywhere.

**Comment by marvinhagemeister** [comment]
The most common way to navigate between pages is via HTML's `<a>`-element. So to navigate to another page it could look like this:

```html
<a href="/path/to/page">Go to my page</a>
```

If using an `<a>`-element doesn't work in your scenario for whatever reason and you really need to trigger a navigation programmatically, then you can use the browser's `location` API.

```js
const onSomeEvent = () => {
  // Navigate to /path/to/page
  location.href = new URL("/path/to/page", location.origin).href
}
```
