### ISSUE TITLE
type error when exporting variables from an island

### ISSUE THREAD

**Issue by sigmaSd** [denoland/fresh#1985]
- deno run -A -r https://fresh.deno.dev
- cd fresh-project
- add `export const a = 4;` to islands/Counter.tsx
- deno check main.ts

```
Check file:///home/mrcool/dev/deno/lab/bug/fresh-project/main.ts
error: TS2345 [ERROR]: Argument of type '{ routes: { "./routes/_404.tsx": typeof $0; "./routes/_app.tsx": typeof $1; "./routes/api/joke.ts": typeof $2; "./routes/greet/[name].tsx": typeof $3; "./routes/index.tsx": typeof $4; }; islands: { "./islands/Counter.tsx": typeof $$0; }; baseUrl: string; }' is not assignable to parameter of type 'Manifest'.
  Types of property 'islands' are incompatible.
    Type '{ "./islands/Counter.tsx": typeof $$0; }' is not assignable to type 'Record<string, IslandModule>'.
      Property '"./islands/Counter.tsx"' is incompatible with index signature.
        Type 'typeof import("file:///home/mrcool/dev/deno/lab/bug/fresh-project/islands/Counter.tsx")' is not assignable to type 'IslandModule'.
          Property 'a' is incompatible with index signature.
            Type 'number' is not assignable to type 'ComponentType<any>'.
await start(manifest, config);
            ~~~~~~~~
    at file:///home/mrcool/dev/deno/lab/bug/fresh-project/main.ts:13:13
```

To improve the error message you can modify fresh.gen.ts like this
```diff
diff --git a/fresh.gen.ts b/fresh.gen.ts
index c86443f..d3c911c 100644
--- a/fresh.gen.ts
+++ b/fresh.gen.ts
@@ -8,6 +8,7 @@ import * as $2 from "./routes/api/joke.ts";
 import * as $3 from "./routes/greet/[name].tsx";
 import * as $4 from "./routes/index.tsx";
 import * as $$0 from "./islands/Counter.tsx";
+import { Manifest } from "$fresh/server.ts";
 
 const manifest = {
   routes: {
@@ -21,6 +22,6 @@ const manifest = {
     "./islands/Counter.tsx": $$0,
   },
   baseUrl: import.meta.url,
-};
+} satisfies Manifest;
 
 export default manifest;
```

Now it will point the error to `"./islands/Counter.tsx"`

**Comment by deer** [comment]
Hey @sigmaSd, thanks for logging this. I was wrong about the cause of the problem. It's not an issue with the primary runtime (i.e. when the server is responding to requests), but rather with how the manifest is generated. So I see two enhancements here to fix the problem:

1. Insert `satisfies Manifest` into the code generating the manifest. This is a trivial improvement which makes dealing with manifest issues way easier.
2. Investigate whether we can filter out invalid exports when generating the manifest.

**Comment by deer** [comment]
If we get the manifest file to generate something different, like this:
```diff
diff --git a/tests/fixture/fresh.gen.ts b/tests/fixture/fresh.gen.ts
index bdaa2a7..debf160 100644
--- a/tests/fixture/fresh.gen.ts
+++ b/tests/fixture/fresh.gen.ts
@@ -79,7 +79,7 @@ import * as $$0 from "./islands/Counter.tsx";
 import * as $$1 from "./islands/FormIsland.tsx";
 import * as $$2 from "./islands/Greeter.tsx";
 import * as $$3 from "./islands/HookIsland.tsx";
-import * as $$4 from "./islands/MultipleCounters.tsx";
+import CounterZero, { CounterOne, CounterTwo } from "./islands/MultipleCounters.tsx";
 import * as $$5 from "./islands/ReturningNull.tsx";
 import * as $$6 from "./islands/RootFragment.tsx";
 import * as $$7 from "./islands/RootFragmentWithConditionalFirst.tsx";
@@ -172,7 +172,7 @@ const manifest = {
     "./islands/FormIsland.tsx": $$1,
     "./islands/Greeter.tsx": $$2,
     "./islands/HookIsland.tsx": $$3,
-    "./islands/MultipleCounters.tsx": $$4,
+    "./islands/MultipleCounters.tsx": { default: CounterZero, CounterOne, CounterTwo },
```
then the problem goes away. (Assuming that `MultipleCounters.tsx` has some "invalid" exports.) But then we need to be worried about name conflicts across files, unless we start importing them using `as` (e.g. `import MultipleCounters_CounterZero, { CounterOne as MultipleCounters_CounterOne, CounterTwo as MultipleCounters_CounterTwo } from "./islands/MultipleCounters.tsx";
`).

I would hold off a refactoring like this until #1790 gets completed, since it's already changing the manifest files quite a bit. Also curious to see what @marvinhagemeister has to say about whether this is even something we want to support.

@sigmaSd, perhaps you could elaborate on your use case for wanting to export other things from your island files.

**Comment by sigmaSd** [comment]
For the use-case: I just happened to export stuff from the island because obviously that seemed a normal thing to do (like any normal tsx file), I can easily refactor this on a separate file.

So maybe if its supposed to work like this, just documenting this would be good, and adding a lint for this would be even better.
