### ISSUE TITLE
Favicon still requested after first request

### ISSUE THREAD

**Issue by ericlery** [denoland/fresh#2003]
I have noticed that the Response Headers for the `/favicon.ico` request include an `etag`. But I have also noticed on Chrome and Edge that, both in local, and on Deno Deploy, that the favicon is still requested. 

On Chrome and Edge, looking at the DevTools, it displays `304 Not Modified`, which is “fine” in general, but that's not what I expect for a favicon. Also in the context of Deno Deploy, each request after the first one will still count as 2, isn't it? The 1M monthly request go straight down to 500K.

On Firefox, it is not the case, as when looking at the DevTools it displays `200 OK`, but, it's cached thanks to `FaviconLoader.sys.mjs`, I suppose it's a Firefox mechanism.

I've also used a `_middleware.ts` file in my `routes` folder to debug this observation, both in local and on Deno Deploy. 

On Firefox, it rightfully triggers only one request, after the first one  `/` 👍,  as all the JavaScript files get cached (in prod with Deno Deploy, of course in dev some get triggered).

On the other hand, Chrome and Edge still trigger both `/` and `/favicon.ico`.

Also, I've tried to set some headers, unfortunately, It was still unsuccessful even though they are set (I've checked on all the DevTools).

```ts
import { MiddlewareHandlerContext } from "$fresh/server.ts";

export async function handler(req: Request, ctx: MiddlewareHandlerContext) {
  const res = await ctx.next();
  console.log(req.url);
  console.log(res.headers.has("Cache-Control"))
  if (req.url.endsWith("favicon.ico") && !res.headers.has("Cache-Control")) {
    console.log("ENTER!");
    res.headers.set("Cache-Control", "max-age=604800");
    res.headers.set("Last-Modified", "Last-Modified: Wed, 30 Oct 2023 12:00:00 GMT");
    res.headers.set("Expires", "Thu, 30 Nov 2023 00:00:00 GMT");
  }
  return res;
}

```
![image](https://github.com/denoland/fresh/assets/7095073/33068586-3791-4530-85e0-490c3123fb76)

**Comment by marvinhagemeister** [comment]
Quoting from [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/3049) on the page about the 304 status code:

> Note: Many [developer tools' network panels](https://firefox-source-docs.mozilla.org/devtools-user/network_monitor/index.html) of browsers create extraneous requests leading to 304 responses, so that access to the local cache is visible to developers.

**Comment by ericlery** [comment]
> Quoting from [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/3049) on the page about the 304 status code:
> 
> 
> 
> > Note: Many [developer tools' network panels](https://firefox-source-docs.mozilla.org/devtools-user/network_monitor/index.html) of browsers create extraneous requests leading to 304 responses, so that access to the local cache is visible to developers.

Thanks for your answer. I guess that I am gonna have to use a CDN to not cut on my Deno Deploy requests. 

Issue closed.
