### ISSUE TITLE
Add a plugin to get remote IP from HTTP-Header

### ISSUE THREAD

**Issue by git001** [denoland/fresh#2016]
As in #1827 discussed the remote IP  from a client could be different the the [remoteAddr](https://github.com/denoland/fresh/blob/main/src/server/types.ts#L252) Variable. Some Applications, nowadays, run behind a reverse proxy and send the real client IP in http headers like X-Forwarded-For or [Forwarded HTTP Extension](https://www.rfc-editor.org/info/rfc7239) which should be parsed and set the remoteAddr, or another Variable, with that header value.

There are two to-do's from my point of view.

[ ] Implement Forwarded and/or X-Forwarded-For Parser in a fresh plugin
[ ] Create a example to show the usage of the plugin.

**Comment by marvinhagemeister** [comment]
No, as described in #1827 this should not live in the Fresh code base at all, neither directly in Fresh, nor as a plugin. Adding it to the Fresh repository would imply that we would keep it up to date and maintain it. We won't do that. It should either live in the project's code directly as a middleware or as a plugin in a separate repository. I'm happy to point to that from the docs once a repository for a plugin exists or something like that.
