### ISSUE TITLE
docs: Point to `aria-current` instead of `data-*` attributes for active links

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/fresh#2018]
We need to update our docs to point to `aria-current` instead of `data-*` properties for styling active links. Both are supported, but going with `aria-current` has benefits for accessibility and we should remove the `data-current` and `data-ancestor` at some point.

**Comment by RayZwankhuizen** [comment]
In the current situation data-current and aria-current behave differently.
I have a menu, like this: 

  const menus = [
    { name: "Home", href: "/" },
    { name: "Components", href: "/components" },
    { name: "Docs", href: "/docs" },
  ];

And it is displayed using this:

      <ul class="flex items-center gap-6">
        {menus.map((menu) => (
          <li>
            <a
              href={menu.href}
                class={"[data-current]:text-[#eff4f6] font-bold hover:text-gray-700"}
            >
              {menu.name}
            </a>
          </li>
        ))}
      </ul>


This works when using [data-current], when I click on Components for instance, that is shown in a light color and all other items are darker.
However when I change that to [aria-current] the Home link always stays light, that never changes.
