### ISSUE TITLE
Missing test for init without config.

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/fresh#2026]
A mishap just happened with `1.5.3` where the init + update script where referencing mapped paths from the import map. When running these scripts though, we cannot rely on those because import maps only work in the current project, not on a dependency level. That's the reason I had to revert https://github.com/denoland/fresh/pull/1986 for `1.5.4`. We really need a test for this with `--no-config`. It's already late for me, I'll check it out tomorrow.

**Comment by deer** [comment]
Hey @marvinhagemeister, happy to pick this one up if you can provide a few more details on the case that's missing.
