### ISSUE TITLE
Sync and Async routes have different signatures causing confusion and difficult bugs

### ISSUE THREAD

**Issue by cknight** [denoland/fresh#2042]
Sync routes have the following signature:

```ts
export default function MyRoute(props: PageProps<any, MyState>) { ... }
```
while Async routes have this signature:
```ts
export default async function MyRoute(req: Request, ctx: RouteContext<any, MyState>) { ... }
```
Unless you are familiar with this oddity, changing from sync to async can cause difficult to track bugs.  For example, if you have in your sync route:
```ts
const url: URL = props.url;
```
and change the route to async by only adding the `async` keyword to the signature, e.g.
```ts
export default async function MyRoute(props: PageProps<any, MyState>) { ... }
```
typescipt will not complain that you have the wrong signature and `props` rather than being `PageProps` (as in the Sync route) is actually a `Request` instead and `url` becomes a `string` and not a `URL` as expected, or indeed, asserted in Typescript.

It would be great to unify the signature so that swapping between sync and async didn't cause any unexpected outcomes.

**Comment by ericlery** [comment]
Nice catch 👌

**Comment by marvinhagemeister** [comment]
Closing as they now have the exact same signature in Fresh 2. Fresh 2 will release soon.
