### ISSUE TITLE
Docs: add an example of processing a POST submission

### ISSUE THREAD

**Issue by CAYdenberg** [denoland/fresh#2043]
It took me quite a while to discover how straightforward request body parsing is in Deno.

```
const body = await req.formData();
const username = body.get('your-username');
```

I think it would be helpful to include an example of a handler that processes a POST request (with data in the request body) so that those less familiar with Deno can see right upfront how to do it.

If this is of interest I'd be happy to submit the PR myself.

**Comment by marvinhagemeister** [comment]
That's a great idea! Go for it.

**Comment by CAYdenberg** [comment]
I must have missed this example: https://fresh.deno.dev/docs/concepts/forms#post-request-with-multipartform-data

I'm not sure further documentation on this is necessary.
