### ISSUE TITLE
Fresh docs website navigation is broken

### ISSUE THREAD

**Issue by shivajivarma** [denoland/fresh#2046]
OS: Windows 11
Browser: Chrome 119.0.6045.124

https://github.com/denoland/fresh/assets/1388742/4a4d6dbd-b293-4abe-9055-8703b6846ad6

**Comment by shivajivarma** [comment]
seen following errors on load

![Screenshot 2023-11-16 101255](https://github.com/denoland/fresh/assets/1388742/f8ac9363-27ba-4fe1-b234-bf5547dcecef)

**Comment by marvinhagemeister** [comment]
fixed by https://github.com/denoland/fresh/pull/2047
