### ISSUE TITLE
Generate manifest at runtime

### ISSUE THREAD

**Issue by vwkd** [denoland/fresh#205]
The promise of fresh is great: Just write code and push to GitHub. No build step required, as everything is handled at runtime by Deno Deploy. As no local setup is needed this opens the door to writing code everywhere where there is a text editor with Git integration like on mobile devices.

However, in practice fresh still has a build step even if tiny: generating the manifest. So, we’re back at square one requiring a local developer installation, a terminal, fiddling with shell scripts, PATH variables, etc. pp. Remote code environments like GitHub Codespaces offer only a limited workaround as they just shift the problem to another device, and often creating new problems in the meantime like being limited to a less performant Web client, no mobile support, no persistence in containers, paid, etc. which makes things even more difficult. My current workaround is running it in a GitHub action workflow that creates a pull request with the updated manifest.

Generating the manifest at runtime would eliminate this. Currently this will most probably give a performance hit, as it needs to generate it over and over again for each request, but this could be solved in the future when Deno Deploy gains persistence.

In the meantime until Deno Deploy gains persistence, fresh could support both, by using a pre-built manifest if available and if it isn’t generating it at runtime, so developers have the choice of less complexity for a performance hit.

**Comment by lucacasonato** [comment]
We can unfortunately not generate the manifest at runtime, as Deno Deploy does not support dynamic imports. Once it supports those, the manifest no longer needs to be generated.

I am just waiting on one final issue in Deno to be resolved (https://github.com/denoland/deno/issues/14685), before being able to generate the manifest seamlessly during development in `fresh`.

**Comment by vwkd** [comment]
Thanks. Let’s hope Deno Deploy supports dynamic imports soon so that fresh can generate the manifest at runtime.

Meanwhile automating the build step with  #223 is a nice first step. Though unlike mentioned it doesn’t fix this issue “Generating the manifest at runtime”, since a build step is still necessary, and with it as mentioned all the complexity of a local developer setup.

**Comment by vwkd** [comment]
@lucacasonato Please reopen. Currently there is a build step, as mentioned in my previous comment.

Everywhere in the README, the manual, and even the [1.0 announcement](https://deno.com/blog/fresh-is-stable) is the incorrect claim that there is no build step.

There is no build step, if one can push code to Deno Deploy without ever having it run locally using the Deno CLI.

**Comment by lucacasonato** [comment]
@vwkd That is not a build step.

**Comment by vwkd** [comment]
@lucacasonato What do you understand by “build step”?

If not a build step, how would you call necessary code generation (manifest file) after development (writing code in a text editor) before runtime (pushing to Deno Deploy)?

The fact that you’re hiding it for most people, by automating it while testing the code locally, is smart, but doesn’t make it go away. Again, try writing your project without running the dev server locally and see how far you get.

**Comment by lucacasonato** [comment]
This file does not change every time you change code. It changes only if you update the file structure of your project. You can make code changes to your project, not run it locally, and it will still deploy correctly using the correct code and correct output. As such it is not a build step.

**Comment by vwkd** [comment]
So, you’re saying a “build step” that only happens sometimes [^1] is not a “build step”?

So, most transpilations like TypeScript to JavaScript are also not a “build step”, because the output doesn’t (need to) change for certain input changes (assuming the transpiler is smart enough), like adding an empty line to the input file.

Haven’t seen this concept of a “build step” anywhere else.

[^1]: namely, when adding/removing files in the routes or islands folders, which includes renaming
