### ISSUE TITLE
'Unexpected token '.'' error in frontend when a filename on the island includes a period

### ISSUE THREAD

**Issue by hashrock** [denoland/fresh#2069]
This is a bit niche use case, but I'm trying to create something as an alternative to Storybook. I attempted to distinguish it from the components by using the extension `FooComponent.stories.tsx`. But I encountered an issue below:

Create a file named `islands/FooCounter.bar.tsx`, and when I import and use it, the following error occurs in the browser.

> foo.bar:37 Uncaught SyntaxError: Unexpected token '.' (at foo.bar:37:1086)

<img width="977" alt="image" src="https://github.com/denoland/fresh/assets/3132889/4f14890e-0601-4781-9aec-d6a93b34f449">

minimal reproduction:

https://github.com/hashrock-sandbox/repro-fresh-island-filename-with-dot

Perhaps when the filename contains a period, it needs to be replaced with a different character.

**Comment by hashrock** [comment]
![image](https://github.com/denoland/fresh/assets/3132889/d7cce3cc-d9b7-4a27-bfe9-b9d346f284f0)

The issue still reproduces in the latest version.

https://github.com/denoland/fresh/blob/1501699988e9fd07a7d8e50b599bdb6383837cd6/src/server/rendering/fresh_tags.tsx#L140

It seems that a period can be included in `island.name`.

**Comment by marvinhagemeister** [comment]
The fix was merged 3 days ago and since then no new release was published. If all goes well it should go out tomorrow.

**Comment by marvinhagemeister** [comment]
Reopening, could reproduce the issue.
