### ISSUE TITLE
Idea: Add an option to enable "editor.formatOnSave" during project initialization

### ISSUE THREAD

**Issue by hashrock** [denoland/fresh#2091]
When creating a new project, it would be nice to have auto formatting enabled.
It might be a good idea to ask it after "Do you use VS Code?". I'll be happy to make a PR!

**Comment by hashrock** [comment]
Could it be that many people have the auto-format set to on globally, which might be why the setting is currently not included?

**Comment by marvinhagemeister** [comment]
Yeah, it's something everyone in my circles has enabled globally. That said we can add it too our generated vscode settings too. Happy to accept any such PR.

**Comment by kerimhudson** [comment]
I did have a look at implementing this as I've been curious to try and get more involved with Fresh. But I had some concerns around whether or not a framework really make decisions about how your editor works?

It seems like it would be cumbersome to add it as another option to toggle when starting a fresh project, as I think we should be careful about how many options to provide. This would mean you could set it as automatically enabled by default, but that just doesn't feel right to me.

Out of curiosity I did look at [Next.js](https://github.com/vercel/next.js/tree/canary/packages/create-next-app/templates/default/ts) and [Astro](https://github.com/withastro/astro/tree/main/examples/minimal) to see if they do this at all, and both don't. So I wonder if this is really something Fresh should be doing.

**Comment by CAYdenberg** [comment]
I'm with @baosoy - I can't think of a compelling reason why a user who hasn't enabled this for all vscode projects would want to do so specifically for Fresh.

**Comment by marvinhagemeister** [comment]
Fair point, Fresh shouldn't be too "invasive" to the user's preferences.
