### ISSUE TITLE
Is automatic installation possible?

### ISSUE THREAD

**Issue by Octo8080X** [denoland/fresh#2095]
I am making a plugin for Fresh.
I would like to install the latest version of Fresh in the CICD pipeline and assign and test the specified plugin.

To do the installation Fresh, use `Project Name [fresh-project] ? ` and other, but is it possible to skip this?

**Comment by marvinhagemeister** [comment]
You can skip the prompts by passing the relevant arguments. In our testing for Fresh we do basically
```sh
deno run -A https://fresh.deno.dev my-project-name
```

Here is the full list of available options.

```sh
Initialize a new Fresh project. This will create all the necessary files for a
new project.

To generate a project in the './foobar' subdirectory:
  fresh-init ./foobar

To generate a project in the current directory:
  fresh-init .

USAGE:
    fresh-init [DIRECTORY]

OPTIONS:
    --force   Overwrite existing files
    --tailwind   Setup project to use 'tailwind' for styling
    --vscode  Setup project for VSCode
    --docker  Setup Project to use Docker
```

**Comment by Octo8080X** [comment]
@marvinhagemeister 

Thanks for reaching out to me.  
I have tried following your teachings, but the options don't seem to be working?  
If I am wrong, please let me know.

```sh
$ deno run -A https://fresh.deno.dev ./test --tailwind

 🍋 Fresh: The next-gen web framework.

Let's set up your new Fresh project.

Fresh has built in support for styling using Tailwind CSS. Do you want to use this? [y/N]
```

**Comment by marvinhagemeister** [comment]
Ah apologies, it's `--twind` not `--tailwind`. I pulled the help info from `main` where we switched to a tailwind plugin.

**Comment by Octo8080X** [comment]
@marvinhagemeister 

Thank you very much. It worked. I appreciate it very much.

```sh
$ deno run -A https://fresh.deno.dev my-project-name --force --twind --vscode
```
