### ISSUE TITLE
December 2023 iteration plan

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/fresh#2108]
I'm not sure if we'll be able to land enough new features to warrant a new minor release as this cycle is cut short due to vacations around Christmas. It might happen that we'll skip this one and move it to January. That said, we'll likely cut a patch release before ending the year.

I kinda do want to spent time updating our site and docs as well.

The current plan is to work on these items, although it's likely that they will continue into January.

- [ ] View Transitions https://github.com/denoland/fresh/pull/1532
- [ ] HMR explorations
- [ ] Support JSX precompile transform
- [ ] Pending states for Partials

**Comment by csvn** [comment]
> I kinda do want to spent time updating our site and docs as well.

I noticed while [reading the blog](https://deno.com/blog/fresh-1.6#simplified-typings) that the docs still use a lot of the deprecated interfaces (such as [`ErrorPageProps` and `UnknownPageProps`](https://fresh.deno.dev/docs/concepts/error-pages)). It should be a pretty quick fix to ensure it avoids deprecated interfaces, and I might help out with a PR, but I think that would help a lot for existing and new users to get a feel for the "suggested" approach.

**Comment by mustafa-hanif** [comment]
Is this repo dead?

**Comment by marvinhagemeister** [comment]
@mustafa-hanif What makes you say that?

**Comment by csvn** [comment]
Dead repo's usually don't have commit's almost every day 😅
![image](https://github.com/denoland/fresh/assets/8770194/0b9831d5-9805-47ee-98dc-c43701ae5d82)

**Comment by marvinhagemeister** [comment]
Next roadmap plan is here https://github.com/denoland/fresh/issues/2363
