### ISSUE TITLE
Asynchronous app as plugin

### ISSUE THREAD

**Issue by HelloFillip** [denoland/fresh#2112]
I'm currently trying to re-use as much of the same work as possible between applications, and the plugin API makes sense as a starting point. 

However, I'm starting with the `_app.tsx` as a skeleton route, which doesn't seem to work for an async function. Is this by design, or am I missing some information on how to use async routes in plugins?

Using synchronous is fine usually, but I'm doing a lot of data and asset fetching, using `fetch` the simplest approach is to use `await`. Is there an alternative recommended approach whereby some async fetch routines can be used, in the synchronous routes / components without a need to re-render?

**Comment by deer** [comment]
Hey @HelloFillip, I've confirmed this is a bug in at least the type system (and possibly the runtime as well). I will work on a fix. Thanks for pointing this out.
