### ISSUE TITLE
Add support for autoprefixer with 1.6

### ISSUE THREAD

**Issue by sntran** [denoland/fresh#2117]
The new Tailwind integration does not support using autoprefixer.

To be fair, autoprefixer is not the responsibility of tailwind. I was just migrating from https://deno.land/x/fresh_tailwind@v0.5.3 to fresh 1.6 and thought it would be nice to have it supported.

**Comment by marvinhagemeister** [comment]
Resolved by https://github.com/denoland/fresh/pull/2152
