### ISSUE TITLE
Tailwind upgrade feedback

### ISSUE THREAD

**Issue by cknight** [denoland/fresh#2120]
Just migrating from twind to tailwind following the instructions at https://fresh.deno.dev/docs/examples/migrating-to-tailwind.  Some feedback:

1. I have a twind.config.ts in my project.  What to do with this isn't referenced in the migration guide.   E.g.
```ts
import { defineConfig } from "$fresh/server.ts";
import twindPlugin from "$fresh/plugins/twind.ts";
import twindConfig from "./twind.config.ts";

export default defineConfig({
  plugins: [twindPlugin(twindConfig)],
});
```

presumably becomes:
```ts
import { defineConfig } from "$fresh/server.ts";
import tailwind from "$fresh/plugins/tailwind.ts";

export default defineConfig({
  plugins: [tailwind()],
});
```
?  I.e. Is the new tailwind.config.ts auto-discovered and you don't need to reference it in the plugin registration?

2. Suggestion to move the deno.json changes higher up the order so you don't have to live with compile errors until the very last step (or rather you can cache the new dependencies as you go along).

**Comment by vietthedev** [comment]
`twind` and its config can be removed after migrating to `tailwind`. The code below should be in `fresh.config.ts` according to the docs. It is the plugin registration.

![image](https://github.com/denoland/fresh/assets/5486625/1b9acf93-7ae5-4741-8e9a-bc577b20c5db)
