### ISSUE TITLE
TailwindCSS does not work on Deno deploy

### ISSUE THREAD

**Issue by jurajkrivda** [denoland/fresh#2126]
I create a new project with version 1.6. On localhost Tailwind works well. On Deno deploy I don't see any styles,

**Comment by sylc** [comment]
Have you setup your project with AOT https://fresh.deno.dev/docs/concepts/ahead-of-time-builds ?

**Comment by marvinhagemeister** [comment]
I probably forgot to update the Deploy Template to nudge folks to the AOT build.

**Comment by terrytas13** [comment]
I experienced this same issue yesterday. I upgraded to 1.60 and migrated to TailwindCSS and ran the ahead of time build. Pushed to production and the CSS did not work. Had to revert back to twind.

Created a new install of 1.60 in a separate repository, ran AOT build, pushed to a new Deploy instance and the same thing happened.

Unsure if I'm missing something? Thanks for the assistance (huge fan of Deno Fresh, DX is amazing)

**Comment by lcmkevin** [comment]
Me also have such issues,  using fresh 1.6 and updated to use TailwindCSS , resulting on deno deploy is no style. How can i solve this ?! my project running on local is working fine.

**Comment by altmanlib** [comment]
> I probably forgot to update the Deploy Template to nudge folks to the AOT build.

急

**Comment by marvinhagemeister** [comment]
>> I probably forgot to update the Deploy Template to nudge folks to the AOT build.
>
> 急

@uezjk What does that mean?

**Comment by altmanlib** [comment]
> > > I probably forgot to update the Deploy Template to nudge folks to the AOT build.
> > 
> > 
> > 急
> 
> @uezjk What does that mean?

I thought it would be fixed soon, but I didn't expect it to take a few days, just a little anxious :(

**Comment by marvinhagemeister** [comment]
My main problem is that I don't know how to reproduce this issue. I've migrated a couple of our sites to tailwind over the past week and they all work as expected.

**Comment by csvn** [comment]
Maybe some projects above have not upgraded from automatic deploys to Github actions [as mentioned by sylc](https://github.com/denoland/fresh/issues/2126#issuecomment-1837161960).

> - **Automatic:** Deno Deploy will automatically pull code and assets from your repository source every time you push, and deploy it. This mode is very fast, but does not allow for a build step. This is the recommended mode for most users.
>
>
> https://docs.deno.com/deploy/manual/ci_github

Missing styles make sense if there's no build step before deploys.

**Comment by lcmkevin** [comment]
I did reinstall deno deploy to github and recreate the project, still the same no style.
![image](https://github.com/denoland/fresh/assets/28728535/820c7c90-3302-4915-ba31-9fbec8793db4)


> Maybe some projects above have not upgraded from automatic deploys to Github actions [as mentioned by sylc](https://github.com/denoland/fresh/issues/2126#issuecomment-1837161960).
> 
> > * **Automatic:** Deno Deploy will automatically pull code and assets from your repository source every time you push, and deploy it. This mode is very fast, but does not allow for a build step. This is the recommended mode for most users.
> > 
> > https://docs.deno.com/deploy/manual/ci_github
> 
> Missing styles make sense if there's no build step before deploys

**Comment by marvinhagemeister** [comment]
@lcmkevin Are there any indications in the GitHub Action logs that something is not working? Usually it prints out a message when tailwind couldn't find any tokens.

**Comment by lcmkevin** [comment]
@marvinhagemeister I dun see any error prompt.

**Comment by lcmkevin** [comment]
so, is there any idea to solve this？

**Comment by altmanlib** [comment]
> so, is there any idea to solve this？

my solution is relink project in deno deploy, and build mode use github action :

https://fresh.deno.dev/docs/concepts/ahead-of-time-builds#deploying-an-optimized-fresh-project

**Comment by lcmkevin** [comment]
Good , yes, I did re-poly and make sure the project name is exactly the same in deno deploy and the deploy.yml.
Problem solved.  Great ! Thanks !


> > so, is there any idea to solve this？
> 
> my solution is relink project in deno deploy, and build mode use github action :
> 
> https://fresh.deno.dev/docs/concepts/ahead-of-time-builds#deploying-an-optimized-fresh-project

**Comment by stepbrobd** [comment]
Can the `style.css` file be put somewhere else other than `static/style.css`?

I tried putting it into `static/assets/style.css`, and updated imports accordingly. It works fine locally but when I was trying to build:

```shell
$ deno task build
error: Uncaught (in promise) NotFound: No such file or directory (os error 2): writefile '/tmp/_fresh/static/assets/styles.css'
        await Deno.writeTextFile(outPath, result.content);
        ^
    at async writeFile (ext:deno_fs/30_fs.js:809:7)
    at async Object.buildStart (https://deno.land/x/fresh@1.6.0/plugins/tailwind.ts:163:9)
    at async Promise.all (index 0)
    at async build (https://deno.land/x/fresh@1.6.0/src/dev/build.ts:23:3)
    at async dev (https://deno.land/x/fresh@1.6.0/src/dev/dev_command.ts:49:5)
    at async file:///tmp/dev.ts:8:1
```

**Comment by marvinhagemeister** [comment]
@stepbrobd that should definitely work and if not it's a bug. Can you try updating to Fresh 1.6.1? I recall having fixed a bug related to that.

**Comment by stepbrobd** [comment]
Thanks a lot! Didn't realize 1.6.1 was released, updating did resolve the issue.

**Comment by cj-1010-1414** [comment]
The solution is to not using automatic / no build step option in deployment settings.

**Comment by marvinhagemeister** [comment]
Closing as the issue is resolved. The tailwind plugin requires Ahead of time builds to be set up (see https://fresh.deno.dev/docs/concepts/ahead-of-time-builds). Like others mentioned folks seemed to have missed the step in that doc of switching the deployment mode from "Automatic" to "Github Actions" in Deno Deploy.
