### ISSUE TITLE
`data` @deprecated - "Pass values to state instead"

### ISSUE THREAD

**Issue by timharek** [denoland/fresh#2127]
Congrats on the release of `v1.6.0`! 🎉 

After `v1.6.0` `data` in `PageProps` are being deprecated, and says we should use `state` instead. The docs still says we should use `data`, so I guess those need to be updated.

So to ask the question, how am I supposed to use `state` instead? Should I define a new prop in my State type in the middleware that is for page specific data?

(not sure to title the issue, so please rename if it doesn't make sense)

**Comment by marvinhagemeister** [comment]
Hugh, the `data` type in `PageProps` is not deprecated as far as I'm aware. Did you run into any issues?

**Comment by timharek** [comment]
My linter tells me in my routes that `data` in `PageProps<my-data-type>` is deprecated. So I have a bunch of warnings in all my routes

**Comment by timharek** [comment]
I see that I could give more context here, sorry about that!

This is the lint message I'm refering to:
https://github.com/denoland/fresh/blob/f3578f863ff4c0462fa3122aafef227c40045eb2/src/server/types.ts#L194

<details>
<summary>What I'm seeing</summary>

<img width="1068" alt="image" src="https://github.com/denoland/fresh/assets/5453010/5807b4d3-65d3-48c1-b7a3-86e601248984">
</details>

And my actual code for reference as well
```tsx ./routes/index.tsx
import { Handlers, PageProps } from "$fresh/server.ts";
import { PostList } from "../components/PostList.tsx";
import { getSection } from "../src/content.ts";
import { State } from "./_middleware.ts";

interface HomeProps {
  posts: Post[];
}

export const handler: Handlers<HomeProps, State> = {
  async GET(_req, ctx) {
    const posts = (await getSection("blog")).pages as Post[];

    return ctx.render({ posts: posts.slice(0, 5) });
  },
};
export default function Home({ data }: PageProps<HomeProps>) {
  const { posts } = data;
  return <div></div>;
}
```

**Comment by csvn** [comment]
@timharek I think `ctx.state` is just a shared object, and the way to use it is just to assign data you fetch to that object. For a specific route, you can just extend your `State` interface for this view:

```tsx
import { Handlers, PageProps } from "$fresh/server.ts";
import { PostList } from "../components/PostList.tsx";
import { getSection } from "../src/content.ts";
import { State } from "./_middleware.ts";

interface HomeState extends State {
  posts: PostList;
}

export const handler: Handlers<void, HomeState> = {
  async GET(_req, ctx) {
    ctx.state.posts = (await getSection("blog")).pages as PostList;

    return ctx.render();
  },
};
export default function Home({ state }: PageProps<HomeState>) {
  const { posts } = state;
  return <div></div>;
}
```
I think it would be better though to use `defineRoute()` to create an `AsyncRoute`, where you can make the request directly prior to rendering the component. This way you don't need to do anything at all with either `state` or `data` in this instance, and there are less types to import and use:

```tsx
import { defineRoute } from "$fresh/server.ts";
import { PostList } from "../components/PostList.tsx";
import { getSection } from "../src/content.ts";
import { State } from "./_middleware.ts";


export default defineRoute<State>(async (_req, _ctx) => {
  const posts = (await getSection("blog")).pages as PostList;
  return <div></div>;
});
```

**Comment by csvn** [comment]
You can read more about [async route components on the docs](https://fresh.deno.dev/docs/concepts/routes#async-route-components). The [`defineRoute`](https://fresh.deno.dev/docs/concepts/routes#define-helper) method is just a helper to help create routes with correct types with less effort (or when using `.js`/`.jsx`).

**Comment by timharek** [comment]
Thank you, @csvn! I wasn't aware of the `defineRoute()`-helper! 😊 

Regarding extending the interface, I see that works – nice! But is the recommended solution? The [docs (Form submissions)](https://fresh.deno.dev/docs/getting-started/form-submissions) are still using the "old" `data` object.


I guess @marvinhagemeister will be able to elaborate on the recommended solution going forward 💭

**Comment by csvn** [comment]
I don't think docs have caught up yet with the code. 😃

It was just in https://github.com/denoland/fresh/pull/2099 (3 days ago) that all context/props interfaces were merged together into one. In the new `FreshContext`, `data` was `@deprecated` since it fills a similar purpose as `state`, and there is less need of `data` with async routes.

**Comment by waptik** [comment]
> You can read more about [async route components on the docs](https://fresh.deno.dev/docs/concepts/routes#async-route-components). The [`defineRoute`](https://fresh.deno.dev/docs/concepts/routes#define-helper) method is just a helper to help create routes with correct types with less effort (or when using `.js`/`.jsx`).

Thanks for the `AsyncRoute` example and pointing us to the docs. I was lost when the warnings were popping up about `PageProps.data` being deprecated and i didn't know what to do as the docs haven't caught up with the latest release as you've mentioned.

**Comment by marvinhagemeister** [comment]
For now I think it's best to undo the `deprecation` warning. I might have jumped the gun a little there. Longterm I'm hoping for an API that doesn't require passing around implicit generic types and could do something like

```tsx
ctx.render(<Foo value={foo} />) 
```
