### ISSUE TITLE
Tailwind not working with base path config

### ISSUE THREAD

**Issue by vjdv** [denoland/fresh#2130]
I updated from Fresh 1.4.3 to 1.6.0

Replaced twind with tailwind as tutorial says. It worked!

Added a [basepath](https://deno.com/blog/fresh-1.6#serving-from-a-sub-path) config and updated paths.

Now I'm watching this error:

```
NotFound: No such file or directory (os error 2): readfile '/home/user/projectpath/static/basepath/styles.css'
```

And styles get lost.

**Comment by deer** [comment]
Hey @vjdv, thanks for logging this. I've confirmed the bug and I'm working on a fix.
