### ISSUE TITLE
Infinite live reload loop in Firefox

### ISSUE THREAD

**Issue by nicolo-ribaudo** [denoland/fresh#2153]
When I edit a route file, the page auto-refreshes and gets stuck in an infinite loading loop:

<img width="1015" alt="image" src="https://github.com/denoland/fresh/assets/7000710/b5c64ccf-97cd-4715-bd54-40ed2aa5f8f1">

I'm using Fresh 1.6.0

**Comment by darkship** [comment]
Maybe it's related to https://github.com/denoland/fresh/issues/2050?

**Comment by marvinhagemeister** [comment]
hm, I'm not sure how to reproduce this and #2050 regardless of the setup I'm trying out. I'm using Firefox as my main driver on my personal laptop as well, which makes me a bit baffled why I haven't encountered this myself.

**Comment by nicolo-ribaudo** [comment]
[Archive.zip](https://github.com/denoland/fresh/files/13599099/Archive.zip)

@marvinhagemeister Not a _minimal_ reproduction, but this is my project. You will need to define a `AUTH_USERNAME` and `AUTH_PASSWORD` env vars, run `deno task start`, navigate to /reports/2023 (using the username and password you defined), edit `routes/reports/[year].tsx`, and Firefox will get into the infinite loop.

**Comment by nicolo-ribaudo** [comment]
Oh actually, it does not reproduce the issue. Give me a few minutes :thinking:

**Comment by nicolo-ribaudo** [comment]
Ok, it reproduces _an_ issue if you add a `await new Promise(r => setTimeout(r, 200))` in the route function in `routes/reports/[year].tsx`.

However, I see something different in the network tab than in my original screenshot:

https://github.com/denoland/fresh/assets/7000710/c1cc6136-473a-4b45-aff5-85c4204ef49c

Maybe @marvinhagemeister I can share my project with the real full data with you?

**Comment by nicolo-ribaudo** [comment]
Oh well, I cannot reproduce the original screenshot anymore. I'll close this issue assuming that the last video is the same as #2050, but I'll reopen if I hit the problem again.

**Comment by marvinhagemeister** [comment]
Might be that this is resolved by https://github.com/denoland/fresh/pull/2154
