### ISSUE TITLE
Framework security

### ISSUE THREAD

**Issue by lcmkevin** [denoland/fresh#2169]
how can we ensure framework called web libraries are secure?

**Comment by marvinhagemeister** [comment]
I'm not sure I understand the question correctly. I'm assuming you want to know how Fresh ensures that it is secure?

Fresh is built around Preact which ensures that developers don't open themselves up to XSS attacks by escaping any attribute value or text value that is rendered into the HTML. The escape hatch there is setting content via `dangerouslySetInnerHTML` where the user is responsible for doing so if necessary. So there is enough friction to make the user aware of that.

Other than that Fresh only depends on Deno's standard library to function. Those are mostly a few helper functions.

When it comes to security it always helps to think in terms of what an attack vector into your application could look like. Are you handling user input? If so are you validating it properly on the server before processing it? What happens if someone uses a command line tool like curl to send the request themselves rather than going through your application UI?

**Comment by lcmkevin** [comment]
thank you marvinhagemeister !
So, using deno fresh is safe as I believe deno will do the checking before allow different libraries posting.
Agreed that user input must properly validate and any server request should handle  well too.

**Comment by lcmkevin** [comment]
one more question,  how can I setting secure web header on deno deploy or my fresh web.

- Strict-Transport-Security
- Content-Security-Policy
- X-Frame-Options
- X-Content-Type-Options

**Comment by marvinhagemeister** [comment]
> deno will do the checking before allow different libraries posting

We do occasionally look at libraries posted on our registry, but there is no vetting process in place. When using dependencies from `npm:` or `https://esm.sh` those are typically not vetted either. Were we do actively vet is the dependency that both Deno or Fresh itself use, but that doesn't extend to dependencies you might pull into your project.

> one more question, how can I setting secure web header on deno deploy or my fresh web.
>
> - Strict-Transport-Security
> - Content-Security-Policy
> - X-Frame-Options
> - X-Content-Type-Options

Headers can be added to `Response` objects by doing `response.headers.set("My-Header", "My-Value")`.

**Comment by lcmkevin** [comment]
Oｋ！Thank you! for the response.headers.set , previously I have a language response headers set to determine en or cn. 
Don;t know why i added the security header and then the EN and CN is not working.

```tsx
import { FreshContext } from "$fresh/server.ts";
import en from "../i18n/en.json" assert { type: "json" };
import cn from "../i18n/cn.json" assert { type: "json" };
import { Translation } from "../i18n/types.ts";

export type State = {
  lang: "cn" | "en";
  t: Translation;
};

export async function handler(
  req: Request,
  ctx: FreshContext<State>
) {
  const res = new Response();

  res.headers.set("Strict-Transport-Security", "max-age=31536000; includeSubDomains; preload");
  res.headers.set("X-Frame-Options", "DENY");
  res.headers.set("X-Content-Type-Options", "nosniff");
  res.headers.set("Referrer-Policy", "strict-origin-when-cross-origin");
  res.headers.set(
    "Permissions-Policy",
    "accelerometer=(), camera=(), document-domain=(), encrypted-media=(), gyroscope=(), interest-cohort=(), magnetometer=(), microphone=(), midi=(), payment=(), picture-in-picture=(), publickey-credentials-get=(), sync-xhr=(), usb=(), xr-spatial-tracking=(), geolocation=()"
  );

  try {
    let setLangCookie = true;
    if (
      req.headers.has("cookie") &&
      req.headers.get("cookie")!.includes("lang")
    ) {
      ctx.state.lang = req.headers.get("cookie")!.includes("lang=en")
        ? "en"
        : "cn";
      setLangCookie = false;
    } else if (req.headers.get("accept-language")?.includes("en")) {
      ctx.state.lang = "en";
    } else {
      ctx.state.lang = "cn";
    }

    ctx.state.t = ctx.state.lang === "en" ? en : cn;
    const nextResponse = await ctx.next();

    setLangCookie && nextResponse.headers.set("Set-Cookie", `lang=${ctx.state.lang}`);

    const bodyText = await nextResponse.text();
    const status = nextResponse.status;
    const headers = nextResponse.headers;

    return new Response(bodyText, { status, headers });
  } catch (error) {
    console.error("An error occurred during request processing:", error);
    res.headers.set("X-Custom-Header", "Error");
    res.status = 500;
    res.body = "An error occurred during request processing";

    return res;
  }
}```

**Comment by marvinhagemeister** [comment]
> (...) then the EN and CN is not working.

How does this manifest? Are the headers not present in the response?

**Comment by lcmkevin** [comment]
the header is not present as I checked using  another web header checking tools. 
initially, I check deno deployed web and find that the result is marked no header set and it shows the web insecure , that's  why I would like to implement those headers. 
I would suggest deno deploy  adding option to let user to selectively turn on different header instead of coding into the web. This approaches  like ngnix or apache. this is not handling by programmer but handle by system operations.

**Comment by marvinhagemeister** [comment]
Closing as there is nothing left to do here.
