### ISSUE TITLE
Plugin islands are not pre-buildable

### ISSUE THREAD

**Issue by cbinzer** [denoland/fresh#2171]
Hi,

I noticed that islands that are provided over a plugin are not pre-buildable. When I run `deno run -A --unstable dev.ts build` and start the app with `deno run -A --unstable main.ts` I get a not found error in the browser for the island. I don't see the island in the _fresh directory either.

Regards
Christian

**Comment by deer** [comment]
Thanks for logging this. It's likely that I forgot this use case. I'll take a look later this week.

**Comment by deer** [comment]
@cbinzer, do you mind sharing your `dev.ts`? If it looks like this:
```ts
#!/usr/bin/env -S deno run -A --watch=static/,routes/

import dev from "$fresh/dev.ts";

await dev(import.meta.url, "./main.ts");
```
please try changing it to this:
```ts
#!/usr/bin/env -S deno run -A --watch=static/,routes/

import dev from "$fresh/dev.ts";
import config from "./fresh.config.ts";

await dev(import.meta.url, "./main.ts", config);

```

**Comment by cbinzer** [comment]
Hi @deer,

indeed, you're right. I forgot to set the config in dev.ts. Now it works. Thank you very much 🙏
