### ISSUE TITLE
Retrieve the generated nonce token

### ISSUE THREAD

**Issue by iam0day** [denoland/fresh#2179]
Hi, as per title would it be possible to retrieve the nonce token that generates the framework? I would like to do this for the CSP header: https://content-security-policy.com/nonce/

Even using the `useCSP` function, I have no way to retrieve the nonce token.

**Comment by marvinhagemeister** [comment]
Related issue https://github.com/denoland/fresh/issues/1874

**Comment by marvinhagemeister** [comment]
Closing as duplicate of #1874 .
