### ISSUE TITLE
The "Data Fetching" page in the documentation still references props.data despite being labeled as deprecated

### ISSUE THREAD

**Issue by andrewfgarrison** [denoland/fresh#2187]
I apologize if this is my own ignorance causing the issue, but I have been using Fresh's documentation in order to learn and build some personal websites, and one issue is that in my IDE (Visual Studio Code), the `data` attribute on `props` is labeled as deprecated when passing data from a custom handler to the exported JSX function. It currently works without issue, but my assumption is that it will be fully replaced in the future, and I would like to update the code accordingly. However, the only explanation in the VS Code display is to "pass to state," and I cannot find a source of information on how to do that.

As the title says, the "Data Fetching" page still references `props.data` as the main means to pass data; is this method safe to use for the forseeable future, and if not, what is the recommended method? In addition, is it possible to include a section on using state in the Data Fetching page of the documentation, or include an independent page discussing any unique aspects of state in Fresh?

**Comment by andrewfgarrison** [comment]
Adding in a screenshot of the VS Code display for clarity.

![image](https://github.com/denoland/fresh/assets/64180300/a5c9313b-8efa-4984-aca9-52cb8310bd65)

**Comment by marvinhagemeister** [comment]
We jumped the gun a little with the deprecation and "un-deprecated" it in Fresh 1.6.1 again. Updating to Fresh 1.6.1 will resolve this warning in the editor.
