### ISSUE TITLE
[Question] Integrate with layout service

### ISSUE THREAD

**Issue by chrgue** [denoland/fresh#2191]
Hi there,

because of our microservice architecture we not able to use html output directly. We currently have our own server side rendering service which renders and creates a json with the html output and the necessary resources (scripts+ styles). This json will then been used by our layout service to integrate it onto the page. So basically we're rendering small react applications on the whole page. 

So my question is can fresh also produce json output instead of the outer html? I saw we are able to overwrite the "_app.tsx" but it would be so nice if I could put the rendered html and resources (scripts + styles).

Thanks in advance,
Chris

**Comment by marvinhagemeister** [comment]
You can write a middleware and intercept the returned `Response` object. That way you can grab the raw HTML and send it back as json or something. The HTML rendering itself cannot be changed to render json.
