### ISSUE TITLE
suggest renaming deno tasks

### ISSUE THREAD

**Issue by liigo** [denoland/fresh#2197]
- `deno task start` may be rename to `deno task dev`
- `deno task preview` may be rename to `deno task serve`

reason: cleaner description.

ref: `npm run dev` `npm run serve`.

**Comment by marvinhagemeister** [comment]
> ref: `npm run dev` `npm run serve`.

Can you elaborate on where you got those references from? I feel like this issue is a bit missing the reasons on "why" those names are preferable. I'm certainly open to changing the names of the tasks.

**Comment by liigo** [comment]
@marvinhagemeister 

They don't clearly express which scenario to be used for.
`deno task start` is for dev/debug scenario, but 'start' may be misleading (to start a production version).
`deno task preview` is for production/release scene, but 'preview' is obvious misleading (to preview a develop version).
'dev' / 'serve' is cleaner in semantic than 'start' / 'preview', IMO.

**Comment by marvinhagemeister** [comment]
We renamed the tasks for the upcoming Fresh 2 release to
- `dev`: Run development server
- `start`: Run production server
- `build`: Build production app, same as before
