### ISSUE TITLE
passing server JSX into island props

### ISSUE THREAD

**Issue by mayank99** [denoland/fresh#2202]
After #1285, it became possible to pass server-generated JSX to islands through `children`. The natural next step is to allow the same for arbitrary props (`children` is also just a prop after all).

This works today:
```jsx
<IslandComponent>
  <ServerComponent />
</IslandComponent>
```

This fails silently:
```jsx
<IslandComponent
  slot1={<ServerComponent1 />}
  slot2={<ServerComponent2 />}
/>
```

**Comment by mcgear** [comment]
Is anyone looking into this? I have a few different controls that could use this. If not already in flight, i can try to find some time to look at it.

**Comment by marvinhagemeister** [comment]
This is supported in Fresh 2 out of the box. Fresh 2 will release soon.
