### ISSUE TITLE
Import JSON fail in Island

### ISSUE THREAD

**Issue by sonickseven** [denoland/fresh#2214]
I'm creating app with Fresh and [i18Next](https://deno.land/x/i18next@v23.7.16) package and all were working fine until that me must a import the file [config](https://github.com/i18next/i18next/blob/master/examples/typescript/i18n/config.ts) in one component inside of folder **islands**, the translate works fine, but in my shell appear this message: 

![image](https://github.com/denoland/fresh/assets/3733406/19eab994-676e-4079-b8e5-7f7d10a93e5d)

With **denojs** works fine, but only when I import from island show that error.

My code:

```typescript
import i18next from 'i18next';
import loginupEn from '@helpers/i18n/locales/en/loginup.json' with { type: 'json' };
import footerEn from '@helpers/i18n/locales/en/footer.json' with { type: 'json' };
import loginupEs from '@helpers/i18n/locales/es/loginup.json' with { type: 'json' };
import footerEs from '@helpers/i18n/locales/es/footer.json' with { type: 'json' };

export const defaultNS = 'loginup';

export const resources = {
  en: {
    loginup: loginupEn,
    footer: footerEn,
  },
  es: {
    loginup: loginupEs,
    footer: footerEs,
  },
};

i18next.init({
  lng: 'en', // if you're using a language detector, do not define the lng option
  debug: true,
  resources,
  defaultNS,
});
```

Somebody know the solution without change JSON to file TS?

**Comment by sonickseven** [comment]
I could solved changing the word `type` from `assert` in import of JSON:

code:

```typescript
import i18next from 'i18next';
import loginupEn from '@helpers/i18n/locales/en/loginup.json' assert { type: 'json' };
import footerEn from '@helpers/i18n/locales/en/footer.json' assert { type: 'json' };
import loginupEs from '@helpers/i18n/locales/es/loginup.json' assert { type: 'json' };
import footerEs from '@helpers/i18n/locales/es/footer.json' assert { type: 'json' };
```

**Comment by marvinhagemeister** [comment]
Reopening, because the spec changed from `assert` to `with` and the latter is what we recommend to use onwards. Maybe our escrow version is too old
