### ISSUE TITLE
Plugin API: extends render/renderAsync to pass more stuff

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/fresh#2220]
The `ctx` parameter to the render plugin API should receive more stuff on it. Things like the `Request` object, etc. It should match other areas of the plugin API.

**Comment by guitavano** [comment]
Started here: https://github.com/denoland/fresh/pull/2224

**Comment by marvinhagemeister** [comment]
Closing as this isn't necessary in Fresh 2 anymore which will release soon.
