### ISSUE TITLE
TailwindCSS doesn't load on production but in development it works

### ISSUE THREAD

**Issue by jheysaaz** [denoland/fresh#2223]
This problems happens with the following project: [jheysaav/jheysonsaavedra.com](https://github.com/jheysaav/jheysonsaavedra.com/tree/63184af98ad4ec2d106aae2b28fb88482db465be). The projects is alive [here](https://jheysaav.deno.dev).

TailwindCSS is configured as a the docs explain it and when I run `deno task start` it works fine like this:
![image](https://github.com/denoland/fresh/assets/84047886/11864762-014a-4105-a659-a41416370876)

But in the production mode when I run `deno task preview` or when I deploy it to Deno Deploy it seen like this:
![image](https://github.com/denoland/fresh/assets/84047886/77cdb6fa-ec21-4d50-9a29-585680ac30ea)

The Tailwind css file doesn't work.

This is my `tailwind.config.ts`: 
```typescript
import { type Config } from "tailwindcss";
import colors from "tailwindcss/colors.js";

export default {
  content: [
    "{routes,islands,components}/**/*.{ts,tsx}",
  ],
  darkMode: "class",
  theme: {
    fontFamily: {
      sans: ["Inter Variable", "Inter", "sans-serif"],
    },
    colors: {
      gray: colors.zinc,
      primary: colors.blue,
      secondary: colors.emerald,
    },
  },
} satisfies Config;
```

The `routes/_app.tsx` file looks like this:
```tsx
import { type PageProps } from "$fresh/server.ts";
import Header from "../components/Header.tsx";

export default function App({ Component, url }: PageProps) {
  return (
    <html lang="en">
      <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>Jheyson Saavedra</title>
        <link rel="stylesheet" href="/styles/tailwind.css" />
        <link rel="stylesheet" href="/styles/inter.css" />
      </head>
      <body className="w-scren h-screen flex flex-col bg-gray-50 dark:bg-gray-900 text-gray-900 dark:text-gray-50">
        <Header url={url} />
        <main>
          <Component />
        </main>
      </body>
    </html>
  );
}

```

Finally the `static/styles/tailwind.css` file looks as this:
```css
@tailwind base;
@tailwind components;
@tailwind utilities;
```

**Comment by marvinhagemeister** [comment]
The tailwindcss plugin requires Ahead of time builds to be set up, see the requirements section in https://fresh.deno.dev/docs/examples/migrating-to-tailwind . This involves two steps:

1. Set deployment mode to `GitHub Actions` in Deno Deploy (your's is likely set to automatic which won't work)
2. Add the `deploy.yml` file from https://fresh.deno.dev/docs/concepts/ahead-of-time-builds and update the project name to match yours. The project name can be found in Deno Deploy under `Settings > Project Name`

I'm planning to add a specific error page to Fresh when it detects that the tailwindcss styles are not compiled and show a nice error page. It seems to be something that many users run into, so it's definitely on us to improve the DX.

Related issues:
- https://github.com/denoland/fresh/issues/2188
- https://github.com/denoland/fresh/issues/2126

**Comment by jheysaaz** [comment]
> The tailwindcss plugin requires Ahead of time builds to be set up, see the requirements section in https://fresh.deno.dev/docs/examples/migrating-to-tailwind . This involves two steps:
> 
> 
> 
> 1. Set deployment mode to `GitHub Actions` in Deno Deploy (your's is likely set to automatic which won't work)
> 
> 2. Add the `deploy.yml` file from https://fresh.deno.dev/docs/concepts/ahead-of-time-builds and update the project name to match yours. The project name can be found in Deno Deploy under `Settings > Project Name`
> 
> 
> 
> I'm planning to add a specific error page to Fresh when it detects that the tailwindcss styles are not compiled and show a nice error page. It seems to be something that many users run into, so it's definitely on us to improve the DX.
> 
> 
> 
> Related issues:
> 
> - https://github.com/denoland/fresh/issues/2188
> 
> - https://github.com/denoland/fresh/issues/2126

This solution works for me. @marvinhagemeister thank you.
