### ISSUE TITLE
Trying to use a tailwind plugin, but seems to not be working

### ISSUE THREAD

**Issue by mcgear** [denoland/fresh#2278]
I am trying to use a tailwind plugin in order to get our child components in a place where their base styles are easily overridable.  After looking through some different options i settled on ``.

Here is my tailwindconfig, but the plugin is not working.  Any thoughts on what i may be doing wrong?

```ts
import { type Config } from "tailwindcss";
import * as colors from "tailwindcss/colors.js";
import unimportant from "npm:tailwindcss-unimportant";
import { buildTailwindComponentsConfigs } from "@fathym/common";
import BiotechAtomicTailwindComponents from "@fathym/atomic/tailwind.components.ts";
// import ;

const tailwindComponents = [...BiotechAtomicTailwindComponents];

await buildTailwindComponentsConfigs(tailwindComponents);

export default {
  content: [
    "{routes,islands,components}/**/*.{ts,tsx}",
    "build/tailwind-components.config",
  ],
  plugins: [unimportant],
  theme: {
    extend: {
      backgroundImage: {
        "hero-pattern":
          "linear-gradient(rgba(0, 0, 40, 0.85),rgba(0, 0, 40, 0.85)), url('https://fresh.deno.dev/gallery/hero-bg.webp')",
      },
      color: {
        primary: "#4a918e",
        secondary: "#4a918e",
        tertiary: "#4a918e",
        info: colors.blue,
        error: colors.red,
        warning: colors.yellow,
      },
    },
  },
} satisfies Config;
```

**Comment by marvinhagemeister** [comment]
Just tried it out and the `tailwindcss-unimportant` plugin works as expected. Adding the their `-:` prefix to selectors reduces specificity of those classes.

> Here is my tailwindconfig, but the plugin is not working. Any thoughts on what i may be doing wrong?

With "not working" do you mean that the `-:` prefix doesn't work?

**Comment by mcgear** [comment]
Yea, it broke all of my styles across the board. This got me thinking though.. I am using a set of styles that come from supporting libraries. We have the styles coming in, however we use a helper to append the '-:' to each class. Which means that those styles aren't there to be picked up during the ahead of time build so tailwind doesn't see them. I guess that is my issue. So i am looking into ways to surface those completed styles to be picked up by tailwind during ahead of time compilation.
