### ISSUE TITLE
Bug: Tailwindcss not working in js/jsx files

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/fresh#2291]
Was reported on discord earlier today. Haven't looked into it yet.

**Comment by kerimhudson** [comment]
The default `tailwind.config.ts` doesn't include js,jsx in the content. The default initialisation could just add `js,jsx` to the list, if it's worth it.

```
import { type Config } from "tailwindcss";

export default {
  content: [
    "{routes,islands,components}/**/*.{ts,tsx}",
  ],
} satisfies Config;
```
