### ISSUE TITLE
Tailwindcss takes a long time to compile

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/fresh#2308]
Mostly making this issue as a note for me to investigate a bit. Looked at the tailwind internals a while back here https://marvinh.dev/blog/speeding-up-javascript-ecosystem-part-8/ . So there is lots of room to speed it up.

We might also speed the UX up greatly by adding proper HMR support.

**Comment by king8fisher** [comment]
Wondering if transitioning to UnoCSS could give us better results?
https://unocss.dev/integrations/runtime mentions something that might be appealing to Fresh.
Might need a migration guide.

**Comment by marvinhagemeister** [comment]
I benchmarked all the various libraries when writing the article. UnoCSS takes the same time as tailwindcss. We need to create styles also server side.

**Comment by miguelrk** [comment]
Although fresh sort-of went the tailwindcss route already, it would be cool to (officially) have unocss as an alternative as well, by landing https://github.com/denoland/fresh/pull/1966 which I've been using (unofficialy) already for a while and should be ready 👍🏼

**Comment by marvinhagemeister** [comment]
@miguelrk Who's going to maintain the UnoCSS plugin? If we merge it than the burden falls on me.

**Comment by miguelrk** [comment]
Good point, totally understandable @marvinhagemeister... in case it helps someone, I maintain [a fork](https://deno.land/x/netzo@0.4.37/plugins/unocss?source) 👍🏼 . In any case, eager to see improvements in the HMR space!

**Comment by miguelrk** [comment]
Good point, totally understandable @marvinhagemeister... in case it helps someone, I maintain [a fork](https://deno.land/x/netzo@0.4.37/plugins/unocss/plugin.ts?source) 👍🏼 . In any case, eager to see improvements in the HMR space!

**Comment by marvinhagemeister** [comment]
Closing, as I've been sporadically in touch with the tailwindcss team and they made great strides in improving compilation performance. Once their new major version is out I'd expect it to be noticeably faster.
