### ISSUE TITLE
`useState()` hook stops working when `Deno.readTextFile()` is used

### ISSUE THREAD

**Issue by ooker777** [denoland/fresh#2312]
This code works fine:
##### `routes/index.tsx`:
```tsx
import Test from "../islands/test.tsx";

export default function a() {
  return <Test></Test>
}
```
##### `islands/test.tsx`:
```tsx
import { useState } from 'preact/hooks';

export default function Test() {
  const [count, setCount] = useState(0);
  const increment = () => setCount(count + 1);
  const decrement = () => setCount((currentCount) => currentCount - 1);

  return (
    <div>
      <p>Count: {count}</p>
      <button onClick={increment}>Increment</button>
      <button onClick={decrement}>Decrement</button>
    </div>
  )
}
```

If I add:
```js
async function f(){} 
const a = await f()
```
outside the function, then it still runs fine. However, if the line is:
```js
const a = await Deno.readTextFile('posts/lydo.md') 
```
or
```js
const a = Deno.readTextFileSync('posts/lydo.md') 
```
then the hook stops working. Why is that?

**Comment by marvinhagemeister** [comment]
In which file are you adding those functions? In the route file or the island file? If it's inside an island than this is expected to break. The browser doesn't have a global `Deno` variable, that's unique to Deno. If used in an island there is likely a big red error shown in the browser console.

**Comment by ooker777** [comment]
Yes on the island file. I see. Is it possible to fix this? I wonder if Node having the same problem?

**Comment by king8fisher** [comment]
@ooker777 Have you tried to add a custom handler to your route? They run on the server.
https://fresh.deno.dev/docs/getting-started/custom-handlers

**Comment by marvinhagemeister** [comment]
> Yes on the island file. I see. Is it possible to fix this? I wonder if Node having the same problem?

Islands run in the browser and cannot access functions from the server execution environment. The same scenario occurs with Node or any other runtime for that matter. That's the way different JavaScript runtime work. Each runtime has their own set of APIs and whilst Deno has the biggest overlap with the browser from them all, it doesn't mean that every single function available in Deno is available in the browser.

Like @king8fisher suggested, server code goes on the server and putting them anywhere else other than inside islands is the way to address this.

Closing as it's working as expected.

**Comment by ooker777** [comment]
I wonder why Fresh doesn't just break when such situation happens? Instead it still renders fine and only interactivity is broken

**Comment by yuhr** [comment]
This causes difficulty on debug. Fresh should definitely detect this and emit errors.
