### ISSUE TITLE
Modifying HEAD_CONTEXT in middleware

### ISSUE THREAD

**Issue by sudhirj** [denoland/fresh#232]
Taking off from #147, how would one go about adding a stylesheet to all routes in a middleware? I've gotten as far as 

```
useContext(HEAD_CONTEXT).push([h('link', {href: asset('/tailwind.css'), type: 'stylesheet'})]);
```
but the context isn't accessible in the middleware, which makes sense because I guess it isn't in the render flow. How could one hook into the render flow, though?

**Comment by sudhirj** [comment]
Or is there something one could pass to middleware state that the rendered could use when making the <head> tag?

**Comment by lucacasonato** [comment]
As you have discovered, using hooks or any form of JSX during data loading / routing is not possible. You can only use these primitives during rendering.

What you can do is make use of a common `<Layout />` component across some pages, or use the `ctx.state` to propagate data from a middleware to a route handler, and then to the renderer using the data prop to the render function.
