### ISSUE TITLE
Code is displayed incorrectly on fresh docs on Windows Edge browser (on recent install)

### ISSUE THREAD

**Issue by epangelias** [denoland/fresh#2322]
![image](https://github.com/denoland/fresh/assets/140029624/69a0e5bf-685d-42b6-9ecf-4fb9e0042237)
![image](https://github.com/denoland/fresh/assets/140029624/784f2d06-1f24-49bd-bea3-944636d8491c)
![image](https://github.com/denoland/fresh/assets/140029624/f884d461-1e20-4a5c-8dd9-c71d26f123b0)

**Comment by marvinhagemeister** [comment]
I can reproduce that. This is super odd

**Comment by epangelias** [comment]
Believe it is being caused by partials, it goes away when reloading the page

**Comment by foxscotch** [comment]
I'm seeing the same thing on both Chrome 121.0.6167.185 (64-bit) and Firefox 120.0.1 (64-bit). I can't imagine OS is related but just for the sake of completeness I'm on Windows 11 22H2 Build 22621.3007.

If someone else doesn't figure it out before the weekend, I'd be happy to look into it myself.

**Comment by marvinhagemeister** [comment]
Yeah it's not OS related and is reproduceable in every browser. It's likely that it's triggering something weird in Preact's child reconciliation algorithm

**Comment by marvinhagemeister** [comment]
Likely related: https://github.com/preactjs/preact/pull/4287
