### ISSUE TITLE
Add "Help Wanted" labels? 

### ISSUE THREAD

**Issue by sudhirj** [denoland/fresh#233]
I'm really liking the approach here, seems very fresh :D and well thought out. 

How can I help? If there are help wanted labels on any of the issues I'm happy to raise PRs. 

Lots of docs need to be written as well, from what I can see. Would you be willing to accept drafts for docs or would like them all in the single voice and tone etc?

**Comment by Utwo** [comment]
I've also just discovered this project and would like to help! Really like the concept, seems like an Astro version for Deno. How can I help?

**Comment by lucacasonato** [comment]
There is not much "good first issue" work right now. I have labeled a few issues with this label now though.

Thanks for the interest though!
