### ISSUE TITLE
using nunjucks with Fresh

### ISSUE THREAD

**Issue by choucavalier** [denoland/fresh#2335]
hello! trying to use nunjucks to generate html within Deno Fresh.

i created a `./views` folder at the root of my project. it contains html templates.

however, when i build the site, this `./views` folder is not moved to the `_fresh` build folder

therefore, nunjucks does not find my templates at runtime

what is the right way to solve this?

thanks for any help!

p.s. i don't really want to expose my views in the `static` folder, since this is leaking information about the code to the user

**Comment by marvinhagemeister** [comment]
I'd like to understand your setup better. Why does the `./views` folder need to be in `_fresh`? Why is nunjucks looking for it there?

**Comment by marvinhagemeister** [comment]
Closing as we haven't heard back.
