### ISSUE TITLE
Custom headers in defineRoute possible?

### ISSUE THREAD

**Issue by vicary** [denoland/fresh#2339]
With `defineRoute` being a really convenient method for type inference, I almost exclusively use this helper method.

I found it falls short for pages with forms, where it is supposed to go stale when navigated away, a common practise would be adding `Cache-Control: no-cache, no-store, must-revalidate`.

Is it possible to allow custom headers when returning a component from the helper?

**Comment by marvinhagemeister** [comment]
Headers are set in so called `Handler` functions in Fresh that are executed before any rendering happens. See https://fresh.deno.dev/docs/getting-started/custom-handlers

**Comment by vicary** [comment]
Note to self: useContext breaks (#983) when exporting `defineRoute` with an async callback, while exporting a sync FunctionComponent works.
