### ISSUE TITLE
How do I turn off fresh's automatic redirect from /page/ to /page?

### ISSUE THREAD

**Issue by masx200** [denoland/fresh#2342]
How do I turn off fresh's automatic redirect from /page/ to /page?

**Comment by masx200** [comment]
https://github.com/denoland/fresh/issues/2343

**Comment by marvinhagemeister** [comment]
Please don't open multiple issues for the same thing.

**Comment by ooker777** [comment]
Perhaps they intended to make a duplication to increase the search keyword?
