### ISSUE TITLE
Add a way to disable trailing slash logic

### ISSUE THREAD

**Issue by masx200** [denoland/fresh#2343]
A global middleware that is not affected by fresh is required.
The handler defined in the routes/_middleware.ts file is not global middleware and will be affected by the trailingSlashEnabled redirect from fresh.

https://deno.land/x/fresh@1.6.5/src/server/context.ts?source#L175

https://deno.land/x/fresh@1.6.5/src/server/context.ts?source#L237

**Comment by masx200** [comment]
https://github.com/denoland/fresh/issues/2342

**Comment by marvinhagemeister** [comment]
Closing as this is resolved in the upcoming Fresh 2 release. There, by default Fresh will leave the URL as is and devs can opt in to always appending a trailing slash or always removing it via a middleware:

```ts
import { App, fsRoutes, staticFiles, trailingSlashes } from "@fresh/core";

export const app = new App()
  .use(staticFiles())
  .use(trailingSlashes("never"));   // <--
```
