### ISSUE TITLE
Setting multiple cookies before render will only send the last Set-Cookie header

### ISSUE THREAD

**Issue by onemenzel** [denoland/fresh#2346]
When creating a `Headers` object, setting multiple cookies on it and passing that to `ctx.render` via the `RenderOptions`, only the last cookie will be set. There is a workaround one can render the response and then modifying the headers on the response but it should work via the other way, too, I suppose.

```ts
// this will not work
const headers = new Headers();
cookie.setCookie(headers, /*...*/);
cookie.setCookie(headers, /*...*/); // <- only this one will be set
return ctx.render({}, { headers });

// this will work
const res = await ctx.render({});
cookie.setCookie(res.headers, /*...*/);
cookie.setCookie(res.headers, /*...*/);
return res
```

**Comment by deer** [comment]
Thanks for logging this. I agree this is a bug and I'll create a PR soon.
