### ISSUE TITLE
Fresh install from the docs throws errors.

### ISSUE THREAD

**Issue by remainstheday** [denoland/fresh#2350]
After running the initial commands I received the console error shown in the image below.
https://fresh.deno.dev/docs/getting-started/create-a-project

![CleanShot 2024-03-07 at 19 05 33@2x](https://github.com/denoland/fresh/assets/4063510/171506f6-60c0-46f7-bc15-0903d288df08)

**Comment by marvinhagemeister** [comment]
What version of Deno are you using? Are you on latest? Looking at the trace I'd assume that the Deno version installed on your machine is a bit old.

**Comment by marvinhagemeister** [comment]
I'm assuming that this is resolved as we haven't heard back. It's very likely that the error was thrown because the Deno version was too old, because otherwise we'd be using `Deno.serve` in Fresh.
