### ISSUE TITLE
Location and description of import_map.json

### ISSUE THREAD

**Issue by k35o** [denoland/fresh#2364]
`.vscode/import_map.json` is used in `deno.json` as well as `.vscode/settings.json`.
If `deno.json` uses it, I thought it was fine to place it in root.

Even if not, I felt that the following notations should be eliminated.
```json
  "scopes": {
    "THIS FILE EXISTS ONLY FOR VSCODE! IT IS NOT USED AT RUNTIME": {}
  },
```
https://github.com/denoland/fresh/blob/main/.vscode/import_map.json#L2-L4

**Comment by marvinhagemeister** [comment]
Closing as we removed it in the Fresh 2 codebase.
