### ISSUE TITLE
Support React as alternative to Preact

### ISSUE THREAD

**Issue by gerabell** [denoland/fresh#2375]
Even so very similar in many aspects, there are also more and more differences between those two. Working with both in parallel is getting quite challenging.
Do you see any options for allowing to use / support React for Fresh - on the server-side but also for islands?
Especially in expectation of React 19 this would be a great support for Fresh.

**Comment by marvinhagemeister** [comment]
There are no plans to change the underlying framework at the moment. What parts of React 19 are you interested in specifically and would like to see in Fresh?

**Comment by gerabell** [comment]
I am most interested in the new React compiler approach which prevents to use manual, error-prone memoization to speed up rendering/avoid unneeded refreshing. Maybe this would also have an effect on the server to avoid expensive re-calculation.
Apart from that the new „Actions“ approach for submits etc seems interesting.

**Comment by marvinhagemeister** [comment]
Signals are an alternative to the React compiler which already work today. They offer even more granular control over when something re-renders compared to what we've seen so far from what has been revealed about the React compiler so far.

The server actions are certainly interesting, but it's more of a next.js feature, not something that comes with React. If Fresh would switch to React there wouldn't be server actions out of the box. It's something that's built on top of React. Whether you build server actions on React or Preact makes no difference in the end.

**Comment by katungi** [comment]
Preact supports using React stuff using `compat`. Is it possible to opt into compat mode using fresh?
Just curious.

**Comment by marvinhagemeister** [comment]
Yes that's possible, see https://github.com/denoland/fresh/issues/1395 .

Closing this issue as there are no plans to move to React.
