### ISSUE TITLE
Bundle a webapp into an executable using `deno compile`?

### ISSUE THREAD

**Issue by cowboyd** [denoland/fresh#239]
Not the primary deployment target, but we're looking to bundle a web application (the [Effection inspector](https://frontside.com/effection/docs/guides/inspector) specifically) into an executable so that you can start it from the command line. e.g.

```
$ effection inspect
--> Effection inspector running on http://localhost:8700
```

The web server, along with all the assets comprising the application would be embedded inside the executable.  Is it possible to do something like this with Fresh?

**Comment by lucacasonato** [comment]
No, this is not possible right now.

**Comment by cowboyd** [comment]
What is your feeling on the capabilities that are currently missing make this not possible? 

I've  been looking into this lately, and have found a couple of tools such as [denobundle](https://github.com/txthinking/denobundle) that allow you to pack a rudimentary read-only file system into a single javascript which could hypothetically be used to include the web assets inside the executable. 

If you think this is something that could be done, and might also have a chance of being included, I'd be happy to have a look.

**Comment by barcellos-pedro** [comment]
Hey @cowboyd, there is a similar issue #785 about compiling Fresh applications.
Do you think this one also has something to do with it?

**Comment by cowboyd** [comment]
Yes it is a similar issue, and what you are looking to do is not possible. 

In our case, we worked around this by using Vite(https://vitejs.dev) to build the web app, and then bundled it with our application binary using https://github.com/thefrontside/graphgen/blob/v1/cli/tasks/bundle-assets.ts

**Comment by z-nerd** [comment]
It's possible:
deno compile --allow-net --allow-read --allow-env --allow-run  main.ts
I compiled the quick start example and API joke worked but main page had below error:

An error occurred during route handling or page rendering.

ReferenceError: React is not defined
    at Object.Home (file:///home/zero/Desktop/my-project/routes/index.tsx:4:5)
    at https://esm.sh/v122/preact-render-to-string@5.2.6/X-ZS8q/deno/preact-render-to-string.mjs:12:1830
    at T (https://esm.sh/v122/preact-render-to-string@5.2.6/X-ZS8q/deno/preact-render-to-string.mjs:12:1857)
    at T (https://esm.sh/v122/preact-render-to-string@5.2.6/X-ZS8q/deno/preact-render-to-string.mjs:12:1933)
    at T (https://esm.sh/v122/preact-render-to-string@5.2.6/X-ZS8q/deno/preact-render-to-string.mjs:12:1933)
    at T (https://esm.sh/v122/preact-render-to-string@5.2.6/X-ZS8q/deno/preact-render-to-string.mjs:12:1933)
    at T (https://esm.sh/v122/preact-render-to-string@5.2.6/X-ZS8q/deno/preact-render-to-string.mjs:12:1933)
    at z (https://esm.sh/v122/preact-render-to-string@5.2.6/X-ZS8q/deno/preact-render-to-string.mjs:12:316)
    at realRender (https://deno.land/x/fresh@1.1.5/src/server/render.ts:109:20)
    at Object.render (https://deno.land/x/fresh@1.1.5/src/server/render.ts:128:13)


Please fix this ReferenceError.

**Comment by wycbk** [comment]
> It's possible: deno compile --allow-net --allow-read --allow-env --allow-run main.ts I compiled the quick start example and API joke worked but main page had below error:
> 
> An error occurred during route handling or page rendering.
> 
> ReferenceError: React is not defined at Object.Home (file:///home/zero/Desktop/my-project/routes/index.tsx:4:5) at https://esm.sh/v122/preact-render-to-string@5.2.6/X-ZS8q/deno/preact-render-to-string.mjs:12:1830 at T (https://esm.sh/v122/preact-render-to-string@5.2.6/X-ZS8q/deno/preact-render-to-string.mjs:12:1857) at T (https://esm.sh/v122/preact-render-to-string@5.2.6/X-ZS8q/deno/preact-render-to-string.mjs:12:1933) at T (https://esm.sh/v122/preact-render-to-string@5.2.6/X-ZS8q/deno/preact-render-to-string.mjs:12:1933) at T (https://esm.sh/v122/preact-render-to-string@5.2.6/X-ZS8q/deno/preact-render-to-string.mjs:12:1933) at T (https://esm.sh/v122/preact-render-to-string@5.2.6/X-ZS8q/deno/preact-render-to-string.mjs:12:1933) at z (https://esm.sh/v122/preact-render-to-string@5.2.6/X-ZS8q/deno/preact-render-to-string.mjs:12:316) at realRender (https://deno.land/x/fresh@1.1.5/src/server/render.ts:109:20) at Object.render (https://deno.land/x/fresh@1.1.5/src/server/render.ts:128:13)
> 
> Please fix this ReferenceError.

I have also encountered this situation.
