### ISSUE TITLE
[Bug] Preact's hydrate will clear uncontrolled property(e.g.`defaultValue)

### ISSUE THREAD

**Issue by ahuigo** [denoland/fresh#2406]
Preact's hydrate will clear uncontrolled property(e.g., `defaultValue="12"`), this is wrong 
> We could see that `defaultValue="12"` is cleared by client's hydrate.

I'm not sure if this is a  fresh bug.

## Demo:
https://fresh-demo-ahuigo.deno.dev/react/hello

## Source code: 
https://github.com/ahuigo/fresh-demo/blob/hydrate-bug/islands/react/hello.tsx

**Comment by rschristian** [comment]
This doesn't appear to be a hydration bug actually, as hydration shouldn't diff props, but a bug in Preact's render diffing _I think_.

To reproduce: [Repl](https://preactjs.com/repl?code=aW1wb3J0IHsgaHlkcmF0ZSwgcmVuZGVyIH0gZnJvbSAncHJlYWN0JwppbXBvcnQgeyBodG1sIH0gZnJvbSAnaHRtL3ByZWFjdCc7CgpmdW5jdGlvbiBBcHAoKSB7CiAgICByZXR1cm4gaHRtbGAKICAgICAgICA8aW5wdXQgZGVmYXVsdFZhbHVlPSJiYXIiIC8%2BCiAgICBgOwp9Cgpjb25zdCBlbnRyeSA9IGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCdhcHAnKQplbnRyeS5pbm5lckhUTUwgPSAnPGlucHV0IHZhbHVlPSJmb28iIC8%2BJwoKLy9oeWRyYXRlKGh0bWxgPCR7QXBwfSAvPmAsIGVudHJ5KTsgIC8vIGhhcyBhIHZhbHVlIG9mIGBmb29gCnJlbmRlcihodG1sYDwke0FwcH0gLz5gLCBlbnRyeSk7IC8vIHNldHMgdGhlIGBkZWZhdWx0VmFsdWVgIHByb3AgY29ycmVjdGx5LCBidXQgY2xlYXJzIGB2YWx1ZWAK)

Looks like `render()` will update the `defaultValue` prop but clear `value`
