### ISSUE TITLE
Tailwind plugin wanders into `scss` files then crashes on build

### ISSUE THREAD

**Issue by marcusjang** [denoland/fresh#2420]
When adding included Tailwind plugin to an existing project with sass/scss files in static directory, the plugin on `buildStart` will walk the static directory in search for css files. However when it bumps into `scss` files which postcss isn't able to parse, it throws the error below:

```
error: Uncaught (in promise) CssSyntaxError: <css input>:22:17: Unknown word
```

Seemingly caused by the line below in the plugin, which matches any files ending with `css`, including `*.scss`. Changing `exts` from `"css"` to `".css"` seemed to solve the issue, but I'm not 100% sure if this was due to a design decision or simply a bug.

https://github.com/denoland/fresh/blob/main/plugins/tailwind.ts#L103

**Comment by marvinhagemeister** [comment]
Just checked and this is resolved in Fresh 2 which will be released soon.
