### ISSUE TITLE
What do the <reference /> mean in main.ts?

### ISSUE THREAD

**Issue by ashah888** [denoland/fresh#2425]
Hi. First time Deno/Fresh user here.

At top of main.ts, there are 5 comments that look like this:
```
/// <reference no-default-lib="true" />
/// <reference lib="dom" />
/// <reference lib="dom.iterable" />
/// <reference lib="dom.asynciterable" />
/// <reference lib="deno.ns" />
```

What do these mean? Is this an example of something?

Is <reference /> an actual component?

What do each of these lib=".." mean (or do)?

**Comment by marvinhagemeister** [comment]
It's a TypeScript feature, see https://www.typescriptlang.org/docs/handbook/triple-slash-directives.html
