### ISSUE TITLE
Clicking the recipe demo on Fresh's homepage changes the page title to "My Fresh app"

### ISSUE THREAD

**Issue by frou** [denoland/fresh#2431]
<img width="966" alt="Screenshot 2024-05-17 at 19 00 46" src="https://github.com/denoland/fresh/assets/172663/157afbca-bf95-48e8-bf0d-dc47fe7a17ec">

**Comment by marvinhagemeister** [comment]
Whoops, that's an oversight on our part. Thanks for filing an issue!
