### ISSUE TITLE
Build: DNS Error registry-staging.deno.com

### ISSUE THREAD

**Issue by epikoder** [denoland/fresh#2438]
58.45 error: Import 'https://registry-staging.deno.com/@luca/esbuild-deno-loader/meta.json' failed: error sending request for url (https://registry-staging.deno.com/@luca/esbuild-deno-loader/meta.json): error trying to connect: dns error: failed to lookup address information: Name or service not known
58.45     at https://deno.land/x/fresh@1.6.8/src/build/deps.ts:9:29

Is computer behind a proxy: NO
I tried VPN same problem

Also building on DigitalOcean droplet throw the same error

**Comment by marvinhagemeister** [comment]
We used the `registry-staging.deno.com` as our registry URL before it officially became JSR. It very much sounds like you're on an older version of Deno. Upgrade Deno to resolve this error.
