### ISSUE TITLE
Just a very small note of "original.jpeg" binary file

### ISSUE THREAD

**Issue by hoangph271** [denoland/fresh#246]
https://github.com/lucacasonato/fresh/blob/main/www/static/illustration/original.jpeg

For now, the image is used on the front page and it's a .jpeg...!
This means when the user agent uses some weird `background-color`, it's kind look weird, too...!

I just one to add a `// TODO: ` somewhere, so...!

Please todo this...?
Great project, btw...!

Screenshot from my mac using the `plash` app

**Comment by hoangph271** [comment]
<img width="1280" alt="image" src="https://user-images.githubusercontent.com/39024711/174334553-9d6bba36-05ac-441b-918f-daff992854fc.png">

**Comment by lucacasonato** [comment]
I am happy to take a PR that forces the page background color to white.

**Comment by Suya1671** [comment]
> I am happy to take a PR that forces the page background color to white.

That sounds like a bad idea for people that rely on dark themes for accessibility reasons. Why not just make it a png/webp and make the bg transparent?

**Comment by hoangph271** [comment]
> > I am happy to take a PR that forces the page background color to white.
> 
> That sounds like a bad idea for people that rely on dark themes for accessibility reasons. Why not just make it a png/webp and make the bg transparent?

This really sounds better, can you take the PR...?
I'm quite stupid with these editing stuffs...!

**Comment by hashrock** [comment]
Let me take this issue. I'd like to rebuild it in SVG💪
