### ISSUE TITLE
Children in an island component do not render

### ISSUE THREAD

**Issue by orsi** [denoland/fresh#247]
When using `children` in an island component, Fresh renders an error page, however, when that same component is moved out of the `islands/` folder, it seems to work. I'm sure I'm using the framework wrong, but still seems like you should be able to use `{children}` in an island component.

Repo: https://github.com/orsi/orsi.dev/tree/feature/fresh

<img width="445" alt="Screen Shot 2022-06-17 at 12 41 00 PM" src="https://user-images.githubusercontent.com/7156655/174340852-1b6da793-7e2d-4a5b-aa0c-8bd6d6b02e37.png">

```
An error occured during route handling or page rendering.
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Object'
    |     property '__c' -> object with constructor 'Object'
    --- property '__v' closes the circle
    at JSON.stringify (<anonymous>)
    at render (https://raw.githubusercontent.com/lucacasonato/fresh/main/src/server/render.tsx:243:14)
    at async https://raw.githubusercontent.com/lucacasonato/fresh/main/src/server/context.ts:405:24
    at async https://crux.land/api/get/uYQG.ts:155:22
    at async Server.#respond (https://deno.land/std@0.128.0/http/server.ts:298:18)
```

Moving `/islands/Container.tsx` -> `/components/Container.tsx` solves the issue:
<img width="397" alt="Screen Shot 2022-06-17 at 12 41 51 PM" src="https://user-images.githubusercontent.com/7156655/174340952-33ffc16c-9704-4e9d-bdbf-0bee6418af06.png">

```
// Container.tsx
/** @jsx h */
import { h } from "$fresh/runtime.ts";

export default function Container({ children }) {
  return <div>{children}</div>;
}
```

**Comment by orsi** [comment]
The above might have been related to the way I was inserting JSON.

I tried removing everything inside the Container except a div, and it solved the error, but instead it flashes the `children` content for a moment before removing it from the DOM.

Simplified branch with the issue: https://github.com/orsi/orsi.dev/tree/container-issue
Deploy: https://orsi-dev-container-issue.deno.dev

```
// islands/Container.tsx
/** @jsx h */
import { h } from "$fresh/runtime.ts";

export default function Container({ children }: any) {
  return <div>{children}</div>;
}

// routes/index.tsx
/** @jsx h */
import { h } from "$fresh/runtime.ts";
import Container from "../islands/Container.tsx";
export default function Home() {
  return (
    <div>
      Top
      <Container>
        <div>Bottom</div>
      </Container>
    </div>
  );
}
```
<img width="1353" alt="Screen Shot 2022-06-17 at 1 12 45 PM" src="https://user-images.githubusercontent.com/7156655/174346227-1592fb13-d40d-4dcf-8b4a-45a09afd06a6.png">

**Comment by lucacasonato** [comment]
All props passed to islands must be JSON serializable, and as such you can not pass children to islands.

**Comment by orsi** [comment]
Ahh, gotcha I was not aware of that.

**Comment by orsi** [comment]
Question: why do islands have to be JSON serializable and not work like regular React components?

**Comment by orsi** [comment]
@lucacasonato ^

**Comment by lucacasonato** [comment]
> Question: why do islands have to be JSON serializable and not work like regular React components?

Because the props passed to islands on the server need to be serialized so that the island can be revived with the right props on the client.
