### ISSUE TITLE
Islands should support React.js

### ISSUE THREAD

**Issue by EdamAme-x** [denoland/fresh#2517]
I think islands of Fresh should support react.  

Because Preact alone does not preserve many compatibilities; there are compatibles such as **compat**, but using them takes a lot of time and is plagued by unexplained compatibility bugs.

What do you think?

**Comment by EdamAme-x** [comment]
Support for react and other jsxSources (hono/jsx, emotion/jsx) would allow many great libraries to be used. (e.x. Radix, Shadcn, CSS in JS, etc)

**Comment by marvinhagemeister** [comment]
There are no plans to switch to another framework at the moment. We don't have the required bandwidth to maintain multiple frameworks.
