### ISSUE TITLE
Button presses should not trigger zoom

### ISSUE THREAD

**Issue by oaustegard** [denoland/fresh#252]
On the homepage at https://fresh.deno.dev/, viewed in Chrome on iOS iPhone 12, when tapping either of the Example’s plus or minus buttons repeatedly, if your tap speed hits the double-tap threshold the screen zooms unexpectedly to the width of the current number and the button you pressed. On zoom in the two increment/decrement presses are counted, then the zoom happens, on zoom out the zoom out happens first and “eats” the increment/decrement. 

Both behaviors are surprising to a user and deserve a more consistent behavior.

**Comment by lucacasonato** [comment]
I'd be happy to take a PR to fix this. It seems like some oddity in Apple's Safari.

**Comment by TommyDew42** [comment]
Lemme take this up! 🚀

**Comment by TommyDew42** [comment]
@lucacasonato 

I am testing the change in my mobile device. Does fresh server by default listen to network request too? I don't seem to be able to connect to my local server from my mobile device.

**Comment by lucacasonato** [comment]
@TommyDew42 It binds to `localhost` by default I think. You may need to explicitly bind to `hostname: "0.0.0.0"` (you can specify this as an option to `start` in `//www/main.ts`.

**Comment by lino-levan** [comment]
This should probably be closed since #277 got merged.

**Comment by iuioiua** [comment]
Closing, as this has been completed.
