### ISSUE TITLE
failed to init fresh project by JSR

### ISSUE THREAD

**Issue by SteveSuv** [denoland/fresh#2527]
when I init fresh project follow by https://github.com/denoland/fresh/tree/main/init
```sh
deno run -Ar jsr:@fresh/init
```
throw error
```
error: Could not find version of '@fresh/init' that matches specified version constraint '*'
```

**Comment by marvinhagemeister** [comment]
There is no public stable release of `@fresh/init` yet as Fresh 2 isn't released yet. Until we'll make the first public release for the latest tag JSR requires an explicit version:

```diff
- deno run -Ar jsr:@fresh/init
+ deno run -Ar jsr:@fresh/init@2.0.0-alpha.16
```

Once Fresh 2 is out, this will not be necessary anymore.
