### ISSUE TITLE
Configuration-Driven Running Modes/Profiles

### ISSUE THREAD

**Issue by x80486** [denoland/fresh#2531]
## Description

Currently, when Fresh project is generated, a `dev.ts` and `main.ts` files are created — along with some related tasks. These files are intuitive enough to figure it out what's their role within the project.

The `dev.ts` file looks very much like something users shouldn't have to deal with directly because it reflects _a way to run the application_. I think this approach could be streamlined because Fresh already has a configuration file. Basically, Fresh could be able to hide all this and have a single entrypoint by introducing the notion of _running modes_ (or something similar), driven by the configuration file and some flag specified in a task when the application is run.

This could lead to a more declarative configuration, where things like `dotenv` (usually only used for local development) and things like that are meant to be used only, let's say in `dev` mode, and some others won't be used in `prod` or `test` mode — just throwing ideas.

```javascript
// fresh.config.js
export default defineConfig({
  modes: {
    dev: {
      loadModules: ["dotenv"],
      envFile: ".env"
      watch: ["components", "routes", "static"]
    }
    prod: {
      // ...
    },
    test {
      loadModules: ["dotenv"]
      envFile: ".env"
    }
  }
});
```

I'm not sure how complex this could be, or if it aligns with how you would like Fresh to behave in general, but it certainly reduces boilerplate code (for users) and makes environment management more intuitive — twelve-factor app, etc.

**Comment by marvinhagemeister** [comment]
You might be happy to hear that this has been cleaned up a bit with the upcoming Fresh 2 release. The code has already landed in the `main` branch and can be checked out. We got rid of the config file all together and moved everything dev related into `dev.ts` and anything else into `main.ts`.

**Comment by x80486** [comment]
Looking forward Fresh 2.0 release! :ok_hand:
