### ISSUE TITLE
f-partial does nothing

### ISSUE THREAD

**Issue by finalclass** [denoland/fresh#2544]
I've created a brand new project (the way described in the docs).
Then I've added two files:

**routes/test/index.tsx**

```tsx
import { Partial } from "$fresh/runtime.ts";

export default function Test() {
  return (
    <div>
      TEEEEEEEEEEE
      <a href="" f-partial="/partials/test">GO</a>

      <Partial name="CartProducts">
        ???
      </Partial>
    </div>
  );
}
```

**routes/partials/test.tsx**

```tsx
import { Partial } from "$fresh/runtime.ts";

export default function Test() {
  return (
    <Partial name="CartProducts">
      DONE
    </Partial>
  );
}
```

After visiting the `/test` route and clicking the "GO" button the page refreshes instead of loading the partial.

**Comment by marvinhagemeister** [comment]
Partials only become active if the element you clicked on or one of its ancestors has `f-client-nav` attribute set. If that is not set or it's set to false, then partials are disabled. See https://fresh.deno.dev/docs/concepts/partials 

Wondering if we should enable this by default when `f-partial` is set. That might be less confusing.

**Comment by finalclass** [comment]
Thanks for clarifying. Maybe adding a full code example here would be clearer:

![image](https://github.com/denoland/fresh/assets/1343930/851a0b24-a8a5-4284-94e4-826cf54e6c3c)
