### ISSUE TITLE
Dead link

### ISSUE THREAD

**Issue by finalclass** [denoland/fresh#2546]
https://fresh.deno.dev/docs/concepts/plugins
![image](https://github.com/denoland/fresh/assets/1343930/73afa03a-0e7b-40a2-b902-210816f669ac)
![image](https://github.com/denoland/fresh/assets/1343930/4616a37d-c974-4ad2-9059-cd0447c69d61)

**Comment by marvinhagemeister** [comment]
We should inline a basic example for Fresh 1.x plugins in the docs instead of referring to a file in the repository.

**Comment by Mrashes** [comment]
Taking a crack at this, PR should be coming in the hour

**Comment by marvinhagemeister** [comment]
Resolved by https://github.com/denoland/fresh/pull/2575
