### ISSUE TITLE
init.ts creates broken project (if prior Fresh `main` is cached)

### ISSUE THREAD

**Issue by NfNitLoop** [denoland/fresh#255]
# Steps to reproduce

```
deno run -A --no-check https://raw.githubusercontent.com/lucacasonato/fresh/main/init.ts my-project
cd my-project
deno task start
```

Then load the URL in your browser.  

# Results

```
An error occured during route handling or page rendering. Error: Build failed with 1 error:
deno:file:///C:/Users/cody/my-project/islands/Counter.tsx:4:40: ERROR: [plugin: deno] The module was missing and could not be loaded.
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.14.39/mod.js:1572:15)
    at https://deno.land/x/esbuild@v0.14.39/mod.js:1218:28
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.14.39/mod.js:1001:63)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.14.39/mod.js:1216:7)
    at https://deno.land/x/esbuild@v0.14.39/mod.js:1325:14
    at https://deno.land/x/esbuild@v0.14.39/mod.js:633:9
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.14.39/mod.js:730:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.14.39/mod.js:599:7)
    at https://deno.land/x/esbuild@v0.14.39/mod.js:1846:11
An error occured during route handling or page rendering. Error: Build failed with 1 error:
deno:file:///C:/Users/cody/my-project/islands/Counter.tsx:4:40: ERROR: [plugin: deno] The module was missing and could not be loaded.
    at failureErrorWithLog (https://deno.land/x/esbuild@v0.14.39/mod.js:1572:15)
    at https://deno.land/x/esbuild@v0.14.39/mod.js:1218:28
    at runOnEndCallbacks (https://deno.land/x/esbuild@v0.14.39/mod.js:1001:63)
    at buildResponseToResult (https://deno.land/x/esbuild@v0.14.39/mod.js:1216:7)
    at https://deno.land/x/esbuild@v0.14.39/mod.js:1325:14
    at https://deno.land/x/esbuild@v0.14.39/mod.js:633:9
    at handleIncomingPacket (https://deno.land/x/esbuild@v0.14.39/mod.js:730:9)
    at readFromStdout (https://deno.land/x/esbuild@v0.14.39/mod.js:599:7)
    at https://deno.land/x/esbuild@v0.14.39/mod.js:1846:11
```

It doesn't seem to like the `$fresh` import map. I remember this working before, so I tried rolling back from Deno 1.23.0 to 1.22.3 but saw the same behavior there.

`$fresh` is obviously working for other generated code.  Just not in Counter.tsx. (Broken for islands?)  Replacing $fresh with the full path fixes the issue.

**Comment by sylc** [comment]
@NfNitLoop adding `--reload`, to burst the cache, solves it for me.

<img width="574" alt="image" src="https://user-images.githubusercontent.com/10268458/174469522-cdcc6081-030f-43c0-be55-d51e3db78d19.png">

**Comment by NfNitLoop** [comment]
ahaa, I see. It's because of old versions of "https://raw.githubusercontent.com/lucacasonato/fresh/main/" in my Deno cache.

Without the [`deno install -f`][1] of the CLI to update the cache, `init.ts` can end up including mixed versions from `main` over time.

[1]: https://github.com/lucacasonato/fresh/commit/836cc24bdd111577f3b36341977872e8d185d8f6#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L38

A maybe more correct fix is to update importMap to import a specific version of Fresh instead of whatever happens to be in `main` in a given day:

```json
    "$fresh/": "https://raw.githubusercontent.com/lucacasonato/fresh/61b71c672035f89271cd6796bdc3499c0e0d4b35/"
```

This fixes the issue for me.

**Comment by lucacasonato** [comment]
> A maybe more correct fix is to update importMap to import a specific version of Fresh instead of whatever happens to be in `main` in a given day:

Yes, that is the intent. The fresh + install script will soon be properly versioned, so this will happen automatically.

**Comment by lucacasonato** [comment]
I will close this as this will be fixed as a result of publishing versioned releases.
