### ISSUE TITLE
Incorrect processing of URLSearchParams when submitting forms inside f-nav-client

### ISSUE THREAD

**Issue by limkaa4** [denoland/fresh#2567]
If we have some example form 

  ```
 <form>
        <label>
            <input type="checkbox" name="interests" value="sports">
            Sports
        </label><br>
        <label>
            <input type="checkbox" name="interests" value="music">
            Music
        </label><br>
        <label>
            <input type="checkbox" name="interests" value="travel">
            Travel
        </label><br>
        <input type="submit" value="Submit">
    </form>
```

Now, if we pick all interests and submit form. On search params we looks like this 

`?interests=travel`

but correct is 

`?interests=sports&interests=music&interests=travel`

It seems that replacing set with append is enough to fix it [on this](https://github.com/denoland/fresh/blob/main/src/runtime/client/partials.ts#L255)

**Comment by marvinhagemeister** [comment]
Thanks for the excellent bug report! You're spot on that it should've been `.append()` there 👍
