### ISSUE TITLE
[fresh@2.0] File-based routing has inconsisten middleware behavior 

### ISSUE THREAD

**Issue by miguelrk** [denoland/fresh#2588]
From [`this thread`](https://discord.com/channels/684898665143206084/991511118524715139/1260586156764958821):

`_middleware.ts` files will not run the handler sometimes (I tried all handler signatures). It is pretty inconsistent, sometimes it runs (e.g. for `/route/one`, and then for `/route/two` it won't run. I might be doing something wrong (don't think so this time, I have the WIP docs revamped for Fresh 2.0 open), but I can confirm that at a minimum, the behavior is different than that of `_middleware.ts` files in fresh 1.x (not sure if intended or not). Funny enough, not doing file-based routing and using `app.use((ctx) => {...})` directly instead, in e.g. `main.ts` with the same handler as in the `_middleware.ts` file, works normally as it should.

**Comment by timreichen** [comment]
Ref https://github.com/denoland/fresh/issues/2657 with a reproduction guide.

**Comment by marvinhagemeister** [comment]
Resolved by https://github.com/denoland/fresh/pull/2680
