### ISSUE TITLE
iOS15 Partials link do not work

### ISSUE THREAD

**Issue by jsb188** [denoland/fresh#2597]
In iOS15.2, any usage of Partials do not work with error message "Partial not found .. Skipping ..."

Tested on Android Chrome, all links work.

Tested on iOS, Safari and Chrome, links do not work.

How to duplicate: Test using any minimal code that uses partials.

**Comment by marvinhagemeister** [comment]
So you're saying that the docs on https://fresh.deno.dev are broken on iOS? I'm unable to reproduce that on my end.

**Comment by jsb188** [comment]
Nope, those work fine.

But Partials always confused me.

Does anything look wrong with this code?

```
[_app.tsx]
<body f-client-nav>
  <Partial name='page' key='page'>
    <div>
      Something in here
    </div>
  </Partial>

  <Partial name='other' key='other'>
    <div>
      Something in here
    </div>
  </Partial>
</body>
```

```
[/routes/somewhere/page.tsx]
<a href="/route-to-somewhere" f-client-nav>
  Clicking me should change page-partial.
</a>
```

**Comment by marvinhagemeister** [comment]
What does the contents of the partial response look like?

**Comment by jsb188** [comment]
> What does the contents of the partial response look like?

it's a new page to whatever route, static or with islands, same result.

Also a related issue where a `<form>` element breaks and even though I can "type" into a input field, none of the event handlers work (in iOS 15 only). On the surface it looks like event handlers are not working, but if I look closely, the reason why the `<form>` and `<input>` breaks is because the html form is complaining with the same "Partials not found ... skipping" error, so I've deduced that somewhere in the page (or form url), Fresh thinks the page breaks because partials doesn't exist (when it actually does).

**Comment by marvinhagemeister** [comment]
I see. It seems like there is some general confusion on what partials are and how they can be used. Let me explain them in a bit of simpler setup where we ignore Fresh specific features like islands for second and only look at the HTML.

When a user goes to your page, the server respond with some HTML. We'll ignore the outer HTML document and only focus on the contents of the `<body>` tag for now.

```html
<body>
  <nav>
    <a href="/">home</a>
    <a href="/about">about me</a>
  </nav>
  <div id="content">
    <h1>hello, this is my cool website!</h1>
  </div>
</body>
```

Next to our default home page (=`/`) we also have an `/about` page, which renders the following HTML:

```html
<body>
  <nav>
    <a href="/">home</a>
    <a href="/about">about me</a>
  </nav>
  <div id="content">
    <h1>Read more about me</h1>
  </div>
</body>
```

If we compare the two pages, only the elements inside `<div id="content">` have changed. All the outer HTML is the exact same.

```diff
  <body>
    <nav>
      <a href="/">home</a>
      <a href="/about">about me</a>
    </nav>
    <div id="content">
-     <h1>hello, this is my cool website!</h1>
+     <h1>Read more about me</h1>
    </div>
  </body>
```

Since only a little piece of the HTML changes, a natural optimization would be to only updated that part and keep the rest of the page alive. This way we can avoid a full page load which typically clears the whole screen and builds it up again that tends to cause a white flicker on many devices.

We know for a fact that only the contents inside `<div id="content">` changes. So what if we intercept clicks on `<a>`-tags, do a `fetch()` call, grab all elements inside `<div id="content">` from the server response and inject them into the current page?

```js
// Over simplified code of how we could do this
document.querySelector("a").addEventListener("click", async event => {
  event.preventDefault();
  
  // Fetch the page the `<a>`-tag points to
  const url = event.target.getAttribute("href");
  const res = await fetch(url);
  const htmlString = await res.text();
  
  // parse the raw html string into an HTML document
  const htmlDoc = new DOMParser().parseFromString(htmlString, "text/html");
  
  // Grab the `<div id="content">` element from the response
  const newContent = htmlDoc.querySelector("#content");
  
  // Get the current `<div id="content">` element on the page
  const currentContent = document.querySelector("#content")
  
  // ... and insert the elements from the response into that
  // First: Clear all old children
  currentContent.textContent = '';
  
  // The insert the new ones
  newContent.children.forEach(child => currentContent.append(child))
});
```

This works and allows us to swap out the content inside `<div id="content">` whenever the user clicks one of our links. Pretty cool so far! But what happens when the response _doesn't have_ a `<div id="content">` element? Let's enhance our example for that by adding a third `/contact` page.

```diff
  <body>
    <nav>
      <a href="/">home</a>
      <a href="/about">about me</a>
+     <a href="/contact">contact</a>
    </nav>
    <div>
      <h1>hello, this is my cool website!</h1>
    </div>
  </body>
```

Notice how the `/contact` page doesn't have a `<div id="content">` element. It has a `<div>` element, but no element with `id="content"`. So we open our home page in the browser, click the `/contact` link, our link interception logic fires and woa... it breaks! Our code checks for `document.querySelector("#content")` but there is not such element in the HTML response for the contact page. So what should we do? Maybe we can add a little warning to be shown in the browser console whenever that happens. Let's enhance our snippet for that:

```diff
```js
  // Over simplified code of how we could do this
  document.querySelector("a").addEventListener("click", async event => {
    event.preventDefault();
    
    // Fetch the page the `<a>`-tag points to
    const url = event.target.getAttribute("href");
    const res = await fetch(url);
    const htmlString = await res.text();
  
    // parse the raw html string into an HTML document
    const htmlDoc = new DOMParser().parseFromString(htmlString, "text/html");
  
    // Grab the `<div id="content">` element from the response
    const newContent = htmlDoc.querySelector("#content");
    
+  if (newContent === null) {
+    console.warn(`No <div id="content"> element found in the HTML response. Skipping...`)
+    return // abort we can't continue
+  }
  
    // Get the current `<div id="content">` element on the page
    const currentContent = document.querySelector("#content")
    
    // ... and insert the elements from the response into that
    // First: Clear all old children
    currentContent.textContent = '';
    
    // The insert the new ones
    newContent.children.forEach(child => currentContent.append(child))
  });
```

And this is basically exactly what partials in Fresh are. We didn't use HTML elements directly because inserting them affects CSS styling and use Preact components to keep track of them instead. We also have some logic to revive islands and all that sort of thing. But conceptually, this is exactly how partials work.

**Comment by jsb188** [comment]
> I see. It seems like there is some general confusion on what partials are and how they can be used. Let me explain them in a bit of simpler setup where we ignore Fresh specific features like islands for second and only look at the HTML.
> 
> When a user goes to your page, the server respond with some HTML. We'll ignore the outer HTML document and only focus on the contents of the `<body>` tag for now.
> 
> ```
> <body>
>   <nav>
>     <a href="/">home</a>
>     <a href="/about">about me</a>
>   </nav>
>   <div id="content">
>     <h1>hello, this is my cool website!</h1>
>   </div>
> </body>
> ```
> 
> Next to our default home page (=`/`) we also have an `/about` page, which renders the following HTML:
> 
> ```
> <body>
>   <nav>
>     <a href="/">home</a>
>     <a href="/about">about me</a>
>   </nav>
>   <div id="content">
>     <h1>Read more about me</h1>
>   </div>
> </body>
> ```
> 
> If we compare the two pages, only the elements inside `<div id="content">` have changed. All the outer HTML is the exact same.
> 
> ```diff
>   <body>
>     <nav>
>       <a href="/">home</a>
>       <a href="/about">about me</a>
>     </nav>
>     <div id="content">
> -     <h1>hello, this is my cool website!</h1>
> +     <h1>Read more about me</h1>
>     </div>
>   </body>
> ```
> 
> Since only a little piece of the HTML changes, a natural optimization would be to only updated that part and keep the rest of the page alive. This way we can avoid a full page load which typically clears the whole screen and builds it up again that tends to cause a white flicker on many devices.
> 
> We know for a fact that only the contents inside `<div id="content">` changes. So what if we intercept clicks on `<a>`-tags, do a `fetch()` call, grab all elements inside `<div id="content">` from the server response and inject them into the current page?
> 
> ```js
> // Over simplified code of how we could do this
> document.querySelector("a").addEventListener("click", async event => {
>   event.preventDefault();
>   
>   // Fetch the page the `<a>`-tag points to
>   const url = event.target.getAttribute("href");
>   const res = await fetch(url);
>   const htmlString = await res.text();
>   
>   // parse the raw html string into an HTML document
>   const htmlDoc = new DOMParser().parseFromString(htmlString, "text/html");
>   
>   // Grab the `<div id="content">` element from the response
>   const newContent = htmlDoc.querySelector("#content");
>   
>   // Get the current `<div id="content">` element on the page
>   const currentContent = document.querySelector("#content")
>   
>   // ... and insert the elements from the response into that
>   // First: Clear all old children
>   currentContent.textContent = '';
>   
>   // The insert the new ones
>   newContent.children.forEach(child => currentContent.append(child))
> });
> ```
> 
> This works and allows us to swap out the content inside `<div id="content">` whenever the user clicks one of our links. Pretty cool so far! But what happens when the response _doesn't have_ a `<div id="content">` element? Let's enhance our example for that by adding a third `/contact` page.
> 
> ```diff
>   <body>
>     <nav>
>       <a href="/">home</a>
>       <a href="/about">about me</a>
> +     <a href="/contact">contact</a>
>     </nav>
>     <div>
>       <h1>hello, this is my cool website!</h1>
>     </div>
>   </body>
> ```
> 
> Notice how the `/contact` page doesn't have a `<div id="content">` element. It has a `<div>` element, but no element with `id="content"`. So we open our home page in the browser, click the `/contact` link, our link interception logic fires and woa... it breaks! Our code checks for `document.querySelector("#content")` but there is not such element in the HTML response for the contact page. So what should we do? Maybe we can add a little warning to be shown in the browser console whenever that happens. Let's enhance our snippet for that:
> 
> ```diff
> ```js
>   // Over simplified code of how we could do this
>   document.querySelector("a").addEventListener("click", async event => {
>     event.preventDefault();
>     
>     // Fetch the page the `<a>`-tag points to
>     const url = event.target.getAttribute("href");
>     const res = await fetch(url);
>     const htmlString = await res.text();
>   
>     // parse the raw html string into an HTML document
>     const htmlDoc = new DOMParser().parseFromString(htmlString, "text/html");
>   
>     // Grab the `<div id="content">` element from the response
>     const newContent = htmlDoc.querySelector("#content");
>     
> +  if (newContent === null) {
> +    console.warn(`No <div id="content"> element found in the HTML response. Skipping...`)
> +    return // abort we can't continue
> +  }
>   
>     // Get the current `<div id="content">` element on the page
>     const currentContent = document.querySelector("#content")
>     
>     // ... and insert the elements from the response into that
>     // First: Clear all old children
>     currentContent.textContent = '';
>     
>     // The insert the new ones
>     newContent.children.forEach(child => currentContent.append(child))
>   });
> ```
> 
> And this is basically exactly what partials in Fresh are. We didn't use HTML elements directly because inserting them affects CSS styling and use Preact components to keep track of them instead. We also have some logic to revive islands and all that sort of thing. But conceptually, this is exactly how partials work.

Can you help me understand why the same code works in Android and iPad (unknown OS version but I can check) but not in iOS 15?

**Comment by marvinhagemeister** [comment]
No, I've never seen that happen anywhere and can't reproduce that on my end. There should be no difference. Do you have some code or a repository where that is reproducible?

**Comment by jsb188** [comment]
I've already created several reproducible demos and videos (for other bugs) and... and I'd really like to wait until v2.0 is released before I create any more reproducible demos.

Speaking of which, when is it going to be released? I thought last month was the release month?

**Comment by marvinhagemeister** [comment]
I see. I guess in that case the issue isn't actionable and it's better to close it.
