### ISSUE TITLE
🍋 No styles in production deployment

### ISSUE THREAD

**Issue by leongobbs** [denoland/fresh#2605]
My local styles work correctly, but the moment I deploy using deno-deploy, my site breaks. What could be the problem? I rebuilt the project on a fresh deno run -A -r https://fresh.deno.dev 
version fresh@1.6.8
reps: https://github.com/leongobbs/leon-bio-blog

**Deno deploy settings**
Project Name `leongobbs-leon-bio-78`
Build Step `deno task build`
Root directory `.`
Production Branch` main.ts`
Entrypoint `main.ts`

I did everything all over again, the deployment mode on GitHub Actions, the styles still didn’t work

**Comment by CAYdenberg** [comment]
In `dev.ts`, your config must be passed as the 3rd argument to `dev`. See https://fresh.deno.dev/docs/concepts/ahead-of-time-builds#migrating-existing-projects-with-plugins

If you do this, you'll notice that `deno task build` takes considerably longer: presumably that is Tailwind working over your project.

**Comment by leongobbs** [comment]
Thank you very much, it really worked!
