### ISSUE TITLE
deno task start fails: registry-staging not available

### ISSUE THREAD

**Issue by bobbwhy** [denoland/fresh#2622]
I created a new project and ran deno task start as described in the docs.
error was: 
Import 'https://registry-staging.deno.com/@luca/esbuild-deno-loader/meta.json' failed: error sending request for url (https://registry-staging.deno.com/@luca/esbuild-deno-loader/meta.json): error trying to connect: dns error: failed to lookup address information: nodename nor servname provided, or not known

thank you

**Comment by marvinhagemeister** [comment]
To resolve this error upgrade your Deno version (=run `deno upgrade`).

The `registry-staging.deno.com` URL was the prototype URL around December 2023 before JSR became officially JSR. Upgrade your Deno version to fix the error.
