### ISSUE TITLE
Importing server components in islands. Fresh 2.0

### ISSUE THREAD

**Issue by predaytor** [denoland/fresh#2623]
https://fresh.deno.dev/docs/canary/concepts/islands#passing-jsx-to-islands
> You can also create shared components in your components/ directory, which can be used in both static content and interactive islands. When these components are used within islands, interactivity can be added, such as onClick handlers (using an onClick handler on a button outside of an island will not fire).

I need to share some data from the server via the Context API, it will sure only be available to the server components. How to include such a component in island component? Is this a bad pattern? We can check with `IS_BROWSER`, but I don't need conditional rendering in my case.

`_app.tsx`:
```tsx
import type { PageProps } from "fresh";
import { createContext } from "preact";

interface AppContextValue extends PageProps {}

export const AppContext = createContext<AppContextValue | null>(null);

export default function App(props: PageProps) {
  return (
    <html>
      <head></head>
      
      <body>
        <AppContext.Provider value={props}>
          <props.Component />
        </AppContext.Provider>
      </body>
    </html>
  );
}
```
`routes/index.tsx`:
```tsx
import { define } from "../utils.ts";
import { Link } from "../components/Link.tsx";
import { TestIsland } from "../islands/Test.tsx";

export default define.page(function Home() {
  return (
    <div>
      <TestIsland />
      <br />
      <Link href="https://example.com">External link (server component)</Link>
    </div>
  );
});
```
`components/Link.tsx`:
```tsx
import type { ComponentChildren } from "preact";
import { AppContext } from "../routes/_app.tsx";
import { useContext } from "preact/hooks";

// import { IS_BROWSER } from "fresh/runtime";

export interface LinkProps {
  href: string;
  children?: ComponentChildren;
}

export function Link(props: LinkProps) {
  console.log("hydrated");

  const appContext = useContext(AppContext)!;
  const url = new URL(props.href, appContext.url);
  const isExternal = url.protocol.startsWith("http") && url.host !== appContext.url.host;

  return (
    <a
      rel={isExternal ? "noopener" : undefined}
      target={isExternal ? "_blank" : undefined}
      {...props}
    />
  );
}
```
`islands/Test.tsx`:
```tsx
import { Link } from "../components/Link.tsx";

export function TestIsland() {
    return (
        <>
            <Link href="https://example.com">
                External link (client component)
            </Link>
        </>
    );
}
```
It renders correctly, but there is a mismatch between the server and the client. (`appContext` is null on the client).

<img width="812" alt="Знімок екрана 2024-08-20 о 15 23 59" src="https://github.com/user-attachments/assets/ac39bbc9-9654-4347-8a63-d88e36ab25e4">

<img width="812" alt="Знімок екрана 2024-08-20 о 15 25 35" src="https://github.com/user-attachments/assets/af9a009a-585b-45bc-9b1c-cd4d878e1854">

---

If a server component is included in island, does it become a client component (aka island)? What about imported packages? Will it be full hydration including bundle size of imported packages of such a component? At first I thought that only the passed props would be serialized, and things like event handlers (eg `onClick`) would be reattached in some other way than via full hydration, like regular island.

**Comment by marvinhagemeister** [comment]
Everything import in an island component via `import` statements will end up in the bundle and will be rendered on the client. Right now it's not possible to pass data from the server to the client via context. Passing functions to island props and effectively passing functions from the server to the client isn't possible either.

**Comment by predaytor** [comment]
Thx for reply!
