### ISSUE TITLE
Tailwind CSS: automatic class sorting

### ISSUE THREAD

**Issue by LearnWebGitHub** [denoland/fresh#2629]
It's usually supported by  Prettier plugin: [Automatic Class Sorting with Prettier](https://tailwindcss.com/blog/automatic-class-sorting-with-prettier), and it's extremely helpful for debugging Tailwind CSS.

Is there any solution for deno fmt to support it?

**Comment by marvinhagemeister** [comment]
No, at the moment there is no solution to sort tailwind classes with `deno fmt`. Related issue on the deno issue tracker: https://github.com/denoland/deno/issues/21617
