### ISSUE TITLE
We're on v1.7.1 not v1.6.8

### ISSUE THREAD

**Issue by adamzerner** [denoland/fresh#2633]
After https://github.com/denoland/fresh/pull/2620 we're on Fresh v1.7.1. But the docs say that 1.6.8 is the latest version.

<img width="1438" alt="Screenshot 2024-08-31 at 3 36 02 PM" src="https://github.com/user-attachments/assets/b556b185-034d-42e1-b35a-bee570b62874">

And after starting a new Fresh project and running `deno task start` I see "Fresh 1.7.1 is available. You're on 1.6.8":
```
Watcher File change detected! Restarting!

 🍋 Fresh ready
    Local: http://localhost:8000/

    Fresh 1.7.1 is available. You're on 1.6.8
    To upgrade, run: deno run -A -r https://fresh.deno.dev/update
```

**Comment by felix-schindler** [comment]
Running the update task also stays on 1.6.8 for me and doesn't actually update to 1.7.1

**Comment by eser** [comment]
same here :(

**Comment by csvn** [comment]
Same here, trying to update to `1.7.1` with `deno run -A -r https://fresh.deno.dev/update .` just goes to `1.6.8` each time.

**Comment by rempas** [comment]
> Same here, trying to update to `1.7.1` with `deno run -A -r https://fresh.deno.dev/update .` just goes to `1.6.8` each time.

Does it work now? I just tried it and it works for me
