### ISSUE TITLE
Bug: svg inside partial link leads to 404

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/fresh#2637]
Reported on Discord: https://discord.com/channels/684898665143206084/991511118524715139/1279900797932666961

> Hey, anyone experienced with fresh (partials) knows why the link with text <a> works fine while the same link placed in the same <div> but instead of text there's SVG, results in loading 404? I'm really new to the  deno and don't have a background in node either (PHP so far), so it might be a beginner thing, but I can't find a fix online...

**Comment by thegaryroberts** [comment]
Probably the same as this issue, temporary workaround in there: https://github.com/denoland/fresh/issues/2239

**Comment by marvinhagemeister** [comment]
Good point, marking as duplicate of https://github.com/denoland/fresh/issues/2239
