### ISSUE TITLE
`<textarea spellCheck={false} />` omits `spellcheck` attr (should be string `"false"`)

### ISSUE THREAD

**Issue by lionel-rowe** [denoland/fresh#2649]
Not sure whether this is a Fresh issue (@1.7.1) or upstream. `preact-render-to-string@6.5.10` (latest) _sort-of_ has the same issue, but only if you write the attr name all-lowercase in JSX, whereas Fresh has the issue even if you use camel-case (in non-island components) and _only_ has the issue for `spellCheck={false}` for island components.

FWIW, TypeScript accepts both the lowercase and camel-case variants, so presumably both should be supported.

## Non-island component in `fresh@1.7.1`

JSX | Expected | Actual | Match?
-|-|-|-
`<textarea spellCheck={true} />` | `<textarea spellcheck="true"></textarea>` | `<textarea spellcheck></textarea>` | ❌
`<textarea spellCheck={false} />` | `<textarea spellcheck="false"></textarea>` | `<textarea></textarea>` | ❌
`<textarea spellcheck={true} />` | `<textarea spellcheck="true"></textarea>` | `<textarea spellcheck></textarea>` | ❌
`<textarea spellcheck={false} />` | `<textarea spellcheck="false"></textarea>` | `<textarea></textarea>` | ❌

## Island component in `fresh@1.7.1`

JSX | Expected | Actual | Match?
-|-|-|-
`<textarea spellCheck={true} />` | `<textarea spellcheck="true"></textarea>` | `<textarea spellcheck="true"></textarea>` | ✅
`<textarea spellCheck={false} />` | `<textarea spellcheck="false"></textarea>` |  `<textarea></textarea>` | ❌
`<textarea spellcheck={true} />` | `<textarea spellcheck="true"></textarea>` | `<textarea spellcheck="true"></textarea>` | ✅
`<textarea spellcheck={false} />` | `<textarea spellcheck="false"></textarea>` | `<textarea spellcheck="false"></textarea>` | ✅

## `preact-render-to-string@6.5.10`

JSX | Expected | Actual | Match?
-|-|-|-
`<textarea spellCheck={true} />` | `<textarea spellcheck="true"></textarea>` | `<textarea spellcheck="true"></textarea>` | ✅
`<textarea spellCheck={false} />` | `<textarea spellcheck="false"></textarea>` |  `<textarea spellcheck="false"></textarea>` | ✅
`<textarea spellcheck={true} />` | `<textarea spellcheck="true"></textarea>` | `<textarea spellcheck></textarea>` | ❌
`<textarea spellcheck={false} />` | `<textarea spellcheck="false"></textarea>` | `<textarea></textarea>` | ❌

**Comment by rschristian** [comment]
Relevant: https://github.com/preactjs/preact/issues/3399 & ~~https://github.com/preactjs/preact-render-to-string/pull/388~~

I think we will remove the `spellCheck` typing altogether from Preact, it shouldn't be there. Should use lowercase.

Edit: Mixed up your examples, looks like a bug in RTS if `spellcheck` (lowercased) isn't properly supported. Will look into getting that corrected.

**Comment by rschristian** [comment]
Thanks for writing out the comparison, super helpful! Was indeed some funky inconsistencies in Preact.

https://github.com/preactjs/preact/pull/4497 fixes the types, so `spellCheck` will be invalid/an error, and https://github.com/preactjs/preact-render-to-string/pull/393 will ensure RTS handles `spellcheck`, the intended casing, properly.

**Comment by rschristian** [comment]
Try `preact-render-to-string@v6.5.11` when you have a chance, that + lower-cased `spellcheck` should fix your issues.
