### ISSUE TITLE
deno task  build is not working

### ISSUE THREAD

**Issue by phoens** [denoland/fresh#2654]
deno task start

<img width="654" alt="Screenshot 2024-09-19 at 8 30 59 AM" src="https://github.com/user-attachments/assets/1462f057-3e97-4b6f-9e3e-98ca261e6063">

But when I try to build

<img width="737" alt="Screenshot 2024-09-19 at 8 32 06 AM" src="https://github.com/user-attachments/assets/33534cf2-47b3-4068-bdbc-de1c5140190b">

Infact deno deploy (automatic one is also not working) Github action got failed saying 360 minutes exceeded

**Comment by marvinhagemeister** [comment]
Are you using Deno KV by chance or anything else that sets up long running code to listen for something?

Related https://github.com/denoland/fresh/issues/2240

**Comment by phoens** [comment]
> #2240

I am using mongo atlas (remote database). However removing database related code didn't actually help.

They portray it as a production grade, Now basic things are breaking. I just switched from react and node to here to avoid typescript config and easy configuration of SSR and react linting etc

**Comment by phoens** [comment]
> marvinhagemeister

Do you know how to debug the build issues ?

**Comment by phoens** [comment]
> Are you using Deno KV by chance or anything else that sets up long running code to listen for something?
> 
> Related #2240

Hi I fixed this issue by adding database connections inside `onListen` callback function to `defineConfig` inside `fresh.config.ts`
