### ISSUE TITLE
Feature Request -- Add fav.farm/🍋 favicon to default template

### ISSUE THREAD

**Issue by cotyhamilton** [denoland/fresh#2688]
Feature request to add [fav.farm](https://fav.farm) lemon emoji as the default favicon. 

Created by Wes Bos and built with deno, hosted on deploy, it renders emojis as favicons (and has a fallback for safari)

This also makes it easy to add a little flair on new projects without having to think too much, just change the path param

```html
<link rel="icon" href="https://fav.farm/lemon" />
<!-- or -->
<link rel="icon" href="https://fav.farm/🍋" />
```

safari fallback:

![image](https://github.com/user-attachments/assets/bac68d89-1fd8-49e3-9e27-e4565056379b)

**Comment by frou** [comment]
I don't think security-conscious projects like Deno stuff should make requests to novelty sites

**Comment by marvinhagemeister** [comment]
For the Fresh starter template we try to keep dependencies to third parties on a minimum. Starting the Fresh starter template should always work and should never have to reach out to external domains. For that reason we're not going to add a dependency in our template on `https://fav.farm`.

**Comment by cotyhamilton** [comment]
I actually didn't notice the favicon in the default template since there was no link tag in the template, I thought the project was missing one. Sorry about that!
