### ISSUE TITLE
Docs: blockquote text not parsed as markdown

### ISSUE THREAD

**Issue by mackieburgess** [denoland/fresh#2699]
👋

The text inside blockquotes isn't being parsed as markdown: this means that – in mild instances – text which should be rendered as a codespan is instead displaying with backticks, and – in severe instances – codespans containing HTML are rendering as actual HTML, instead of being escaped (examples of both below).

Will put in a PR imminently :)

<img width="731" alt="Screenshot 2024-10-10 at 13 41 24" src="https://github.com/user-attachments/assets/1b4cf993-c68b-4fac-96aa-45d2a149d1f8">

<img width="725" alt="Screenshot 2024-10-10 at 13 41 39" src="https://github.com/user-attachments/assets/92ce6736-7810-45c0-9ba4-0c68803feb01">

**Comment by monooleate** [comment]
After your recent commit, the info|warn|tip tags are still not functioning as expected. It seems that with your changes in markdown.ts, these tags will work if you modify the ADMISSION_REG constant by removing the "<" p ">" tag, like so: /^\[(info|warn|tip)\]:\s/. This adjustment should resolve the issue.

**Comment by mackieburgess** [comment]
@monooleate ah yes, I can put this in as a separate PR.

**Comment by marvinhagemeister** [comment]
Resolved with #2702
