### ISSUE TITLE
Island build fails with `"nodeModulesDir": "auto"`

### ISSUE THREAD

**Issue by adamgreg** [denoland/fresh#2701]
After moving to Deno 2.0, I have added `"nodeModulesDir": "auto"` to my config file. That leads to a failure when building the islands via dev mode of Fresh 1.7.2. There is no problem if I remove the line from the config file, and run `deno task start` with either `--node-modules-dir=auto` or `--node-modules-dir=none`. I assume that the way esbuild_deno_loader is run means that the CLI arguments have no effect, while the config file does.

I think the underlying issue may be fixed a couple of weeks ago by https://github.com/lucacasonato/esbuild_deno_loader/pull/141 . I've created a new issue to ask for another release: https://github.com/lucacasonato/esbuild_deno_loader/issues/146 . After the release, I guess Fresh 1.x will need to update its dependency.

I've tried testing by updating the esbuild_deno_loader dep in my own GitHub fork of Fresh to use a raw GitHub URL, but that fails with an unresolved relative import.

**Comment by marvinhagemeister** [comment]
Resolved by #2708
