### ISSUE TITLE
 Deno 2.0 nodeModulesDir :"auto" conflicting with true

### ISSUE THREAD

**Issue by Priyansh4444** [denoland/fresh#2715]
**Describe the bug**
While first running fresh I was given this warning:
```bash
Warning `"nodeModulesDir": true` is deprecated in Deno 2.0. Use `"nodeModulesDir": "auto"` instead
    at /PowerpointScraper/powerpoint_scraper/deno.json
```
and so I changed it accordingly to auto

But then when I tried to do go and deploy the project using deno deploy, 
in github actions I got this error
```bash
Failed deserializing config file '/PowerpointScraper/PowerpointScraper/deno.json'.

Caused by:
    invalid type: string "true", expected a boolean
   ```
**To Reproduce**

1. Start a fresh "fresh" project
2. Run using deno task start
3. Get Warning
4. Deno Deploy and deploy the project providing no github manual github actions
5. Fail the Build step because of error mentioned

**Expected behavior**

I did not expect the build step to fail
I am assuming this is something to do with a type error which could not be handled

**Screenshots**

![image](https://github.com/user-attachments/assets/ae787d5b-1530-4930-9a99-e63ff564c11e)
![image](https://github.com/user-attachments/assets/6658dbcd-9ae4-4711-b656-f9317173f27c)

**Versions**

vscode: 1.94.2 deno: 2.0.0 extension: 3.42.0

With guidance I would love to help and fix the issue since I want to contribute to this since I had a lot of fun working with deno and fresh 😄

**Comment by marvinhagemeister** [comment]
Thanks for reporting this issue. Deno Deploy currently supports Deno 1.x . Support for Deno 2 will land soon.

**Comment by arnauorriols** [comment]
The error is at the build step, previous to deploying to Deno Deploy. Deno Deploy support for 2.0 is complete, you should not expect any issue deploying your app once the build step is fixed. 

Maybe you need to upgrade the version of Deno you are installing in the previous step?

**Comment by Priyansh4444** [comment]
I have deno 2.0 installed.
Basically the recommendation I was given by deno task start, about "auto" conflicted with true, while deploying. Since the value true works on the build step if that makes sense but "auto" doesn't 
![image](https://github.com/user-attachments/assets/a061179a-ae0d-47c8-a605-5561934d556c)

**Comment by Priyansh4444** [comment]
Essentially the only thing that is conflicting is the warning, since if I did not follow the warning, the build would occur if that makes sense.

**Comment by arnauorriols** [comment]
I mean the version of Deno installed in the GH action:

![image](https://github.com/user-attachments/assets/33473ee6-676e-48c0-beac-d2f653c99641)

**Comment by marvinhagemeister** [comment]
Could it be that you're using `denoland/setup-deno@v1` instead of `denoland/setup-deno@v2` in your GitHub actions? The error message sounds like an older version of Deno is running in the CI environment.

**Comment by Priyansh4444** [comment]
I am quite unsure about that since I let the dashboard on deno make it's own yaml for github actions, thought that might be the issue!

**Comment by Priyansh4444** [comment]
I just checked the yaml file, and you are correct it is still running v1.
Is it possible to make the automatic switch to V2?

**Comment by marvinhagemeister** [comment]
yes, Fresh 1.7.3 works out of the box with Deno 2

**Comment by Priyansh4444** [comment]
Sorry for the confusion, I meant when generating the github acitons through deploy, is it automatic to change it in the github actions to v2, and thank you I think this issue is resolved now!
