### ISSUE TITLE
Warning: "nodeModulesDir": true deprecated in Deno 2.0 - Fresh project initialization

### ISSUE THREAD

**Issue by y12studio** [denoland/fresh#2721]
When initializing a new Fresh project using `deno run -A -r https://fresh.deno.dev myapp --force --tailwind --vscode --docker` with Deno 2.0.1, the following warning appears twice:

```
Warning "nodeModulesDir": true is deprecated in Deno 2.0. Use "nodeModulesDir": "auto" instead
    at file:///myapp/deno.json
```

This warning occurs once immediately after project initialization and a second time when starting the development server with `deno task start`.

**Steps to reproduce**

1. Create a new Fresh project using the following command (within a Docker container using `denoland/deno:2.0.1`):

```shell
deno run -A -r https://fresh.deno.dev myapp --force --tailwind --vscode --docker
```

2. Observe the warning.

3. Navigate to the project directory: `cd myapp`

4. Start the development server: `deno task start`

5. Observe the warning again.

**Expected behavior**

The Fresh project initialization should either:

* Automatically set `"nodeModulesDir": "auto"` in the generated `deno.json` file, preventing the warning.

https://github.com/denoland/fresh/blob/d9764e20055c2a972074c86907d8cc674b27dabc/init.ts#L635-L642

**Environment**

* Deno version: 2.0.1
* Fresh version: 1.7.3 (as indicated by the downloaded dependencies)
* OS: Linux (inside Docker container `denoland/deno:2.0.1`)

**Additional context**

The `test.sh` script used to reproduce the issue is attached below:

```shell
#!/bin/bash
docker run --rm -i denoland/deno:2.0.1 sh <<EOF
date
env
deno run -A -r https://fresh.deno.dev myapp --force --tailwind --vscode --docker
cd myapp
deno task start
EOF
```

The full output of the script showing the warnings.

```
Fri Oct 18 00:46:39 UTC 2024
HOSTNAME=1aad4b2db1c5
HOME=/root
DENO_INSTALL_ROOT=/usr/local
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
DENO_DIR=/deno-dir/
PWD=/
DENO_VERSION=2.0.1
Download https://fresh.deno.dev/
Download https://deno.land/x/fresh@1.7.3/init.ts
Download https://deno.land/x/fresh@1.7.3/src/dev/deps.ts
Download https://deno.land/x/fresh@1.7.3/src/dev/error.ts
Download https://deno.land/x/fresh@1.7.3/src/dev/mod.ts
Download https://deno.land/x/fresh@1.7.3/src/dev/imports.ts
Download https://deno.land/std@0.216.0/path/mod.ts

  ...

Download https://deno.land/std@0.208.0/path/_common/to_file_url.ts
Download https://deno.land/std@0.208.0/path/_common/glob_to_reg_exp.ts

 🍋 Fresh: The next-gen web framework. 

Let's set up your new Fresh project.

The manifest has been generated for 5 routes and 1 islands.

Project initialized!

Enter your project directory using cd myapp.
Run deno task start to start the project. CTRL-C to stop.

Stuck? Join our Discord https://discord.gg/deno 

Happy hacking! 🦕
Warning `"nodeModulesDir": true` is deprecated in Deno 2.0. Use `"nodeModulesDir": "auto"` instead
    at file:///myapp/deno.json
Task start deno run -A --watch=static/,routes/ dev.ts
Watcher Process started.
Warning `"nodeModulesDir": true` is deprecated in Deno 2.0. Use `"nodeModulesDir": "auto"` instead
    at file:///myapp/deno.json
Download https://registry.npmjs.org/tailwindcss
Download https://registry.npmjs.org/@alloc/quick-lru

  ...

Download https://esm.sh/v135/@preact/signals-core@1.5.1/X-ZS8q/denonext/signals-core.mjs

 🍋 Fresh ready 
    Local: http://localhost:8000/

```

This issue highlights a minor inconsistency between the generated `deno.json` and Deno's current recommendations.  Addressing this will improve the user experience by removing unnecessary warnings and ensuring generated projects are up-to-date with best practices.

**Comment by qingzhoufeihu** [comment]
No such warning with fresh 1.7.3 and deno 2.0.2, but I got an error on Deno  Deploy :"nodeModulesDir should be a boolean"
