### ISSUE TITLE
Fresh in a subfolder errors out

### ISSUE THREAD

**Issue by BOLL7708** [denoland/fresh#2727]
Hello! I'm trying to run Fresh in a subfolder in a bigger project, to act as the server component. I'm struggling to get that to work though, and am wondering if it is at all possible.

As soon as I drop a `deno.json` file in the root folder, one step outside the fresh folder, any way I try to run Fresh then gives me this error:
```
error: Relative import path "preact/hooks" not prefixed with / or ./ or ../ and not in import map from "https://deno.land/x/fresh@1.7.3/src/runtime/csp.ts"
    at https://deno.land/x/fresh@1.7.3/src/runtime/csp.ts:2:28
```
And I'm honestly not sure how to fix this. Is Fresh simply impossible to run in a subfolder with a different `deno.json` in the parent folder? I'm starting to think that is the case, so I should just give up and plonk all my other code inside the fresh folder. I'm trying to make this happen just to have some separation between Fresh and the rest of the codebase.

**Comment by marvinhagemeister** [comment]
Took a look into this, but I'm not able to reproduce the described error. I followed the steps on https://fresh.deno.dev/docs/examples/changing-the-src-dir and it works for me. Can you share the steps you did? Are you in a workspace?

**Comment by BOLL7708** [comment]
That works yeah! Nice 🥳 

The original plan I had was to split the config up in workspaces, but so far that has just caused me pain and suffering. What I tried to do was to make the Fresh folder a workspace, and my other code a workspace, and for them to have separate import blocks, but I guess this will work out. Should be simpler to maintain one deno.json file, although it's quite chonky now, it's a shame vanilla JSON doesn't do comments so I could section things up.

I mostly wanted to split things up so while porting my old code I wouldn't run the risk of messing up Fresh as well when adding and removing dependencies 🤣 This will have to work though, now it's time to port my project to Deno + Fresh 😁 Cheers!
