### ISSUE TITLE
markdown not rendered properly in docs

### ISSUE THREAD

**Issue by OmerDavidson** [denoland/fresh#2732]
in the docs, markdown with links are not real links
![image](https://github.com/user-attachments/assets/11788358-5a77-43bc-b8dc-07c7a51ccfa8)

the picture was taken from here: https://fresh.deno.dev/docs/getting-started/create-a-route

it happened in both chrome and firefox

**Comment by brandiqa** [comment]
It appears the issue has already been resolved:

![image](https://github.com/user-attachments/assets/3c2a06fe-d890-4f2c-a02a-282ddf05ba4e)
