### ISSUE TITLE
Deploy error on Deno Deploy

### ISSUE THREAD

**Issue by wardpoel** [denoland/fresh#275]
Hey

I tried out Fresh today and it's a cool web framework.
After hacking a small test project, I tried to deploy it on Deno Deploy.

Following error occured:
```
Error The deployment failed: Relative import path "preact" not prefixed with / or ./ or ../ and not in import map from "https://raw.githubusercontent.com/lucacasonato/fresh/main/src/runtime/csp.ts"
```

Does anyone have an idea how to fix this?

Thanks!

**Comment by lucacasonato** [comment]
Do you have your `deno.json` file set up, and referencing the `import_map.json` in the root of the project?

Do you have some code to share so I can test myself?

**Comment by JorchRL** [comment]
Hi i'm having the same error. 

I can share the project i'm attempting to deploy on Deno Deploy, if that could help. 

:D

**Comment by nhrones** [comment]
I've deployed three apps today, and have not experienced this issue?

**Comment by JorchRL** [comment]
I managed to get it deployed it by importing preact from my import_map. The problem was that it didn't come with the default import_map. (but everything worked fine with `deno task start` locally).

Browsing the files i saw that csp.ts imports from `"preact"` so i added this to the import_map.json

```
{
"imports: {

    "preact": "https://esm.sh/preact@10.8.1",
    "preact/": "https://esm.sh/preact@10.8.1/",
    "preact-render-to-string": "https://esm.sh/preact-render-to-string@5.2.0?deps=preact@10.8.1",
}
```

But now it is giving me another error on deno deploy's logs:

```
Uncaught SyntaxError: The requested module '$fresh/runtime.ts' does not provide an export named 'h'
    at file:///src/components/atoms/Header.tsx:2:10
```

I'm not sure what is going on there. But my guess that's a problem with Preact not exporting `h`?

I guess it is most likely a breaking change with fresh. So I'll reinstalling it. I started my project a couple of days ago so that may be it. 

Hopefully that helps :D

**Comment by nhrones** [comment]
Please be aware that Fresh no longer uses a cli.  The new 1.0.0-rc requires that you use ...
```
deno run -A -r https://fresh.deno.dev my-app
```
to initialize your app.  This will insure you have the correct import-map and initialization.
Please see `getting started` at https://fresh.deno.dev/

**Comment by JorchRL** [comment]
Thanks @nhrones that solved the problem for me. There were indeed a lot of differences between the version I was using and 1.0.0-rc 

Hopefully this also works for you @wardpoel 

:D

**Comment by lucacasonato** [comment]
Yes, there have been quite a few changes recently that probably broke you. This is why the warning about the framework still being unstable is still on the home page :)

There is now a pretty stable release available that I don't expect to change much (the 1.0.0-rc.3 release candidate).

**Comment by wardpoel** [comment]
I have a `deno.json` that references to `import_map.json`.
![Screenshot 2022-06-24 at 08 48 52](https://user-images.githubusercontent.com/7559956/175479377-7763b8ee-16f6-4c82-8339-9dbdfa3db6f7.png)

Anything else that could be wrong? 

Here's the project that I want to deploy: [https://github.com/wardpoel/fresh](https://github.com/wardpoel/fresh)

**Comment by nhrones** [comment]
@wardpoel 
With the most recent version of Fresh, your import map should look like this.
```
{
  "imports": {
    "$fresh/": "https://fresh.deno.dev/@1.0.0-rc.3/",
    "preact": "https://esm.sh/preact@10.8.1",
    "preact/": "https://esm.sh/preact@10.8.1/",
    "preact-render-to-string": "https://esm.sh/preact-render-to-string@5.2.0?deps=preact@10.8.1"  }
}
```
However, I would suggest that you restart your project using the instructions on the `getting started` section of https://fresh.deno.dev/

**Comment by wardpoel** [comment]
Thanks! It's working now 😄
