### ISSUE TITLE
Client side route transition support?

### ISSUE THREAD

**Issue by ukabuer** [denoland/fresh#287]
After loading the first page, every navigation to a new page will trigger a full server side rendering. It seems like Fresh doesn't have client side routing right now or did i just miss something?

And thanks for the hard work, it didn't take long for me to migrate a nextjs project to Fresh :)

**Comment by crowlKats** [comment]
Fresh is primarily a SSR framework, but does include some client side interactivity with islands; as such, I personally would say client-side routing is out of scope for fresh, and something like aleph is more appropriate if such functionality is necessary

**Comment by lucacasonato** [comment]
> It seems like Fresh doesn't have client side routing right now or did i just miss something?

Correct, all pages are server side rendered only. Only "island" components are shipped to the client to be rendered there.
