### ISSUE TITLE
Incorrect link on "Data fetching" docs page

### ISSUE THREAD

**Issue by TranquilMarmot** [denoland/fresh#298]
This page: https://fresh.deno.dev/docs/concepts/data-fetching

Links to: https://fresh.deno.dev/docs/concepts/route-handlers which gives a 404

It seems like it should maybe link to https://fresh.deno.dev/docs/getting-started/custom-handlers instead?

Also maybe the "Data fetching" page is redundant with the "Fetching data" page?

**Comment by TomLorenzi** [comment]
https://github.com/denoland/fresh/pull/331

I would agree with you
If you're right let's go for this then 😄

**Comment by TomLorenzi** [comment]
May we clause this issue since it got resolved :) ?

**Comment by lucacasonato** [comment]
Fixed
