### ISSUE TITLE
Alert or confirm in render path hangs the dev server and waits for user input in the console 

### ISSUE THREAD

**Issue by leawp** [denoland/fresh#304]
I encountered the issue when playing around with a timer with an alert and setting minutes to -1 running locally (I have the code in one of my repos)
![image](https://user-images.githubusercontent.com/6289091/176323491-4505a5ae-f187-41b9-915a-2e582a6d88f9.png)

the minimal case is the example app from the fresh init script with the following code in `index.tsx`:

![image](https://user-images.githubusercontent.com/6289091/176322338-b25bb734-e449-435d-ba55-0cb9c40afaf2.png)

![image](https://user-images.githubusercontent.com/6289091/176322311-2b02544b-91a2-4cc3-bd18-fe3e4821d87f.png)

I guess that it shouldn't wait for the user's input **in the console**.
Not sure if it's the right repo for the issue though.

`deno 1.23.1`
`fresh 1.0`

**Comment by lucacasonato** [comment]
This is working as designed. Deno implements `alert` and `confirm`. The page is server side rendered, and as such all of the component code for a given page is executed on the server when a user makes a request. If you want some code to only execute on the client (if it is in an island), wrap it in an `if (IS_BROWSER)`.

**Comment by leawp** [comment]
Oh, thank you for clarifying that. The timer code I wrote is actually on an island.
I'm closing the issue then.
Cheers.
