### ISSUE TITLE
Error while initialising a new project

### ISSUE THREAD

**Issue by mxvsh** [denoland/fresh#306]
`Deno Version: deno 1.13.2`

I just tried to initiate a new project using the command given in the blog, but I am getting this error.

![image](https://user-images.githubusercontent.com/31907722/176355078-1d78290d-efa0-4752-aea5-176d9825d916.png)

**Comment by alex1504** [comment]
The same error I encounted.
- Deno version is 1.6.1
- Platform: windows 10

When upgrade to deno 1.23.1 it works correctly.

**Comment by royletron** [comment]
@alex1504 @xencodes from what I can see there are a bunch of things that were added to Deno around v1.19 (`Error.cause` for example) that a lot of the dependant libraries use. It seems best to keep up to date with Deno's rapidly improving feature set.

**Comment by bartlomieju** [comment]
Please update your Deno to latest version (1.23.1), `fresh` doesn't support earlier version of Deno.
