### ISSUE TITLE
Error creating a route in the default project template

### ISSUE THREAD

**Issue by JoseSolorzanoC** [denoland/fresh#308]
Hello!

I've just heard about fresh and I'm just giving it a try. 

I've created a project with "`deno run -A -r https://fresh.deno.dev my-app`". Then I created an "about.tsx" file in the routes folder and added some content. While in vscode the linter is showing me this error (see image):
![image](https://user-images.githubusercontent.com/36819629/176371211-b154cf9d-f6bf-4fc9-8046-7526f1c30712.png)

As you can see, the preact import is not being used. I also have the Deno extension installed. At first the project executes without problems, as you can see in the next image:

![image](https://user-images.githubusercontent.com/36819629/176371751-72efee15-c96c-4a12-b64c-866c467d54e1.png)

But when I access the "`localhost:8000/about`" route I have the following errors:

![image](https://user-images.githubusercontent.com/36819629/176372073-2ade89c2-64dd-4c86-aad1-e96697ef3bb3.png)
![image](https://user-images.githubusercontent.com/36819629/176373582-83bd2d84-e67b-488b-a708-0ff61db97b5a.png)

I'm kinda new with Preact and Deno, and I haven't found any resources about Preact & Fresh. I have no idea of what I'm facing. This is literally my first Issue of all time, so excuse me if I made any mistake.

**Comment by xinha-sh** [comment]
@JoseSolorzanoC You need to have in your component file.

```tsx
/** @jsx h */
```
Check documentation: https://fresh.deno.dev/docs/getting-started/create-a-route

<img width="1280" alt="Screenshot 2022-06-29 at 1 00 12 PM" src="https://user-images.githubusercontent.com/107257599/176378095-6713f4aa-8837-4a85-9c40-2ec07e295b43.png">

**Comment by JoseSolorzanoC** [comment]
@xinha-sh  Omg... thank you so much. I got frustrated and I didn't saw that. The problem is solved. I'll be very careful reading the documentation from here on out.
