### ISSUE TITLE
`main.js` and `island-counter.js` 404 Not found when running in docker container

### ISSUE THREAD

**Issue by space-shell** [denoland/fresh#310]
When running fresh locally the `main.js` and the `island-counter.js` files load as expected

When running the project in a docker container using the official `denoland/deno` image the two files listed above are not found when navigating to the application.

For context, the `refresh.js` file request does succeed as expected.

**Comment by lucacasonato** [comment]
I'm going to need a little more than this. Please create a repository with a reproduction.

**Comment by space-shell** [comment]
Typical, I've been testing this all morning and it's been failing.

I spin up the same project right now and it's working just fine...

PS. Thanks for the reply
