### ISSUE TITLE
Wrong type (unknown) being inferred for context state

### ISSUE THREAD

**Issue by xinha-sh** [denoland/fresh#312]
I'm trying to instantiate Supabase client using middleware. On doing so when I'm using ``ctx.state.supabase`` type being inferred is **unknown**.

```tsx
// routes/_middleware.ts
import "https://deno.land/x/dotenv@v3.2.0/load.ts";
import {
  createClient,
  SupabaseClient,
} from "https://cdn.jsdelivr.net/npm/@supabase/supabase-js/+esm";
import { MiddlewareHandlerContext } from "https://deno.land/x/fresh@1.0.0/server.ts";

interface State {
  supabase: SupabaseClient;
}

export async function handler(
  _req: Request,
  ctx: MiddlewareHandlerContext<State>
) {
  const SUPABASE_DB_URL = Deno.env.get("SUPABASE_DB_URL") ?? "";
  const SUPABASE_ANON_KEY = Deno.env.get("SUPABASE_ANON_KEY") ?? "";
  const supabase = createClient(SUPABASE_DB_URL, SUPABASE_ANON_KEY, "");
  ctx.state.supabase = supabase;
  const resp = await ctx.next();
  return resp;
}
```

In **routes/auth/signup.tsx**

<img width="918" alt="Screenshot 2022-06-29 at 6 27 43 PM" src="https://user-images.githubusercontent.com/107257599/176442691-ab711997-2204-418e-aa3a-ba56acf153cc.png">

Upon checking the interface I found out ``Record<string, unknown>`` is causing the issue
```ts
export interface MiddlewareHandlerContext<State = Record<string, unknown>>
  extends ConnInfo {
  next: () => Promise<Response>;
  state: State;
}
```
Is there a specific reason for enforcing the input to be of type `Record<string, unknown>`` ?

**Comment by lucacasonato** [comment]
TypeScript can not infer types across files. Explicitly specify the `State` type in the second type parameter slot for `Handlers`.
