### ISSUE TITLE
Clarification for "It is also not supported to nest islands within other islands." 

### ISSUE THREAD

**Issue by abdallahmz** [denoland/fresh#313]
Hello,

Reading the documentation I was surprised to read

> [It is also not supported to nest islands within other islands.](https://fresh.deno.dev/docs/concepts/islands)

What I understood was "it is not possible to call other islands within an island" (which might be my misunderstanding of what nesting is).
The framework does seem to allow us to do so, not through passing the properties, but we can call an island in another (just like we call an island in the first place). I tested it and it seems to work, but reading the quote I wonder if it is a good idea.

TLDR:
- is calling an island from another one supported or not ?
- if it is, what is the meaning of "nesting island" in the quote ?

Thanks

**Comment by lucacasonato** [comment]
It is not supported to do this:

```
// islands/A.tsx

import B from "./B.tsx";

export default function A() {
  return <div><B /></div>;
}
```

```
// islands/B.tsx

export default function B() {
  return <h1>Hello from B</h1>;
}
```

Even if this works right now, it likely will stop working in the future. Do not rely on this behavior.
