### ISSUE TITLE
getting started - docs 

### ISSUE THREAD

**Issue by rasoulMO** [denoland/fresh#319]
"Run `deno task start` in the project directory to get started".   It’s might seemes obvious to me as experienced developer, but I think that might be confusing for beginners, 

$ deno run -A -r https://fresh.deno.dev my-project
The manifest has been generated for 3 routes and 1 islands.

Project created!
** WE NEED TO ADD THE FOLLOWING : 
`cd my-project`
** AND THEN: 
Run `deno task start`

**Comment by lucacasonato** [comment]
Happy to merge a PR for this :)

**Comment by TomLorenzi** [comment]
https://github.com/denoland/fresh/pull/330

Here it is 😄

**Comment by FloweDewolf** [comment]
[#329](https://github.com/denoland/fresh/pull/329)

I think it will be ok, I just heard about the project from Fireship from YouTube.
I am very pleased to make my first contribution ever 🔥

**Comment by rasoulMO** [comment]
[ #334](https://github.com/denoland/fresh/pull/334)

this is to complete [#329](https://github.com/denoland/fresh/pull/329)

**Comment by rasoulMO** [comment]
both [#329](url) & [#334](url) has been merged so the task completed.
