### ISSUE TITLE
render static tsx file from another microservices

### ISSUE THREAD

**Issue by lim-enhui** [denoland/fresh#332]
From project https://fresh.deno.dev

I clone 2 separated services (1 port 8000, 1 port 3000)

I intend to import remotely from another service

`import Counter from "http://localhost:3000/Counter.tsx";`

I have Counter.tsx file in the static directory that serves from port 3000. It does import the file and has rendered the page but the function for incremental and decremental state is not working.

**Comment by 0xHexE** [comment]
Interesting question. But it seems the component from the islands folder only supports client hydration.

**Comment by lim-enhui** [comment]
Then what is the difference between this and many others? Another repackaged framework? Same product different branding?

**Comment by lim-enhui** [comment]
I found the work around.
You need to import into islands directory and export it from the directory to work!

`import Counter from "http://localhost:3000/Counter.tsx";

export default Counter;
`
