### ISSUE TITLE
Standard formatting for those who want to contribute

### ISSUE THREAD

**Issue by rasoulMO** [denoland/fresh#335]
I just made my first pull request and then I realise that I had a different formatting because of my local settings, so it will  be really nice if we had a standard  formatting.

Prettier ??

**Comment by bartlomieju** [comment]
You can use `deno fmt` to format code to align with the the rest of the repo.

**Comment by lucacasonato** [comment]
Use `deno fmt`. The CI enforces this. We should probably add a CONTRIBUTING.md file...

**Comment by rasoulMO** [comment]
can we add  that  in .vscode settings  ?  to make it in the way that runs automatically  when you  commit  your changes !

**Comment by lucacasonato** [comment]
@rasoulMO Sure, I am happy to merge a PR for that.

**Comment by rasoulMO** [comment]
perfect, I'll work on this

**Comment by rasoulMO** [comment]
done on [#457 ](https://github.com/denoland/fresh/pull/457)
