### ISSUE TITLE
fresh 1.0.0 Dockerfile self-hosting auto-reload

### ISSUE THREAD

**Issue by ajf-sa** [denoland/fresh#340]
I'm try to run fresh on my server using docker 

this is my Dockerfile 
```dockerfile

FROM denoland/deno:1.23.1
WORKDIR /app
ADD ./webapp ./
RUN deno cache main.ts
CMD ["run", "--allow-net","--allow-read","--allow-env","--allow-write","--allow-run","main.ts"]

```  

docker logs 
```sh
....
Server listening on http://localhost:8000
fresh-v1  | Download https://deno.land/x/fresh@1.0.0/src/runtime/main.ts

```
I get auto-load forever !

**Comment by ajf-sa** [comment]
I set `DENO_DEPLOYMENT_ID` [deno environment variable](https://deno.com/deploy/docs/projects#environment-variables) in Dockerfile , 

```dockerfile
FROM denoland/deno:1.23.1
WORKDIR /app
ADD ./webapp ./
ENV DENO_DEPLOYMENT_ID=unique-id
RUN deno cache main.ts
CMD ["run","-A", "--allow-net","--allow-read","--allow-env","--allow-write","--allow-run","main.ts"]
```
I hope this help 👍🏽

**Comment by jheysaaz** [comment]
> I set `DENO_DEPLOYMENT_ID` [deno environment variable](https://deno.com/deploy/docs/projects#environment-variables) in Dockerfile ,
> 
> ```dockerfile
> FROM denoland/deno:1.23.1
> WORKDIR /app
> ADD ./webapp ./
> ENV DENO_DEPLOYMENT_ID=unique-id
> RUN deno cache main.ts
> CMD ["run","-A", "--allow-net","--allow-read","--allow-env","--allow-write","--allow-run","main.ts"]
> ```
> 
> I hope this help 👍🏽

This solution works fine. I suggest @alfuhigi to close this issue.
