### ISSUE TITLE
Nested middleware not being invoked

### ISSUE THREAD

**Issue by thiagomagro** [denoland/fresh#343]
Hello guys.
Im learning this amazing framework, but I cant make nested middleware works.
I have 2 _middleware.js, one in the routes folder and another in the routes/admin. The one in the admin is never invoked.
Any ideas?

**Comment by lucacasonato** [comment]
Can you create a GitHub repo with the reproduction? We have tests to ensure this should work, but maybe something with your setup is a case we did not consider.

**Comment by jcs224** [comment]
Same issue. Using latest Deno and Fresh 1.0. Here is my reproduction:

https://github.com/jcs224/fresh-middleware-issue

I'm just `console.log`-ing the before/after the `next()` method is called. In my console, after visiting `/api/joke`, I expect:

```
first
first api
first joke api
last joke api
last api
last
```

but I'm getting:

```
first
first api
last api
last
```

It seems to skip executing `api/joke/_middleware.ts`

**Comment by lucacasonato** [comment]
Thank you! #407 will fix this.
