### ISSUE TITLE
Deno Task start fails when NPM registry can't be found 

### ISSUE THREAD

**Issue by sldion** [denoland/fresh#344]
When following the first steps to run locally found [here](https://fresh.deno.dev/docs/getting-started/running-locally) . I get the following message when running `deno task start` 
```
An error occured during route handling or page rendering. TypeError: error sending request for url (https://registry.npmjs.org/esbuild-darwin-64/-/esbuild-darwin-64-0.14.39.tgz): error trying to connect: tcp connect error: Operation timed out (os error 60)
    at async mainFetch (deno:ext/fetch/26_fetch.js:287:14)
    at async fetch (deno:ext/fetch/26_fetch.js:501:9)
    at async installFromNPM (https://deno.land/x/esbuild@v0.14.39/mod.js:1707:18)
    at async install (https://deno.land/x/esbuild@v0.14.39/mod.js:1789:12)
    at async https://deno.land/x/esbuild@v0.14.39/mod.js:1800:23
```
Which is occurring cause I cannot access NPM registry when behind my company firewall.

I am unable/ don't know how to set fresh/deno to use an alternative registry that I can access behind the firewall.

**Comment by lucacasonato** [comment]
You can download the esbuild binary manually, and then use `ESBUILD_BINARY_PATH` to tell fresh to use that esbuild binary.

**Comment by lucacasonato** [comment]
Closing as this is not actionable for us.
