### ISSUE TITLE
where cookies call?

### ISSUE THREAD

**Issue by Lightnet** [denoland/fresh#345]
How to set up cookie to add and remove?

**Comment by crgeary** [comment]
To set cookies you use the `Set-Cookie` HTTP header ([MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie)).

Fresh sets HTTP headers with `res.headers.set();` where `res` is the response object. You can see an example of this on the [custom handlers](https://fresh.deno.dev/docs/getting-started/custom-handlers) page of the docs.

I've not used Fresh myself yet. I've just been curious enough to read through some of the docs, so there may be some helper methods I'm unaware of that abstract some of the complexity away.

**Comment by lucacasonato** [comment]
You can use the setCookie and getCookies methods from https://deno.land/std/http/cookie.ts.

Here is an example of setting a cookie in a POST handler: https://github.com/lucacasonato/freshworkshop/blob/main/routes/settings.tsx#L13-L24.

And here is an example of getting cookies from an incoming request:  https://github.com/lucacasonato/freshworkshop/blob/main/routes/_middleware.ts#L12

**Comment by Lightnet** [comment]
That help from the discord and this. There lack of docs how since I learn from nodejs so it different how http handle.
