### ISSUE TITLE
WebSocket support?

### ISSUE THREAD

**Issue by TheBotlyNoob** [denoland/fresh#347]
I'm trying to create a basic chat app with Fresh, but I have no clue how to use WebSockets.

**Comment by lucacasonato** [comment]
You use [`Deno.upgradeWebSocket`](https://doc.deno.land/deno/stable/~/Deno.upgradeWebSocket) in a handler function.

**Comment by Lightnet** [comment]
how to set up the handler and the location files?

**Comment by TheBotlyNoob** [comment]
thank you @lucacasonato I guess I should learn a little more about Deno.

**Comment by zoeleu** [comment]
@lucacasonato can we use this on the edge, or will edge kill the app?

**Comment by wcastand** [comment]
Sorry to bump this but was trying to use `upgradeWebSocket` in the handler but the issue is that i need to do `e.respondWith(request)` where e is
```
const conn = Deno.listen({ port: 80 });
const httpConn = Deno.serveHttp(await conn.accept());
const e = await httpConn.nextRequest();
```

but i can't access the `respondWith` so i cannot open the connection.

anyone succeeded?
