### ISSUE TITLE
Website infinitely reloads

### ISSUE THREAD

**Issue by yurtemre7** [denoland/fresh#348]
I was actively developing my new website with fresh and suddenly after some unrelated changes the production website stopped loading. I looked into the console of my server and saw this:
`Deno requests run access to "/root/.cache/esbuild/bin/esbuild-linux-64@0.14.39" Run again with --allow-run to bypass this prompt.
   Allow? [y/n (y = yes allow, n = no deny)]`

After allowing 3 times the website started to glitch, reload forever, website wasnt useable anymore. What could be the issue?
Just installed deno and fresh today, no extra dependencies besides tailwind.

My task, that I run is:
`deno run --allow-env --allow-read --allow-net main.ts`

My code is also publically available here on github: [yurtemre_deno](https://github.com/yurtemre7/yurtemre_deno).

Thanks and hopefully we will find a fix!

**Comment by bartlomieju** [comment]
What is your Deno version?

**Comment by yurtemre7** [comment]
Newest version, v1.23.2.

**Comment by bartlomieju** [comment]
I'll let @lucacasonato respond then, I've encountered similar problems but on older versions of Deno.

**Comment by lucacasonato** [comment]
@yurtemre7 To run fresh in production mode you need to set the `DENO_DEPLOYMENT_ID` environment variable. It needs to be set to a value that uniquely identifies the version of your source code (for example the current git hash).

**Comment by yurtemre7** [comment]
This still doesnt solve my issue. Can someone please look into my source code and tell me what may be wrong ?
Sadly this cool new web framework doesnt have much documentation or tutorial itself :)

**Comment by yurtemre7** [comment]
The website in question: https://www.yurtemre.de/

**Comment by nikableh** [comment]
> The website in question: https://www.yurtemre.de/

It opens and loads fine for me. Do you still have the issue?

**Comment by yurtemre7** [comment]
its really strange, its like, whenever I restart the server this reloading takes place but after a while it goes away. Might that be an external issue? Something like cloudflare?

**Comment by yurtemre7** [comment]
Issue still occurs when I rebuild my website after some changes, please look into it. 
My repo is here: [yurtemre_deno](https://github.com/yurtemre7/yurtemre_deno)
Only has reload issue after pushing to production ? idk how that works to be honest.

run via `deno task run`

**Comment by lucacasonato** [comment]
I can not reproduce this issue.
