### ISSUE TITLE
Add optional trailing slash `/` redirect behavior configuration to manifest

### ISSUE THREAD

**Issue by lorenzosignoretti** [denoland/fresh#359]
Requests that end with a trailing slash are redirected to their non-trailing slash counterpart ([source](https://github.com/denoland/fresh/blob/main/src/server/context.ts#L275-L277)).

The Fresh manifest could support a new, optional `trailingSlash` config to revert this behavior, where urls without trailing slashes were redirected to their counterparts _with_ trailing slashes `/about -> /about/`. This would exclude static assets.

This flexibility could be desirable in some cases with specific SEO needs.

Happy to look into this and open a PR if the core team greenlights the proposal!

**Comment by lucacasonato** [comment]
An option in the `start()` options bag in `main.ts` sounds good. I'd be happy to land a PR for this.

**Comment by fdemir** [comment]
I think it would be great to keep all router's config in a property called `router` in StartConfig. I can add `trailingSlashes` if it's fit for you.

**Comment by lucacasonato** [comment]
Sure, let's bikeshed the name in the PR.
