### ISSUE TITLE
Deno is not defined

### ISSUE THREAD

**Issue by vorcigernix** [denoland/fresh#372]
I am running into a weird issue. I have a very simplistic island component: https://github.com/vorcigernix/freshweb3kit/blob/master/islands/Wallet.tsx but when I include it, it reports 
```
Uncaught ReferenceError: Deno is not defined
    at island-wallet.js:13:3669
(anonymous) @ island-wallet.js:13
```
in the console and I guess it breaks SSR (because only server code is rendered). I tried to google this error message but still can't find what could be the problem here. I also added global type definition for window.ethereum, could be relevant but it all works until I use the island component.

**Comment by excessivecoding** [comment]
I think you are trying to access `Deno` in the browser (client-side) which is not possible as Deno is the server-side only.

Can you provide an example of what you where trying to achieve ?

**Comment by vorcigernix** [comment]
Thanks. I'm not though, definitely not intentionally. Could be the ethers
library issue, that's probably biggest difference between my code and
Counter.

**Comment by Lightnet** [comment]
You can used import { IS_BROWSER } from "$fresh/runtime.ts"; since I notice that server and client is being call in the console.log.

**Comment by vorcigernix** [comment]
I am using a browser check if that is a suggestion. It introduces some other problems though, the code I shared never fired the client part, perhaps breaking somewhere in a hydration process. I added the same logic to the Counter and it works as expected (quickly render loading the server message and then hydrate the content).

**Comment by vorcigernix** [comment]
The problem was indeed introduced by ethers library, my guess is that as they don't support deno, an automated transition mechanism of esm.sh replaced node calls with deno in a wrong way and that was causing what @xstevenyung mentioned - calling Deno from client. It is fixed in my codebase (for future reference).

**Comment by eeve** [comment]
![image](https://user-images.githubusercontent.com/16770728/202415206-ab11e7ad-2096-429c-a66c-1c0f58b852de.png)
![image](https://user-images.githubusercontent.com/16770728/202415339-f7ca30e2-1aac-47ad-931b-87de4241c485.png)

same problem
