### ISSUE TITLE
Misspell in the routes/api/joke.ts file.

### ISSUE THREAD

**Issue by Dequog** [denoland/fresh#383]
Hello there is a misspell in the routes/api/joke.ts file in the project generator. In the joke, "My favourite computer based band is the Black IPs," the word "favourite" is spelled wrong. It should be favorite.

**Comment by theophile-wallez** [comment]
Favorite and favourite are two variant spellings of the same word with the exact same definition. **Favorite** without the "u" is the spelling used in the United States, while **favourite** is used in the rest of the English-speaking world.
