### ISSUE TITLE
proposal: API for generating manifest manually without using $fresh/dev.ts

### ISSUE THREAD

**Issue by hyp3rflow** [denoland/fresh#384]
How about re-exporting generate and collect on `fresh/dev.ts`?
I want to regenerate the manifest file(fresh.gen.ts) manually without starting fresh server using [$fresh/dev.ts](https://github.com/denoland/fresh/blob/main/src/dev/mod.ts). 
or it will be awesome if there is simple function just collect and generate at once like below:
```typescript
import { collect, generate } from "$fresh/dev.ts";
import { dirname, fromFileUrl } from "https://deno.land/std/path/mod.ts";

async function manifest(entrypoint: string) {
  const dir = dirname(fromFileUrl(entrypoint));
  
  const manifest = await collect(dir);
  await generate(dir, manifest);
}

// this will generate manifest manually.
await manifest("./main.ts");
```

**Comment by lucacasonato** [comment]
I am happy to take a PR for this.

**Comment by anishkny** [comment]
I would like to see this as well. I took a stab at it in #908. Open to feedback.
