### ISSUE TITLE
proposal: Add option in $fresh/server.ts to know when the server will be started.

### ISSUE THREAD

**Issue by hyp3rflow** [denoland/fresh#385]
This option will be useful when you serves fresh server within other deno scripts. (ex. making desktop webview apps in deno)

Now there is a `console.log` between two asynchronous steps. processing the ServerContext(L52), and serving the server with the processed one(L58).
https://github.com/denoland/fresh/blob/3569e645a5dde7593c9538b346cef13df07593a9/src/server/mod.ts#L48-L59
So I want to propose new option in StartOptions to trigger the callback exactly before the server starts.
```typescript
export async function start( 
  routes: Manifest, 
  opts: StartOptions = {}, 
) { 
  const ctx = await ServerContext.fromManifest(routes, opts); 
  console.log( 
    `Server listening on http://${opts?.hostname ?? "localhost"}:${ 
   	  opts?.port ?? 8000 
    }`, 
  ); 
  opts.onServe?.(); // here
  await serve(ctx.handler(), opts); 
} 
```

**Comment by lucacasonato** [comment]
I suggest you just do `const ctx = await ServerContext.fromManifest(routes, opts)` yourself, and then call `serve()` yourself.

**Comment by hyp3rflow** [comment]
okay, thanks!
