### ISSUE TITLE
request doesn't resolve if you try over and over

### ISSUE THREAD

**Issue by fdemir** [denoland/fresh#388]
<img width="150" alt="image" src="https://user-images.githubusercontent.com/48316033/177043591-1c345b0c-d21b-45aa-80e3-8396671d1de1.png">
create a new project and try to refresh the page over and over. it will be stuck at the pending state and doesn't resolve the request. can someone please confirm and test it.

**Comment by lucacasonato** [comment]
This does not happen for me. What are you doing specifically? Do you have internet access?

**Comment by fdemir** [comment]
I guess It's about my browser. I couldn't understand what causes it. U can close this issue for now.
