### ISSUE TITLE
Error with helpful error when the page component is `async`

### ISSUE THREAD

**Issue by lucacasonato** [denoland/fresh#405]
See #396

**Comment by un-versed** [comment]
Actually, vscode gives us a hint about this

![Peek 2022-07-04 15-20](https://user-images.githubusercontent.com/12012284/177203293-5afc2cdc-bcfc-4d4a-9a65-d5426d963c2c.gif)

The idea is throw an error when this occours in fresh?

**Comment by lucacasonato** [comment]
Correct

**Comment by un-versed** [comment]
I'm preparing the PR, what do you think would be a good error message?
![image](https://user-images.githubusercontent.com/12012284/177205275-955c78b6-ce04-4e53-9f7a-ef48b475b6ea.png)

Maybe this?

**Comment by un-versed** [comment]
I'm preparing the PR, what do you think would be a good error message?

![image](https://user-images.githubusercontent.com/12012284/177206385-4c2870cb-cec0-4513-9846-517699553a40.png)

Maybe this?

**Comment by un-versed** [comment]
We can close this?

**Comment by lino-levan** [comment]
This should probably be closed

**Comment by iuioiua** [comment]
Closing, as this is solved.
