### ISSUE TITLE
[QUESTION] Components vs Islands

### ISSUE THREAD

**Issue by nikableh** [denoland/fresh#421]
1. Should I create a separate `/components` folder for my `.tsx` components if they are not strictly interactive like islands supposed to be? Or do I need to put such components inside `/island` directory no matter if they are interactive or not?
2. Is it a requirement for an island to be _interactive_?
3. What is considered _interactive_ in terms of islands?
4. In what way are islands _(I assume that islands are considered to be all the `.tsx` files in `/islands` directory)_ treated differently from just regular `.tsx` components? If I do this...
```tsx
/** @jsx h */
import { h } from "preact";
import MyComponent from "../some-random-directory/MyComponent.tsx";

export default function Home() {
  return (
    <MyComponent/>
  );
}
```
...how exactly it is being treated differently from this...
```tsx
/** @jsx h */
import { h } from "preact";
import MyComponent from "../islands/MyComponent.tsx";

export default function Home() {
  return (
    <MyComponent/>
  );
}
```

I did read about island architecture and somewhat understood it, so my questions are more about best practices _(or at least how people think it should be done)_ of creating an app with Fresh.

**Comment by nikableh** [comment]
It seems that what I'm asking is similar to what is discussed in https://github.com/denoland/fresh/discussions/326#discussioncomment-3058069 and proposed in https://github.com/denoland/fresh/issues/350

**Comment by nikableh** [comment]
_I suppose I should have posted this question in the discussion tab. I'm sorry._

**Comment by lucacasonato** [comment]
Components are static, islands are dynamic. They should be split across folders as such. You should never have static islands.

Interactive means you need to do some logic client side, for example `onclick`, `useEffect`, `useState` or similar.
