### ISSUE TITLE
I get an error when execute the compiled file

### ISSUE THREAD

**Issue by yuyichen** [denoland/fresh#422]
I compliled the demo in the documentation and got an executable file named 'fresh-demo'
```bash
deno compile main.ts 
```

but when I execute this file, I got an error:
```bash
./fresh-demo 
error: Relative import path "$fresh/server.ts" not prefixed with / or ./ or ../ from "file:///xxxx/fresh-demo/main.ts"
```

Did I miss something, or `fresh` haven't support this feature yet?

[deno compile command doc](https://deno.land/manual/tools/compiler)

**Comment by lucacasonato** [comment]
Fresh does not work with `deno compile`.

**Comment by yuyichen** [comment]
OK，thanks for replying. It's better to mention that in the documentation
