### ISSUE TITLE
404 page

### ISSUE THREAD

**Issue by UmbrellaCrow612** [denoland/fresh#424]
Hi

I know fresh comes with a customer error page but it requires a set up from the developer, I was wondering if:

we could have a default 404 page and if the developer wanted to change it could overwrite it by defining it themselves. 

Thoughts ?

**Comment by nikableh** [comment]
Btw, do I understand it correctly that the "default" 404 page we have now is just a blank page?

**Comment by UmbrellaCrow612** [comment]
Is development when you go to a faulty url it throws a browser error, unless you define a 404 page, was wondering if it would come with a default 404 to show like next js and allow us in both production and development.

**Comment by nikableh** [comment]
Why did you close the issue?

**Comment by UmbrellaCrow612** [comment]
I thought it might not be something to implement straight away, but if you do it’s fine.
