### ISSUE TITLE
init fresh app get wrong dir

### ISSUE THREAD

**Issue by ajf-sa** [denoland/fresh#431]
when I init app with code in Doc `deno run -A -r https://fresh.deno.dev my-app`
I get these message 
```sh

Project created!
`cd my-project` to enter to the project directory.
Run `deno task start` to start the development server.

```

my dir Name is `my-app` why I got `cd my-project` !

**Comment by fdemir** [comment]
This has already been fixed by https://github.com/denoland/fresh/pull/415

**Comment by ajf-sa** [comment]
I see .. thanks 👍🏽
