### ISSUE TITLE
Website doesn't have a 404 page

### ISSUE THREAD

**Issue by UmbrellaCrow612** [denoland/fresh#446]
Hi

On your website when you go a malformed url you are not given a 404 page error.

Just 

This fresh.deno.dev page can’t be foundNo web page was found for the web address: https://fresh.deno.dev/raw
HTTP ERROR 404

Which doesn't allow a user to navigate back home.

**Comment by lucacasonato** [comment]
PR welcome!

**Comment by UmbrellaCrow612** [comment]
Its my first time sending a PR, i have send the PR

**Comment by UmbrellaCrow612** [comment]
I managed to implement the 404 error and 500 error pages, it was done through running deno task start.
