### ISSUE TITLE
toc.json spelling mistake

### ISSUE THREAD

**Issue by UmbrellaCrow612** [denoland/fresh#454]
In the file it says
`
 ["architechture", "Architecture"],
`

But this is spelt wrong it should be 

`
["architecture", "Architecture"],
`

**Comment by UmbrellaCrow612** [comment]
As well if you where to fix this you would then get a 500 error upon visiting the page so the .MD file name is spelt wrong as well

**Comment by un-versed** [comment]
There's an open PR for this already https://github.com/denoland/fresh/pull/397

I asked @kazuma0129 for changes
