### ISSUE TITLE
Can support custom static folder?

### ISSUE THREAD

**Issue by biluohc** [denoland/fresh#460]
My static in other directory because my front-end code is a separate project

**Comment by nikableh** [comment]
That would be a nice addition. For now, I suppose you can use symlinks to achieve the same result.

**Comment by lucacasonato** [comment]
An option in the `FreshOptions` passed to `start` would be a good addition. Something along the lines of:

```
await start(manifest, { staticDir: "../frontend/dist" });
```

I'd be happy to take a PR for this.

**Comment by frostzt** [comment]
Hey @lucacasonato I have opened PR for the changes you suggested! Would you mind giving it a look!
