### ISSUE TITLE
Could add a tutorial like Remix's Joke App?

### ISSUE THREAD

**Issue by zwl1619** [denoland/fresh#463]
Could add a tutorial like [Remix's Joke App](https://remix.run/docs/en/v1/tutorials/jokes)?

**Comment by nikableh** [comment]
PR welcome!

**Comment by iamsahilsonawane** [comment]
@synalice @zwl1619 
What do we need to add a tutorial for? And in the docs?

**Comment by nikableh** [comment]
@iamsahilsonawane, I don't have any ideas on what to add, since the current documentation seems to cover everything you would need to know. You can always create a pull request if you have anything to offer.
