### ISSUE TITLE
index of a directory is prioritized over the middleware

### ISSUE THREAD

**Issue by imjamesb** [denoland/fresh#464]
For example, given a folder structure

```
index.tsx
sub/index.tsx
sub/_middleware.ts
sub/other.tsx
```

When the user navigates to /, no middlewares are run, as expected.

When the user navigates to /sub, no middlewares are run, which IMO is unexpected and most likely a bug with Fresh.

When the user navigates to /sub/other, the middleware is run as expected.

**Comment by lucacasonato** [comment]
Duplicate of #343. Use fresh 1.0.1.
