### ISSUE TITLE
Missing .gitignore file after project initialization

### ISSUE THREAD

**Issue by xyntechx** [denoland/fresh#477]
Should we add a .gitignore file to the default project generated after running `deno run -A -r https://fresh.deno.dev my-project`?

If yes, what should we include other than `.vscode`, which is generated if we enter `y` to the prompt `Do you use VS Code?`?

**Comment by iamsahilsonawane** [comment]
I don't really think there's something that needs to be added in the default .gitignore file apart from .vscode at least for the starter code. Pretty much everything, I think, needs to be added.

Though we can do one for extensions like .env and others though. 

_Needs triage_

**Comment by fdemir** [comment]
it needs definitely a `.gitignore` file. we could add some local env list like the following. also, .vscode should be added to ignore the list since it's not a must editor.
 
```
 # local env files
.env.local
.env.development.local
.env.test.local
.env.production.local
```

**Comment by xyntechx** [comment]
PR made!
