### ISSUE TITLE
Bug: does not work onChange Event  

### ISSUE THREAD

**Issue by blacktoast** [denoland/fresh#479]
this code is Input component in islands folder 
```js
/** @jsx h */
import { h } from 'preact';
import { tw } from '@twind';
import { useState } from 'preact/hooks';
import { IS_BROWSER } from '$fresh/runtime.ts';

interface InputProps {}

const Input = ({}: InputProps) => {
  const [state, setState] = useState('aa');
  const update = (e: any) => {
    setState('testtt');
  };

  return (
    <input
      onChange={update}
      value={state}
      placeholder="test"
      disabled={!IS_BROWSER}
    ></input>
  );
};

export default Input;
```
In my opinion, when it is entering the input component, the input value should be fixed as 'test' while the onChange event occurs

That's how it works in react
![Kapture 2022-07-08 at 17 18 28](https://user-images.githubusercontent.com/10705018/177949262-5929fdfc-618f-48b8-94e6-9fe74dc567a5.gif)

but in fresh framwork, it does not work this way

in fresh, it works like this video
![Kapture 2022-07-08 at 17 21 29](https://user-images.githubusercontent.com/10705018/177950254-0b8010cc-f92c-49d8-a985-314a15efa8b6.gif)

so I was wondering why fresh framework works this way ?

ps. Although I removed `disabled={!IS_BROWSER}`, it still did not work

**Comment by hyp3rflow** [comment]
It is because the fresh uses preact. Sadly, there are some differences between React and Preact.
For example,
1. Preact doesn't actually control the component. https://github.com/preactjs/preact/issues/3175
2. And you need to use `onInput` instead of `onChange` if you want to do something same as in React. https://preactjs.com/guide/v10/differences-to-react#use-oninput-instead-of-onchange

These two differences can occur a bug like this :(, If you want to avoid this, you can use `preact/compat`.
I think It will be awesome if fresh has some option for preact/compat mode. :)...

**Comment by hyp3rflow** [comment]
So, If you want to get an expected behavior, you have to write the code like this.
```typescript
/** @jsx h */
import { h } from 'preact';
import { tw } from '@twind';
import { useState } from 'preact/hooks';
import { IS_BROWSER } from '$fresh/runtime.ts';

interface InputProps {}

const Input = ({}: InputProps) => {
  const [state, setState] = useState('aa');
  const update = (e: any) => {
    setState('testtt'); // this will update the state, but sadly the state will not affect to the input value.
+	e.target.value = 'testtt'; // so you have to change the value directly
  };

  return (
    <input
+     onInput={update} // onChange → onInput
      value={state}
      placeholder="test"
      disabled={!IS_BROWSER}
    ></input>
  );
};

export default Input;
```

**Comment by blacktoast** [comment]
Wow, Thank you so much.
I got  it thanks to your explanation

**Comment by ericlery** [comment]
Is something as changed since? Do Fresh uses `preact/compat` now? Because I use onChange, and my code works.
