### ISSUE TITLE
How do you / what is the best way to add a global stylesheet?

### ISSUE THREAD

**Issue by JasperSurmont** [denoland/fresh#480]
I'm inexperienced in this environment, so sorry if this is a trivial question. I want to set a font family and other global styling things. What is the way to do this?

**Comment by nikableh** [comment]
Read https://github.com/denoland/fresh/discussions/307, https://github.com/denoland/fresh/issues/371 and https://github.com/denoland/fresh/discussions/301

**Comment by xstevenyung** [comment]
You can create a `<Layout />` component with a `<link />` pointing to a `.css` file in your `static/` folder (e.g. `/static/global.css`), which then will wrap each routes:

```css
/** /static/global.css */
body {
	margin: 0;
}
```

```tsx
/** @jsx h */
import { h, Fragment } from "preact";

// /components/Layout.tsx
export default function Layout({ children }) {
	return (
		<Fragment>
			<Head>
				<link rel="stylesheet" href="/global.css" />
			</Head>

			{children}
		</Fragment>
	)
}
```

then in each routes, you will have to wrap your routes with your `<Layout />` component:
```tsx
// /routes/index.tsx or any routes
import Layout from "../components/Layout.tsx";

export default function Index() {
	return (
		<Layout>
			<div>My content goes here</div>
		</Layout>
	);
}
```

Related: https://github.com/denoland/fresh/issues/371#issuecomment-1172915981
