### ISSUE TITLE
fresh + mysql error : WebAssembly.Compile is disallowed on the main thread, if the buffer size is larger than 4KB.

### ISSUE THREAD

**Issue by bobwatcherx** [denoland/fresh#483]
I use fresh and mysql for crud applications, but in using insert queries in fresh. and click the add button I got an error

Uncaught (in promise) ReferenceError: Deno is not defined

my syntax:

addpost.tsx
```
/** @jsx h */
import { h } from "preact";
import { useState } from "preact/hooks";
import { tw } from "@twind";
import {client} from '../connection/conn.js';


export default function Counter() {
  const addpost = async()=>{
    let result = await client.execute(`INSERT INTO users(name) values(?)`, [
  "Jessica",
]);

  }
  return (
    <div >
      <button onClick={addpost}
      >add to database</button>
    </div>
  );
}
```

my conn.js
```
import { Client } from "https://deno.land/x/mysql/mod.ts";
export const client = await new Client().connect({
  hostname: "172.17.0.1",
  username: "root",
  db: "dbxstd",
  password: "rororororoor",
});

```

**Comment by excessivecoding** [comment]
The MySQL client is a server-only library. So it's not possible to call SQL request directly from the client-side (which is what island are for).

You need to run the code in the handler function of your routes and pass down the data.

cf. https://fresh.deno.dev/docs/getting-started/custom-handlers

**Comment by bobwatcherx** [comment]
> The MySQL client is a server-only library. So it's not possible to call SQL request directly from the client-side (which is what island are for).
> 
> You need to run the code in the handler function of your routes and pass down the data.
> 
> cf. https://fresh.deno.dev/docs/getting-started/custom-handlers

I have been able to solve the error, but a new problem appears

when i fetch data from mysql database to fresh .
I have not posted data to the POST method, only the div part that I have designed
i get console browser error

_island-inputbody.js:5 Uncaught RangeError: WebAssembly.Compile is disallowed on the main thread, if the buffer size is larger than 4KB. Use WebAssembly.compile, or compile on a worker thread._

my code:
```
/** @jsx h */
import { h } from "preact";
import { Handlers, PageProps } from "$fresh/server.ts";
import {tw} from '@twind';
import {useState} from 'preact/hooks';
import {client} from '../connection/conn.js';
export const handler: Handlers= {
  async GET(_, ctx) {
    const query = await client.execute("select * from user")
    return ctx.render(query);
  },
  async POST(req,ctx){
    const newname = await req.formData();
    console.log(newname)
    return ctx.render("tolol")
  }
};

export default function InputBody({ data }: PageProps) {
    const [name,setName] = useState("");
    function addpost(){
      alert("dwdw")
    }
  if (!data) {
    return <h1>User not found</h1>;
  }
  return (
   <div
   class={tw`
    flex flex-row 
    m-3
    gap-10
    `}
   >
    <div class={tw`
      p-3
      basis-1/2
      font-bold
      `}>
      Input 
    </div>
     <div class={tw`
      p-3
      bg-grey-200
      basis-3/4
      `}>
      <input type="text"/>
    </div>
     <div class={tw`
      p-3
      bg-grey-200
      basis-3/4
      text-left
      `}>
      <button
      class={tw`
        bg-red-200
        hover:bg-purple-700
        hover:text-white
        hover:shadow-xl
        `}
      >add</button>
    </div>
   </div>

  );
}
```

**Comment by excessivecoding** [comment]
I think more context is required about your code.

As it seems like it's a different issue and not on the Fresh codebase side, could you move this to a discussion and close the issue as issues are not really made for tech question / debugging.
