### ISSUE TITLE
Manually invoke 404 page

### ISSUE THREAD

**Issue by byhemechi** [denoland/fresh#484]
As far as i can tell, there's no (documented) way of returning the global 404 page from a handler.

This is pretty much entirely an issue with dynamic routes, as the only way to have a not found page when the route matches is to return the default export from `_404.tsx` in the route's component while wrapping `ctx.render` with another response whose `status` is 200

**Comment by harrel56** [comment]
Seems like there is already PR for that [#481](https://github.com/denoland/fresh/pull/481).

**Comment by lucacasonato** [comment]
Fixed by https://github.com/denoland/fresh/pull/481.
