### ISSUE TITLE
Cannot find name `__FRSH_BUILD_ID`

### ISSUE THREAD

**Issue by lj-n** [denoland/fresh#490]
If I use the the variable `__FRSH_BUILD_ID` I get the Deno Linter Error `Cannot find name '__FRSH_BUILD_ID'. deno-ts(2304)`

```tsx
<link  rel="stylesheet" href={`/base.css?build=${__FRSH_BUILD_ID}`} />
```
It works like expected, but is there a way to get rid of this error without using `// deno-lint-ignore`?

**Comment by lucacasonato** [comment]
You shouldn't use this variable. Use the `asset` function from `$fresh/runtime.ts` instead like explained in https://fresh.deno.dev/docs/concepts/static-files. It will add a cache busting query parameter automatically, and even improve cache performance for the static asset.
