### ISSUE TITLE
Update documentation to include info about _app.tsx

### ISSUE THREAD

**Issue by harrel56** [denoland/fresh#491]
I'm guessing that lack of such information in docs is not intentional. There are many issues being created asking how to modify html template. Docs should contain complete example how to achieve this using special `<Head>` component.

**Comment by harrel56** [comment]
Created PR for that #494

**Comment by lucacasonato** [comment]
The reason this is not documented yet, is that I am contemplating ripping out `_app.tsx` in favor of a more customisable layouts system that let's you layer layouts, and supports changing the HTML document in it's entirety.

**Comment by hashrock** [comment]
Merged documentation about _app.tsx. Hopefully it will be replaced by a Layout system in the near future.
