### ISSUE TITLE
Using static CSS in Fresh

### ISSUE THREAD

**Issue by tsklxiv** [denoland/fresh#492]
Hi there!

I am building a website for my classless CSS style, [Subreply CSS](https://github.com/HoangTuan110/subreply-css).

As such, I wanted to use the CSS to style the website, but I can't find any way to use them in Fresh. Is there any way to import a static CSS file into Fresh?

**Comment by harrel56** [comment]
Hope it helps: https://github.com/denoland/fresh/issues/476#issuecomment-1179442271

**Comment by EdAyers** [comment]
Working example to save some comment trawling: 

Put your stylesheet (eg `mystyles.css`) in `static/`, and put this in `routes/_app.tsx`.

```tsx
// routes/_app.tsx
/** @jsx h */
/** @jsxFrag Fragment */
import { Fragment, h } from "preact";
import { Head, asset } from "$fresh/runtime.ts";
import { AppProps } from "$fresh/server.ts";

export default function App(props: AppProps) {
  return (
    <>
      <Head>
        <link href={asset('/mystyles.css')} rel="stylesheet"/>
      </Head>
      <props.Component />
    </>
  );
}
```

I couldn't find any docs for `_app.tsx`, I guess it is where you put the top level wrapper for your pages?

**Comment by harrel56** [comment]
> I couldn't find any docs for _app.tsx, I guess it is where you put the top level wrapper for your pages?

Yes, `routes/_app.tsx` is correct. As for docs there is issue for that #491

**Comment by lucacasonato** [comment]
Closing as this seems resolved.
