### ISSUE TITLE
Any way to send a HTTP 103 Early Hints response to start preloading images before the normal 200 response?

### ISSUE THREAD

**Issue by FredslundMagnus** [denoland/fresh#497]
It might already be possible, I just couldn't find any example or documentation.

https://github.com/bashi/early-hints-explainer/blob/main/explainer.md

I currently have something like this:
```tsx
import { asset, Head } from "$fresh/runtime.ts";

<Head>
    <link rel="preload" as="image" href={asset(data.image)}></link>
    ...
</Head>
...
<img src={data.image} />
```
However it does not start to load the image before the server is done with the full response, and the browser has received the html.

**Comment by lucacasonato** [comment]
You can't. Deno does not support multiple responses to a single HTTP request.
