### ISSUE TITLE
Uncaught Error: Handle not valid. (os error 6)

### ISSUE THREAD

**Issue by Bellisario** [denoland/fresh#504]
I ran the command to create a Fresh project but I see this error:

```bash
Do you want to use 'twind' (https://twind.dev/) for styling? [y/N] error: Uncaught Error: Handle non valido. (os error 6)
    at Object.opSync (deno:core/01_core.js:170:12)
    at readSync (deno:runtime/js/12_io.js:94:24)
    at Stdin.readSync (deno:runtime/js/40_files.js:167:14)
    at readLineFromStdinSync (deno:runtime/js/41_prompt.js:55:23)
    at confirm (deno:runtime/js/41_prompt.js:29:20)
    at https://deno.land/x/fresh@1.0.1/init.ts:79:5
```

How can I solve? I'm using Windows 7 (service pack 2) with Deno 1.23.3 and I tried both CMD and Git Bash to make sure this was not a terminal issue. Seems the problem occurs after all script downloads and just when asking to use "twind" for styling.

**Comment by lucacasonato** [comment]
Deno does not officially support Windows 7. Please use a newer version of Windows.

**Comment by Bellisario** [comment]
Ok, sorry I didn't know, maybe because I installed manually using the .zip release nothing warned me... I didn't find anyway any notice neither from deno.land nor GitHub releases...

Anyway, for who is using Windows 7, too, seems the `confirm` built-in function is broken (this is the only broken thing I found) and I solved just by passing manually `--vscode=true` and `--twind=false` args (in my case).
