### ISSUE TITLE
This is amazing, is there a repository with example projects?

### ISSUE THREAD

**Issue by kyle-ssg** [denoland/fresh#506]
I decided to give this a try and within 5 minutes I got it working with my isomorphic feature flag library (which happened to have an es module!). I'm actually amazed at how simple and fast it is, going to be learning a lot more about this.

Do you plan on hosting a repository or section within the documentation where there are examples? I'd be happy to flesh out and offer up mine https://github.com/Flagsmith/flagsmith-js-client/tree/main/examples/deno-fresh. 

One of the reasons I ask is that the example around data fetching in the docs wasn't super clear about where Handlers / PageProps come from and I instinctively went looking for examples.

**Comment by lj-n** [comment]
There is a [chat platform template](https://github.com/denoland/showcase_chat) which uses fresh and supabase

**Comment by lucacasonato** [comment]
There are currently not too many good examples. We're working on a "Showcase" section on the website with a bunch of real websites using Fresh. For now, a curated list:

The deno.land website uses most features of Fresh: https://github.com/denoland/dotland

The fresh website also uses fresh, but is not as advanced: https://github.com/denoland/fresh/tree/main/www

My personal website is much simpler, and does no dynamic data fetching: https://github.com/lucacasonato/luca

This repo for a workshop about fresh that I gave uses middleware, data fetching, and islands:  https://github.com/lucacasonato/freshworkshop

A chat application that our team built using Fresh: https://github.com/denoland/showcase_chat

**Comment by kyle-ssg** [comment]
Thanks for the info!
