### ISSUE TITLE
How to make an redirect?

### ISSUE THREAD

**Issue by the-man-with-a-golden-mind** [denoland/fresh#507]
Hello, I have to make redirect for auth process. 
Is it possible with fresh? I can not find anything in the Fresh documentation about that.

Best,
MM

**Comment by lj-n** [comment]
You can return a Response with a Location header in your handler functions:
```ts
export function handler(req: Request): Response {
  // ...
  const headers = new Headers({
    location: new URL(req.url).origin,
  });
  return new Response(null, {
    status: 302,
    headers,
  });
}
```

Hope this helps.
