### ISSUE TITLE
JS version

### ISSUE THREAD

**Issue by ivan-kobzar** [denoland/fresh#51]
Do you guys plan to add a pure JS version?

**Comment by lucacasonato** [comment]
@ivan-kobzar What do you mean? `fresh` can be used with JS only. You do not need to be familiar with TypeScript. Anywhere you can use a `.ts` file, you can also use a `.js` file.

**Comment by ivan-kobzar** [comment]
@lucacasonato Oh sorry, didn't notice that, thank you!
