### ISSUE TITLE
How do you use preact refs in fresh?

### ISSUE THREAD

**Issue by wyvernbw** [denoland/fresh#515]
Hello! I was trying to use refs in preact as stated in their documentation [here](https://preactjs.com/guide/v10/refs). They use the `createRef() ` function but I cannot find an import for it. In the fresh docs they use `import ... from 'preact/hooks'` so I tried to import `'preact/ref'`, `'preact/refs'`, `'preact/references'` but none of these work. Am I missing something?

**Comment by elianiva** [comment]
`createRef` also comes from `preact`, so you can just do `import { createRef } from "preact"`

**Comment by wyvernbw** [comment]
Ohh okay tysm, should have tried that first.
