### ISSUE TITLE
Render page as an SVG file

### ISSUE THREAD

**Issue by samarkandiy** [denoland/fresh#530]
I have a code that is supposed to generate an SVG image. But when I add the code it includes document tags as well.

    ` /** @jsx h */
    import { h, Fragment } from "preact";
    import { PageProps } from "$fresh/server.ts";
    
    export default function City(props: PageProps ) {
      
      const city = props.params.city.toLowerCase().replace(/-|\s/g," ").replace(/\b(\w)/g, s => s.toUpperCase());
      
      return <svg height="30" width="200">
                      <text x="0" y="15" fill="#111111">{city}</text>
                </svg>
      
    } `

How can I render the image as an SVG file?

I'm adding the code above in the routes/[city]/ folder, the file name is featured-image.tsx For example, if the city name is Miami, the URL looks like the following localhost:8000/miami/featured-image

**Comment by excessivecoding** [comment]
This is a pretty special case, but it was fun to hack out.

If you just specify a default page component, Fresh is going to assume we want to render it inside the default document.

You need to work with the handler in the case to specify the `Content-Type` and "bypass" the default rendering

Here and example while still keeping the JSX syntax:

```tsx
/** @jsx h */
import { h } from "preact";
import { renderToString } from "preact-render-to-string";
import { Handlers } from "$fresh/server.ts";

export const handler: Handlers = {
  GET(_req, ctx) {
    return new Response(
      renderToString(
        <svg
          height="30"
          width="200"
          fill="none"
          xmlns="http://www.w3.org/2000/svg" // You need to specify this, otherwise, it's not consider a valid SVG to serve
        >
          <text x="0" y="15" fill="#111111">Paris</text> // Change your text here
        </svg>,
      ),
      {
        headers: { "Content-Type": "image/svg+xml" }, // Don't forget to specify the Content-Type to indicate what file format is expected to the browser
      },
    );
  },
};
```

**Comment by samarkandiy** [comment]
It worked, thanks @xstevenyung !
