### ISSUE TITLE
"_frsh/refresh.js"  and "_frsh/alive"   How to remove in production

### ISSUE THREAD

**Issue by Link-Kou** [denoland/fresh#535]
<img width="952" alt="image" src="https://user-images.githubusercontent.com/22113151/180586082-50993b59-3a5b-481c-b037-a5fac4c91ac3.png">

**Comment by ZackarySantana** [comment]
Happening for me too-- messing up my lighthouse reports

**Comment by ZackarySantana** [comment]
Looking at some relevant issues, maybe https://github.com/denoland/fresh/issues/84 is similar?

**Comment by Link-Kou** [comment]
@ZackarySantana  Thanks for your response.

Because I'm a beginner
I don't know how to set env

**Comment by christiankozalla** [comment]
I've defined another `task` in `deno.json` to run Fresh in production. In order to enter production mode, you need to specify an environment variable `DENO_DEPLOYMENT_ID` while running `main.ts`.

I've decided to use the hash of the latest git commit. So here is my `task` for `deno.json`

```json
{
  "tasks": {
    "start": "deno run -A --watch=static/,routes/ dev.ts",
    "production": "DENO_DEPLOYMENT_ID=\"$(git rev-parse HEAD)\" deno run -A main.ts"
  },
  "importMap": "./import_map.json"
}
```

Run the task with `deno task production`

**Comment by thegaryroberts** [comment]
> I've defined another `task` in `deno.json` to run Fresh in production. In order to enter production mode, you need to specify an environment variable `DENO_DEPLOYMENT_ID` while running `main.ts`.
> 
> I've decided to use the hash of the latest git commit. So here is my `task` for `deno.json`
> 
> ```json
> {
>   "tasks": {
>     "start": "deno run -A --watch=static/,routes/ dev.ts",
>     "production": "DENO_DEPLOYMENT_ID=\"$(git rev-parse HEAD)\" deno run -A main.ts"
>   },
>   "importMap": "./import_map.json"
> }
> ```
> 
> Run the task with `deno task production`

This is a really nice solution, I had almost the same prod task (for locally testing/lighthouse) and didn't realise the caching implications of not including a dynamic variable for the ID. @christiankozalla as the source of genius I think you should propose this be added to the docs (possibly even the framework init process, if we're all going to be doing it).
