### ISSUE TITLE
How to debug project using Webstorm ?

### ISSUE THREAD

**Issue by Link-Kou** [denoland/fresh#537]
I use WebStorm，The deno plug-in is installed。
Click the Debug button，It doesn't debug。

**Comment by Link-Kou** [comment]
"startDebug": "deno run -A --inspect-brk --allow-read --allow-net --watch=static/,routes/ dev.ts"

Why？    

error: The argument '--inspect[=<HOST:PORT>...]' cannot be used with '--watch[=<FILES>...]'

The page is not refreshed in Debug mode

**Comment by ClientCrash** [comment]
Please update your title to something like `How to debug project using Webstorm?`. This will helpt you reach the people that can answer this question.

**Comment by ahuigo** [comment]
```
error: The argument '--inspect[=<HOST:PORT>...]' cannot be used with '--watch[=<FILES>...]'
```
Remove the `--watch` as following:
```
deno run -A --inspect-brk   dev.ts
```
Inspect mode is not compatible with `--watch`.
If you reload your project, inspect mode would be interrupted. 
In fact, every time you re-debug **dev.ts**, your project is refreshed.
