### ISSUE TITLE
Multiple middleware per route

### ISSUE THREAD

**Issue by jcs224** [denoland/fresh#549]
I wonder if it would be feasible to instantiate multiple middlewares for a single route, instead of just a single `_middleware.ts` file.

For example, in Oak, you can stack an infinite number of middlewares for a single route, or a subset of routes.

My main use-case is to authenticate a route, the authentication middleware depends on a session middleware. Like, if I could export more than one handler per `_middleware.ts`...

```ts
import { MiddlewareHandlerContext } from "$fresh/server.ts";

interface State {
  data: string;
}

export async function handler(
  req: Request,
  ctx: MiddlewareHandlerContext<State>,
) {
  console.log('boot up a session')
  const resp = await ctx.next()
  console.log('clean up session')

  return resp;
}

export async function handler2(
  req: Request,
  ctx: MiddlewareHandlerContext<State>,
) {
  console.log('authenticate route, depends on session')
  const resp = await ctx.next()
  console.log('tear down auth')

  return resp;
}
```

I guess the reason I would do this, is because I don't want to split up the before/after middleware manually. This is how I'd handle it now, splitting all my code into before and after `next()`:

```ts
import { MiddlewareHandlerContext } from "$fresh/server.ts";

interface State {
  data: string;
}

export async function handler(
  req: Request,
  ctx: MiddlewareHandlerContext<State>,
) {
  console.log('boot up a session')
  console.log('authenticate route, depends on session')
  const resp = await ctx.next()
  console.log('tear down auth')
  console.log('clean up session')

  return resp;
}
```

**Comment by ahuigo** [comment]
I think there are many ways to implement this

## Method 1: put multiple middleware file like this
Refer to [middleware-layer](https://github.com/denoland/fresh/tree/main/tests/fixture/routes/layeredMdw/layer2/layer3).

```
/routes/_middleware.ts
/routes/layer2/_middleware.ts
/routes/layer2/layer3/_middleware.ts
/routes/index.ts
```
Sine we may have to write our own **url-pattern**, it is a bit cumbersome to implement.

> Note:  The order of middleware files depends on the `sortRoutes(middlewares)` https://github.com/denoland/fresh/blob/7e2ab7fa50585d0848f2d157c85f789bbf648ab4/src/server/context.ts#L190

## Method 2: wrap your middleware
e.g.
```
export async function handler(
  req: Request,
  ctx: MiddlewareHandlerContext<State>,
) {
  console.log('boot up a session')
  const resp = await handler2(req, ctx) // wrap handler2
  console.log('clean up session')

  return resp;
}

export async function handler2(
  req: Request,
  ctx: MiddlewareHandlerContext<State>,
) {
  console.log('authenticate route, depends on session')
  const resp = await ctx.next()
  console.log('tear down auth')

  return resp;
}
```

## Method 3: use merge handler 
For example:

```
import { mergeHandler } from "$fresh/server.ts";
export const handler=mergeHandler(logHandler, corsHandler)
// or
const handlers = [logHandler, corsHandler]
export const handler=mergeHandler(...handlers)
```
I've made a pr which provides such a `mergeHandler` in https://github.com/denoland/fresh/pull/553/files#diff-aa1ebf8512a841257157b5a3999711cd571235092191c1706ba4297460781c66

```ts
import { MiddlewareHandlerContext } from "$fresh/src/server/types.ts";
type Handler = (req: Request, ctx: MiddlewareHandlerContext) => Promise<Response>

// Merge middleware handlers
export function mergeHandler(...handlers: Handler[]) {
  return (_req: Request, ctx: MiddlewareHandlerContext) => {
    const ihandlers = [...handlers]
    const hctx:MiddlewareHandlerContext = new Proxy(ctx, {
      get: function(oriobj, prop: keyof MiddlewareHandlerContext) {
        if(prop=="next"){
            const handler = ihandlers.shift();
            if(handler){
              return () => {
                return handler(_req, hctx);
              } 
            }
        }
        return oriobj[prop]
      }
    });
    return hctx.next()
  }
}
```

**Comment by jcs224** [comment]
Nice, thanks! I tried the first two methods, method 2 worked, method 1 did not. When I renamed the middleware files with 1 and 2 in front, neither middleware fired.

Honestly, method 2 will probably work for my needs. Thanks again!

**Comment by ahuigo** [comment]
@jcs224 Sorry for my mistake. I have fixed the error in method 1.

You could also custom a `mergeHandler()` as method 3. https://github.com/denoland/fresh/pull/553/files#diff-aa1ebf8512a841257157b5a3999711cd571235092191c1706ba4297460781c66
