### ISSUE TITLE
Clearer error handling

### ISSUE THREAD

**Issue by shelbyd** [denoland/fresh#556]
Error pages should allow both specifying any error code `routes/_403.tsx`, etc. and allow being route specific `routes/user/_403.tsx` vs the single global `routes/_403.tsx`. The error resolver can search the directory for the route and recurse up the parents until a handler for the error code can be found. 

To specify an error code, applications should be able to `throw new FreshError(403, { data })` that is passed to the corresponding error handler. Additionally, Fresh could provide named constants for these codes.

**Comment by marvinhagemeister** [comment]
This is resolved with the upcoming Fresh 2 release. There you can use a `_error.tsx` template where all errors are routed to and can be handled in any way necessary.
