### ISSUE TITLE
What about i18n, l10n and multiple apps in a single project/workspace?

### ISSUE THREAD

**Issue by XO39** [denoland/fresh#559]
As much as we'd like Deno in our forntend application, but the lack of a good enough frame work was a showstopper for us.

We were just getting ready for ditching Vue from our three main websites in favor of Angular, When we knew about Fresh, we have our eyes on it way before v1.0.0 was released.

With the release of v1.0.0, we started experimenting the frame work and see how it can fit our needs.

Two issues arose in front of us:
- Our websites are all multilingual, and
- We need to share our core libraries between apps, the way it's don't with Angular (that's why we considered Angular in the first place.

My questions _(as you might have guessed)_:
- Is there any plan to support i18n natively? Or should we find one ourselves?
- Is there any easy way (documentations, guides, etc...) for having multiple apps sharing the some shared libraries and packages? Is that even possible with the current state of Fresh? Is there any plan regrading this?

We might live without the second issue, but the first one is a real issue for us.

**Comment by lucacasonato** [comment]
Yes, i18n will be supported natively at some point (roadmap: #563). But it is not a short term priority, so don't wait for it. If you want something right now, you'll have to set it up yourself.

**Comment by marvinhagemeister** [comment]
Merging this issue into https://github.com/denoland/fresh/issues/666 which seems to have more eyeballs.
