### ISSUE TITLE
Updating Fresh.

### ISSUE THREAD

**Issue by acktax** [denoland/fresh#569]
As someone entirely new to web dev as a whole. Updating Deno is a piece of cake, but how would one update Fresh on an already started project?

Thank you all for the amazing framework, I enjoy learning with it a lot.

As a side note is there any good resources for someone entirely new to learn all these concepts in react/preact and tailwind/twind?

**Comment by lucacasonato** [comment]
There is currently no documentation for this, but essentially you update the version number inside of your `import_map.json`.

```diff
-   "$fresh/": "https://deno.land/fresh@1.0.1/",
+   "$fresh/": "https://deno.land/fresh@1.0.2/",
```
