### ISSUE TITLE
Parameters are not decoded

### ISSUE THREAD

**Issue by rojvv** [denoland/fresh#577]
`PageProps.params.someparameter` is URL encoded, should not be.

**Comment by keremh** [comment]
hi can i work on this issue?

**Comment by rojvv** [comment]
I don't think you need a question. I would've been working on it if I had time. Just create a PR with this description: Closes #577.

**Comment by rojvv** [comment]
This will be fixed when we update the deps after the next https://github.com/denosaurs/rutt release 🎉
