### ISSUE TITLE
Error middleware

### ISSUE THREAD

**Issue by yereby** [denoland/fresh#586]
Hi,
I would like to plug an error middleware. I have this in `routes/_middleware.ts` :

```js
export async function handler(
  request: Request,
  ctx: MiddlewareHandlerContext<State>,
) {
  try {
    return await ctx.next();
  } catch (error) {
    console.debug(error);
  }
}
```

But when i throw an error from another route, it is not catched here

**Comment by lucacasonato** [comment]
Interesting use case. Currently handler errors are transformed into a _500 page before `ctx.next()` returns. I'll have to think if I think this should be changed.

**Comment by excessivecoding** [comment]
I think this becomes mandatory for services like Sentry, etc. which rely on catching error globally across the app

**Comment by OldManFroggy** [comment]
I also agree that treating all handler errors as a 500 error is not the best way for a lot of production apps, keeping a default of 500 is fine (and required for backward compatibility), however an override/trap in a handler to allow a developer to handle errors in a handler in custom way if needed would be very helpful in quite a efw use cases, especially those that work with data from multiple locations and need a sane/clean fallback for example.

**Comment by timfish** [comment]
It's currently possible to catch errors via `onError` passed to `start`:
```ts
import { start } from "$fresh/server.ts";
import manifest from "./fresh.gen.ts";

await start(manifest, {
  onError: (error) => {
    // do something with the error here...
    return new Response("Internal Server Error", { status: 500 });
  },
});
```

`serve` catches errors by default and reports them via [this default](https://github.com/denoland/deno_std/blob/ebeecacd61b8829f52fc6ae947c76a2d7daeda2e/http/server.ts#L87-L91) `onError` handler.

I've brought this up before because catching errors by default seems sub-optimal. It was explained that errors are caught and reported via `onError` because uncaught errors cause the process to terminate. The issue with the process terminating on error is that any other open connections will be closed!

**Comment by martpet** [comment]
`onError` doesn't seem to work for me. I check errors in `_500.tsx` and redirect with a `<meta>` tag if needed.

**Comment by deer** [comment]
@crowlKats, are you aware that you resolved this with https://github.com/denoland/fresh/pull/1123? I recently made some middleware changes, and I thought this would be a good next issue. Imagine my surprise when my test started passing with no changes...

🕵️  mode active: I checked out some commit from last August, and the test sure enough fails. Ok, so when did it start passing? In https://github.com/denoland/fresh/commit/4d8b59fa28c6aee2ef0bdb31f98e675f8b3fc041 it's still failing, but the next commit (https://github.com/denoland/fresh/commit/9dd026e0f50ee79c5f8e2b2464d0a85c3a60fd8c) causes it to start passing.

How do we feel about this in July of 2023? Last August, Luca wasn't sure whether we should have this functionality. I can happily add my test to ensure that this functionality isn't inadvertently regressed. I could also document this somewhere, if we want this to be well known.

FYI my test looks like this:
```ts
Deno.test({
  name: "middleware error",
  fn: async () => {
    const resp = await handler(
      new Request(
        "https://fresh.deno.dev/middleware-error-handler",
      ),
    );
    assert(resp);
    assertEquals(resp.status, Status.InternalServerError);
    const body = await resp.text();
    assertStringIncludes(
      body,
      "500 internal error: this is a basic error which gets rendered in the _500 page",
    );
  },
});
```
```ts
//routes/middleware-error-handler/_middleware.ts
import { MiddlewareHandlerContext } from "$fresh/server.ts";

export async function handler(
  _req: Request,
  ctx: MiddlewareHandlerContext,
) {
  try {
    ctx.state.flag = true;
    return await ctx.next();
  } catch (error) {
    console.log("we've caught the error: " + error);
    throw Error("this is a basic error which gets rendered in the _500 page");
  }
}
```
```tsx
//routes/middleware-error-handler/index.tsx
import { Handlers, PageProps } from "$fresh/server.ts";

export const handler: Handlers = {
  GET(req, ctx) {
    return ctx.render(ctx.state.flag);
  },
};

export default function Home(props: PageProps<boolean>) {
  if (props.data) {
    throw Error("i'm erroring on purpose");
  }
  return <div>this won't get shown</div>;
}
```
