### ISSUE TITLE
Complex URL patterns 

### ISSUE THREAD

**Issue by BobCarver** [denoland/fresh#587]
The documentation needs to up updated from:

// routes/x.ts

import { RouteConfig } from "$fresh/**runtime.ts**";

const config: RouteConfig = {
  routeOverride: "/x/:module@:version/:path*",
};

to
import { HandlerContext, RouteConfig } from "$fresh/**server.ts**"; // update path

**export** const config: RouteConfig = { // must be exported
  routeOverride: "/api/db/:resource(jobs?|bar)/:id(\\d+)?", // example using a more complex pattern
};

Also when I tried to perform deno test.  The test cases failed with many TS2300 [ERROR]:.  The solution for me was to add the following to the test code.
```
/// <reference no-default-lib="true"/>
/// <reference lib="dom" />
/// <reference lib="deno.ns" />
/// <reference lib="deno.unstable" />
```

**Comment by JacobWeisenburger** [comment]
> ```ts
> import { RouteConfig } from "$fresh/server.ts"
> export const config: RouteConfig = {
>    routeOverride: "/api/db/:resource(jobs?|bar)/:id(\d+)?", 
> };
> ```

I don't really understand how this route config is supposed to work. I have tried the following routes and they don't work.
- http://localhost:8000/api/db/bar/1
- http://localhost:8000/api/db/jobs/1
- http://localhost:8000/api/db/job/1

![image](https://user-images.githubusercontent.com/31667350/198060556-568ff090-6600-44b1-ba64-44e926e22f31.png)

Am I doing something wrong?

**Comment by JacobWeisenburger** [comment]
I think I figured it out. You are missing a `\`. `(\d+)` should be `(\\d+)`.


So the whole thing should be:
```ts
import { RouteConfig } from "$fresh/server.ts"

/**
example route matches:
- /api/db/bar/1
- /api/db/jobs/1
- /api/db/job/1
*/ 
export const config: RouteConfig = {
   routeOverride: "/api/db/:resource(jobs?|bar)/:id(\\d+)?", 
};
```
