### ISSUE TITLE
Debug using preact

### ISSUE THREAD

**Issue by gmunumel** [denoland/fresh#611]
Hello, 

I'm new with Deno, but not with Node.js. I started a small project using fresh framework and I'd like to know the best way to debug **Preact**. 

In **Preact** [documentation](https://preactjs.com/guide/v10/debugging/#installation) mention a google chrome extension and `import("preact/debug")` which I couldn't make it work. 

Also try with `--inspect-brk` which works for code but doesn't provide information of states, components, etc, in **Preact**. 

This is my **dev.ts** file: 

```typescript
#!/usr/bin/env -S deno run -A --watch=static/,routes/

import("dotenv");
if (Deno.env.get("ENV") === "DEV") {
  import("preact/debug");
}

import dev from "$fresh/dev.ts";

await dev(import.meta.url, "./main.ts");
```

But doesn't seem to work. Also added at the beginning of **main.ts** file with same result. 

Any advice?

**Comment by moonstripe** [comment]
I'm having a similar issue.
