### ISSUE TITLE
www: missing search functionality

### ISSUE THREAD

**Issue by michael-pfister** [denoland/fresh#617]
As a developer who previously read the [fresh docs](https://fresh.deno.dev/docs/introduction), I sometimes need to look something up that I don't recall the chapter of. Which usually results in me spending 5min searching through the docs.

I think that adding a search bar similar to what you'd find on https://twind.dev/handbook/introduction.html or https://deno.land/manual would significantly improve the user experience.

**Comment by lucacasonato** [comment]
I agree. I'll look into adding Algolia DocSearch

**Comment by lino-levan** [comment]
@lucacasonato Any updates?

**Comment by hashrock** [comment]
implemented by https://github.com/denoland/fresh/pull/949
