### ISSUE TITLE
Unexpected non-whitespace character after JSON at position 3 on deno deploy

### ISSUE THREAD

**Issue by berkaycimsir** [denoland/fresh#619]
I am using deno deploy to deploy my app and i am getting an error like this when i opened the logs tab

It works fine on my local

I checked environment variables but all of them comes correctly. 
I am using mongodb as database.

[repo](https://www.github.com/berkaycimsir/fresh-todos)
 [live url](https://berkaycimsir-fresh-todos.deno.dev/)

when i go the [live url](https://berkaycimsir-fresh-todos.deno.dev/) index page it gives an error but when i go to  [liveurl/api/users](https://berkaycimsir-fresh-todos.deno.dev/api/users) data comes successfully

<img width="1347" alt="Screen Shot 2022-08-14 at 01 49 04" src="https://user-images.githubusercontent.com/47090177/184515814-2faa3471-1f96-4647-9e1d-534a8e71098f.png">

**Comment by BeezBeez** [comment]
Hey ! How did you solved this issue ? I have the same problem right now.
Thank you ! 🙏
