### ISSUE TITLE
ctx.renderNotFound Not found in the release 

### ISSUE THREAD

**Issue by EduM22** [denoland/fresh#636]
[Error docs](https://fresh.deno.dev/docs/concepts/error-pages) points to the new ctx.renderNotFound() render function, but the latest release is older then the pull to add it. 

So someone with release access needs to create a new, so that new users to fresh can use the framework according to the docs

**Comment by irvanmalik48** [comment]
if you like the thrill of using the main branch of fresh for your project, here's a link for you to put in the import map for fresh <https://cdn.jsdelivr.net/gh/denoland/fresh@main/>

**Comment by irvanmalik48** [comment]
otherwise you could wait for the next release
