### ISSUE TITLE
Add document for lang setting

### ISSUE THREAD

**Issue by hashrock** [denoland/fresh#638]
It can be changed by setting `ctx.lang = "en"` in `main.ts`, but it is better to mention it in the documentation.

- Create FAQ section
- or, explicitly specify lang="en" in a generated main.ts

**Comment by vjdv** [comment]
I'm getting `ctx is not defined`, do you have an example?

**Comment by hashrock** [comment]
@vjdv 
here you are:

https://github.com/deno-ja/deno-ja/blob/762dcb5a9cf0bbfcda8bcfaa59b1f65d6a70674e/main.ts#L16
