### ISSUE TITLE
IS_BROWSER or useData tree shaking

### ISSUE THREAD

**Issue by kuboon** [denoland/fresh#65]
Suppose  `server-side-module.ts` does not work on browser.
ex: `import * as xmlParser from "https://cdn.pika.dev/fast-xml-parser@^3.17.3";` works perfect on deno but fails for browser bundle.
I want to use it on serverside rendering and keep runtimeJS true.

```javascript
export const config: PageConfig = { runtimeJS: true }
export default function Page () {
  const data = useData('', async ()=>{
    if(!IS_BROWSER){
      const mod = await import('server-side-module.ts')
      return mod.getVal()
    }
  })
  return <p>{data}</p>
}
```
I hope the import will be removed by tree shaking, but `fresh` will try to bundle the `server-side-module.ts`  and fail.
Is there any better way to do this?

**Comment by kuboon** [comment]
I tried adding build option `define: {IS_BROWSER: true}` to here
https://github.com/lucacasonato/fresh/blob/044da545134b91142e215dc349ec37a59e52cd25/src/server/bundle.ts#L41
but nothing happened. Maybe I have some misunderstanding..

**Comment by lucacasonato** [comment]
Yeah, I am aware of this issue. It is relatively difficult to deal with.

**Comment by sylc** [comment]
This could also easily trip people passing credentials to db calls in a useData fetcher, which is probably one of the main use case of useData, as the credentials will end up in the client bundle.
In the mean time of a proper fix, maybe adding a note in the useData readme to signal that credentials should be passed by environment variables with deno.env.get() could help some. 
I'm happy to raise a PR if that helps.

**Comment by lucacasonato** [comment]
With the new "island" based architecture, this is not a problem anymore.
