### ISSUE TITLE
Deno not defined when trying to create pixi.js application in island

### ISSUE THREAD

**Issue by dagda1** [denoland/fresh#653]
I have created the following [reproduction repo](https://github.com/dagda1/fresh-pixi-bug) that shows the bug.

I have tried to create a [pixi.js](https://github.com/pixijs/pixijs) `Application` instance in an island with the code below but if I check the browser console I can see the error:

> Uncaught ReferenceError: Deno is not defined at island-pixiapplication.js:1:34512

```ts
/** @jsx h */
import { h } from "preact";
import { Application } from "pixi.js";

import { useState, useRef, useEffect } from "preact/hooks";

export default function PixiApplication() {
  const [app, setApp] = useState<Application>();
  const ref = useRef<HTMLCanvasElement>(null);

  useEffect(() => {
    if(ref.current === null) {
      return;
    }

    setApp(new Application({
      view: ref.current,
      width: 400,
      height: 400,
      resolution: 2,
    }));
  }, [])

  return (
    <div>
      <h1>
        <h2>Check browser console for error</h2>
        <strong>Uncaught ReferenceError: Deno is not defined
    at island-pixiapplication.js:1:34512</strong>
      </h1>
      <canvas ref={ref}/>
    </div>
  );
}
```

**Comment by rottenpen** [comment]
pixi.js include Node's libs
https://github.com/denoland/deno_std/issues/1785

**Comment by igorbrasileiro** [comment]
I'm facing the same Uncaught ReferenceError, when the component is an island.
Component example
```tsx
import JSONSchemaForm from "https://esm.sh/@rjsf/core@5.0.0-beta.2/?alias=react:preact/compat";
import type { FormProps } from "https://esm.sh/@rjsf/core@5.0.0-beta.2/?alias=react:preact/compat";

const schema: FormProps["schema"] = {
  title: "Product Shelf",
  "type": "object",
  required: ["title", "collection"],
  properties: {
    title: {
      "type": "string",
      title: "Título",
    },
    collection: {
      "type": "string",
      title: "Título",
    },
  },
};

export default function MyForm() {
  return <JSONSchemaForm schema={schema} validator={() => true} />
}
```
The error in the browser: `Uncaught ReferenceError: Deno is not defined`

**Comment by iuioiua** [comment]
Does adding `?target=es2022` to any imports from esm.sh in your island work?

**Comment by igorbrasileiro** [comment]
> Does adding `?target=es2022` to any imports from esm.sh in your island work?

Thank you for the answer, but it back to work by itself. Seems to be related to esm.sh

**Comment by iuioiua** [comment]
Ok, I'll go ahead and close this as this relates to esm.sh. Glad to hear it works now 😄
