### ISSUE TITLE
fresh spa integration in dev

### ISSUE THREAD

**Issue by elycheikhsmail** [denoland/fresh#656]
Situation :
I am developing a web application, I distinguish two types of pages or user interface:
- some of the pages are generated on the server side so that the site is optimized for search engines, like the HTML pages generated using the Fresh framework
- part consists of a single page with static files (SPA) to give a good experience to our client, in particular to give him the possibility to install our site as a PWA, for this this page is developed using reactjs/ CRA (or other framework)
Problem :
I develop the two applications in parallel: fresh app and reactjs SPA once finished I build the SPA and serve it from the Fresh (I have already tested this task without problem). Since each of the applications listens on a different port, all http requests launched by the SPA to Fresh were blocked, my question here is it possible to disable/enable Fresh http CORS during development, if so how?

**Comment by lucacasonato** [comment]
There is no automatic way to do this. You can use a middleware to do it though.

**Comment by elycheikhsmail** [comment]
> There is no automatic way to do this. You can use a middleware to do it though.

can you give example of code ?

**Comment by elycheikhsmail** [comment]
the solution can be out using caddy proxy in dev
