### ISSUE TITLE
Add a `CONTRIBUTING.md` file

### ISSUE THREAD

**Issue by MarkBennett** [denoland/fresh#657]
> We should probably add a CONTRIBUTING.md file...

_Originally posted by @lucacasonato in https://github.com/denoland/fresh/issues/335#issuecomment-1171772496_

This came up for me as I was trying to write my first contribution to Fresh but couldn't get the tests to run until I realized that [deno-puppeteer needed to be installed first](https://github.com/lucacasonato/deno-puppeteer#installation).

Happy to make a PR if there's interest but wanted to post an issue first.

**Comment by iuioiua** [comment]
I am closing this, as we're instead referencing Deno's central contributing guide in #1233. Thanks anyway, Mark!
