### ISSUE TITLE
A way to import SVG files?

### ISSUE THREAD

**Issue by m4rocks** [denoland/fresh#670]
Does anybody know a way to import a SVG file so it can be used inline in a component? Still trying to explore options but was wondering if there is a proper way to do it.

**Comment by hashrock** [comment]
I don't think SVG can be handled by import statements.
I think the easiest thing to do in Fresh is to make it JSX, you can pass classes with props too.

https://github.com/denoland/fresh/blob/main/www/components/Icons.tsx#L114

**Comment by vanpipy** [comment]
> I don't think SVG can be handled by import statements. I think the easiest thing to do in Fresh is to make it JSX, you can pass classes with props too.
> 
> https://github.com/denoland/fresh/blob/main/www/components/Icons.tsx#L114

How does the `class` work like an inline style in a component? The shape of an SVG cannot be changed by a class name. I did not get the idea of `making it JSX`.

**Comment by hashrock** [comment]
@vanpipy 

> How does the class work like an inline style in a component?

for example,  tweaking width / height like `<Icon class="w-6 h-6" />` (twind class)

**Comment by vanpipy** [comment]
> @vanpipy
> 
> > How does the class work like an inline style in a component?
> 
> for example, tweaking width / height like `<Icon class="w-6 h-6" />` (twind class)

Ohh..., I got what you said. It is the `twind` way, thanks.
