### ISSUE TITLE
Suspense support?

### ISSUE THREAD

**Issue by disjukr** [denoland/fresh#674]
![Screen Shot 2022-08-29 at 4 20 50 PM](https://user-images.githubusercontent.com/690661/187145859-6b96c32d-cc70-49a2-90b3-fc8f95a90536.png)

It seems it has been added [last year](https://github.com/denoland/fresh/pull/59) but removed now.

I want to use [jotai](https://github.com/pmndrs/jotai) in fresh. but it heavily depends on suspense feature when using [async atom](https://jotai.org/docs/guides/async).

**Comment by hyp3rflow** [comment]
fyi. comments above the render function are outdated https://github.com/denoland/fresh/blob/main/src/server/render.ts#L105-L125

**Comment by marvinhagemeister** [comment]
It's very unlikely that we'll do this. `Suspense` is a pretty controversial primitive as it easily leads to perf problems by forcing everything to be loaded in a waterfall like manner. Data loading from inside the render tree only makes sense when you have a cache outside of that. But when you have to use a cache outside of the tree, why trigger data loading from inside the tree?

I'm not sure yet what an alternative would look like, but Suspense is not a good primitive for async stuff.
