### ISSUE TITLE
[Document Needed] The top level APIs of the fresh

### ISSUE THREAD

**Issue by vanpipy** [denoland/fresh#675]
_The code tells us everything_, and I still think a document that describes the top-level APIs is a great way.

The [fresh.deno.dev](https://fresh.deno.dev/docs/introduction) shows the way to reach fresh and its architecture, but the content exposed cannot be found.

An APIs page like [Deno API](https://doc.deno.land/deno/stable) should be another way to describe what fresh is.

**Comment by marvinhagemeister** [comment]
This will be resolved with the upcoming Fresh 2 release. With the move to publishing to JSR there is a nice API reference doc generated on the fly automatically. A preview of that from one of the alpha releases can be found here https://jsr.io/@fresh/core@2.0.0-alpha.14/doc
