### ISSUE TITLE
Support the new `Deno.serve` API

### ISSUE THREAD

**Issue by MarkBennett** [denoland/fresh#678]
The [new Deno.serve() API is supposed to offer significant performance improvements](https://deno.com/blog/v1.25#new-experimental-http-server-api) over the `http_server` used by Fresh.

Is Fresh open to supporting this new API (perhaps behind a flag to start?) Is this limited by Deno Deploy support?

Happy to do a PR if this would be interested. Let me know if you have prefs on the approach.

**Comment by m4rocks** [comment]
I was actually thinking about this. As it says on the release notes, [it is an experimental API](https://deno.com/blog/v1.25#new-experimental-http-server-api). While it would be amazing for fresh to adopt this new API, I reckon @lucacasonato won't implement it as it's still experimental.

**Comment by lucacasonato** [comment]
I'd be willing to accept an implementation that is flagged behind a `experimentalDenoServe: true` option in the `start` function. It will not work on Deno Deploy, but it'd be good to get some initial experience with the new `Deno.serve` server in the real world. PRs welcome.

**Comment by MarkBennett** [comment]
> I'd be willing to accept an implementation that is flagged behind a experimentalDenoServe: true option in the start function. It will not work on Deno Deploy, but it'd be good to get some initial experience with the new Deno.serve server in the real world. PRs welcome.

Sounds good! I'll put together a draft PR adding an `experimentalDenoServe` option to `StartOptions` in [the start function in /src/server/mod.ts](https://github.com/denoland/fresh/blob/main/src/server/mod.ts#L63-L69).

**Comment by MarkBennett** [comment]
Just created a WIP PR. It's a little messy at using the new API requires adding the `--unstable` flag in many places which is likely not desired, but I can confirm Fresh works with the `Deno.serve` function.

Perhaps this waits until the `Deno.serve` function hits stable before merging into `main`?
