### ISSUE TITLE
A way to respect forwarded headers when running behind a proxy

### ISSUE THREAD

**Issue by digitaldesigndj** [denoland/fresh#684]
I am hosting my project behind an nginx proxy, so req.url is http instead of the https that it really uses.

Oak has a proxy option that does something similar, near the bottom of this section: https://deno.land/x/oak@v11.1.0#handle-method

**Comment by lucacasonato** [comment]
You can do something similar in Fresh. Instead of calling `start` in your `main.ts`, you can call:

```ts
import { ServerContext } from "$fresh/server.ts";

const ctx = await ServerContext.fromManifest(routes, opts);
const handler = ctx.handler();

// manually invoke this handler here
```

This will create a handler function that you can manually invoke like you would with Oak.
