### ISSUE TITLE
Delete cookie seems to not work in routes custom folder

### ISSUE THREAD

**Issue by gmunumel** [denoland/fresh#687]
Hello, 

I have created a mini project to show you my problem: https://github.com/gmunumel/fresh-cookie-issue

I have a delete cookie feature that is working if I run it from _routes/_ but doesn't work from _routes/user_:

![Screenshot 2022-09-01 182201](https://user-images.githubusercontent.com/276168/187964236-51858811-1d76-4216-a7f5-acb69336f02a.png)

**delete.tsx:** 

```
import { deleteCookie } from "$std/http/cookie.ts";

export function handler(req: Request): Response {
  console.log(req.url);
  console.log(new URL(req.url).origin);
  const headers = new Headers({
    location: new URL(req.url).origin,
  });
  deleteCookie(headers, "test_cookie");
  return new Response(null, {
    status: 302,
    headers,
  });
}
```

**index.tsx**

```
/** @jsx h */
import { h } from "preact";
import { tw } from "@twind";

export default function Home() {
  return (
    <div class={tw`p-4 mx-auto max-w-screen-md`}>
      <a class={tw`my-6`} href="/create">
        Create Cookie
      </a>
      <br />
      <br />
      <br />
      <a class={tw`my-6`} href="/user/delete">
        Delete Cookie (not work)
      </a>
      <br />
      <br />
      <br />
      <a class={tw`my-6`} href="/delete">
        Delete Cookie (ok)
      </a>
    </div>
  );
}
```
![o7rANQ](https://user-images.githubusercontent.com/276168/187967773-89126fac-989c-4682-bc0b-9c60a68c1d6a.gif)

**Comment by digitaldesigndj** [comment]
You have to set the path on delete cookie: 

```node
  deleteCookie(response.headers, "test_cookie", {
    path: "/",
  });
```
I think it is being set for you, but you want path: "/" or similar. Probably best to be explicit about the path when you set the cookie too.

**Comment by gmunumel** [comment]
That worked. Thanks
