### ISSUE TITLE
Dino Database: Project idea for showcase.json

### ISSUE THREAD

**Issue by xyntechx** [denoland/fresh#695]
Would a Fresh web app featuring dinosaurs (names, images, characteristics, fun facts, etc.) be a good addition to the list of projects to be showcased on https://fresh.deno.dev/? Perhaps we can include a search functionality, a JSON file reader to access the data, and any other features not already demonstrated by the other projects.

**Comment by lucacasonato** [comment]
Yeah, that'd be cool :)

**Comment by xyntechx** [comment]
I found [this](https://github.com/kjanjua26/jurassic-park/blob/main/data/data.csv) CSV file!

**Comment by xyntechx** [comment]
The project is done!
