### ISSUE TITLE
[Missing Function] ctx.renderNotFound()

### ISSUE THREAD

**Issue by bjesuiter** [denoland/fresh#698]
Based on the docs we should have a function called `crx.renderNotFound()` available in a route handler. 

I'm using the newest version of fresh to date, as far as I know this should be 1.0.2. 

But my typescript complains about `renderNotFound` not being a function: 
<img width="891" alt="Bildschirmfoto 2022-09-05 um 20 58 52" src="https://user-images.githubusercontent.com/2365676/188502902-105447eb-34e1-4003-b6e9-91ee977a0c32.png">

I wanted to use it like this: 
<img width="657" alt="Bildschirmfoto 2022-09-05 um 20 55 38" src="https://user-images.githubusercontent.com/2365676/188502921-2f332026-a081-4157-8fc7-f18143ec1cce.png">

This is the file on the branch which is broken: 
https://github.com/codemonument/blog.codemonument.com/blob/2022-09-05_switch-to-fresh/routes/posts/%5Bpost%5D.tsx

Thank you for this framework!

**Comment by lino-levan** [comment]
The documentation is out of date, but not the way you would think... It's actually going to be correct, in the future. I've [attached the commit](https://github.com/denoland/fresh/commit/49092ed83a6c3380058518d2b6211b200d916579) in which `ctx.renderNotFound` was added, and you will notice that there hasn't been a version pushed since it was added. This feature should be out with fresh `1.0.3`.

**Comment by lino-levan** [comment]
I realize that this feels really frustrating for consumers of fresh. @lucacasonato is there any chance we could avoid updating [fresh.deno.dev](https://fresh.deno.dev) until we push the feature updates?

**Comment by lucacasonato** [comment]
Yeah, that is the intention. Slipped through this time though. Sorry!

**Comment by bjesuiter** [comment]
Yeah, I already thought that somehow I did not have the most recent version 😀 

No problem, thanks for looking into this so fast! 

When will the next version will be released? If you can't say it exactly, maybe coarse?

**Comment by lino-levan** [comment]
@bjesuiter Fresh `1.1.0` is out, with `ctx.renderNotFound()` included. I think this issue should be closed?
