### ISSUE TITLE
Asynchronous plugin render functions

### ISSUE THREAD

**Issue by dragonwocky** [denoland/fresh#728]
Hey @lucacasonato, it's awesome to see the first step towards plugin support released!

I attempted to convert the UnoCSS integration I wrote (back in #290) to a Fresh-loadable plugin, but I ran into one issue: UnoCSS' generator function is asynchronous (and likely always will be: https://github.com/unocss/unocss/issues/26), but Fresh plugins are currently synchronous.

It makes a lot of sense to me to allow plugins to register asynchronous render functions, and I'm sure there'll be other integrations/plugins that'll run into the same issue as I did. Looking at the implementation in https://github.com/denoland/fresh/blob/main/src/server/render.ts#L173-L197, it seems like it should be fairly straightforward to implement async plugin render functions (they're already called from an asynchronous context), unless there's something else I've missed?

I would be happy to open a PR for this and to add an UnoCSS plugin to `$fresh/plugins`.

**Comment by lucacasonato** [comment]
The render function needs to be synchronous to ensure no two render functions can run at once. This is required to be able to have thread local state for the render. It would have to be a second `renderAsync` hook that wraps around the sync render hook.

**Comment by tobiasschmidt89** [comment]
+1 to implement renderAsync

**Comment by Hladikes** [comment]
For anyone here trying to use UnoCSS with fresh for some simple project, I made a forked version which adds the ability to use plugins with async render function (https://github.com/Hladikes/fresh). I also added unocss plugin which works with this approach. But as mentioned above, this is not thread safe and you should wait for the official async render support.

**Comment by miguelrk** [comment]
**FYI:** just opened PR https://github.com/denoland/fresh/pull/1303 which adds a `unocss` plugin based on the new `renderAsync()` method 👍🏼. It is based on the workaround proposed by @Hladikes [above](https://github.com/denoland/fresh/issues/728#issuecomment-1413024482)... thanks for that! 🙏
