### ISSUE TITLE
Issue with migration to Fresh v1.1.0

### ISSUE THREAD

**Issue by digitaldesigndj** [denoland/fresh#733]
A small issue:

Code inside ternary expressions inside Islands have some issues, but gets migrated to class="". Here's how I fix it up...
```jsx
        const THE_STYLE = tw`w-full block flex-grow md:flex md:items-center md:w-auto`
        {navOpen
          ? (
            <div
              class={THE_STYLE}
            > : <></>}
```

A smaller issue:
`Fragment` is removed from includes but not elements. Causes not found errors. Had to search replace a bit.

A nitpick:
deno.json has a line ending that `deno fmt` changes after migration

All in all, extremely painless, 4 projects done in a morning. Will keep upgrading. <3 the DevTools stuff

**Comment by lucacasonato** [comment]
Nope, it's not necessary - try it out :)

**Comment by digitaldesigndj** [comment]
I changed my fix to something that really works for me. It's only choking on things that have a prefix like `md:flex` `md:whatever`? Any ideas

**Comment by digitaldesigndj** [comment]
Here's changes I had to do to make the `md:` thing work.

https://github.com/Hyprtxt/fresh-strapi.deno.dev/commit/2c28a332676d350f7226c6d68cd92e96e6e5a1d1#diff-d40036ce99dc031ac7f38f01d1796f8b81f367451547684cc42512c67e71a406

**Comment by lucacasonato** [comment]
I don't understand. Do you have a commit that works and one that does not?

**Comment by digitaldesigndj** [comment]
Doesn't work, the `md:stuff` styles don't do the thing...

This is the broken commit
https://github.com/Hyprtxt/fresh-strapi.deno.dev/commit/6d3132e997e7e8d435a0214b069bd66eb3c78eb7

This commit fixes the issues I had.
https://github.com/Hyprtxt/fresh-strapi.deno.dev/commit/2c28a332676d350f7226c6d68cd92e96e6e5a1d1#diff-d40036ce99dc031ac7f38f01d1796f8b81f367451547684cc42512c67e71a406

It's needs Redis to run which is kind of a pain in the butt. If you want to look at/rename the `.env.example` file if you want to run it.

Feel free to use `API_URL=https://api.videopoker.academy/api` to point at a live Strapi install.

**Comment by digitaldesigndj** [comment]
Not sure if I had a real issue here... if nobody else did
