### ISSUE TITLE
Can't cache documents?

### ISSUE THREAD

**Issue by reggi** [denoland/fresh#735]
Currently you can't cache a document because you can't change the status response using `Etag` / `If-None-Match`, curious if there's a reason this was only done for static content and not pages?

```ts
export const handler: Handlers = {
  async GET(req, ctx) {
    const resp = await ctx.render();
    
    const x = req.headers.get('If-None-Match')
    if (x === 'W/deadbeef') {
      return resp // need to send 304
    }
    
    resp.headers.set("ETag", "deadbeef");
    return resp;
  },
};
```

**Comment by lucacasonato** [comment]
I don't quite understand - why can you not set the `Etag` header on the response object? That should work.
