### ISSUE TITLE
Why islands scripts are pushed to opts.imports?

### ISSUE THREAD

**Issue by pazguille** [denoland/fresh#741]
Hi,

I would like to understand because there are performance improvements about how scripts are loaded. Currently, the script have more importance than LCP images.

The scripts download, parse and execute blocking the render. Maybe, they could be loaded as `modulepreload` using `opts.preloads` instead of `opts.imports`.

Current:

<img width="1085" alt="fresh_-_The_next-gen_web_framework_" src="https://user-images.githubusercontent.com/250856/189349728-559e9a4c-e568-4c09-958a-288f39c5d04d.png">

Removing scripts from `opts.imports`:

<img width="1129" alt="fresh_-_The_next-gen_web_framework_" src="https://user-images.githubusercontent.com/250856/189352796-754725dd-0258-46bc-ab56-97cdaedf73d8.png">

**Comment by lucacasonato** [comment]
To preload them. Not all browsers support `modulepreload` unfortunately.
