### ISSUE TITLE
Support passing JSX components to island props

### ISSUE THREAD

**Issue by lucacasonato** [denoland/fresh#750]
We should support passing JSX elements to island props. Example:

```tsx
import AddToCart from "../islands/AddToCart.tsx";

function IndexPage() {
  return (
    <div>
      <AddToCart>
        Cream Cheese <b>Bagel</b>
      </AddToCart>
    </div>
  );
}
```

The JSX elements passed to island props would be serialized to static markup on the server (just like the surrounding components in the route). These components would **not** be re-rendered on the client. Instead on the client the prop would be replaced with a proxy component that represents the underlying static markup, rather than a real VDOM tree.

**Comment by theogainey** [comment]
Is anyone working on this? This is a pattern I would like to use and I will take a shot at developing this if the effort is still needed

**Comment by RA9** [comment]
Hi @lucacasonato, I am faced with the same issue. Is there a way around this until the issue is resolved?

**Comment by lucacasonato** [comment]
More background on how this should work:

1. All VNode's passed to island props are captured in a Map and assigned IDs.
2. If the VNode is rendered, we wrap it in `<!--frsh-vnode-$id-->` comments.
3. When serializing island props, if the VNode was rendered, we replace it with a "VNode ref" prop pointing to the ID in the wrapper comment. If it was not rendered, we render the VNode and serialize its contents into a "VNode literal" prop.
4. When deserializing, we get the VNode contents either from the DOM, or the serialization, and construct a new VNode that just renders it's contents to the DOM.
5. This real VNode is passed in the island props.
