### ISSUE TITLE
Twind Unknown utility, theme value

### ISSUE THREAD

**Issue by omar2205** [denoland/fresh#751]
I'm having this error whenever I try to use any class that's not a tailwind utility.

![image](https://user-images.githubusercontent.com/1373867/189481656-59b7889a-9d9e-48fd-b257-c6ebdc26ad0e.png)

**Comment by lucacasonato** [comment]
https://github.com/tw-in-js/vscode-twind-intellisense/issues/10

**Comment by imjamesb** [comment]
Fix in https://github.com/tw-in-js/vscode-twind-intellisense/issues/18

**Comment by omar2205** [comment]
> Fix in [tw-in-js/vscode-twind-intellisense#18](https://github.com/tw-in-js/vscode-twind-intellisense/issues/18)

This doesn't fix naming something `class="my-header"` A custom class that I have no intention of adding to `twind.config.ts`
