### ISSUE TITLE
Document post requests

### ISSUE THREAD

**Issue by ry** [denoland/fresh#768]

**Comment by lucacasonato** [comment]
I don't understand this issue.

**Comment by emschwartz** [comment]
The fresh docs currently only show how to write handlers for GET requests but not POST requests. It would be helpful to have an example that includes using the POST request body

(Also thanks for your work on this framework!)

**Comment by gutenfries** [comment]
Hey!
I'm not sure if anyone has been working on this, but I have a [PR open](#853) addressing this. Thank you!
