### ISSUE TITLE
Compiled Island code throws `Uncaught ReferenceError: Deno is not defined`.

### ISSUE THREAD

**Issue by Industrial** [denoland/fresh#774]
I'm getting the error `Uncaught ReferenceError: Deno is not defined`

in this bit of code (compiled, pretty printed in the inspector):

```
Deno?.core ? core = Deno.core : core = {
  setNextTickCallback: void 0,
  evalContext(_code, _filename) {
    throw new Error('Deno.core.evalContext is not supported in this environment')
  },
  encode(chunk) {
    return new TextEncoder().encode(chunk)
  },
  eventLoopHasMoreWork() {
    return !1
  }
};
```

This is in the js for an Island component.

I think the code `typeof Deno === 'undefined'` would work here.

Maybe if someone points me to the bit that compiles this code I could make a PR and start testing.

**Comment by lucacasonato** [comment]
Where does this code come from? What are your dependencies?

**Comment by lino-levan** [comment]
Could we get a reproc example?

**Comment by ahuigo** [comment]
Because island code will be executed in browser. So you have two choices:
1. Do not use native api like `Deno` in island.
2. Use `import { IS_BROWSER } from "$fresh/runtime.ts";` to detect environment before you call native api like `Deno` in island.

**Comment by kjloveless** [comment]
> Where does this code come from? What are your dependencies?

@lucacasonato I think they pushed the error to their repo here: https://github.com/Industrial/deno-fresh-blog/blob/main/islands/PostListIsland.tsx

from the discord it sounds like their issue is coming from the apollo/client library. 
Haven't tested this myself, but I was getting a similar error trying to use node-geocoder. I think this was happening because of that library's dependency on node-fetch though.

**Comment by Industrial** [comment]
Hi. I've just updated the code and replaced Apollo with `react-query` which is a lot smaller but get the same problem.

I'm actually getting a different error in a different spot now and I see that it's trying to bundle code meant for the server. I'll investigate a bit more :)

**Comment by Industrial** [comment]
I fixed the issue with this commit: https://github.com/Industrial/deno-fresh-blog/commit/82aae92302623fdb6d80d6506ffd24c14f109b61#diff-23cc22e12738a61ec6ba2b9485d9104243189e3bdd368c2a517fe8a1d3b90c96L9

I was shipping code that used the `dotenv` library from https://deno.land which is meant for server side code only.

Since Deno Deploy does not support dynamic imports yet (right?) It's currently not possible to ship env vars into a build. In my case I wanted to configure the API URL via an env var since I'm used to this with Next.js but I forgot that Next.js has a custom solution for this (https://nextjs.org/docs/basic-features/environment-variables) which is a bit too much for the Fresh scope I guess :)

You can view the blog at https://c9-deno-fresh-blog.deno.dev/

It's backed by a Directus Community (shared) CMS so the DB instance might spin down at some point..

**Comment by mrcampbell** [comment]
I hit the same snag, and while this is a "D'oh" problem, would it help to update the error message to say "in some cases, this might mean you are trying to import server code into an island" or something? Not necessary, but quality of life.

**Comment by lino-levan** [comment]
This is a good UX improvement. Opened #1053 about it.
