### ISSUE TITLE
Firebase Auth throws `Uncaught ReferenceError: Deno is not defined` on browser

### ISSUE THREAD

**Issue by CarcajadaArtificial** [denoland/fresh#776]
Hello,
First of all, I'm aware of a possible duplicate issue [here](https://github.com/denoland/fresh/issues/774). But I'm not entirely sure that both are about the same thing so that's why I'm opening a new issue.

I'm not doing anything complex, I'm just trying to get basic firebase email sign-in to work on fresh and later on deploy. I know the authentication process works fine. This is the implementation that I've made:

`~/back/firebase.ts`
```TypeScript
import { initializeApp, getAuth, signInWithEmailAndPassword } from '../deps.ts';

const firebaseConfig = JSON.parse(Deno.readTextFileSync('firebase.json'));
// Edit: It doesn't work with this either:
// const firebaseConfig = { /* ... */ };
export const app = initializeApp(firebaseConfig);

export const auth = getAuth(app);
export const signIn = signInWithEmailAndPassword;

// Authentication test (works)
// await signIn(auth, '***', '***');
```

`~/islands/SignIn.tsx`
```TypeScript
import { createRef } from "preact";
import { auth, signIn } from "../back/firebase.ts";

export default function SignIn() {
  const refEmail = createRef();
  const refPassword = createRef();

  return (
    <div>
      <div>
        <label>
          Email
          <input type="email" id="login-email" ref={refEmail} />
        </label>
      </div>
      <div>
        <label>
          Password
          <input type="password" id="login-password" ref={refPassword} />
        </label>
      </div>
      <button
        onClick={async () => {
          // This line throws the error:
          await signIn(
            auth,
            refEmail.current.value,
            refPassword.current.value,
          );
        }}
      >
        Sign in
      </button>
    </div>
  );
}
```

I've tried everything I could think of that might be causing this, but haven't found anything concrete. What could be causing this error?

**Comment by CarcajadaArtificial** [comment]
Also, this is what my dependencies look like:

`~/deps.ts`
```TypeScript
export * from 'https://www.gstatic.com/firebasejs/9.10.0/firebase-app.js';
export * from 'https://www.gstatic.com/firebasejs/9.10.0/firebase-auth.js';
```

**Comment by kjloveless** [comment]
`const firebaseConfig = JSON.parse(Deno.readTextFileSync('firebase.json'));
`
*Sync operations are currently not supported by Deploy, so that's something to consider as well.

https://deno.com/deploy/docs/runtime-fs

**Comment by CarcajadaArtificial** [comment]
Hello, I tried adding a JS object with the config information in place of the file read and it is still throwing the same error.

Context: `~/back/firebase.ts`
```Typescript
// Changed from this:
const firebaseConfig = JSON.parse(Deno.readTextFileSync('firebase.json'));
// To this:
const firebaseConfig = { /* ... */ };
```

Edit: Without the file read, I'm not using the Deno api at all in the project.

**Comment by CarcajadaArtificial** [comment]
I found the error, somewhere else in the project I had the following dependency import:

```TypeScript
export * from 'https://deno.land/std@0.155.0/fs/mod.ts';
```

Removing it solved everything.
