### ISSUE TITLE
how to `deno run` a fresh project published to deno.land/x ?

### ISSUE THREAD

**Issue by stereosteve** [denoland/fresh#777]
I was thinking to have a fresh project that you could easily run with `deno run`.

Here's what I tried so far:

```
deno run -A https://deno.land/x/git_goggles@0.0.2/main.ts  
error: Relative import path "$fresh/plugins/twind.ts" not prefixed with / or ./ or ../
```

```
deno run -A --import-map=https://deno.land/x/git_goggles@0.0.2/import_map.json https://deno.land/x/git_goggles@0.0.2/main.ts
error: Uncaught (in promise) TypeError: Must be a file URL.
    throw new TypeError("Must be a file URL.");
          ^
    at fromFileUrl (https://deno.land/std@0.150.0/path/posix.ts:492:11)
    at Function.fromManifest (https://deno.land/x/fresh@1.1.0/src/server/context.ts:253:42)
    at start (https://deno.land/x/fresh@1.1.0/src/server/mod.ts:64:35)
    at https://deno.land/x/git_goggles@0.0.2/main.ts:13:7
```

I'm wondering if there is some combination of cli flags to set import map + compiler options to match what is in `deno.json`?

Or if there is a better way to approach this?

The idea is to have something similar to Github Desktop instead of an electron app it could be a simple fresh app that could open a tab in your preferred browser.

**Comment by lino-levan** [comment]
It looks like the code uses `toFileUrl` and `fromFileUrl` all over the place. Unless I'm reading this wrong, it looks like it'd be a major refactor.

**Comment by marvinhagemeister** [comment]
Running Fresh projects straight from `deno.land/x` is not possible. That's one of the downsides of import maps that they only take effect in the root project. If a dependency relies on a path being remapped that's not in the root import map then it will not work. It's one of the reasons we built https://jsr.io/ .
