### ISSUE TITLE
twind classes in client-side-only island components don't get registered

### ISSUE THREAD

**Issue by stereosteve** [denoland/fresh#778]
I have an "app style" island component that does dynamic data loading [here](https://github.com/stereosteve/git-goggles/blob/main/islands/HistoryApp.tsx#L79).

Because the data loading happens client side the components are not in the tree during server-side render, and twind does not register them, so they appear un-styled.

There might be some ways to do some of the data-loading in the server-side route to avoid the problem, but I do think this could be a valid use case for apps with a mix of static pages and more "app like" components.

I'm wondering if there could be a way to use tailwind in a "safe" mode that does more optimistic inclusion of the classes from island source files closer to how the official tailwind jit compiler works?

**Comment by e-jigsaw** [comment]
I stuck same problem.

in `islands/Some.tsx`

```tsx
  return (
    <div class="my-1"> {/* <- apply this class */}
      {someClientFetched.map((a) => (
        <div key={...} class="my-2"> {/* <- do not apply this class */}
          {...}
        </div>
      ))}
    </div>
  );
```

@lucacasonato Do you know something avoid this problem?

Thanks

**Comment by crowlKats** [comment]
We had this issue in dotland, and it was hotfixed as such:
https://github.com/denoland/dotland/blob/3dc96230f9b5b7adec5e6c50b4264622d37686f8/util/twind.ts#L142-L158

**Comment by e-jigsaw** [comment]
Thank you for hotfix. I will try it later.

I used Tailwind's PlayCDN for hotfix until now.

**Comment by kjloveless** [comment]
> We had this issue in dotland, and it was hotfixed as such: https://github.com/denoland/dotland/blob/3dc96230f9b5b7adec5e6c50b4264622d37686f8/util/twind.ts#L142-L158

@crowlKats Do you know if this is going to be patched in the plugin itself? I'll take the hotfix for a spin later, but just wondering. 

Thanks!
