### ISSUE TITLE
Very developer-unfriendly error if island contains wrong TS

### ISSUE THREAD

**Issue by dector** [denoland/fresh#784]
STR:
- Clone repository https://github.com/dector/issue-fresh-dx.
- Execute `deno task start`.

ER: Error should point to island file.

AR:
```
error: Uncaught (in promise) SyntaxError: Unexpected reserved word
  await import(entrypoint);
  ^
    at async dev (https://deno.land/x/fresh@1.1.1/src/dev/mod.ts:187:3)
    at async file:///Projects/issue-fresh-dx/dev.ts:5:1
```

Actual error is [here](https://github.com/dector/issue-fresh-dx/commit/0cd7bf5e2a7f25387083e6a134fa430a430bde25#diff-100fa9d184cb53aa9425817cc356c5dfc64b848c8f5e5e1864210db311421551R11): `await` without `async`.

**Comment by karfau** [comment]
Same symptom different resaon: when I started using `await` code in a `handler` without making it	`async`.

Fix: Change
```
export const handler: Handlers = {
  GET(req, ctx) {
```
to
```
export const handler: Handlers = {
  GET: async (req, ctx) => {
```
I would suggest to rename the issue to either 

**Generic error message when missing `async` should point to the code.**

**Comment by cagixr** [comment]
> Same symptom different resaon: when I started using `await` code in a `handler` without making it `async`.
> 
> Fix: Change
> 
> ```
> export const handler: Handlers = {
>   GET(req, ctx) {
> ```
> 
> to
> 
> ```
> export const handler: Handlers = {
>   GET: async (req, ctx) => {
> ```
> 
> I would suggest to rename the issue to either
> 
> **Generic error message when missing `async` should point to the code.**

Thanks! You saved my day :)
