### ISSUE TITLE
[Help wanted] Middleware issue

### ISSUE THREAD

**Issue by garyhe0780** [denoland/fresh#790]
I think `_middleware.ts` right now intercept every request, even with static resources.

For example
```javascript
async function logging(
  req: Request,
  ctx: MiddlewareHandlerContext,
): Promise<Response> {
  const res = await ctx.next();
  console.log(`${req.method} ${req.url} ${res.status}`);
  return res;
}
```
and I get those output:
<img width="732" alt="Screen Shot 2022-09-24 at 10 17 19" src="https://user-images.githubusercontent.com/29646545/192075863-d7506729-8918-4912-a95f-88d90e277403.png">

**Comment by cnnrsprs** [comment]
imo, this seems like the correct behavior. Intercepting requests even for static resources allows developers to manipulate (for e.g.) the response headers for all requests to the application.

I'm improvising and I haven't tested this, but I think one way to avoid running middleware on static assets is to create a middleware that determines whether or not a request path maps to a static file and sets a context property that the other middleware can check for.

```ts
// routes/_middleware.ts
import { MiddlewareHandlerContext } from "$fresh/server.ts";

interface State {
  isStatic?: boolean;
}

async function checkStatic(req: Request, ctx: MiddlewareHandlerContext<State>) {
  const url = new URL(req.url);

  // Also classify /_frsh/ paths as static
  ctx.state.isStatic = url.pathname.startsWith("/_frsh/");

  if (!ctx.state.isStatic) {
    try {
      await Deno.stat(`./static${url.pathname}`);
      ctx.state.isStatic = true;
    } catch {
      ctx.state.isStatic = false;
    }
  }

  return await ctx.next();
}

async function logging(req: Request, ctx: MiddlewareHandlerContext<State>) {
  const res = await ctx.next();
  if (!ctx.state.isStatic) {
    console.log(`${req.method} ${req.url} ${res.status}`);
  }
  return res;
}

export const handler = [
  checkStatic,
  logging,
];
```

**Comment by garyhe0780** [comment]
@connorlogin 
Thanks for you replying, It does give developer more control to their static file. I have no problem with this behavior as long as it's by design.
