### ISSUE TITLE
Argument of type 'URL' is not assignable to parameter of type 'string'.

### ISSUE THREAD

**Issue by boazblake** [denoland/fresh#80]
on line 151 you are passing a url instead of a string
```
const url = new URL(req.url);
      if (url.pathname.length > 1 && url.pathname.endsWith("/")) {
        url.pathname = url.pathname.slice(0, -1);
        return Response.redirect(url, 307);
      }
```

probably should be:
const url = new URL(req.url);
      if (url.pathname.length > 1 && url.pathname.endsWith("/")) {
        url.pathname = url.pathname.slice(0, -1);
        return Response.redirect(JSON.stringify(url), 307);
      }

**Comment by lucacasonato** [comment]
Closed by #81
