### ISSUE TITLE
Upgrade script doesn't work with deno.jsonc

### ISSUE THREAD

**Issue by neezer** [denoland/fresh#800]
[The script to upgrade to Fresh v1.1 doesn't support `deno.jsonc` configuration files.](https://github.com/denoland/fresh/blob/b19c4bb0415b4b2741a59e9b33bdfb3bed3519aa/update.ts#L45)

Right now I get:

> error: Uncaught (in promise) NotFound: No such file or directory (os error 2)
> let denoJsonText = await Deno.readTextFile(DENO_JSON_PATH);
>                    ^
>     at async Object.readTextFile (deno:runtime/js/40_read_file.js:56:20)
>     at async https://deno.land/x/fresh@1.1.1/update.ts:46:20

[Deno docs](https://deno.land/manual@v1.25.4/getting_started/configuration_file) say both `deno.json` and `deno.jsonc` are supported, so I think this script should support both.

**Comment by jazoom** [comment]
It seems it doesn't work with `deno.jsonc` in general for me. `fresh.gen.ts` only ever uses this line:

`import config from "./deno.json" assert { type: "json" };`

And that creates an error if I have `deno.jsonc` in the project instead.

**Comment by deer** [comment]
`update.ts` is definitely still broken, but support for using `deno.jsonc` files in projects was added back in May. I've created a PR to fix the update script and add a test for this.
