### ISSUE TITLE
Unable to set the lang property in render function

### ISSUE THREAD

**Issue by ch99q** [denoland/fresh#805]
Due to the new plugin system, accessing the lang property is no longer possible.

It's a great plugin system with a lot of future possibilities. Still, I would suggest adding lang to `PluginRenderResult`, and possibly if it should be extended to supporting an i18n system, adding `redirect?: Response` to the result. As well as adding `req: Request` to `render?(ctx: PluginRenderContext): PluginRenderResult` in the `Plugin` type. (With the javascript implementation of..)

I can probably cook up a pull request if it's of any interest 😊

**Comment by marvinhagemeister** [comment]
This is possible since Fresh 1.4 through the App wrapper template. See this page in the documentation on how to do it: https://fresh.deno.dev/docs/concepts/app-wrapper
