### ISSUE TITLE
Clarify on the docs that you can pass a string children to an island

### ISSUE THREAD

**Issue by ricardo-devis-agullo** [denoland/fresh#807]
Currently on the [docs for the island chapter](https://github.com/denoland/fresh/blob/f2cc43df64818fd7fbccd3e143d69f4dd77bca35/docs/concepts/islands.md?plain=1#L37) it says:

```
This means that it is not possible to pass children to an island, as children are VNodes, which are not serializable.
```

But, looking at the repository for the website I saw that the [CopyArea component](https://github.com/denoland/fresh/blob/f2cc43df64818fd7fbccd3e143d69f4dd77bca35/www/islands/CopyArea.tsx#L6) works with children when it's just a string (as it gets used on the [introduction page](https://github.com/denoland/fresh/blob/f2cc43df64818fd7fbccd3e143d69f4dd77bca35/www/routes/index.tsx#L217))

So I think the docs should clarify that exception

**Comment by marvinhagemeister** [comment]
Updated the docs in #1285 . Passing children to islands is now supported 🎉
