### ISSUE TITLE
Add support for https.

### ISSUE THREAD

**Issue by haodong404** [denoland/fresh#809]
The `start()` function in fresh is starting an ordinary web server, but I didn't find a function that would start a server with TLS. So I had to define a function myself using `serveTls()` in Deno. And is there a convenient function for that purpose in the future? For example: `startTls()`?

**Comment by lucacasonato** [comment]
`startTls` sounds like a good idea. I welcome a PR :)

**Comment by AffogatoAlCaffe** [comment]
Should be resolved using deno >= 1.35.0
