### ISSUE TITLE
How to read and write a file?

### ISSUE THREAD

**Issue by Suzichen** [denoland/fresh#817]
like this doc [Deno Doc](https://deno.land/manual@v1.26.0/examples/read_write_files)
```
// test.ts
export const getTestJSON = async () => {
  const text = await Deno.readTextFile("../data/test.json")
  return text
}
```
deno run --allow-read test.ts
echo `{"test": 123}`

but in fresh, echo error:
```
error: NotFound: No such file or directory (os error 2)
    at async Object.readTextFile (deno:runtime/js/40_read_file.js:55:20)
    at async getTimelineJSON (file:///xxxx/deno-fresh-demo/test/test.ts:10:16)
```

**Comment by theogainey** [comment]
Your problem may lie in how you are telling Deno which file to read. Try using `Deno.cwd()` to get a string representing the current working directory and use that to tell Deno where the file you want to read is. It will end up looking something like this. 
```
  const text = await Deno.readTextFile(`${Deno.cwd()}data/test.json`)
```

**Comment by Suzichen** [comment]
> Your problem may lie in how you are telling Deno which file to read. Try using `Deno.cwd()` to get a string representing the current working directory and use that to tell Deno where the file you want to read is. It will end up looking something like this.
> 
> ```
>   const text = await Deno.readTextFile(`${Deno.cwd()}data/test.json`)
> ```

Thanks! It works for me!
