### ISSUE TITLE
Add the ability to add `<link>` , `<base>`, `<title>` and similar elements as a plugin

### ISSUE THREAD

**Issue by NanoSpicer** [denoland/fresh#824]
Currently plugins only allow  to add inline styles and inline scripts.
I'd  be great  to be able to provide extra properties for the `<head>` node without creating a higher order component for all pages.

**Comment by marvinhagemeister** [comment]
This is now possible since Fresh 1.4 . See this page in the docs on how to do it: https://fresh.deno.dev/docs/concepts/app-wrapper
