### ISSUE TITLE
Add the ability to configure a base path

### ISSUE THREAD

**Issue by NanoSpicer** [denoland/fresh#825]
Fresh serves a bunch of other files under a fixed url `/_frsh/` something else.

If we want to serve a fresh app alongside others in the same server we need to match `/_frsh/` and proxy-pass that to the original server, which makes running two different fresh apps into the same server impossible.

If we could configure a `baseUrl` parameter into the server that would get us around this issue

**Comment by cowboyd** [comment]
We have a similar situation, but we are not just running in the same server but across different websites, so the `baseURL` would need to be specifiable on a per request basis.

**Comment by cowboyd** [comment]
It appears that this is a duplicate of #697

**Comment by marvinhagemeister** [comment]
Agree, sounds like a duplicate of #697 . If folks feel different I'm happy to reopen this one.
