### ISSUE TITLE
How do I access response content length in a middleware?

### ISSUE THREAD

**Issue by khuongduybui** [denoland/fresh#829]
I'm creating an access log writer middleware (https://github.com/khuongduybui/fresh-logging) but I'm struggling to get the content length for the `bytes` part of the common log format.

I first looked in the `Content-Length` response header, but it's not being set.

My next attempt was to clone the response, read its body into an `ArrayBuffer`, and get the `byteLength`.
That worked, but I found `res.clone()` to take anywhere from 10 to 100 millisecond for a super simple route, which is SIGNIFICANT.

I am wondering if there is a more efficient way to obtain response content length _without_ having to clone and read.
Perhaps it could be set somewhere earlier in the chain while creating the response?

**Comment by marvinhagemeister** [comment]
The `Content-Length` header is usually only set for static files. It's an optional header in the HTTP spec that is not required to be set. You're best bet is the path you've chosen already by calculating the content length yourself in case it's missing.
