### ISSUE TITLE
ATT Flags fresh.deno.dev as malware

### ISSUE THREAD

**Issue by derekr** [denoland/fresh#836]
Hey! Only posting because sometimes the issue lies with the hosting provider (I can't access the docs site or run the init script from the README), but I am also working on my end to unblock the site for my network/in their block list. Def feel free to close, but wanted to flag incase it's something that can be addressed upstream.

If I curl over http I get the ATT response from my network and if I try https I get a connection reset by peer error.

<img width="940" alt="image" src="https://user-images.githubusercontent.com/22249/195438716-e06b3449-f155-42b9-a0b7-35f896d4de4d.png">

<img width="688" alt="image" src="https://user-images.githubusercontent.com/22249/195438806-98eb88a7-2251-4267-b4f7-75f7f2c3b3e8.png">

![image](https://user-images.githubusercontent.com/22249/195682086-07e588d0-9124-441d-aa94-c4db46ae14a4.png)

https://www.virustotal.com/gui/url/dfa37fa02afd5945a0d4e3df438ad5c39dd0e20f69f3a77610602b73a9f82324

**Comment by lino-levan** [comment]
I sent a false positive report to BitDefender and it looks like they removed the flag. 

https://www.virustotal.com/gui/url/4b46104f97d25fd764326136f3109af16d8e1ea9f2b7f95ba75904df843c5f1e

I recommend that we close this issue since it is resolved.

**Comment by joseph-galindo** [comment]
As a heads up, it looks like Malwarebytes Android (likely cross platform too) marks `*.deno.dev` as a phishing site.
