### ISSUE TITLE
Dev/Prod mode?

### ISSUE THREAD

**Issue by nickguimond** [denoland/fresh#84]
https://github.com/lucacasonato/fresh/blob/95289380f3f8bb85c8cc2d0fc3e5ab2ab4de9962/src/server/context.ts#L39

Dev/Prod mode is determined by assuming the end user is using Deno Deploy. I just set a random string for now in my use case but would be nice if this was a config option or something agnostic to the deployment environment. Or even just something to mention how to manually override in the docs.

**Comment by lino-levan** [comment]
There hasn't been a ton of progress on this front but I do want to clarify to anyone reading the thread that we do have docs on how to deploy outside of Deno. Those docs do mention the environment variable:
> When packaging your Fresh app for Docker, it is important that you set the DENO_DEPLOYMENT_ID environment variable in your container. This variable needs to be set to an opaque string ID that represents the version of your application that is currently being run. This could be a Git commit hash, or a hash of all files in your project. It is critical for the function of Fresh that this ID changes when any file in your project changes - if it doesn't, incorrect caching will cause your project to not function correctly.

Ideally this would just be something like `env=PROD` but ¯\\\_(ツ)\_/¯

**Comment by lucacasonato** [comment]
Fresh does not really have much of a prod vs dev mode. The main difference is how caching works.

For caching to work correctly in prod, a unique identifier representing the source code (ie the git commit or a source code hash) needs to be provided to fresh. This is done via the `DENO_DEPLOYMENT_ID` env var. If this not set, Fresh can not cache, and thus can not activate "prod" mode.
