### ISSUE TITLE
fix header text on showcase page

### ISSUE THREAD

**Issue by hashrock** [denoland/fresh#840]
<img width="687" alt="image" src="https://user-images.githubusercontent.com/3132889/195814438-2e522cfe-d03b-42a4-a372-b69441f7e766.png">

it's not `FRESH docs` actually

**Comment by developerium** [comment]
@hashrock It was confusing for me too :joy: , at first I thought the `docs` was part of the name, and I thought the framework was created for documentation

**Comment by hashrock** [comment]
done by #872
