### ISSUE TITLE
fresh as pwa

### ISSUE THREAD

**Issue by elycheikhsmail** [denoland/fresh#845]
document how turn fresh project in pwa

**Comment by sigmaSd** [comment]
I wrote a script to do it here https://github.com/sigmaSd/PwaIt with a fresh example

**Comment by afifurrohman-id** [comment]
I PR for add this request to fresh docs #1533

**Comment by marvinhagemeister** [comment]
Closing, there are currently no plans to support Fresh as a PWA. Happy to accept PRs if folks want to contribute that though.
