### ISSUE TITLE
Docs page is broken on site.

### ISSUE THREAD

**Issue by About7Sharks** [denoland/fresh#85]
## Problem
https://fresh.deno.dev/docs errors
```
This fresh.deno.dev page can’t be foundNo webpage was found for the web address: https://fresh.deno.dev/docs
HTTP ERROR 404
```

**Comment by About7Sharks** [comment]
You can find the docs here https://github.com/lucacasonato/fresh/blob/main/docs

**Comment by so1ve** [comment]
also

**Comment by lucacasonato** [comment]
The doc site is not yet implemented. Progress on the doc site is being tracked in #98.
