### ISSUE TITLE
+ and - buttons in fresh.deno.dev don't work

### ISSUE THREAD

**Issue by lino-levan** [denoland/fresh#851]
It looks like the buttons on the deployed site don't work (but they do seem to work in dev?). The buttons are greyed out and the network requests for the JS bundles are returning error code 500.

Attached is a screenshot of the issue on safari/firefox/chrome. This was tested on my local machine, and a cloud computer (both running into this issue). It's also interesting to note the subtle (or not so subtle) rendering differences between the engines.

<img width="745" alt="Screen Shot 2022-10-18 at 9 55 47 PM" src="https://user-images.githubusercontent.com/11367844/196601082-84caffa1-f3aa-43bd-bba2-cdb0257c8aa4.png">
<img width="685" alt="Screen Shot 2022-10-18 at 9 55 22 PM" src="https://user-images.githubusercontent.com/11367844/196601091-2f39cbb9-f611-4a97-aaf8-9b60a11c27c6.png">
<img width="739" alt="Screen Shot 2022-10-18 at 9 54 42 PM" src="https://user-images.githubusercontent.com/11367844/196601093-d9b56d18-8d77-4aad-9303-a63a132a1b51.png">

**Comment by hashrock** [comment]
Solved in #852, Thank you for reporting!
