### ISSUE TITLE
Image showing at github not on deno.land/x/fresh

### ISSUE THREAD

**Issue by codesculpture** [denoland/fresh#861]
At README.md, this is a very small mistake that the image is showing on github.com/denoland/fresh but not on https://deno.land/x/fresh@1.1.2 at line :5 
```html
<img align="right" src="./www/static/logo.svg" height="150px" alt="the fresh logo: a sliced lemon dripping with juice">
```
It perfectly works at github.com since the logo.svg is at correct path. But at https://deno.land/x/fresh@1.1.2 its not work as it is.
Because current dir can be relative since both are different domains and deno.land just showing the repository homepage not the actual repository. 

so we need to change URL to 
```html 
<img align="right" src="https://fresh.deno.dev/logo.svg" height="150px" alt="the fresh logo: a sliced lemon dripping with juice">```
## Since it is a very small mistake and this is my first PR

**Comment by codesculpture** [comment]
@hashrock Thanks for pointing this..

**Comment by hashrock** [comment]
Thanks!
