### ISSUE TITLE
Uncaught SyntaxError: Unexpected token .

### ISSUE THREAD

**Issue by kkxunguan** [denoland/fresh#878]
fresh 应用在 chrome 72.0.3626.121 浏览器中无法打开，但是edge是正常的？？？

![333333](https://user-images.githubusercontent.com/23550074/199679142-e11ada38-1004-42f2-a1b9-9dee95479905.png)

![44444](https://user-images.githubusercontent.com/23550074/199679237-461b899e-fd59-407a-9111-a1c92b0bc6c5.png)

Uncaught SyntaxError: Unexpected token .

**Comment by kkxunguan** [comment]
好像是资源找不到

**Comment by lucacasonato** [comment]
Your Chrome version is too old.
