### ISSUE TITLE
Support for TLS, SSL and HTTPS missing from Deno.Serve

### ISSUE THREAD

**Issue by Omig12** [denoland/fresh#901]
https://github.com/denoland/fresh/blob/88171feb6d9f1129b48deb518b7c00b7c43f2389/src/server/mod.ts#L68

As documented in [Deno.serve()](https://deno.land/api@v1.27.2?unstable&s=Deno.serve) this function seems to be capable TSL through  [Deno.serveTls()](https://deno.land/std@0.147.0/http/server.ts?s=serveTls).

**Comment by lucacasonato** [comment]
I don't understand, what is the request here?

**Comment by Omig12** [comment]
Hi Luca,

A bit more context I'm running an Apache Web Server with a simple HTML Landing page in a low-resource server. I'd Like to migrate from Apache Web Server to Deno + Fresh and reuse this landing page which is plain HTML setting it as the index.html file that servers as the entry point from that static file.

**Comment by ghost** [comment]
Should be resolved using deno >= 1.35.0 and fresh >= 1.3.0
