### ISSUE TITLE
Why is `params` available in `HandlerContext` but not in `MiddlewareHandlerContext`?

### ISSUE THREAD

**Issue by karfau** [denoland/fresh#903]
I wanted to add a middleware that takes care of setting something in the `context.state` according to a parameter in the route (I have a folder named `[repository]`), I know that in a page handler I was able to to use `ctx.params.state` but when putting it into a middleware the type checks complains:
```
Property 'params' does not exist on type 'MiddlewareHandlerContext<CustomType>'.
```
Would it be possible to handle such a case in middle ware instead of having the related code in each route handler?

**Comment by thegaryroberts** [comment]
I have to manually extract this param from the URL in my middleware files, and it's one of the only sources of frequent bugs in my project post refactoring! (because of the otherwise excellent architecture/tooling from Fresh/Deno)
