### ISSUE TITLE
customize <html> element

### ISSUE THREAD

**Issue by TomokiMiyauci** [denoland/fresh#907]
I want to change the attributes of a root html element.
For example `amp`.

My understanding is that currently only the `lang` attribute can be changed.

How about allowing this with a `RenderFunction`, or adding a hook that allows complete customization of the rendered html?

**Comment by UrielCh** [comment]
Same issue to deal with dark mode.

I want to add class="dark" in my html tag.

**Comment by abdulbasetbasher** [comment]
> Same issue to deal with dark mode.
> 
> I want to add class="dark" in my html tag.

i use this workaround for this problem, this also fix dark mode flickering issue

in routes folder create file named
_app.tsx

```
import { Head } from "$fresh/runtime.ts";
import { AppProps } from "$fresh/src/server/types.ts";

export default function App({ Component }: AppProps) {
  

  return (
    <html>
      <Head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
            window.isDark = localStorage.theme === "dark" || (!("theme" in localStorage) && window.matchMedia("(prefers-color-scheme: dark)").matches)
            document.documentElement.classList[window.isDark ? 'add' : 'remove']("dark");
            `
          }}
        />
      </Head>
      <body class={`bg(gray-100 dark:gray-800) dark:text-gray-100`}>
        <main class="container mx-auto p-4">
          <Component />
        </main>
      </body>
    </html>
  );
}

```

**Comment by UrielCh** [comment]
I do not see how that can fix the flickering.

I try that on a new project:

- deno run -A -r https://fresh.deno.dev my-project
- code my-project
- add `darkMode: 'class',` in twind.config.ts
- add your `routes/_app.tsx`
- deno task start
- enable Dark mode
- reload

yep no flickering...

but some thing is wrong:

- When I change the OS then the page should not change color. `darkMode = class`

I set localStorage.theme = "light" 
...

it like darkMode stay as default


> twind.config.ts (should be ok)
```ts
import { Options } from "$fresh/plugins/twind.ts";

export default {
  darkMode: 'class',
  selfURL: import.meta.url,
} as Options;
```

**Comment by UrielCh** [comment]
I will try again tomorrow.

This technique looks to work

https://fresh-dark-mode.deno.dev/

**Comment by cowboyd** [comment]
Another use-case of this is if you want to set a `base` attribute.

**Comment by afifurrohman-id** [comment]
> > Same issue to deal with dark mode.
> > I want to add class="dark" in my html tag.
> 
> i use this workaround for this problem, this also fix dark mode flickering issue
> 
> in routes folder create file named _app.tsx
> 
> ```
> import { Head } from "$fresh/runtime.ts";
> import { AppProps } from "$fresh/src/server/types.ts";
> 
> export default function App({ Component }: AppProps) {
>   
> 
>   return (
>     <html>
>       <Head>
>         <script
>           dangerouslySetInnerHTML={{
>             __html: `
>             window.isDark = localStorage.theme === "dark" || (!("theme" in localStorage) && window.matchMedia("(prefers-color-scheme: dark)").matches)
>             document.documentElement.classList[window.isDark ? 'add' : 'remove']("dark");
>             `
>           }}
>         />
>       </Head>
>       <body class={`bg(gray-100 dark:gray-800) dark:text-gray-100`}>
>         <main class="container mx-auto p-4">
>           <Component />
>         </main>
>       </body>
>     </html>
>   );
> }
> ```

if you check the source in web(not in dev tools), the element is duplicate like:
```tsx
<body>
   <body className='dark:bg-slate-900 dark:text-slate-200'>
     ....
   </body>
</body>
```

**Comment by marvinhagemeister** [comment]
Related #1529 .

**Comment by deer** [comment]
@marvinhagemeister, I guess https://github.com/denoland/fresh/pull/1617 also closes this one.
