### ISSUE TITLE
Support for multiple languages

### ISSUE THREAD

**Issue by sammarxz** [denoland/fresh#920]
Hello everyone! Great job so far.

So it would be nice to add support for multiple languages. For example, I'm creating my website in Portuguese (Brazil) and my page's html goes with the attribute `lang="en"`, thus making it difficult for SEO and screen readers to work correctly.

![example html lang attr](https://user-images.githubusercontent.com/19997815/203665963-94799cd9-50b3-4a54-82a8-7ad2f2dfb7ec.png)

maybe pass some prop lang on main.ts:

```typescript
await start(manifest, {
  lang: "pt-br",
  plugins: [twindPlugin(twindConfig)] 
});
```

or make it possible to create an `<html>` within our `_app.tsx`, more or less like [nextJS](https://nextjs.org/) does.

## refferences:
* [How to set HTML lang attribute dynamically on NextJs Document?](https://stackoverflow.com/questions/61310847/how-to-set-html-lang-attribute-dynamically-on-nextjs-document)

**Comment by litvinav** [comment]
Hi @sammarxz ,
i have run into the same issue and found a solution after some reverse engineering.
For current fresh (1.1.2) you would have edit the main.ts like follows.

```ts
// static approach
const renderFn: RenderFunction = (ctx, render) => {
  ctx.lang = "pt"
  render()
}

await start(manifest, { plugins: [twindPlugin(twindConfig)], render: renderFn });
```

```ts
// mutliple languages from URL path like "https://example.com/pt/posts"
const renderFn: RenderFunction = (ctx, render) => {
  const lang = ctx.url.pathname.substring(1,3)
  switch (lang) {
    case "pt":
    case "ru":
    case "de":
    case "zh":
    case "en":
      ctx.lang = lang
      break
    default:
      ctx.lang = "pt"
  }
  render()
}

await start(manifest, { plugins: [twindPlugin(twindConfig)], render: renderFn });
```

![image](https://user-images.githubusercontent.com/70129575/204068413-570a8aa5-3c66-47d1-831d-10b912add3b2.png)


But this should be documented and probably changeable via the route ctx by the route handler...

**Comment by sammarxz** [comment]
Oh, that is man! 
Thanks!

Yeap , definitely should be documented

**Comment by aya-eiya** [comment]
Note:
if you write `<html lang="en">` in `_app.tsx` or even it is just only `<html>`, the ctx.lang setting will be ignored.
you must remove the `<html>` tag from `_app.tsx`.
