### ISSUE TITLE
How to debug why island is not working when deployed?

### ISSUE THREAD

**Issue by karfau** [denoland/fresh#923]
https://discord.com/channels/684898665143206084/1046110707617374328

I have an Island containing a select that changes the URL when a new item is selected. It is also disabled afterwards, since the "selected page" might need a bit time to load.
When testing it locally everything works fine, but when pushing and it is deployed to deno deploy the select does nothing. The devtools also say that no event listener has been attached. The code that is being fetched looks correct. I added two console.log to see whether they are called on the client: first line in the Island and first line in the event handler.
None of them reports to the browser console, so they are not executed on the client.
I disabled all adblockers.
How can I debug / understand what is going on?

I now decided to reintroduce the `disabled=!IS_BROWSER || props.disabled` and the select never becomes enabled in the browser when using deno deploy. But when testing it on localhost everything works as expected.

even when running `deno run -A main.ts` locally instead of the start task, (what I am assuming is what deno deploy does), the island seems to work. And I looked at the downloaded code again, and there is nothing suspucios, beside the fact that the hydration doesn't seem to work.
Here is the code of my island: https://gist.github.com/karfau/eddad286fe07fe3a7bfc48b21e665a90

**Comment by lucacasonato** [comment]
You can look at your Deno Deploy logs to see if there was any error during execution.

**Comment by karfau** [comment]
> You can look at your Deno Deploy logs to see if there was any error during execution.

There is no error on Deno deploy logs (and also not in the browser console) and the bundled code get's loaded but seems to never be applied.

**Comment by marvinhagemeister** [comment]
I'm assuming that this is resolved. Happy to re-open if it is not.

**Comment by karfau** [comment]
Never managed to investigate further, still on the initial fresh release, not using any islands so far because of that issue.
So I simply can not judge the current situation. Fine with closing it and open a new one, hopefully with more detailed info, because of all the improvements that have been made since then.

**Comment by marvinhagemeister** [comment]
@karfau Yeah I highly recommend updating to the latest Fresh release. It includes lots of fixes, better error messages and much more.
