### ISSUE TITLE
Deno fresh does not serve static assets with unicode characters

### ISSUE THREAD

**Issue by cwohlman** [denoland/fresh#931]
I have the following file in my project: `static/ēēē.m4a`, 
I reference this file as `/ēēē.m4a` in the source of an Audio element.

This file is never returned by Deno for any url.

The browser appears to be url encoding this path for a result of: `%C4%93%C4%93%C4%93.m4a`

It looks like deno is not url decoding paths for static assets.

I've tried encoding the file name in the file system but that doesn't work.

I've checked that the url encoding the browser is sending matches the url encoding I chose for the file name (there's more than one encoding).

**Comment by hashrock** [comment]
We could not reproduce your situation, what is your environment?

And it would be helpful if you could make a minimal reproducing repo.

**Comment by lucacasonato** [comment]
Can not fix bugs without reproductions and more info. Please provide the info, and then we can re-open the issue.
