### ISSUE TITLE
Can I use MDX with Fresh? 

### ISSUE THREAD

**Issue by o-t-w** [denoland/fresh#933]
Fresh feels well-suited to documentation. Is there a guide to using Fresh in conjunction with MDX?

**Comment by lucis** [comment]
Similar case is Deno Docs: https://github.com/denoland/fresh/blob/main/www/routes/docs/%5B...slug%5D.tsx

**Comment by imjamesb** [comment]
Yes, you can not SSR MDX on Deno Deploy though.
