### ISSUE TITLE
Proper way to use type safe event handling in Preact with Fresh

### ISSUE THREAD

**Issue by ericlery** [denoland/fresh#940]
What is the proper way to use type safe event handling in Preact with Fresh? I could of course use: `e: any => e.target.value` or use JSX for my islands, but it's such a bummer... I'm mainly interested in Deno and Fresh for the TypeScript out of the box, but Preact don't seem to have a fully type checked library according to a core member: https://github.com/preactjs/preact/issues/1930

**Comment by ericlery** [comment]
I found the solution a while ago, so I close as completed.
```ts
import { JSX } from "preact/jsx-runtime";

function functionName(e: JSX.TargetedEvent<HTMLInputElement, Event>) { }
```

**Comment by ynwd** [comment]
I found it works too.

```tsx
import { JSX } from "preact/jsx-runtime";

function functionName(e: JSX.TargetedEvent<HTMLInputElement, InputEvent>) { }
```
