### ISSUE TITLE
Issue with sending props to island component

### ISSUE THREAD

**Issue by vorcigernix** [denoland/fresh#941]
I have code like this
```
import { PageProps } from "$fresh/server.ts";
export default function NewEvent(props: PageProps) {
  const url = `https://${props.url.host}/${props.params.id}`;
  return(<IslandComponent url={url} />)
}
```
and problem is that url is not passed correctly to the component. I suspect that the reason is that the property is server side (and I know that I can read the same thing from the window object) - but I'd like to understand the issue for future reference.

**Comment by lucacasonato** [comment]
What is the issue? This looks like it should work. The URL should be serialized and passed to the client for the island render.

**Comment by marvinhagemeister** [comment]
Closing because we haven't heard back. Please ping us if this is still an issue. Happy to reopen it.
