### ISSUE TITLE
Environment variables in islands

### ISSUE THREAD

**Issue by m4rocks** [denoland/fresh#945]
I noticed using environment variables in islands is not yet possible, and it is obvious why. Would it be possible to add environment variables in islands? If so, how? Would love to add this feature myself, but not sure how.

**Comment by lucis** [comment]
1. Create a handler.
2. Get the env var value.
3. Pass it to `ctx.render(...`.
4. Pass the value to the island.

Remember Islands run on the user's browsers as well

**Comment by m4rocks** [comment]
That's a great solution I have been using. But I was thinking about a more integrated solution. Something built into Fresh.

I'll start crafting something together soon.

**Comment by hashrock** [comment]
In terms of responsibility and security, I believe that the browser and runtime should be considered separately, and if you still want to pass environment variables, it is better to do it in an explicit way like lucis said.
I am closing this Issue, but if you still want to realize this, please re-open it.
