### ISSUE TITLE
Deno Deploy error

### ISSUE THREAD

**Issue by alexbezhan** [denoland/fresh#953]
I have a website built in Fresh. I didn't touch it for few months, now I just went and changed some CSS, pushed to Deploy and now the production is failing with every request:
```
Uncaught SyntaxError: The requested module '/v99/twind@1.0.1/deno/twind.js' does not provide an export named 'directive'
    at https://esm.sh/v99/@twind/line-clamp@0.1.1/deno/line-clamp.js:2:8
```

**Comment by mohsinalipro** [comment]
Try removing `fresh.gen.ts` file and run deno task start then it will create a new `fresh.gen.ts` file then push it to redeploy.

**Comment by alexbezhan** [comment]
> Try removing `fresh.gen.ts` file and run deno task start then it will create a new `fresh.gen.ts` file then push it to redeploy.

Thanks.
I ended up deleting the dependency. It turned out not that important.
But I was very scared. I didn't change any code, didn't upgrade anything. Just changed the text file in existing system and deployed. If this breaks the application, then I'm very scared to use Deno for more important stuff.

**Comment by hashrock** [comment]
It would be helpful if you could create a minimal repro repo to verify.

**Comment by alexbezhan** [comment]
Here you go https://github.com/alexbezhan/deno-deploy-broken-reproduce
@hashrock

**Comment by hashrock** [comment]
Thank you! it seems a dependency problem using esm.sh.
I'm not too familiar with this issue, but the content esm.sh served is changed as esm.sh itself is updated. In this case, the error is caused by twind's incompatible version 1.0.1 being used.

To investigate this, run `deno info main.ts`, then you'll get dependency graph:

```
│ │ ├─┬ deno-deploy-broken-reproduce/utils/twind.ts (906B)
│ │ │ ├─┬ https://esm.sh/@twind/line-clamp@0.1.1 (118B)
│ │ │ │ ├─┬ https://esm.sh/v99/@twind/line-clamp@0.1.1/line-clamp.d.ts (421B)
│ │ │ │ │ └─┬ https://esm.sh/twind@0.16.17 (93B)
│ │ │ │ │   ├─┬ https://esm.sh/v99/twind@0.16.17/twind.d.ts (29.26KB)
│ │ │ │ │   │ └── https://esm.sh/v99/csstype@3.1.1/index.d.ts (837.78KB)
│ │ │ │ │   └─┬ https://esm.sh/v99/twind@0.16.17/deno/twind.js (32.61KB)
│ │ │ │ │     └── https://esm.sh/v99/style-vendorizer@2.2.3/deno/style-vendorizer.js (1.83KB)
│ │ │ │ └─┬ https://esm.sh/v99/@twind/line-clamp@0.1.1/deno/line-clamp.js (369B)
│ │ │ │   └─┬ https://esm.sh/v99/twind@1.0.1/deno/twind.js (109B)
│ │ │ │     └── https://esm.sh/v99/@twind/core@1.0.1/deno/core.js (19.92KB)
```

to fix twind dependency version, change the dependency url in `import_map.json` :

```
"@twind/line-clamp": "https://esm.sh/@twind/line-clamp@0.1.1?deps=twind@0.16.17",
```

It may be possible to fix it with the function "pin" in esm.sh also.

**Comment by alexbezhan** [comment]
@hashrock thank you for the analysis.
The issue seems very complex to me, compared to the business value it provides. So in the future I prefer to delete twind and anything related to that, and stick to the plain tailwind css.
