### ISSUE TITLE
How hard will it be to swap out preact with solid for rendering

### ISSUE THREAD

**Issue by nikivdev** [denoland/fresh#956]
I'd like to use https://www.solidjs.com for reactive updates instead of preact due to nicer API and no VDOM.

I write all my code in deno and want to keep it this way so I thought it'd be great to use fresh but somehow get solid instead of preact there.

How hard would it be to swap out the preact part and add solid? Or that would require a whole new project?

Thank you.

**Comment by nikivdev** [comment]
Alternatively I thought of trying to run https://github.com/solidjs/solid-start on Deno. But not sure how.

There is [this](https://twitter.com/JLarky/status/1582049727427751936) supposed solution but it doesn't work on SSR, author says.

> i'm using deno adapter and I basically use deno just on the production, local development is happening with node/bun

Let me know what would be the easiest way to get deno to interact with solid. I'd really love to make it work. ♥️

**Comment by nikivdev** [comment]
https://github.com/solidjs/solid-start/tree/main/packages/start-deno is adapter being used. 

But yes, maybe it would be viable to make it so fresh uses solid instead of preact. How feasible would this be?

**Comment by lucacasonato** [comment]
Very difficult, because:
- Solid has a completely different rendering model to Preact
- Solid requires compilation for the SSR build for full functionality
- Solid does not provide the same render hooks as Preact that we use to detect islands

I suggest you use Solid Start or Astro, it's a great project :)
