### ISSUE TITLE
passing state to `start`

### ISSUE THREAD

**Issue by harrysolovay** [denoland/fresh#957]
I'm seemingly-unable to supply some state to the Fresh server.

Might it be useful to make it possible to add an additional prop to `start`'s `opts`, which would then be accessible on route `ctx`? Here is my use case:

---

In a given `main.ts`, what if (A) there is some state initialized before `start`ing the server and (B) routes need to make use of that state? For instance:

```ts
const someOtherServer = new SomeOtherServer()
someOtherServer.listen()

await start(manifest)
```
In this case, `someOtherServer` might contain a `port`, about which the fresh routes need be aware in order to make requests of `someOtherServer`. Ideally we could do something like...

```diff
const someOtherServer = new SomeOtherServer()
someOtherServer.listen()

- await start(manifest)
+ await start(manifest, {
+   globalState: { port: someOtherServer.port },
+ })
```

Then, within a given route, we could access that port, and use it to connect to `someOtherServer`.

```ts
import { Handlers } from "$fresh/server.ts"

export const handler: Handlers = {
  GET(_req, ctx) {
    const conn = Deno.connect({
      port: ctx.globalState.port,
      ...
    })
  },
}
```

I'd imagine there are limitations to what kind of data one could supply as `globalState`...

Would this feature be desirable? Is there another approach to solving the same problem? (I'm quite new to Fresh... wouldn't surprise me if there's another approach about which I'm unaware). Thank you!

**Comment by lino-levan** [comment]
Why not just use a module?

```ts
// serverConnection.ts
const someOtherServer = new SomeOtherServer()
someOtherServer.listen()

export const port = 1111
```

```ts
// routes/example.ts
import { Handlers } from "$fresh/server.ts"
import { port } from "../serverConnection.ts"

export const handler: Handlers = {
  GET(_req, ctx) {
    const conn = Deno.connect({
      port: port,
      ...
    })
  },
}
```

**Comment by harrysolovay** [comment]
Perhaps the port state was a bad example. A better example might be a cache.

`main.ts`

```ts
// ...

await start(manifest, {
  globalState: { cache },
})
```

`routes/example.ts`

```ts
import { Handlers } from "$fresh/server.ts"
import { port } from "../serverConnection.ts"

export const handler: Handlers = {
  GET(_req, ctx) {
    const possiblyCachedValue = ctx.globalState.cache.getOrInit(someKey, someInitFn)
    // ...
  },
}
```

Different requests could make use of the same cache instance, supplied to `serve`.

**Comment by lino-levan** [comment]
Maybe I'm not understanding something, but couldn't this also just be a module?

```typescript
// cache.ts
class Cache {
    // ...
}

export const cache = new Cache()
```

```typescript
// routes/example.ts
import { Handlers } from "$fresh/server.ts"
import { port } from "../serverConnection.ts"
import { cache } from "../cache.ts"

export const handler: Handlers = {
  GET(_req, ctx) {
    const possiblyCachedValue = cache.getOrInit(someKey, someInitFn)
    // ...
  },
}
```

**Comment by harrysolovay** [comment]
Good point! I suppose I was thinking about state as if working with an Oak server (where one must specify how state is passed between middleware)...

But yes... when one wants handlers to simply share the same piece of data, a singleton would do! Thank you for bearing with me.

**Comment by harrysolovay** [comment]
Let's say we want to package a Fresh website as a library with some configuration that needs to be accessed by handlers. Ideally, we could expose the site by wrapping the `start` call.

```ts
export interface Props extends StartOptions {
  somePropUsedByHandlers?: string
}

export function theSite(props: Props = {}) {
 return start(manifest, props)
}
```

How would one access the `somePropUsedByHandlers` prop from within handlers?

> Sidenote: perhaps this merits a new issue?: "packaging Fresh site as configurable library"

**Comment by marvinhagemeister** [comment]
To me that seems like an uncommon use case to distribute a website as a library. I'm happy to be proven wrong though if enough people are interested in this feature.

A valid option to pass data around when starting multiple instances of fresh are environment variables. For as long as each fresh instance has their own process, you can pass different env variables to them.
