### ISSUE TITLE
Remove hardcoded dependency on `deno.json`

### ISSUE THREAD

**Issue by vwkd** [denoland/fresh#961]
Currently, fresh has a hardcoded dependency on `./deno.json` for compiler options and throws and error if it doesn’t exist. 

This prevents using fresh in a subdirectory, e.g. `src/`, of the repository, without maintaining duplicate `deno.json` files.

Workaround using a soft or hard link are not optimal. Also they introduce more issues, e.g. a soft link is currently not recognized by `vscode_deno` extension which prevents IntelliSense https://github.com/denoland/vscode_deno/issues/784, while a hard link is not recognized by git which makes it impossible to synchronize it across different computers.

It would be great if the hardcoded dependency on `./deno.json` could be avoided, made optional or configurable.

Seems to be introduced in https://github.com/denoland/fresh/pull/610#pullrequestreview-1095905149

**Comment by lucacasonato** [comment]
We should walk up the tree to find the `deno.json` that is in use.

**Comment by iuioiua** [comment]
I think there are better alternatives, such as providing a CLI flag or taking advantage of Deno's inbuilt method of finding the `deno.json`, which would only be made possible by a new function in the runtime API (proposal [here](https://github.com/denoland/deno/issues/19322)).
