### ISSUE TITLE
Fresh turns double quote (") to &quote and json in footer inline script become invalid

### ISSUE THREAD

**Issue by og-dev** [denoland/fresh#964]
Failed to append inline script to the body

I'm trying to add a script to the page footer, but fresh is converting the json inside `<script>{"val1":25}</script>` to html entities ( `json quote " ` become `{&quot25&quot:25}`).

How can I stop fresh from converting the json to html entities?
or how to add a script to footer page without fresh transform " to &quote?

**Comment by lucacasonato** [comment]
`<script dangerouslySetInnerHTML={{ __html: `{"val1":25}` }} />`
