### ISSUE TITLE
Having problem deploying to Deno Deploy

### ISSUE THREAD

**Issue by medmor** [denoland/fresh#971]
The app is working fine locally. But when I deploy it using Deno Deploy, I get this error
```
TypeError: Cannot read properties of undefined (reading 'deno')
    at ensureMinDenoVersion (https://deno.land/x/fresh@1.1.2/src/dev/mod.ts:6:27)
    at dev (https://deno.land/x/fresh@1.1.2/src/dev/mod.ts:133:5)
    at file:///src/dev.ts:3:7
```

I don't know what to do to fix it

**Comment by kt3k** [comment]
You need to specify `main.ts` as the entrypoint instead of `dev.ts` https://fresh.deno.dev/docs/getting-started/deploy-to-production

**Comment by kt3k** [comment]
maybe we should show better error message if `dev.ts` is specified as the entrypoint of deployment

**Comment by medmor** [comment]
@kt3k Thank you for your answer.
I didn't read the instructions well, that was my fault.
If it's possible to show a better error message when the `main.ts` is not specified as the `entrypoint`, that would be very helpful.
