### ISSUE TITLE
NPM specifiers?

### ISSUE THREAD

**Issue by jimisaacs** [denoland/fresh#974]
Does this work? I tried replacing the esm.sh examples with npm specifiers, but it seems to still be expected for esbuild. Can it work with esbuild?

**Comment by jimisaacs** [comment]
Seems related: https://github.com/lucacasonato/esbuild_deno_loader/issues/29

**Comment by lucacasonato** [comment]
Closing as a duplicate of https://github.com/denoland/fresh/issues/978
