### ISSUE TITLE
NPM specifier support in Fresh

### ISSUE THREAD

**Issue by lucacasonato** [denoland/fresh#978]
To support NPM specifiers in Fresh, we need to support them in esbuild_deno_loader first: https://github.com/lucacasonato/esbuild_deno_loader/issues/29

Also Deno Deploy support is still pending.

**Comment by codesculpture** [comment]
https://github.com/lucacasonato/esbuild_deno_loader/pull/33

**Comment by maciejkulinski** [comment]
https://github.com/lucacasonato/esbuild_deno_loader/pull/40

**Comment by fro-profesional** [comment]
https://deno.com/blog/npm-on-deno-deploy 🔥

**Comment by guy-borderless** [comment]
should this be closed?

**Comment by fro-profesional** [comment]
I think the new release includes this fix: https://github.com/denoland/fresh/pull/1841 so maybe after the new release ¿?

**Comment by marvinhagemeister** [comment]
Basic `npm:` support works in Fresh, but to make peer dependencies work, we're blocked by https://github.com/denoland/deno/issues/20868 . Leaving the issue open until that is resolved.
