### ISSUE TITLE
How to use LocalStorage in Island component 

### ISSUE THREAD

**Issue by HemanthKona** [denoland/fresh#979]
I'm trying to use `localStorage` in a island component but I get Deno not found error. 

For example: 
```ts
const TodoIsland = async () => {
  let storedTodos: TodoStore = {data: []};

  const getTodosFromLocalStorage = await localStorage.getItem('todoStore');
  if (getTodosFromLocalStorage) storedTodos =  JSON.parse(getTodosFromLocalStorage);

  todoStore.data = storedTodos.data;

  return (
    <main> 
        <h1>TODO List</h1>
    </main>
  );
};
```

Error: 
<img width="488" alt="image" src="https://user-images.githubusercontent.com/395381/211636861-f1e70481-b06b-4298-95c6-953635bdcf41.png">

**Comment by lino-levan** [comment]
Before I start, I should point a few things out:
- You say this is an "island component" but in this code snippet you aren't default exporting anything. Please read the docs on this one: https://fresh.deno.dev/docs/concepts/islands
- Your component is inside an async function which is not allowed. Please read the docs on data fetching: https://fresh.deno.dev/docs/getting-started/fetching-data
- You don't even need to be using async/await in the first place because localStorage is a synchronous api. Removing `await` and `async` should fix a whole load of problems.

To get to the meat of your question, "how do I use local storage in an island". It's rather unclear what you are trying to do here. Are you trying to use Deno's localStorage api or the browser's?

If you want to use the browser's we can use preact's `useState` and `useEffect` hooks:
```typescript
export default function TodoIsland () {
  let [todos, setTodos] = useState<TodoStore>({data: []});
  
  useEffect(()=>{
    const getTodosFromLocalStorage = localStorage.getItem('todoStore');
    if (getTodosFromLocalStorage) {
      setTodos(JSON.parse(getTodosFromLocalStorage));
    }
  }, [])

  return (
    <main> 
        <h1>TODO List</h1>
    </main>
  );
};
```

If for some reason we wanted to use Deno's localStorage, we could instead do the data fetching as demonstrated in the link I posted earlier.

I recommend reading up on hooks in general. React's website is a decent source for this. i.e https://reactjs.org/docs/hooks-effect.html

Hope that answers your question!

**Comment by HemanthKona** [comment]
@lino-levan  Thanks for the response. 

- I was exporting the Island component, but did not add that line in the above code. 
```ts

const TodoIsland () => {
  let [todos, setTodos] = useState<TodoStore>({data: []});
  
  useEffect(()=>{
    const getTodosFromLocalStorage = localStorage.getItem('todoStore');
    if (getTodosFromLocalStorage) {
      setTodos(JSON.parse(getTodosFromLocalStorage));
    }
  }, [])

  return (
    <main> 
        <h1>TODO List</h1>
    </main>
  );
};

export default TodoApp;
```

- Thanks for pointing out the async and await, I removed it. 

I tried your example it worked. But I think the reason I was getting that  error is not because of localStorage. It's because I was using the `class-transformer` library and using `plainToInstance` method.  

Below is the  complete Island Component code which is throwing the error. If you are still interested to check the error. But right now I resolved it by removing `class-transformer` library. 



```ts
// import 'reflect-metadata';
import { useEffect, useRef } from "preact/hooks";
import { instanceToPlain, plainToInstance } from "class-transformer";
import autoAnimate from "@formkit/auto-animate";
import { match } from "ts-pattern";
import { proxy, subscribe, useSnapshot } from "valtio";
import { Header } from "../components/layout/header.tsx";

type Status = "pending" | "completed";
type Filter = Status | "all";

abstract class BaseStore {
  abstract data: any[];

  create = (description: string) => {
    this.data.push({
      description,
      status: "pending",
      id: Date.now(),
    });
  };

  delete = (index: number) => {
    console.log(this.data);
    this.data.splice(index, 1);
  };
}
class Todo {
  description!: string;
  status!: Status;
  id!: number;
}

class TodoStore extends BaseStore {
  
  constructor(storedData: BaseStore) {
    super();
    this.data = storedData?.data ?? [];
  }

  filter = "all";
  data: Todo[] = [];
}

let todoStoreData;
const localData = localStorage.getItem('todoStore');
if (localData) todoStoreData = JSON.parse(localData); 
// console.log("localData: ", new TodoStore(todoStoreData));

export const todoStore = proxy<TodoStore>(new TodoStore(todoStoreData ?? {}));

const createData = (description: string) => {
  todoStore.data.push({
    description,
    status: "pending",
    id: Date.now(),
  });
};

const deleteData = (index: number) => {
  todoStore.data.splice(index, 1);
};

const toggleDone = (index: number, currentStatus: Status) => {
  const nextStatus = currentStatus === "pending" ? "completed" : "pending";
  todoStore.data[index].status = nextStatus;
};

const setFilter = (filter: Filter) => {
  todoStore.filter = filter;
};

const filterValues: Filter[] = ["all", "pending", "completed"];

const Filters = () => {
  const snap = useSnapshot(todoStore);
  return (
    <nav>
      {filterValues.map((filter) => (
        <>
          <input
            name="filter"
            type="radio"
            value={filter}
            checked={snap.filter === filter}
            onChange={() => setFilter(filter)}
          />
          <label>{filter}</label>
        </>
      ))}
    </nav>
  );
};

const Todos = () => {
  const todoStoreSnapshot = useSnapshot(todoStore);
  const parent = useRef(null);

  useEffect(() => {
    parent.current && autoAnimate(parent.current);
  }, [parent]);

  return (
    <ul ref={parent}>
      {todoStoreSnapshot.data
        .filter(({ status }) =>
          status === todoStoreSnapshot.filter ||
          todoStoreSnapshot.filter === "all"
        )
        .map(({ description, status, id }, index) => {
          return (
            <li key={id}>
              <span
                data-status={status}
                className="description"
                onClick={() => toggleDone(index, status)}
              >
                {description}
              </span>
              <button className="remove" onClick={() => deleteData(index)}>
                x
              </button>
            </li>
          );
        })}
    </ul>
  );
};

const CreateTodo = () => {
  const inputRef = useRef<HTMLInputElement>(null);

  const onEnter = (e: KeyboardEvent) => {
    match(e.key)
      .with("Enter", () => {
        createData(inputRef.current?.value ?? "");
      })
      .otherwise(() => null);
  };

  return (
    <section>
      <input
        style="width: 90vw;"
        name="description"
        type="text"
        minLength={2}
        ref={inputRef}
        onKeyUp={onEnter}
      />
      <button
        style="margin:0 var(--size-2)"
        className="add"
        onClick={() => createData(inputRef.current?.value ?? "")}
      >
        Add new
      </button>
    </section>
  );
};

const TodoApp = () => {
  const todoStoreSnapshot = useSnapshot(todoStore);
  
  let storedTodos: TodoStore = plainToInstance(TodoStore, {data: []});
  
  useEffect(() => {
    const getTodosFromLocalStorage = localStorage.setItem('todoStore', JSON.stringify(todoStoreSnapshot));
  
  }, [todoStoreSnapshot.data])

  return (
    <main>
      <div style="display: grid; grid-template-rows: 90vh 10vh">
        <div style="padding: var(--size-4); ">
          <Header></Header>
          <h1>
            To-do List{" "}
            <span role="img" aria-label="pen">
              ✏️
            </span>
          </h1>
          <Filters />
          <Todos />
        </div>
        <div style="padding: var(--size-4);">
          <CreateTodo />
        </div>
      </div>
    </main>
  );
};

export default TodoApp;
```


--- 
Closing this issue as the issue was not related to localStorage.

**Comment by ru88s** [comment]
I had a similar problem but solved it by using useEffect.
Thank you very much.

**Comment by ajvanegasv** [comment]
> Before I start, I should point a few things out:
> 
>     * You say this is an "island component" but in this code snippet you aren't default exporting anything. Please read the docs on this one: https://fresh.deno.dev/docs/concepts/islands
> 
>     * Your component is inside an async function which is not allowed. Please read the docs on data fetching: https://fresh.deno.dev/docs/getting-started/fetching-data
> 
>     * You don't even need to be using async/await in the first place because localStorage is a synchronous api. Removing `await` and `async` should fix a whole load of problems.
> 
> 
> To get to the meat of your question, "how do I use local storage in an island". It's rather unclear what you are trying to do here. Are you trying to use Deno's localStorage api or the browser's?
> 
> If you want to use the browser's we can use preact's `useState` and `useEffect` hooks:
> 
> ```ts
> export default function TodoIsland () {
>   let [todos, setTodos] = useState<TodoStore>({data: []});
>   
>   useEffect(()=>{
>     const getTodosFromLocalStorage = localStorage.getItem('todoStore');
>     if (getTodosFromLocalStorage) {
>       setTodos(JSON.parse(getTodosFromLocalStorage));
>     }
>   }, [])
> 
>   return (
>     <main> 
>         <h1>TODO List</h1>
>     </main>
>   );
> };
> ```
> 
> If for some reason we wanted to use Deno's localStorage, we could instead do the data fetching as demonstrated in the link I posted earlier.
> 
> I recommend reading up on hooks in general. React's website is a decent source for this. i.e https://reactjs.org/docs/hooks-effect.html
> 
> Hope that answers your question!

If I want to get the browser apis how should I do it? I want to get the current pathname but I get an error when calling `window.location.pathname` but it doesn't work

**Comment by lino-levan** [comment]
> If I want to get the browser apis how should I do it? I want to get the current pathname but I get an error when calling `window.location.pathname` but it doesn't work

You have a few options in your case. You don't actually need an island to get the pathname of the request, you could just use the req object in the handler. I would recommend reading up on https://fresh.deno.dev/docs/getting-started/custom-handlers and https://fresh.deno.dev/docs/getting-started/fetching-data.  

In the case where you ***really do*** want this to run in the browser, you could use `useEffect` or fresh's `IS_BROWSER` (in an island). Something like:

```ts
import { IS_BROWSER } from "$fresh/runtime.ts";

export default function Island() {
    if(IS_BROWSER) {
        console.log(window.location.pathname)
    }
}
```

**Comment by vikiival** [comment]
I am getting the same error 

<img alt="image" width="488" src="https://user-images.githubusercontent.com/395381/211636861-f1e70481-b06b-4298-95c6-953635bdcf41.png">

is it possible that the island is running in the browser context therefore `Deno` is not defined?
