### ISSUE TITLE
App breaking bug

### ISSUE THREAD

**Issue by m4rocks** [denoland/fresh#992]
I have encountered this bug 3 times already and it's been enough. I am not sure yet if Fresh or Deno Deploy is causing it. A user (see notangelmario/paquet#87) has reported JavaScript errors. It seems that those errors are JavaScript related.

For some reason, my JavaScript was not loading and it kept failing to fetch. A redeployment solves the issue, but I can't let this happen again and again. This issue happens out of nowhere.

Loading the same code locally has no problems. It seems to be some kind of issue with Fresh generating the files and sending them to the client.

I am still investigating this issue.

**Comment by kt3k** [comment]
Looks like the hydration of Navbar component isn't happenning correctly https://github.com/notangelmario/paquet/blob/8a4ea439d9ff543eb15c9bff23b698f867239ef9/islands/Navbar.tsx
(Note: The site: https://paquet.shop/category/news, Top left back button is Navbar component)
cc @lucacasonato 

I guess it might be affected by the usage of ServiceWorker. Is it possible to temporarily disable ServiceWorker for the site?

**Comment by m4rocks** [comment]
The service worker will not cache so much of the page in the future, but it wouldn't really matter. The service worker caches files for offline usage only.

Navbar could be the problem but I am still unable pin down what is wrong with it. It's kind of difficult because it happens randomly.

For example now, production was fine 4 hours ago.

Edit: Also worth noting, all islands break when this bug occurs.

**Comment by m4rocks** [comment]
Could using slightly higher versions of Preact be a problem?

**Comment by m4rocks** [comment]
Update: I removed 'paquet.shop' from custom domains and added it back since I noticed that the domain that the app at the domain provided by Deno Deploy was working just fine.

Now it works for some reason. I didn't change any configuration.

Question marks?

**Comment by m4rocks** [comment]
Closing this issue for now
